### ISSUE TITLE
HassOS 5.3 & 5.5

### ISSUE THREAD

**Issue by BlackTurtle123** [home-assistant/operating-system#1012]
**Hardware Environment**

- [x] Raspberry Pi4 8GB
- SSD with external power resource

**Home Assistant OS release:**
- [x] Fresh installation of release 5.3 and 5.5

**Description of problem:**
When booting from ssd connected through USB, the installation doesn't work. It goes to a black screen which doesn't do anything.
Booting from sd card does work. booting raspian from the same ssd does also work.

**Comment by BlackTurtle123** [comment]
Update 5.2 does boot

**Comment by agners** [comment]
Hm, that is weird, as U-Boot used in 5.2 basically has all the patches which ultimately went into U-Boot 2020.10, which is part of 5.3/5.5.

Does maybe reboot vs. cold boot make a difference?

What firmware are you using? Can you maybe try with the latest stable 2020-09-03 (update using Raspberry Pi OS).

**Comment by BlackTurtle123** [comment]
I was using the latest rpi non stable release I think.
Cold or hot boot didn't make any change.


Op ma 23 nov. 2020 14:44 schreef Stefan Agner <notifications@github.com>:

**Comment by agners** [comment]
Ok, can you also check firmware?

**Comment by BlackTurtle123** [comment]
I will check if I still got the rpi card. Around.
Something else I noticed today, the hassos goes into read-only mode. Have
to look into the details. A reboot/power reset fixes this.


Op di 24 nov. 2020 21:23 schreef Stefan Agner <notifications@github.com>:

**Comment by BlackTurtle123** [comment]
> Ok, can you also check firmware?

Aug 19 2020 17:38:16 
Copyright (c) 2012 Broadcom
version e90cba19a98a0d1f2ef086b9cafcbca00778f094 (clean) (release) (start)

**Comment by BlackTurtle123** [comment]
Also what I noticed is that my ssd usb, powered via external power. samsung evo 970, regulary goes into read only mode.
Nothing works anymore then, and only option left is to fully reboot everything. Not sure if it has something to do with this?

**Comment by agners** [comment]
The read-only mode could be due to UAS mode issue. Are you using `usb-storage.quirks`? https://www.raspberrypi.org/forums/viewtopic.php?t=245931

As for the boot issue on 5.3/5.5: Do you use a custom config.txt?

Do you have a USB to UART TTL adapter? If so, a capture of the serial console would be interesting. See also: https://github.com/home-assistant/operating-system/tree/rel-4/Documentation/boards/raspberrypi#serial-console

**Comment by BlackTurtle123** [comment]
I tried today to set the uas settings.
Let's see.
It didn't worked to make my usb3 port work. But if it doesn't crash anymore
i am already happy. Will keep posted.

Op wo 25 nov. 2020 18:08 schreef Stefan Agner <notifications@github.com>:

**Comment by BlackTurtle123** [comment]
Update:
The custom boot didn't helped the issue.
The system crashed with read errors just now again, within 4 hours.

**Comment by BlackTurtle123** [comment]
Update 2: reflashed and tested the USB once again. 5.5 seems to work now. With usb2 port. And still these read-only file system errors.

Sadly don't have this adapter by the hand

**Comment by agners** [comment]
Can you post logs which show the read errors?

**Comment by BlackTurtle123** [comment]
Yes, will do. Sadly when this happens my system becomes dead and so can't ssh or access logs besides by screen. So can't do it now since by booting it of they become corrupt. However will makeba picture next time

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/100389999-4be7a300-302f-11eb-9e9b-faf6275e8f05.png)

After 22 hours roughly from no issues it appeared again. No change in hardware.

**Comment by BlackTurtle123** [comment]
It happened again today. 
![Uploading 16066463449424376167714269139466.jpg…]()

**Comment by BlackTurtle123** [comment]
![16066464127657233262913141896699](https://user-images.githubusercontent.com/16037736/100539556-a8b5aa00-3237-11eb-8084-2ace0a5c4adc.jpg)

**Comment by agners** [comment]
Kinda hard to tell, but the most likely cause is USB issues of some kind. You write "SSD with external power", maybe this power source is not good (enough?) What kind of SSD are you using? Maybe a different helps...

Unfortunately SSD boot with RPi4 is a bit brittle, and it works better on some SSDs and not so well on others... It's a bit a hit and miss.

**Comment by BlackTurtle123** [comment]
I tried a different usb hub with power source.
I use a Samsung nvme. It seemq under Ubuntu there might also be problems with it. 
So i guess it's a broader topic. I now try to edit some boot params and we will see..

**Comment by BlackTurtle123** [comment]
Does hassos can handle all the boot params Ubuntu and other os'es are able to use?

**Comment by BlackTurtle123** [comment]
Another update, also HassOS 5.6 seems to freeze after a while an doesn't work on usb3 with this hardware. However the not working also happens with raspian os... so I also opened a ticket there. Let's see

**Comment by agners** [comment]
@BlackTurtle123 thanks for the update! Also note that HAOS 5.6 uses the exact same git hash as the latest Raspberry Pi OS 2020-12-02/04 (https://github.com/raspberrypi/linux/commit/9797f1a4938c20139b00a25de93cc99efb5c291b).

**Comment by BlackTurtle123** [comment]
I sended back a usb3 external power source after I seen that my ssd booted if directly connected. Until it wouls require to much power consumption. So it seems hardware related/external hub related. Now trying something out. Will report back if it crashed again like before with an unreachable disk.

**Comment by BlackTurtle123** [comment]
Stable now since 2days and 9 hours. Never been this good. Let's see if it's just a lucker or not
