### ISSUE TITLE
Suggest upgrade to PyUSB 1.1.0 (libusb) as contain bug-fixes

### ISSUE THREAD

**Issue by Hedda** [home-assistant/operating-system#1067]
**Hardware Environment**

- [] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [x] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 0.118.3
- [ ] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Suggest upgrade Home Assistant OS from PyUSB 1.0.0 to PyUSB 1.1.0 as contain bug-fixes for libusb and openusb:

https://pypi.org/project/pyusb/

https://github.com/pyusb/pyusb/releases

Among other bug-fixes PyUSB 1.1.0 contains a fix to prevent segfault if libusb fails to initialize:

https://github.com/pyusb/pyusb/issues/232

As an example, this bug has been seen by ZHA users in Home Assistant when plugin a ZiGate DIN Zigbee adapter.

https://github.com/zigpy/zigpy-zigate/issues/71

"I'm using zigate usb (old prolific version) with home-assistant 0.118.3 in a docker container on a synology ds218+"

**Comment by agners** [comment]
@Hedda The operating system has no Python interpreter installed or any Python library. This is all part of the Home Assistant Core container. And the Home Assistant Core container is built according to Python dependencies. In this case, Home Assistant depends on `zigpy-zigate==0.7.3`, which was still depending on pyusb 1.0.0. From what I can tell zigpy-zigate did not do a release with the new dependency yet. So the way to go here is to wait for them to create a release, then bump the dependency in Home Assistant Core.
