### ISSUE TITLE
HassOs 5.6

### ISSUE THREAD

**Issue by BlackTurtle123** [home-assistant/operating-system#1071]
**Hardware Environment**

- [x] Raspberry Pi [/4]

- [x] Fresh installation of release 5.6

**Supervisor logs:**
![image](https://user-images.githubusercontent.com/16037736/101631129-29d52400-3a24-11eb-93a7-e3b84b174495.png)

**Description of problem:**
Can't seem to update or download new docker containers due to above error. Both update containers are listed below.
![image](https://user-images.githubusercontent.com/16037736/101633642-d5cc3e80-3a27-11eb-9c5f-cb26bcaf77d5.png)

Funny part: new add-ons do work, I tried following;
```
20-12-09 13:04:04 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_dnsmasq
20-12-09 13:04:04 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: core_dnsmasq
20-12-09 13:04:04 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
20-12-09 13:04:04 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-dnsmasq with tag 1.3.
20-12-09 13:04:21 INFO (MainThread) [supervisor.addons] Add-on 'core_dnsmasq' successfully installed
```

**Comment by BlackTurtle123** [comment]
Update, weird thing, a manual docker pull did work docker pull homeassistant/aarch64-hassio-supervisor:2020.12.6

**Comment by agners** [comment]
Hm, I have seen Docker Hub hick-ups in the past: Just random container pulling failing with errors, and 5 seconds later working... Have you been able to reproduce this? Otherwise, I think I'll close it and book it into the category "random Docker Hub hick-ups..."

**Comment by BlackTurtle123** [comment]
I am now reinstalling hassos 5.6 again. Since i was trying out something
else and report back.


Op wo 9 dec. 2020 20:24 schreef Stefan Agner <notifications@github.com>:

**Comment by BlackTurtle123** [comment]
Yes. Did a clean install. Imported my old backup. Try to update supervisor.
Same docker hiccup

Op wo 9 dec. 2020 20:24 schreef Stefan Agner <notifications@github.com>:

**Comment by agners** [comment]
@BlackTurtle123 I still haven't come across this issue, but the fact that you have been able to reproduce seems like there is something wrong in some situations.

Is `systemctl status systemd-resolved` saying something if that happens?

**Comment by BlackTurtle123** [comment]
I haven't checked that one out at that point. But i will do later when some
time pops up again.

Op vr 11 dec. 2020 10:46 schreef Stefan Agner <notifications@github.com>:

**Comment by BlackTurtle123** [comment]
What i can say that was weird tho, ping, curl and docker pull by cmd worked, altho docker pull for these 2 containers didnt worked. Even after i tested curl. It's for now running stable, and didnt encounter it during graphana and influx install.

Might it have been that my backup restore destroyed something?

**Comment by agners** [comment]
I don't think that backup restore can have destroyed something.

Docker uses the hosts DNS lookup capabilities, which is now provided by systemd-resolved in release 5. That curl/ping worked but Docker pull didn't is indeed strange, it sounds as if Docker and/or systemd-resolved cached an unsuccessful lookup or something.

**Comment by BlackTurtle123** [comment]
> I don't think that backup restore can have destroyed something.
> 
> Docker uses the hosts DNS lookup capabilities, which is now provided by systemd-resolved in release 5. That curl/ping worked but Docker pull didn't is indeed strange, it sounds as if Docker and/or systemd-resolved cached an unsuccessful lookup or something.

Currently testing if my system can be up and running for a week to test stability. (for the other issue) after that I can retry it again.

**Comment by BlackTurtle123** [comment]
![Screenshot_20201219_234840_io homeassistant companion android](https://user-images.githubusercontent.com/16037736/102701210-e4e79380-4254-11eb-8b21-2e9454f8d28a.jpg)
It seems it happened again. 
I am atm on hassos 5.8
Docker pull did work again.
