### ISSUE TITLE
Can't import the 5.8 ova Image in Synology Virtual Manager

### ISSUE THREAD

**Issue by TobiasKarge** [home-assistant/operating-system#1107]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [x ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x ] Fresh installation of release x.y
- [ ] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

- Is the problem reproducible? yes
- Has this been working before (is this a regression?) yes the ova 4.16 works
- Has there been attempt to rule out harware issues? (different SD card etc.) No the Hardware is the same

The image cannot be imported. We have tried on different synologys with always the same error. On all Synology NAS the 4.16 image can be imported.

**Comment by agners** [comment]
This is likely related to #1084. Can you try with 5.9?
