### ISSUE TITLE
Fail to boot NUC after upgrade to 5.9

### ISSUE THREAD

**Issue by haniffm** [home-assistant/operating-system#1116]
**Hardware Environment**
- [X] Intel NUC 10i3

**Home Assistant OS release:**
- [X] Updated from version 5.8

**Description of problem:**

NUC not starting after upgrade from OS 5.8 to 5.9. I get the following error message on boot:
```
bootchooser: No valid targets found: ...
```
I've also tried to boot from a USB flash with fresh HA OS 5.9, with the same error.
![fail_to_boot](https://user-images.githubusercontent.com/2280177/102840018-20739080-4402-11eb-8219-51af9a8c4785.jpeg)

**Comment by agners** [comment]
Hm, it looks like our bootloader Barebox can't find a bootable image.

Can you check what is on the first boot partition?

**Comment by haniffm** [comment]
This is on the boot image.
![image](https://user-images.githubusercontent.com/2280177/102889129-60666200-445a-11eb-83b7-b29b5b80cb21.png)

**Comment by aqualx** [comment]
Same issue with NUC D5425 :( "Reboot and Select proper Boot device". IMHO 5.9 version for NUC must be blocked for update!
Is there any possible quick fix without reinstalling?

**Comment by agners** [comment]
@haniffm are the file sizes ok (e.g. not 0 byte?) in particular /EFI/barebox/state.dtb?

@aqualx I did update Intel NUC just fine here, so its really not clear to me why it fails in some situation. Did you have to power it off or something?

Are the files corrupted in your case?

If the boot partition is corrupted, restoring it from the image should be possible. Probably the easiest method is using an Ubuntu Live image on the Intel NUC. Download the Home Assistant OS image and extract the downloaded image using `unxz hassos_intel-nuc-5.9.img.xz`. Then use "Disks" to mount the boot partition of the image:
![image](https://user-images.githubusercontent.com/34061/102938845-5c176480-44ad-11eb-94a1-b92139621632.png)

You then can mount it using the "Play" symbol. You then 
![image](https://user-images.githubusercontent.com/34061/102938833-5752b080-44ad-11eb-9d0b-bf8c146536d5.png)

Now you should have access to the FAT boot partition of a fresh installed image. Copy the files to the boot partition of your Intel NUC.

**Comment by aqualx** [comment]
Thanks!
hassos-boot partitions only contained some log files... Copied EFI folder and hassos booted.

PS: I rebooted PC after 0.5-1 hour after hassos update.

**Comment by haniffm** [comment]
@agners Thx for the help, but that did not work for me. I can also add that the size of the the `/EFI/barebox/state.dtb` was about 1.2 KB.

Any other ideas?

**Comment by agners** [comment]
@haniffm so you restored the whole boot partition and still get the "no valid targets" message?

**Comment by haniffm** [comment]
@agners that is correct. I mounted the partition as you discribed above and copied the entire hassos-boot partition sith `cp -r ...` command.

**Comment by atze09** [comment]
Same issue here need to do a fresh installation of 5.9.

**Comment by orohde** [comment]
I have the same issue. I restarted my NUC today and did not come up again. Upgraded to 5.9 a few days ago. I get the same error as above but I am only able to read it if I hold the Enter button, otherwise the screen is turning black right away.

**Comment by haniffm** [comment]
I'm guessing that this happened to me because I was a little bit impatient and forcefully rebooted the NUC. I have solved my problem by moving from HA OS install to a self maintained OS and HA in docker, because I don't want to experience this kind of downtime ever again.

However, I can still assist if there is a need for debugging this issue further (have the old install on a different drive).

**Comment by superm1** [comment]
Those affected, can you try `bootchooser -s` to reset the failed boot counter?
