### ISSUE TITLE
oDroid N2+: # CONFIG_HIDRAW is not set

### ISSUE THREAD

**Issue by mvieleers** [home-assistant/operating-system#1120]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [X] ODROID [C2/C4/N2(+)/XU4] (Home Assistant Blue device)
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [X] Updated from version 5.8 
- Additional information (if accessible): Home Assistant Blue came with 5.8, updated to 5.9

version: 2020.12.1
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.9.15
arch: aarch64
timezone: Europe/Amsterdam

GitHub API: ok
Github API Calls Remaining: 4501
Installed Version: 1.9.0
Stage: running
Available Repositories: 767
Installed Repositories: 28

logged_in: true
subscription_expiration: January 8, 2021, 1:00 AM
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: false
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 5.9
update_channel: stable
supervisor_version: 2020.12.7
docker_version: 19.03.13
disk_total: 113.9 GB
disk_used: 6.9 GB
healthy: true
supported: true
board: odroid-n2
supervisor_api: ok
version_api: ok
installed_addons: Check Home Assistant configuration (3.6.0), Samba share (9.3.0), Mosquitto broker (5.1), Terminal & SSH (8.10.0), deCONZ (6.6.1), AppDaemon 4 (0.3.2), Visual Studio Code (2.9.1), Home Assistant Google Drive Backup (0.102.0), rest980 Docker Image (20200205), php-nginx Docker Image (latest)

dashboards: 14
mode: auto-gen
resources: 18

api_endpoint_reachable: ok

- 20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS homeassistant/aarch64-hassio-dns with version 2020.11.0 - 172.30.32.3
20-12-22 09:57:27 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-audio with version 17
20-12-22 09:57:27 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_audio application
20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio homeassistant/aarch64-hassio-audio with version 17 - 172.30.32.4
20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-cli with version 2020.11.1
20-12-22 09:57:27 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
20-12-22 09:57:27 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_cli application
20-12-22 09:57:28 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI homeassistant/aarch64-hassio-cli with version 2020.11.1 - 172.30.32.5
20-12-22 09:57:28 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-observer with version 2020.10.1
20-12-22 09:57:28 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-multicast with version 3
20-12-22 09:57:28 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
20-12-22 09:57:28 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application
20-12-22 09:57:28 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/aarch64-hassio-multicast with version 3 - Host
20-12-22 09:57:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-22 09:57:29 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/odroid-n2-homeassistant with version 2020.12.1
20-12-22 09:57:29 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 33 Home Assistant secrets
20-12-22 09:57:29 INFO (MainThread) [supervisor.hassos] Detect HassOS 5.9 / BootSlot A
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/fe49a976 repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/7be23ff5 repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/39c40414 repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/7ad98f9c repository
20-12-22 09:57:29 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 77 new - 0 remove
20-12-22 09:57:29 INFO (MainThread) [supervisor.addons] Found 10 installed add-ons
20-12-22 09:57:29 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 5.1
20-12-22 09:57:29 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to webhippie/php-nginx with version latest
20-12-22 09:57:29 INFO (SyncWorker_9) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-samba with version 9.3.0
20-12-22 09:57:29 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 8.10.0
20-12-22 09:57:29 INFO (SyncWorker_8) [supervisor.docker.interface] Attaching to hassioaddons/vscode-aarch64 with version 2.9.1
20-12-22 09:57:29 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to 39c40414/aarch64-addon-rest980 with version 20200205
20-12-22 09:57:29 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to hassioaddons/appdaemon-aarch64 with version 0.3.2
20-12-22 09:57:29 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to sabeechen/hassio-google-drive-backup-aarch64 with version 3.12
20-12-22 09:57:29 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-deconz with version 6.6.1
20-12-22 09:57:29 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-check_config with version 3.6.0
20-12-22 09:57:29 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files
20-12-22 09:57:29 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
20-12-22 09:57:29 INFO (MainThread) [supervisor.ingress] Loaded 2 ingress sessions
20-12-22 09:57:29 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
20-12-22 09:57:29 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-22 09:57:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
20-12-22 09:57:30 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
20-12-22 09:57:30 INFO (MainThread) [__main__] Running Supervisor
20-12-22 09:57:30 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
20-12-22 09:57:30 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
20-12-22 09:57:30 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 1 add-ons
20-12-22 09:57:30 INFO (SyncWorker_8) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
20-12-22 09:57:30 INFO (SyncWorker_8) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 5.1
20-12-22 09:57:31 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
20-12-22 09:57:35 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 4 add-ons
20-12-22 09:57:35 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_core_samba application
20-12-22 09:57:36 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-samba with version 9.3.0
20-12-22 09:57:36 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_ssh application
20-12-22 09:57:36 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-ssh with version 8.10.0
20-12-22 09:57:36 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_deconz application
20-12-22 09:57:37 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-deconz with version 6.6.1
20-12-22 09:57:37 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_vscode application
20-12-22 09:57:38 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on hassioaddons/vscode-aarch64 with version 2.9.1
20-12-22 09:57:38 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_vscode
20-12-22 09:57:42 INFO (MainThread) [supervisor.core] Start Home Assistant Core
20-12-22 09:57:42 INFO (SyncWorker_6) [supervisor.docker.interface] Starting homeassistant
20-12-22 09:57:42 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
20-12-22 09:58:21 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-22 09:58:33 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
20-12-22 09:58:33 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 4 add-ons
20-12-22 09:58:33 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 8edd9ee6e8d8c0acb5dc15af0366c2be763c0e9dd1291ae623e71e90e5414089676b04c831a10db0c56a1a9aab3e7030c1046d26cbc447416cf04445a4360a29
20-12-22 09:58:33 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_appdaemon application
20-12-22 09:58:34 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on hassioaddons/appdaemon-aarch64 with version 0.3.2
20-12-22 09:58:34 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_cebe7a76_hassio_google_drive_backup application
20-12-22 09:58:35 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 3.12
20-12-22 09:58:35 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_39c40414_rest980 application
20-12-22 09:58:36 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on 39c40414/aarch64-addon-rest980 with version 20200205
20-12-22 09:58:36 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_39c40414_php-nginx application
20-12-22 09:58:37 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_appdaemon
20-12-22 09:58:37 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on webhippie/php-nginx with version latest
20-12-22 09:58:38 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup
20-12-22 09:58:38 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
20-12-22 09:58:38 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-12-22 09:58:38 INFO (MainThread) [supervisor.api.security] /snapshots/db22ae23/info access from cebe7a76_hassio_google_drive_backup
20-12-22 09:58:42 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-12-22 09:58:42 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-12-22 09:58:42 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-12-22 09:58:42 INFO (MainThread) [supervisor.host.info] Updating local host information
20-12-22 09:58:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-22 09:58:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
20-12-22 09:58:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
20-12-22 09:58:42 INFO (MainThread) [supervisor.host.services] Updating service information
20-12-22 09:58:42 INFO (MainThread) [supervisor.host.network] Updating local network information
20-12-22 09:58:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-12-22 09:58:43 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon
20-12-22 09:58:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-12-22 09:58:45 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-12-22 09:58:45 INFO (MainThread) [supervisor.host] Host information reload completed

**Kernel logs:**

**Description of problem:**

The image that comes pre-installed on the Home Assistant Blue (oDroid N2(+) seems to have HIDRAW support disabled. Therefore a device that needs to use this driver is not showing up under hardware in Supervisor. Using the same device on a raspberry pi 4b, with the 64-bit image, works flawlessly. The device is shown under hardware as /dev/hidraw0

I believe the issue is that the kernel module for HIDRAW is not enabled in the oDroid image.
Home Assistant Blue: 
~ $ gzip -d < /proc/config.gz | grep HIDRAW
# CONFIG_HIDRAW is not set

Can this kernel module be enabled like it is on the raspberry pi 4b 64-bit version?

- Is the problem reproducible? Yes
- Has this been working before (is this a regression?) No
- Has there been attempt to rule out harware issues? (different SD card etc.) Yes. Using the image for raspberry pi 4b 4gb 64-bit (https://github.com/home-assistant/operating-system/releases/download/5.9/hassos_rpi4-64-5.9.img.xz) the device that needs to use HIDRAW is working properly.

**Comment by agners** [comment]
Just wondering, what is your use case?

**Comment by mvieleers** [comment]
@agners I have an Alarm System (Jablotron 100). The system is connected to home assistant using a usb cable. Using the HACS package (https://github.com/kukulich/home-assistant-jablotron100) to read the status of devices and to interact with it.

**Comment by chadlyy** [comment]
Wyze Sense also uses hidraw:  https://github.com/kevinvincent/ha-wyzesense

**Comment by agners** [comment]
Fix will be in 5.10 onwards.

**Comment by chadlyy** [comment]
What is the targeted release date for 5.10?  Is that also the first Wednesday of every month? Thank you! :)
