### ISSUE TITLE
Raspberry pi 400 + SSD - HA 5.9 won't boot

### ISSUE THREAD

**Issue by ondrackajan** [home-assistant/operating-system#1134]
**Hardware Environment**

- [x] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release x.y
- [x] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

I'm unable to boot version 5.9 on my Pi 400 with SSD. I've used both update from UI (from version 5.8) and clean installation.
In both cases it's stuck in boot loop like I've experienced with versions 5.5 and lower on my Pi 400.

Version 5.8 works without a problem.

**Comment by alexbakrasp** [comment]
facing the same problem here!

**Comment by agners** [comment]
Hm, that is interesting. With 5.9 (see #1094) now actually deploy the correct device tree for this device, which if anything should make the Pi 400 properly work :-)

Do you see anything on the screen when the system is stuck? If so, can you make a screenshot?

Does SD card boot gets stuck too?

**Comment by alexbakrasp** [comment]
Its stuck in a boot loop (the power led Pi400 remains flashes in a sec). I dit not tried to boot it with an sd card.

**Comment by alexbakrasp** [comment]
Everithing works fine on HA 5.8...   see you all next year! ;-)

**Comment by ondrackajan** [comment]
> 
> 
> Hm, that is interesting. With 5.9 (see #1094) now actually deploy the correct device tree for this device, which if anything should make the Pi 400 properly work :-)
> 
> Do you see anything on the screen when the system is stuck? If so, can you make a screenshot?
> 
> Does SD card boot gets stuck too?

I'm unable to see anything on the screen as it keeps reconnecting the video source.

SD card boot is stuck too.

**Comment by BarBaar44** [comment]
Looks a lot like the issue I have/had with an Odroid C2.

The device is not booting with a fresh install. Also first installing HA 4.2 and then upgrading to HA 5.9 resulted in a unbootable situation..

Screen remains black, and not heartbeat (blue led) on the Odroid either...

**Comment by agners** [comment]
@BarBaar44 this is a different issue. Let's track it in #1142

**Comment by agners** [comment]
Fix will be in 5.10 onwards.
