### ISSUE TITLE
Prevent sd card breaking, let's join minds

### ISSUE THREAD

**Issue by Bellavista** [home-assistant/operating-system#1174]
Hi all!
I hope to open this thread correctly.
I have an Rsb 3+ 1gb with sd 32mb.
We are all familiar with the SD card crash problem and methods to delay the break.
The question is the following!
Before the breakdown, the system begins to give signs of malfunction which can be cofused.
I thought ... if I had a parameter, a sensor ... something to monitor before the break, I would avoid intervening only after the crash.
There is a sensor for the SD that you can check and get a warning!
SMART SD ... :) read and or write error sensor... wrong acces to memory sensor
My knowledge is limited I ask for help from the community
Thanks
Please don't answer change device!

**Comment by agners** [comment]
Harddisks such as S-ATA SSD drives have S.M.A.R.T. attributes which allow to read how the wear state of the flash cells.

Unfortunately, the SD card standard has no mechanism to read the state of the device.

Also the SD card fail in quite different ways. Some have read error, some just don't boot. I don't think that there is a reliable indication we could use.

The best thing is to use a storage drive which has a mechanism to read the state, e.g. a Intel NUC with S-ATA drive or the Home Assistant Blue which uses eMMC. eMMC usually hold longer, and they also report the estimated flash lifetime.
