### ISSUE TITLE
problem to reboot after HASSOS upgrade on RPI3b+

### ISSUE THREAD

**Issue by pilot1981** [home-assistant/operating-system#1221]
**Hardware Environment**
- [X] Raspberry Pi 3b+ with HASSOS booting from SSD disk USD attached

**Home Assistant OS release:**
- [X] Updated from version HASSOS 5.10 and Home Assistant 2021.2.2, core-2021.2.2,Versione Frontend: 20210127.7
- Additional information (if accessible):
please see attached screenshoot
![{B7265108-1135-486B-B219-5935203881B1} png](https://user-images.githubusercontent.com/46350465/107548791-5eee2600-6bcf-11eb-93cc-0d1ae2c88c02.jpg)

**Supervisor logs:**
please attached screenshoot

![eba216af25b628d4d26be080a9a0bc0a8e0457d3_2_666x500](https://user-images.githubusercontent.com/46350465/107548867-72998c80-6bcf-11eb-8a72-8d26abe51e7e.jpeg)

**Journal logs:**
journalctl don't exist

**Kernel logs:**
![eba216af25b628d4d26be080a9a0bc0a8e0457d3_2_666x500](https://user-images.githubusercontent.com/46350465/107549240-e0de4f00-6bcf-11eb-95ae-209f13c55803.jpeg)

**Description of problem:**
from many months, many releases, everytime I upgrade HASSOS, RPI3b+ stop on reboot phase (as you can see in picture). then I have to manually power off raspberry and then attach again power supply and it come back alive booting fine....
Reboot works fine when I use manual command and when I upgrade supervisor!

**Comment by agners** [comment]
Is that reproducible when manually trigger an update or downgrade? E.g. when you now move back to OS 5.10 using `ha os update --version 5.10` or/and when moving back to 5.11 using  `ha os update --version 5.11`?

**Comment by pilot1981** [comment]
Yes, sure!

**Comment by pilot1981** [comment]
@agners you need more info?

**Comment by agners** [comment]
Just tested with 5.12, downgrading to 5.11 and upgrading to 5.12 seems to work fine when booting from SD card. I guess it must be related to USB boot. Did you consider using the `datactl` approach? https://github.com/home-assistant/operating-system/blob/dev/Documentation/partition.md#data-disk

**Comment by pilot1981** [comment]
Hi,
thanks for reply!
I also think this could be related to use of USB disk, but my firend with the same architecture don't have same issue...


I wouldn't use both SD and USB disk...

we have any other way to try to solve it?

**Comment by agners** [comment]
> [..] but my firend with the same architecture don't have same issue...

That is a the problem with USB SSD support: There are so many combinations, and some work and some don't, and some just behave weird (like yours, works but doesnt reboot :man_shrugging: ). That is why we kinda try to move away from USB SSD support, as it is just hard to properly support.

What I would do is check if it also happens with Raspberry Pi OS. If so, then its likely a general kernel/firmware issue, and needs to be reported with the Raspberry Pi project.

Maybe forums help, e.g. a quick Google brought up this one: https://www.raspberrypi.org/forums/viewtopic.php?t=213394

**Comment by pilot1981** [comment]
I moved to SSD after 3 Sd Card broken...

**Comment by agners** [comment]
Sorry, I should have been a bit more specific,  USB SSD boot support.

Booting from SD card and using USB SSD just for data is more reliable as only LInux has to deal with the USB SSD (what I referred above with datactl approach, see https://github.com/home-assistant/operating-system/blob/dev/Documentation/partition.md#data-disk). We only write to the SD card when updating, as the root file system is read-only with Home Assistant OS.  So SD cards will wear-out a lot slower.

**Comment by pilot1981** [comment]
problem solved changing USB adapter and enabling TRIM!

I think i's sufficient change USB adapter to solved this issue!
