### ISSUE TITLE
REQUEST : Add Canbus support for like can2usb dongles

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/operating-system#1223]
Hi, this is a request for canbus ,canbus is widely used in car industry, but also in home automations...
There are dongles like https://canable.io/ to talk with the system

But we need to load an extra module loaded in kernel 'socketcan'

https://www.kernel.org/doc/html/latest/networking/can.html
https://en.wikipedia.org/wiki/SocketCAN

so we can make use of:

sudo modprobe can
sudo modprobe can_raw
sudo modprobe slcan

is this possible as a request?

more info : http://pascal-walter.blogspot.com/2015/08/installing-lawicel-canusb-on-linux.html

thnx and appreciated

EDIT : or is there a way to add those modules manually? any instruction is appreciated!
@pvizeli  , can you help me with this?

**Comment by pvizeli** [comment]
You can make an PR again https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/kernel/device-support.config - please test it before you make the PR public.

**Comment by pergolafabio** [comment]
ok, interesting allthough not sure what lines i need to add there? where can i find these for canbus?

**Comment by pergolafabio** [comment]
is it enought by adding like below? : 

config_can=y
config_vcan=y
config_can_raw=y
config_slcan=y

**Comment by pvizeli** [comment]
https://github.com/home-assistant/operating-system/tree/dev/Documentation

**Comment by pergolafabio** [comment]
ok, but if i make a PR wit these lines, you need to bring it in DEV before i can test it right?

```
CONFIG_CAN=m
CONFIG_CAN_RAW=m
CONFIG_CAN_VCAN=m
CONFIG_CAN_SLCAN=m
CONFIG_CAN_DEV=m
```

**Comment by pergolafabio** [comment]
done : 

https://github.com/home-assistant/operating-system/pull/1228

**Comment by pergolafabio** [comment]
merged in  : https://github.com/home-assistant/operating-system/pull/1228
