### ISSUE TITLE
Updating OS ERROR on Task exception was never retrieved

### ISSUE THREAD

**Issue by d4s1r** [home-assistant/operating-system#1226]
**Hardware Environment**

Raspberry Pi [3]
Operating System Family | Linux
Operating System Version | 5.4.79-v7
CPU Architecture | armv7l

**Home Assistant OS release:**
Version | 2021.1.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
- Additional information (if accessible):
Host Operating System | Home Assistant OS 5.10
Update Channel | stable
Supervisor Version | 2021.02.9
Docker Version | 19.03.13
Disk Total | 13.9 GB
Disk Used | 6.4 GB
Healthy | true
Supported | true
Board | rpi3
Supervisor API | ok
Version API | ok
Installed Add-ons | Terminal & SSH (8.9.1), Mosquitto broker (5.1), File editor (5.2.0), Happy Bubbles (3.1.4), Zigbee2mqtt (1.16.2.2)

**Supervisor logs:**
https://paste.ee/p/mSHvJ

**Journal logs:**
N/A

**Kernel logs:**
https://paste.ee/p/mSHvJ

**Description of problem:**

I tried to update the Core and the OS. It always stops throwing this exception. The changelogs refer to an old version of python no longer being available, which might hint to a connection to my issue.

**Comment by agners** [comment]
It seems that the system has problems reading data in general:

```
[ 2397.210416] SQUASHFS error: zlib decompression failed, data probably corrupt
[ 2397.210555] SQUASHFS error: squashfs_read_data failed to read block 0x1fc1be
```

This sounds like a broken SD card... I would try to create a snapshot, download it and move to a new card asap.

**Comment by d4s1r** [comment]
@agners Thank you very much. I was able to create a snapshot and recover the data on a new SD Card.
