### ISSUE TITLE
Can't run hassos in virtualbox on windows 10?

### ISSUE THREAD

**Issue by UnbendableStraw** [home-assistant/operating-system#1255]
**Hardware Environment**
Windows 10 Pro (up to date), Oracle VirtualBox 6.1.18
Virtualbox appliance configured for 4 cores, 4gb ram, bridged network adapter, EFI

Host: hp dl380 gen9 w/ intel xeon e3-1230 v6, 16gb ram

**Home Assistant OS release:**
HassOS 5.12 for Windows VirtualBox

**Description of problem:**

When I try to start the virtualbox application, it never loads and stops at "Loading MSDOS Executable "/mnt/system/bzImage" 

I've tried redownloading and reextracting the vdi file and remaking the appliance in virtualbox. What am I doing wrong?

![image](https://user-images.githubusercontent.com/22043907/109559430-80845400-7a8f-11eb-93b0-bad03671389c.png)

**Comment by agners** [comment]
I assume you are following the instructions provided here?
https://www.home-assistant.io/installation/windows

Not sure, but maybe the IDE Secondary Device, the optical drive causes problems. Can you disable it?

**Comment by UnbendableStraw** [comment]
The VirtualBox instructions leave little to miss;

```Create a new virtual machine
Select “Other Linux (64Bit)
Select “Use an existing virtual hard disk file”, select the VDI file from above
Edit the “Settings” of the VM and go “System” then Motherboard and Enable EFI
Then “Network” “Adapter 1” Bridged and your adapter.```

I've moved onto HyperV and its working fine there. Thank you
