### ISSUE TITLE
NUC Compatible - Shutdown doesn't power it off

### ISSUE THREAD

**Issue by marciogranzotto** [home-assistant/operating-system#1272]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [x] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 5.12
- [ ] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

![image](https://user-images.githubusercontent.com/11080704/111083746-c7d9fe00-84ed-11eb-81bb-da5845556727.png)

**Journal logs:**

**Kernel logs:**

**Description of problem:**

I'm using an off-brand (Shenzhen Tengyatong TG-J1800) Mini PC that uses an Intel Celeron J1800, 4GB of RAM, 128GB SSD.
The issue is if I try to shut it off, using either the Supervisor UI ( Supervisor > System > Shutdown Host ), or `ha host shutdown`, or even pressing the physical power button, the console shows all the shutdown logs, but then gets stuck on `Reached target Power-off` and doesn't power down the PC.
I tried to wait for like an hour, but it never powers down.

Here's a picture of the actual board for reference:
![image](https://user-images.githubusercontent.com/11080704/111083927-cb21b980-84ee-11eb-9740-bc7141947af5.png)

**Comment by marciogranzotto** [comment]
On other OS', like Proxmox, the same hardware has no problem powering down after the shutdown procedure.

**Comment by agners** [comment]
On x86 with modern ACPI a poweroff should be triggered by the kernel and lead to poweroff on ACPI side.

Do you use EFI boot for other OS' as well? Does maybe a BIOS update help? Another thing you can try is using one of the latest nightly builds which comes with a newer Linux kernel version: https://os-builds.home-assistant.io/6.0.dev20210311/

**Comment by marciogranzotto** [comment]
> Do you use EFI boot for other OS' as well?

yeah, its a regular Proxmox 6.3 installation, so I do think so.

> Does maybe a BIOS update help?

I tried to find a newer BIOS, but I had no luck, since this board is so off-brand

> Another thing you can try is using one of the latest nightly builds which comes with a newer Linux kernel version: https://os-builds.home-assistant.io/6.0.dev20210311/

I'll do that and report back

**Comment by marciogranzotto** [comment]
@agners Proxmox started to behave the same way. Also, the nightly build didn't work.
I guess the issue is on the BIOS 😕 
I'll close the issue for now. Thanks!
