### ISSUE TITLE
IPv4 forwarding to access local LAN

### ISSUE THREAD

**Issue by dec0dOS** [home-assistant/operating-system#1285]
**Home Assistant OS release:**
Home Assistant OS Release-5 build 12

**Description of problem:**
There is no option to enable ipv4 forwarding. It may be useful when using home assistant os device as an entry point to your home network.

Referring to https://github.com/hassio-addons/addon-zerotier/issues/23 with more description about the problem.

**Comment by agners** [comment]
Not sure if Home Assistant OS really should aim to become a router...

**Comment by frenck** [comment]
It also not the goal of that add-on to be that.
