### ISSUE TITLE
high CPU usage from plugin-audio

### ISSUE THREAD

**Issue by luka6000** [home-assistant/operating-system#1288]
**Hardware Environment**
- [X ] Raspberry Pi4

**Home Assistant OS release:**
ha > info
arch: armv7
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.12"
homeassistant: 2021.3.4
hostname: homeassistant
logging: info
machine: raspberrypi4
operating_system: Home Assistant OS 5.12
state: running
supervisor: 2021.03.6
supported: true
supported_arch:
- armv7
- armhf
timezone: Europe/Warsaw

**Description of problem:**

high CPU usage of plugin-audio

> ha > audio info
> audio:
> application: []
> card: []
> input: []
> output:
> 
> applications: []
> card: null
> default: true
> description: Dummy Output
> index: 0
> mute: false
> name: auto_null
> volume: 1
> host: 172.30.32.4
> update_available: false
> version: 2021.02.1
> version_latest: 2021.02.1
> 

It is the most CPU hungry process of all containers

> PID USER PR NI VIRT RES %CPU %MEM TIME+ S COMMAND
> 1169 root 20 0 87.8m 39.3m 0.0 2.1 24:01.66 S python3 -m supervisor
> 1760 root 20 0 789.6m 17.6m 0.7 0.9 9:04.55 S coredns -conf /etc/corefile
> 2499 root 9 -11 77.2m 4.7m 8.7 0.2 **594:06.99 S pulseaudio** --system -vvv --disallow-exit --exit-idle-time=-+
> 2761 root 20 0 0.7m 0.0m 0.0 0.0 3:10.00 S mdns-repeater -f eth0 hassio
> 3163 root 20 0 16.5m 15.8m 0.7 0.8 4:52.70 S mosquitto -c /etc/mosquitto.conf
> 3875 root 20 0 265.7m 67.9m 9.3 3.6 399:23.11 S deCONZ -platform xcb --auto-connect=1 --dbg-info=1 --dbg-ap+
> 2936 root 20 0 430.9m 270.0m 9.3 14.1 **41:33.77 S python3 -m homeassistant** --config /config
> 

Every second it takes 100% CPU core for a short while. It's 10x the actual homeassistant core process. And it logs a lot! My sd card won't make it for long with this amount of logs.
How can I disable audio plugin? I really don't need it.

**Comment by agners** [comment]
Probably the same as https://github.com/home-assistant/plugin-audio/issues/53
