### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [home-assistant/operating-system#1302]
**Hardware Environment**

- [x] Raspberry Pi [1/2/**3**/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 5.12
- [ ] Updated from version x.y
- Additional information (if accessible): Nothing

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Its clean and fresh install without any configuration, running on Raspberry Pi 3 64bit, I have tried `hassos_rpi3-64-5.12.img.xz` & `hassos_rpi3-5.12.img.xz` both of them have this problem.

```
Panic: runtime error: invalid memory address or nil pointer deference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3ee4d8]

goroutine 1 [running]:
github.com/home-assistant/cli/cmd.glob..func27(0x79a360, 0x7b71dc, 0x0, 0x0)
             /home/runner/work/cli/cli/cmd/banner.go:73 +0x198
github.com/spf13/cobra.(*command).ExecuteC(0x79f610, 0x1, 0x15538
```
its so much to write, please take a look at image.

![20210407_164128](https://user-images.githubusercontent.com/17345129/113865940-f59b2580-97c1-11eb-9374-7aa6843fd07a.jpg)

**Comment by agners** [comment]
The stack trace has been addressed with https://github.com/home-assistant/cli/pull/286. This will be fixed once new CLI/HA OS releases come out.

As for the other messages: You have to wait until the system is ready.
