### ISSUE TITLE
NUC D54250WYK: hassos_intel-nuc-5.13.img.xz installer fails to boot (reproducible)

### ISSUE THREAD

**Issue by evoncken** [home-assistant/operating-system#1358]
**Hardware Environment**
Intel NUC D54250WYK, Haswell CPU, latest BIOS (0054).

**Home Assistant OS release:**
Fresh installation via USB stick, hassos_intel-nuc-5.13.img.xz, flashed via BalenaEtcher as documented.

**Description of problem:**
When attempting UEFI boot with Secure Boot disabled, some text flashes by and boot appears to hang:
- non-blinking cursor in top left, F2/F7/F10/F12 POST hotkeys still displayed onscreen

When attempting Legacy boot, error message is displayed:
- "Reboot and Select proper Boot device
   or Insert Boot media in selected Boot device and press a key"

Attempted with 2 USB sticks, same results:
- BalenaEtcher flash/verify of Verbatim 32GB USB drive succeeded. This same drive was used for BIOS update beforehand.
- BalenaEtcher flash/verify of Sandisk 16GB USB drive succeeded. This was a new unused drive, still in packaging.

I took some high-speed video of the boot process in hopes of catching the text flashing by, and managed to transcribe most of it:

    bare box 2020.04.0 #1 The Apr 1 15:19:58 UTC 2021
   
    Board: bare box EFI payload
    EFI v2.31 by American Megatrends v262798
    efi-cs efi-cs: probe failed: No such device
    acpi2: Found XSDT (OEM: INTEL D5) with 13 entries
    efi-fs handle-0000000xxxxxxxx: mounted on /boot
    efi-fs handle-0000000xxxxxxxx: mounted on /efi1
    malloc space: 0x300000000 -> 0x3ffffffff (size 256 MiB)
    state: New state registered 'state'
    state: Using bucket 0@x00000000
    description: SATA : PORT 3 : Crucial_CT240M500SSD3: PART 0 : Boot Drive
    path: BSS-Harddrive()
    environment load /efivars/barebox-env-5b91f69c-8b88-4a2b-9269-5f1d802b5175: No s
    uch file or directory
    Maybe you have to create the partition.
    running /env/bin/init...
    - Hit m for menu or wait for autoboot -
    Booting entry 'bootchooser'
    Booting entry 'system0'
    ext4 ext40: probe failed: Invalid argument
    could not open /mnt/sysimage/bzImage: No such file or directory
    Booting entry 'system0' failed
    Booting entry 'bootchooser' failed
    Nothing bootable found

**Other variations attempted:**
- Enabled / disabled Secure Boot (clean config) --> no effect
- Reset all BIOS settings to default (F9) --> no effect

I cannot see why the installer claims "Nothing bootable found"

**Comment by evoncken** [comment]
Same issue reproduced with:
- Home Assistant OS Release-6 build 0 (RC1)
- HassOS Release-4 build 20 (Stable)

**Comment by evoncken** [comment]
Same issue reproduced on Intel NUC 5i3RYH

**Comment by agners** [comment]
You are trying to boot Home Assistant OS from a USB drive? This is currently not implemented for intel-nuc/generic-x86-64...

You have to install HA OS onto the internal boot medium directly (in your case a SATA disk from the looks). One way is using a external USB to SATA adapter, or boot a live distribution (e.g. Ubuntu) and use that live distribution to flash Home Assistant OS directly onto the internal SATA disk.

Unfortunately, the Intel NUC installation is not really clear about this fact.

**Comment by evoncken** [comment]
Hi agners, thanks for the reply.

It seems the NUC installation instructions are indeed incorrect ;-)
As a quick test, I've tried booting an Ubuntu live distro, and copied the image manually:

    sudo -i
    lsblk                     # this shows me that the mSATA disk is at /dev/sda
    cp /media/ubuntu/Sandisk16G/has* /tmp/   # Copy and unpack the hassos img.xz
    cd /tmp
    xz -d hassos_intel-nuc-5.13.img.xz
    dd if=/tmp/hassos_intel-nuc-5.13.img of=/dev/sda bs=4M conv=fsync

The NUC is set to Legacy boot, mSATA SSD is set to AHCI. Now, the system boots Home Assistant!

**Comment by evoncken** [comment]
I sent feedback for the NUC Installation page, with the steps I took to install HA

**Comment by agners** [comment]
The NUC/generic-x86-64 installation page got updated since this issue has been opened. Assume fixed.
