### ISSUE TITLE
Bluetoothctl : waiting for bluetoothd

### ISSUE THREAD

**Issue by GuillaumeDen** [home-assistant/operating-system#1367]
## Hardware Environment
- [x] Raspberry Pi 3b+
- [x] PiZiGate Hat (used in ZHA integration)

## System Health

version | core-2021.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v7
arch | armv7l
timezone | UTC

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 13.9 GB
disk_used | 3.4 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.0), Terminal & SSH (9.1.1)

</details>

## Description

I just wanted to add a bluetooth keyboard to my installation, in order to use the "Keyboard Remote" integration.
So I installed the "Terminal & SSH" addon, in order to have an access to bluetoothctl for pairing my device.

```
~ $ bluetoothctl
Waiting to connect to bluetoothd...
```

And the terminal is stuck here, nothing moves, nothing happens, just waiting.
I see nothing in logs related to bluetooth.

**Comment by agners** [comment]
On which Home Assistant OS Version is this? Use `ha info` to get the OS version as well.

Just tested on a Raspberry Pi 3 and 3+ using 6.0.rc2, it seems to work here:
```
~ $ bluetoothctl 
Agent registered
[CHG] Controller B8:27:EB:63:F4:E1 Pairable: yes
[bluetooth]#
```
