### ISSUE TITLE
The console shell doesn't respawn when exited

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/operating-system#1387]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [x] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

KVM on running on Ubuntu 20.04 using VNC to access the console

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [x] Updated from version x.y
- Additional information (if accessible):

Updated from 5.13 to 6.0rc3

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

The latest change to skip the login at the console and go straight to the root shell is welcome, but the shell doesn't auto-respawn if I exit it inadvertently.  It used to go back to the login prompt in 5.x and allow another login, but now I'm stuck until I reboot the VM if I exit the shell (with ctrl-D, for instance).

**Comment by agners** [comment]
I was able to reproduce and fix this. Nice find, thanks for reporting!
