### ISSUE TITLE
On fresh 6.1 installation, if reboot system, it crashes

### ISSUE THREAD

**Issue by Rockman18** [home-assistant/operating-system#1435]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [x] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 6 build 1
- [ ] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

![IMG_20210628_220241](https://user-images.githubusercontent.com/1739183/123714533-c94ded00-d876-11eb-951d-c3c9b0583e16.jpg)
![IMG_20210628_220359](https://user-images.githubusercontent.com/1739183/123714536-ca7f1a00-d876-11eb-98aa-c01a5fc45cb3.jpg)

**Description of problem:**

After a fresh installation of the latest release 6 build 1 on a Intel NUC like system (Lenovo Thinkcentre M700 Tiny, Intel G4400T, 4GB of RAM, 500GB HDD). I use balena etcher to burn haos_generic-x86-64-6.1.img.xz on the HDD, then boot for the first time without issue.
After minimal configuration (create user and home), I try to restart the system but boot process crash with following issue.
I try to reboot several times but nothing works, so i reburn the img OS and retry but it's exactly the same. (first boot ok, then crash)

**Comment by agners** [comment]
Hm, what type of harddrive is this?

It seems the bootloader really has trouble writing or reading from it, as it reports I/O error when trying to save the boot state as well as trying to access the kernel partition.

**Comment by Rockman18** [comment]
It was a 500GB Seagate Laptop Thin HDD without any issue by the past. I've replaced it with a PNY SSD and every thing's ok now.

**Comment by agners** [comment]
> It was a 500GB Seagate Laptop Thin HDD without any issue by the past. I've replaced it with a PNY SSD and every thing's ok now.

Thanks for the update! I guess an hardware issue then. Just had a HDD fail on my this week as well :( Unrelated to HAOS though.

Closing as I'd consider it as a hardware issue.
