### ISSUE TITLE
Feature Request: HAOS image for LXD VM

### ISSUE THREAD

**Issue by xiki808** [home-assistant/operating-system#1438]
LXD allows for creating containers and also VMs. I have tried this and it works great. The only thing that is missing for a perfect scenario is to have a HAOS with lxd-agent. This will allow me to access and run commands in the VM from my bash script that automates my whole server setup. Would it be possible to provide an Image for the operating system including the agent?

**Comment by pvizeli** [comment]
Please make an post on: https://community.home-assistant.io/c/feature-requests - this is issue only
