### ISSUE TITLE
SSL problem with the new HA OS 6.2

### ISSUE THREAD

**Issue by victorputroagung** [home-assistant/operating-system#1489]
**Hardware Environment**
Raspberry Pi [4]

**Home Assistant OS release:**
Updated from version 6.1 to 6.2

**Description of problem:**
after updating to 6.2 from 6.1
can't access to grafana graph or tasmo admin gui at another port.
i suspect that the SSL is the problem.

nothing changed at my config, nor do my network.
tried to fresh install through balena again but the problem still persist.

![Screenshot 2021-08-03 182032](https://user-images.githubusercontent.com/40070719/128007125-049d5b6b-d263-4fbd-ac66-ca15266ba79e.jpg)
![Screenshot 2021-08-03 182116](https://user-images.githubusercontent.com/40070719/128007130-69d861d1-5e66-4e8f-82c9-53b2588b1f01.jpg)

**Comment by agners** [comment]
Hm, those we interface are not provided by the operating system itself, but by the Tasmo/Graphana add-on.

To validate that the OS indeed is not the problem, can you downgrade to 6.1? Using the following command in the terminal should do it:

```
ha os update --version 6.1
```

**Comment by victorputroagung** [comment]
> Hm, those we interface are not provided by the operating system itself, but by the Tasmo/Graphana add-on.
> 
> To validate that the OS indeed is not the problem, can you downgrade to 6.1? Using the following command in the terminal should do it:
> 
> ```
> ha os update --version 6.1
> ```

ill try to downgrade it today, will post an update later :)

**Comment by victorputroagung** [comment]
> Hm, those we interface are not provided by the operating system itself, but by the Tasmo/Graphana add-on.
> 
> To validate that the OS indeed is not the problem, can you downgrade to 6.1? Using the following command in the terminal should do it:
> 
> ```
> ha os update --version 6.1
> ```

you were right, seems like the problem is at the ISP itself. ill close the issue, thanks for helping! :)
