### ISSUE TITLE
Fresh Install never boots

### ISSUE THREAD

**Issue by damusmf** [home-assistant/operating-system#1500]
**Hardware Environment**

- [ ] Generic x86-64 (like Intel NUC)
- [ ] Dell Optiplex 5090 Ultra
- [ ]  Intel Core i5- 1145G7
- [ ] 16GB RAM
- [ ] M.2 512GB PCIe NVMe

**Home Assistant OS release:**
- [ ] Fresh installation of release 6.2

- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Not entirely sure how to provide useful info here.  Had a new-ish unused optiplex 3090 ultra laying around and wanted to test out HA OS.  Booted to a ubuntu live cd and burned the image onto the internal drive using Etcher.  Reboot and it just hangs,  currently sitting at "waiting for root device PARTUUID=SomeLongString"

Attempted reburning multiple times but it never finishes the boot process.  If i plug in/unplug USB devices i do get messages on the screen so the whole thing isn't just locked up.  Can also type into the console but it does nothing.  Attaching pictures of where it gets stuck and then what happens when i plug in and unplug a device.  My guess is something in this computer just is not compatible with HA OS currently and i will have to try a different machine. 

![stuck](https://user-images.githubusercontent.com/31552122/128646742-9ed847b4-a0a2-4022-9d0f-47b3cc266b77.jpg)
![plugin](https://user-images.githubusercontent.com/31552122/128646746-3a3d2891-f3f4-4978-bb53-682c1ba5475c.jpg)
![unplug](https://user-images.githubusercontent.com/31552122/128646777-fe2947ec-e2fc-4906-9915-918db130a06e.jpg)

**Comment by damusmf** [comment]
Can close this.  In BIOS needed to switch drive type from the default RAID to the AHCI/NVME option.

**Comment by agners** [comment]
Thanks for the update!
