### ISSUE TITLE
hass constantly crashes, general instability

### ISSUE THREAD

**Issue by zolstarym** [home-assistant/operating-system#1501]
**Hardware Environment**

- [x] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [x ] Updated from version 21.8.0
- Additional information (if accessible):

logs unavailable due to crash. Hass crashes before I could get any logs

**Description of problem:**

- Is the problem reproducible?
yes

- Has this been working before (is this a regression?)
yes
- Has there been attempt to rule out hardware issues? (different SD card etc.)
yes

When using hass OS 21.8.4 on raspberry pi 4, it becomes unstable quickly after plugging it in. Unstable on new installs as well.

**Comment by agners** [comment]
> [x ] Updated from version 21.8.0

21.8.0 is not the version number of the OS.  Which version of the Operating System image did you install? (You can find the current and older release images here: https://github.com/home-assistant/operating-system/releases).

There is 32-bit and 64-bit version, which version have you been using?

Does the same hardware work stable when using Raspberry Pi OS?

**Comment by zolstarym** [comment]
6.2 64 bit
The pi previously ran ubuntu before and seemed stable for a few days, but I never tested for more than that.

**Comment by lepeli** [comment]
I had issues before 6.0 where my raspberry pi would crash randomly every day. It didn't really happen that much in 6.0 but after updating to 6.2 I had this issue again. 

I did downgrade again to 6.0 and it fixed this issue. 

if you want to downgrade you can probably use the SSH addon, and then type 
```bash
ha os update --version 6.0 
```
And it should downgrade the OS. I just don't know if it works using the SSH addons tho.


If a maintainer sees this, how can we provide you data when something like this happens to us ?

**Comment by zolstarym** [comment]
still happening
