### ISSUE TITLE
shelly mqtt and webos-tv

### ISSUE THREAD

**Issue by manustars** [home-assistant/operating-system#1502]
Hi everyone, I've been hitting my head for a while but I can't get over it.

there are a couple of problems that came up after the updates.

1. shelly cover - I integrated the shellys through mqtt without using the native integration for greater control, but the configuration performed as per procedure does not take into account the values ​​set "position_open / position_closed", I have respectively set them to 95 / 5, but the command via google home always takes 100/0 (like the default one), I state that it worked normally with previous versions.

2. webostv 1.4, even if the addition is done correctly I can see the status of the TV, turn it off and change the volume, the ignition no longer works and the thumbnails of the sources are sometimes seen and sometimes not. Even this with previous versions worked fine.

I leave some logs hoping it will be useful.

HAINFO installed on vmware esxi
~ $ ha info
arch: amd64
channel: stable
docker: 20.10.6
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- hassos
hassos: "6.2"
homeassistant: 2021.8.5
hostname: jarvis
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 6.2
state: running
supervisor: 2021.06.8
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Rome

HA SU LOGS
21-08-10 08:27:25 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-08-10 08:31:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-10 09:01:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-10 09:03:44 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-08-10 09:27:25 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-08-10 09:29:55 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-08-10 09:30:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-08-10 09:31:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-10 10:01:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-10 10:03:18 INFO (MainThread) [supervisor.host.info] Updating local host information
21-08-10 10:03:18 INFO (MainThread) [supervisor.host.services] Updating service information
21-08-10 10:03:19 INFO (MainThread) [supervisor.host.network] Updating local network information
21-08-10 10:03:19 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-08-10 10:03:19 INFO (MainThread) [supervisor.host] Host information reload completed
21-08-10 10:03:46 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-08-10 10:27:25 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-08-10 10:30:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-08-10 10:30:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-08-10 10:30:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-08-10 10:30:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
21-08-10 10:30:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
21-08-10 10:31:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-10 10:49:40 INFO (MainThread) [supervisor.snapshots] Creating new partial-snapshot with slug ba827c8b
21-08-10 10:49:40 INFO (MainThread) [supervisor.snapshots] Snapshotting ba827c8b store folders
21-08-10 10:49:40 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-08-10 10:50:04 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-08-10 10:50:04 INFO (MainThread) [supervisor.snapshots] Creating partial-snapshot with slug ba827c8b completed
21-08-10 10:50:04 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.8.5
21-08-10 10:50:04 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2021.8.4 to ghcr.io/home-assistant/qemux86-64-homeassistant:2021.8.5
21-08-10 10:50:04 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2021.8.5.
21-08-10 10:50:09 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-10 10:50:09 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/ba827c8b/info access from cebe7a76_hassio_google_drive_backup
21-08-10 10:50:10 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/36d50dd4/remove access from cebe7a76_hassio_google_drive_backup
21-08-10 10:50:10 INFO (MainThread) [supervisor.snapshots] Removed snapshot file 36d50dd4
21-08-10 10:50:10 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/ba827c8b/download access from cebe7a76_hassio_google_drive_backup
21-08-10 10:50:10 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot ba827c8b
21-08-10 10:50:57 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-10 10:50:58 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-10 10:51:59 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping homeassistant application
21-08-10 10:52:06 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning homeassistant application
21-08-10 10:52:06 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
21-08-10 10:52:07 INFO (SyncWorker_4) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/qemux86-64-homeassistant with version 2021.8.5
21-08-10 10:52:07 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-08-10 10:52:11 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-08-10 10:52:11 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-10 10:52:47 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-08-10 10:52:47 INFO (MainThread) [supervisor.homeassistant.core] Successful started Home Assistant 2021.8.5
21-08-10 10:52:47 INFO (SyncWorker_2) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/qemux86-64-homeassistant:2021.8.4']
21-08-10 10:55:47 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-08-10 10:55:47 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-08-10 10:55:47 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
21-08-10 10:55:47 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
21-08-10 10:57:57 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from core_ssh

**Comment by agners** [comment]
This repository is about issues related to Home Assistant OS. Your problem seem more about [Home Assistant Core](https://github.com/home-assistant/core/) itself.

Also this kind of initial investigation/requests are better discussed in the community: https://community.home-assistant.io/. Once the problem is somewhat isolated, you should create a separate issue for each problem.
