### ISSUE TITLE
WIFI not supported for NUC6

### ISSUE THREAD

**Issue by eriknn** [home-assistant/operating-system#1505]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [X ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [X ] Fresh installation of release 6.1
- [X ] Updated from version 6.1
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**
[    1.440938] Intel(R) Wireless WiFi driver for Linux
[    1.442043] iwlwifi 0000:01:00.0: enabling device (0000 -> 0002)
[    1.461405] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-36.ucode failed with error -2
[    1.462608] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-35.ucode failed with error -2
[    1.463859] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-34.ucode failed with error -2
[    1.465145] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-33.ucode failed with error -2
[    1.466367] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-32.ucode failed with error -2
[    1.467424] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-31.ucode failed with error -2
[    1.468514] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-30.ucode failed with error -2
[    1.469903] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-29.ucode failed with error -2
[    1.471767] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-28.ucode failed with error -2
[    1.473944] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-27.ucode failed with error -2
[    1.475711] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-26.ucode failed with error -2
[    1.476919] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-25.ucode failed with error -2
[    1.478163] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-24.ucode failed with error -2
[    1.479419] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-23.ucode failed with error -2
[    1.480964] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8000C-22.ucode failed with error -2
[    1.482331] iwlwifi 0000:01:00.0: no suitable firmware found!
[    1.483201] iwlwifi 0000:01:00.0: minimum version required: iwlwifi-8000C-22
[    1.484004] iwlwifi 0000:01:00.0: maximum version supported: iwlwifi-8000C-36
[    1.484006] iwlwifi 0000:01:00.0: check git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

**Description of problem:**
Some older NUCs use Intel® Wireless-AC 8260 WIFI chipset, and firmware for this is not included in the OS. Seeing that NUCs are among recommended and popular devices for HASS, I think these drivers should be included.

**Comment by eriknn** [comment]
Actually I see the following:
BR2_PACKAGE_LINUX_FIRMWARE_IWLWIFI_8000=y
in buildroot-external/configs/generic_x86_64_defconfig

I would expect this to be the correct option - so why isn't the driver in the OS then?

**Comment by agners** [comment]
The package is actually named `BR2_PACKAGE_LINUX_FIRMWARE_IWLWIFI_8000C`. Just created a PR to fix the name and add some other firmwares.

**Comment by agners** [comment]
The firmware will be part of OS release 6.3 onward.
