### ISSUE TITLE
DS9490R not recognized by HomeAssistent

### ISSUE THREAD

**Issue by sipodd** [home-assistant/operating-system#1513]
DS9490R is not recognized or mounted by HomeAssistent
Raspberry Pi 4 & ODROID N2+
Fresh installation of release 
Home Assistant OS 6.2

# ha info
arch: aarch64
channel: stable
docker: 20.10.6
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- hassos
hassos: "6.2"
homeassistant: 2021.8.8
hostname: homeassistant
logging: info
machine: odroid-n2
operating_system: Home Assistant OS 6.2
state: running
supervisor: 2021.06.8
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Berlin

When i plug it in (either Raspberry 4 or Odroid N2+) i see the device beeing recognized as a new USB device:
Host log:
[ 5665.309943] usb 1-1.4: new full-speed USB device number 8 using xhci-hcd

But thats all, its not mounted and can not be used by owserver addon.

I tried the DS9490R Stick on a PC and it works just fine.

I`m not sure if there is any other information i can provide, please let me know if this is the case.
I'm quite sure this has been reported in the stale & closed issue #883 

cheers Simon

**Comment by agners** [comment]
More often than hooking up this kind of devices (like 1-wire and other sensors) through a ESPHome device is more flexible and easier. Since there is an add-on which can deal with 1-wire devices and just a driver is needed I'll add it to the OS.

**Comment by agners** [comment]
After looking at the owserver add-on I am pretty sure that  enabling this server will not help you: owserver talks via serial port (UART) to the chip. What you are using is a 1-Wire stick directly, so Linux will be the 1-Wire master.

**Comment by sipodd** [comment]
I got 1-wire sensors running via ESPHome, too :-)
But i also got an existing "bus" with several sensors attached, that i would like to bring into HA.
On another Linux Server this works like a charm, but i would really like to have it consolidated to my odroid, hanging in the electrical subdistribution, fuse box....how ever it is called in english (where all the cables come together).

I was hoping to beeing able to get [hassio-owserver addon](https://github.com/irybak/hassio-owserver) running, if the stick is getting recognized and mounted.

**Comment by agners** [comment]
> On another Linux Server this works like a charm,

What software are you using there?

> I was hoping to beeing able to get hassio-owserver addon running

The addon talks to 1-Wire devices which are exposed as serial ports to Linux (the example mentions that MERA-PROJECT device, which comes with a FTDI FT232RL USB to serial adapter, and a DS2480B serial to 1-wire.

What you own is a USB to 1-wire device directly. This is under Linux *not* exposed as a serial port, but as a "true" 1-wire device (which seems to be exposed via sysfs and netlink, see https://www.kernel.org/doc/html/latest/w1/w1-generic.html).

**Comment by sipodd** [comment]
Any ideas when this might get into a release?
