### ISSUE TITLE
WIFI unreachable if not also connected to ethernet

### ISSUE THREAD

**Issue by ozziej** [home-assistant/operating-system#1514]
Hardware
- [ ] Raspberry Pi 3

**Home Assistant OS release:**
Fresh installation of release of Home Assistant 2021.8.8

**Supervisor logs:**
Cannot retrieve 

**Journal logs:**
Cannot retrieve 

**Kernel logs:**
Cannot retrieve 

**Description of problem:**
Yes, completely.
Install new fresh SD card with HASS on Pi3.
Wait 20 minutes for config.
Standard login / setup.
(Connected via Ethernet)
Go to Supervisor -> System -> Host -> IP address -> Change.
Select WIFI - Connect to WiFi
Set IPV4 Address either with DHCP or Static.
Confirm it works by browsing to HA from NEW IP address  (Works)
Disconnect ethernet network cable
Can no longer connect via IPV4 Address on Wifi

(Also unable to retrieve logs as the add on store ALSO does not work so I cannot install the SSH client)

**Comment by agners** [comment]
Just tried to reproduce this on a Raspberry Pi 3 64-bit: It seems to work here: Connect via WiFi, remove Ethernet and I was still able to connect via WiFi. I am using Home Assistant OS 6.2, Home Assistant 2021.9.1 and Supervisor 2021.08.1.  What version of OS/Supervisor specifically have you been using?
