### ISSUE TITLE
Unable to load add-on store

### ISSUE THREAD

**Issue by ozziej** [home-assistant/operating-system#1515]
**Hardware Environment**
- [ ] Raspberry Pi [3]

**Home Assistant OS release:**
- [ ] Fresh installation of Home Assistant 2021.8.8
- Additional information (if accessible):
## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Africa/Johannesburg

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 13.9 GB
disk_used | 2.0 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Supervisor logs:**
Cannot Retrieve 
**Journal logs:**
Cannot Retrieve 
**Kernel logs:**
Cannot Retrieve 

**Description of problem:**
I cannot get the add-on store to display.
When selecting Supervisor -> Add on Store -> nothing loads, continually shows the rotating icon.
Nothing more happens.

**Comment by agners** [comment]
This is probably caused by network connectivity issues.

You can also check if there is something in the resolution center via HA CLI:

```
ha > resolution info
```
