### ISSUE TITLE
Driver for Ralink MT7601U Wireless USB Adapter

### ISSUE THREAD

**Issue by iosoft** [home-assistant/operating-system#1520]
**Hardware Environment**
Raspberry Pi 3

**Home Assistant OS release:**
Fresh installation of release: 6.2
Core: 2021.8.8

**Description of problem:**
Dear @agners , can you pls include the Driver for Ralink MT7601U Wireless USB Adapter in the upcoming version of Home Assistant?
It will be a great help for me. These adapters are very cheap, common, good speed and good performance. It also supports monitor mode and AP (which is not needed in HA :P) I use/need this as I can use a better wifi antenna for better coverage.

In my Raspberry Pi OSMC, it is auto detected as -
`Bus 001 Device 004: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter`
But not in HA.

It will be a great help for me if you can add the driver in future release.

Thanking you for your great work.

**Comment by agners** [comment]
This will be resolved from 6.3 onwards.
