### ISSUE TITLE
Hue gu10 and lightbulb problem.

### ISSUE THREAD

**Issue by najklez** [home-assistant/operating-system#1521]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [X ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
-  [X] Oracle VM
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [ X ] Updated from version x.y
- Additional information (if accessible): 
- updated from 2021.1.5 to 2021.8.8
## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4890
Installed Version | 1.13.2
Stage | running
Available Repositories | 920
Installed Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 19, 2021, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.08.1
docker_version | 19.03.15
disk_total | 28.8 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), File editor (5.2.0), Duck DNS (1.12.1), Terminal & SSH (8.6.0), deCONZ (6.10.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 15
views | 13
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Supervisor logs:**
21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.check] System checks complete 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING 21-09-02 06:19:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete 21-09-02 06:19:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 06:49:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 07:19:55 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.check] System checks complete 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING 21-09-02 07:19:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete 21-09-02 07:19:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository 21-09-02 07:19:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository 21-09-02 07:19:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_post' is deprecated, 'backup_post' should be used instead. Please report this to the maintainer of MariaDB 21-09-02 07:19:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_pre' is deprecated, 'backup_pre' should be used instead. Please report this to the maintainer of MariaDB 21-09-02 07:19:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of deCONZ 21-09-02 07:19:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_post' is deprecated, 'backup_post' should be used instead. Please report this to the maintainer of MariaDB 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_pre' is deprecated, 'backup_pre' should be used instead. Please report this to the maintainer of MariaDB 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of deCONZ 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller 21-09-02 07:19:59 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome 21-09-02 07:19:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove 21-09-02 07:19:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove 21-09-02 07:19:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 07:39:59 INFO (MainThread) [supervisor.host.info] Updating local host information 21-09-02 07:39:59 INFO (MainThread) [supervisor.host.services] Updating service information 21-09-02 07:39:59 INFO (MainThread) [supervisor.host.network] Updating local network information 21-09-02 07:40:01 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information 21-09-02 07:40:01 INFO (MainThread) [supervisor.host.manager] Host information reload completed 21-09-02 07:50:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.check] System checks complete 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING 21-09-02 08:19:56 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete 21-09-02 08:20:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 08:50:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token 21-09-02 08:57:29 INFO (MainThread) [supervisor.backups.manager] Found 26 backup files 21-09-02 08:57:29 INFO (MainThread) [supervisor.backups.manager] Found 26 backup files 21-09-02 09:00:43 INFO (MainThread) [supervisor.backups.manager] Found 26 backup files 21-09-02 09:00:43 INFO (MainThread) [supervisor.backups.manager] Found 26 backup files

**Journal logs:**

**Kernel logs:**

**Description of problem:**
Have a lot of autmations and scripts that use effect: colorloop. After updating to 21.8.8 colorloop don't work on  Hue lightbulb and Hue gu10. Still working on Hue ledstripe. 
 Yes.

**Comment by agners** [comment]
> updated from 2021.1.5 to 2021.8.8

This is a core version, and the description of your problem sounds like a issue in Core. Please check if the problem has already been reported and report if not in the Core repository: https://github.com/home-assistant/core/
