### ISSUE TITLE
CC2652R is slow after update to 6.3

### ISSUE THREAD

**Issue by pro2call-nl** [home-assistant/operating-system#1537]
The problem
My system is running Z2M under 6.2 this was working fine. I have upgraded to 6.3 and now there is lag in signal's. If i switch an lightbulb "on" it takes 10 sec's to turn on. if i look at the mqtt explorer the on command is send immediately to mqtt. in the log of Z2M the command comes but takes a time to been sent.

I believe this is an issue with the kernel.

Please see:

https://github.com/Koenkk/zigbee2mqtt/issues/8623
 
What is version of Home Assistant Core has the issue?
core-2021.9.3

What was the last working version of Home Assistant Core?
core-2021.9.2

What type of installation are you running?
Home Assistant OS

Integration causing the issue
No response

Link to integration documentation on our website
No response

Example YAML snippet
No response

Anything in the logs that might be useful for us?
No response

Additional information
No response

**Comment by Koenkk** [comment]
Same root cause as https://github.com/home-assistant/operating-system/issues/1532
