### ISSUE TITLE
How to make the generated hassos image file contain the hassos addon application by default

### ISSUE THREAD

**Issue by darcyg** [home-assistant/operating-system#1542]
hi,
My hassos environment:
odroid-c4 emmc16G. The compilation branch is rel-6.
I am learning to develop hassos. Currently adjust the makefile. Support proxy download and some buildroot package compilation, kernelmenuconfig and other functions.
I am studying the use of buildroot-external/package/hassio. I hope to add more default addons, such as mosquitto/porttainor/red-node/appdaemon to the installation image and work by default.
Because it is difficult to connect to docker and other websites on the Chinese network, it is difficult to install various ha addons, mainly when downloading or when there is an http request, abnormal errors will occur, usually the network connection timeout.Docker or the system needs to be configured with vpn to stabilize the network.

Hope to give some help. Thank you

**Comment by agners** [comment]
Currently `buildroot-external/package/hassio` only installs plug-ins, which is slightly different from Add-Ons. From what I know, Add-Ons installation is more involved. You probably need to study the Supervisor code (github.com/home-assistant/supervisor) to understand what an add-on installation exactly does, and replicate that in `buildroot-external/package/hassio`.

The #dev_os channel on Discord is probably the better platform to discuss this topic.
