### ISSUE TITLE
energy dashboard data moved up a place in most recent update

### ISSUE THREAD

**Issue by bartgrefte** [home-assistant/operating-system#1579]
**Hardware Environment**
- [X] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
VMWare Workstation 15.5.6 build-16341506 on a system with the following hardware: Shuttle XPC slim DH310, i3 8100, 16GB RAM, MX500 500GB 2.5" SATA SSD. Host OS is Windows 10 x64.

**Home Assistant OS release:**
- Additional information (if accessible):
## System Health

version | core-2021.10.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.62
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.6
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.1.3), File editor (5.3.3), SQLite Web (3.1.0), Mosquitto broker (6.0.1), Glances (0.13.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

**Description of problem:**
Updating core-2021.9.7 to core-2021.10.0 breaks the energy dashboard, it looks like all data on the graphs has moved one place back. Accumulative data for today (7th) is displayed on the 6th, data of the 6th is displayed on the 5th. The monthly accumulation of this month is listed above september, data of september above august. and data on the year tab is suddenly displayed in 2020 instead of 2021.

Backup restore of core-2021.9.7 solves the problem, data in energy dashboard is displayed correctly again.

There also seems to be a lack of electricity data during the hours HASS OS was on core-2021.10.0, everything electricity related comes in through mqtt, incoming data seems to have stopped after upgrade to core-2021.10.0 and started coming in again after downgrade.

- Has this been working before (is this a regression?)
No problem in core-2021.9.7, problem in core-2021.10.0
- Has there been attempt to rule out hardware issues? (different SD card etc.)
Seems a software problem, triggered by most recent update.

**Comment by agners** [comment]
This seems not OS related but Core. Please submit an issue in the core repository: https://github.com/home-assistant/core/issues/new/choose
