### ISSUE TITLE
can‘t update Home Assistant Operating System

### ISSUE THREAD

**Issue by gx19970920** [home-assistant/operating-system#1591]
**Hardware Environment**

- [x] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [x] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

 21-10-12 22:37:42 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot kernel.0: Opening output device /dev/disk/by-partlabel/hassos-kernel0 failed: Device or resource busy
**Journal logs:**

**Kernel logs:**

**Description of problem:**

when I want to update theHome Assistant Operating System from 6.3 to 6.5, it failed, how can I fix this problem

**Comment by agners** [comment]
Is the kernel log (Host log from the Supervisor -> System page) showing any clue? Is updating after reboot working?

**Comment by agners** [comment]
Sounds like there was a problem reading that partition. Are you using an SD card? If so, maybe it gets it caused some problems.

Closing for now then. Feel free to reopen in case you can reproduce again and seems not a hardware failure.
