### ISSUE TITLE
Fresh install to emergency console

### ISSUE THREAD

**Issue by SummerSeaSun** [home-assistant/operating-system#1594]
Hi,

Followed: https://www.home-assistant.io/installation/raspberrypi

I've writtend this image: 

`https://github.com/home-assistant/operating-system/releases/download/6.5/haos_rpi4-64-6.5.img.xz`

to an SD, then plug it on raspberry pi4, then rebooted twice with same result:

```
Waiting for the HOME Assistant CLI to be ready
WARNING load emergency cli
#
```

No web console is available, console is available.
BR

**Comment by Summer88** [comment]
Thanks for the reply, the pi4 ethernet is connected to internet,  from emergency console I can see that eth0 is up and can reach google, but browsing **pi4ip::8123** got connection refused.
Anyway it takes more than five minutes to boot, I've re booted again and tried `systemd-analyze time` but command doesn't exist.
