### ISSUE TITLE
Unable to change hostname

### ISSUE THREAD

**Issue by fencer** [home-assistant/operating-system#1597]
Just installed Home Assistant OS 64bit (Home Assistant OS 7.0.dev20211012) on a PI compute 4 . when I try to change the hostname I get this error: 

`[homeassistant.components.hassio] Failed to to call /host/options - Error: GDBus.Error:org.freedesktop.hostname1.ReadOnlyFilesystem: /etc/hostname is in a read-only filesystem.`

**Comment by agners** [comment]
Fixed with #1617.
