### ISSUE TITLE
HA cloud turns off random plugs/lights

### ISSUE THREAD

**Issue by Mpgod80** [home-assistant/operating-system#1603]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [x] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [x ] Updated from version 6.4
- Additional information (if accessible):

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.70
arch | aarch64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4934
Installed Version | 1.15.2
Stage | running
Available Repositories | 952
Installed Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 3 november 2021 1:00
relayer_connected | true
remote_enabled | false
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.0
docker_version | 20.10.7
disk_total | 113.9 GB
disk_used | 19.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | TellStick (2.1.0), Node-RED (10.0.1), Terminal & SSH (9.2.1), File editor (5.3.3), Visual Studio Code (3.6.2), Grafana (7.2.0), InfluxDB (4.2.1), AppDaemon 4 (0.7.0), Z-Wave JS (0.1.45), Z-Wave JS to MQTT (0.27.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 6
-- | --
resources | 7
views | 7
mode | storage

</details>

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

My Home assistant is turning off lights randomly, and this time it turned off the z-wave plug that my Odroid is getting power from.  
In the logbook i see the following event : "20211021  22:10:44 - Tv vardagsrum turned off by Home Assistant Cloud"

Why did HA cloud turn this plug off? I have no schedule for that plug at all. It should always be on.
This problem has been present since i upgraded from OS version 6.2.

And the supervisor and other logs i can´t post because the Odroid got powerless when this happened....

I got more logs from the logbook for other dates, where different lights has been turned off by HA cloud.

**Comment by ukrolelo** [comment]
I would suggest turn off goole assistant in HA and see?

**Comment by austwhite** [comment]
I have seen this behaviour also, usually it is a command that got delayed somewhere and repeated.

I honestly am not sure this is an OS issue though.  This would be a Nabu Casa cloud related issue, not an OS related issue.

I ended up stopping it by turning off Google in the cloud and using the manual work around.  No more phantom light commands after that

**Comment by agners** [comment]
I use ODROID-N2 and haven't seen such things with Google cloud.

> Be aware, if you use the Nabu Casa cloud, even if you do not issue a voice command, commands go to your Voice Assistants when they are setup to keep the status of devices updated. If this is delayed/corrupted/packet lost for some reason, this may also cause the cloud to change the status of a device to what it thinks it should be.

Hm, that is interesting. I must say, I configured Google cloud to only push certain states to the cloud, so I am probably less affected.

> I honestly am not sure this is an OS issue though. This would be a Nabu Casa cloud related issue, not an OS related issue. The cloud component is what integrates with Google Home and Alexa's ecosystem

Agreed. The OP claimed it started with an OS update.. I guess some lower level problems (e.g. unreliable network in this case?) could trigger problems on different problems. Whenever issues appear with a new OS release, to prove that it is really OS related I always recommend to downgrade and see if it really is happening.

I am going to close this for now.
