### ISSUE TITLE
haos_rpi3-64-6.6 ethernet stucks getting eth0 IP configuration

### ISSUE THREAD

**Issue by walking-octopus** [home-assistant/operating-system#1616]
**Hardware Environment**
- [x] Raspberry Pi 3
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Appliance, on Intel NUC or any other hardware, please add the Hypervisor you are using)
- [ ] Khadas VIM3

**Home Assistant OS release:**
- [x] Fresh installation of haos_rpi3-64-6.6
- [x] Updated from version haos_rpi3-64-6.4
- Additional information (if accessible): I updated from 64-6.4 to 64-6.6, and in a day I couldn't reach web UI. I connected HDMI and saw no IP address. After a day of debugging, I realized that it couldn't get an IP configuration. I reinstalled Home Assistant and still had this issue, but installing haos_rpi3-64-6.5 immediately fixed it.

**Description of problem:**
- Is the problem reproducible?  Yes, it is. I reproduced this issue several times.
- Has this been working before (is this a regression?):  Yes. It worked on haos_rpi3-64-6.4 and haos_rpi3-64-6.5.
- Has there been an attempt to rule out hardware issues? (different SD card etc.)  Yes. I tried several Ethernet cables and reflashed the SD card.

**Comment by walking-octopus** [comment]
After two days, the same issue reappeared on 6.5. Here's the NetworkManager log.

![IMG_20211030_113231~2](https://user-images.githubusercontent.com/46994949/139526749-90670c93-89ae-4633-b602-d32077e7bb24.jpg)

**Comment by walking-octopus** [comment]
It seems comical, but it actually was the router. After rebooting the router, it immediately got an IP.

**Comment by agners** [comment]
Thanks for the update!
