### ISSUE TITLE
Uncorrected timezone Russia/Moscow after update to 10.7 and upper series core

### ISSUE THREAD

**Issue by frfstu** [home-assistant/operating-system#1630]
After update HaOS camera stream incorrect displayed time (for gtm+3). If HaOS & camera software time settings changed GTM +3, displayed realtime -1 hour, if HaOS & camera time settings changed GTM +2, displayed realtime -2 hours.
Camera sonoff(ewelink).
How change ntp server on HaOS and change time zone settings in system?

**Comment by agners** [comment]
Please, don't just skip all the question when opening an issue! Instead answer them properly. It helps us to better understand your setup.

Anyways, this is unlikely an Home Assistant OS issue: The OS itself does not set a time zone, it runs in UTC. Home Assistant Core manages time zones on its own. The Supervisor sets the time zone for all Add-ons (check `ha su info` to see what time zone is configured). However, Add-ons need to have time zone data installed (package named `tzdata` or similar).

If you are using an Add-on, I'd suggest to create an issue on the Add-on repository.
