### ISSUE TITLE
The VMware OVA file for "Home Assistant OS Release-6 build 6" is flagged by Microsoft Edge Chromium as "not-secure"

### ISSUE THREAD

**Issue by davide-italy** [home-assistant/operating-system#1632]
The VMware OVA file for "Home Assistant OS Release-6 build 6" is flagged by Microsoft Edge Chromium as "not-secure" and download is blocked.

The URL is: https://github.com/home-assistant/operating-system/releases/download/6.6/haos_ova-6.6.ova

**Comment by agners** [comment]
Not sure under what basis Microsoft Edge Chromium declares it as "not-secure". The ending `ova` is the official ending for Open Virtual Appliance (see also https://en.wikipedia.org/wiki/Virtual_appliance).

Also the URL/server is GitHub, this really shouldn't be considered as un-safe per-se.

Not sure what is going on here. I think I'd report an issue with the Microsoft Edge Chromium team or use a browser which can handle `ova` files.
