### ISSUE TITLE
Intermittently very slow, high cpu usage in Virtual box

### ISSUE THREAD

**Issue by vandad51** [home-assistant/operating-system#1646]
### Describe the issue you are experiencing

The issue seemed to start once I installed the Nortek Husbzb combo stick (I had to install the expansion pack for Vbox). I can't confirm it was a direct cause though. Access to my HA instance from my ios app made me aware to the problem as accessibility to HA was hit and miss. As well as my internet being very slow as it's redirected through AdGaurd. I checked my Surface tablet running the VM, and it was at a steady 40-60% usage. Yet when I check the supervisor, the cpu usage charts report normal 2-10% usage. I can try to access backups with CLI but it's extremely slow [(I'll try to attach a video)](https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FATy-HtI6vv0TzIVSMIFAun2BCeZjAQC5HSTS-ycqCkcgaipa5vYgSc48%2F%24%7Bf%7D%3Fo%3DAoshrMW519hlIADDHS0uMEhPjheVW3njgh9fpSKcs08C%26v%3D1%26x%3D3%26a%3DCAogrXeDfJ_5JxrXvZRV_YBwNqVZM6wRbrxNxQTMBam2czsSdhDAje2G0S8YwJ3o2tovIgEAKgkC6AMA_0zVY9pSBIEJ5mNaBCBJzjxqJdVTr8dmfN_USECMlWumlYo5eDryAiIbLGG6qw-gEhSSvP7cLlJyJWYm25GlhGNYHcNvJSivF6a_gTBFYpXpirgccAn7uCr_l39J-Qk%26e%3D1639257345%26fl%3D%26r%3D14085061-6495-4CD3-B58B-5A2959EAEE39-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D538DE0E2-391E-4C23-9197-3B0C0ADB61BB%26p%3D41%26s%3DX3aoG9QX5DhpgIbVBeKlL8rKloA&uk=sNZHsfO0g0cqaCuGjTOoRQ&f=IMG_8477.MOV&sz=141656223) Also some errors that came up while trying to restore a backup to a few days ago.
![IMG_8478](https://user-images.githubusercontent.com/88515012/141370583-2229b888-0b87-4eaf-98e7-1cd6d68dffd6.JPG)

I'm running HAos 11.1, Can't see supervisor version right now as it's still stuck restoring a backup. VirtualBox 6.1.26. I should also say that i tried to update vbox a week ago and home assistant would not start up with vbox showing a error. I downgraded back to the current version that was working and it was back to normal.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

at this point, the problem is constant. Sometimes it cools off and the CPU load drops back to normal, but then within 5 minutes its back to 40-60% usage 

### Anything in the Supervisor logs that might be useful for us?

```txt
This was after i got it to start back up again, and it seems to be running fine at the moment.
21-11-11 16:31:21 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-11-11 16:31:21 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-cli with version 2021.09.0
21-11-11 16:31:21 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
21-11-11 16:31:21 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning hassio_cli application
21-11-11 16:31:23 INFO (SyncWorker_1) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/amd64-hassio-cli with version 2021.09.0 - 172.30.32.5
21-11-11 16:31:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-dns with version 2021.06.0
21-11-11 16:31:23 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
21-11-11 16:31:23 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_dns application
21-11-11 16:31:26 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS homeassistant/amd64-hassio-dns with version 2021.06.0 - 172.30.32.3
21-11-11 16:31:26 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-11-11 16:31:26 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-audio with version 2021.07.0
21-11-11 16:31:26 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-11-11 16:31:26 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning hassio_audio application
21-11-11 16:31:29 INFO (SyncWorker_1) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/amd64-hassio-audio with version 2021.07.0 - 172.30.32.4
21-11-11 16:31:29 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-observer with version 2021.10.0
21-11-11 16:31:29 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-multicast with version 2021.04.0
21-11-11 16:31:29 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
21-11-11 16:31:29 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application
21-11-11 16:31:31 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host
21-11-11 16:31:31 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-11-11 16:31:31 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
21-11-11 16:31:31 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/qemux86-64-homeassistant with version 2021.11.1
21-11-11 16:31:31 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 6.4 / BootSlot A
21-11-11 16:31:35 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-11-11 16:31:35 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-11-11 16:31:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 62 all - 62 new - 0 remove
21-11-11 16:31:39 INFO (MainThread) [supervisor.addons] Found 12 installed add-ons
21-11-11 16:31:39 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/amd64 with version 3.6.2
21-11-11 16:31:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/adguard/amd64 with version 4.1.9
21-11-11 16:31:39 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.3.3
21-11-11 16:31:39 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-duckdns with version 1.14.0
21-11-11 16:31:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-samba with version 9.5.1
21-11-11 16:31:39 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-vlc with version 0.1.3
21-11-11 16:31:39 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/log-viewer/amd64 with version 0.12.0
21-11-11 16:31:39 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/node-red/amd64 with version 10.0.0
21-11-11 16:31:39 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 6.0.1
21-11-11 16:31:39 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/glances/amd64 with version 0.13.0
21-11-11 16:31:39 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-ssh with version 9.1.3
21-11-11 16:31:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-zwave_js with version 0.1.45
21-11-11 16:31:39 INFO (MainThread) [supervisor.backups.manager] Found 9 backup files
21-11-11 16:31:39 INFO (MainThread) [supervisor.discovery] Loaded 4 messages
21-11-11 16:31:39 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-11 16:31:39 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-11-11 16:31:39 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-11 16:31:39 INFO (MainThread) [__main__] Running Supervisor
21-11-11 16:31:40 INFO (MainThread) [supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
21-11-11 16:31:40 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-11-11 16:31:40 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 0 add-ons
21-11-11 16:31:40 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 5 add-ons
21-11-11 16:31:40 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_samba application
21-11-11 16:31:41 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-samba with version 9.5.1
21-11-11 16:31:41 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_vscode application
21-11-11 16:31:43 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/default/info access from core_samba
21-11-11 16:31:44 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/vscode/amd64 with version 3.6.2
21-11-11 16:31:44 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_adguard application
21-11-11 16:31:47 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/adguard/amd64 with version 4.1.9
21-11-11 16:31:48 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_duckdns application
21-11-11 16:31:52 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-duckdns with version 1.14.0
21-11-11 16:31:52 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_vlc application
21-11-11 16:31:56 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/default/info access from a0d7b954_adguard
21-11-11 16:31:56 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-vlc with version 0.1.3
21-11-11 16:32:02 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-11-11 16:32:02 INFO (SyncWorker_5) [supervisor.docker.interface] Starting homeassistant
21-11-11 16:32:03 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-11-11 16:32:21 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
21-11-11 16:32:21 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-11 16:32:23 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-11 16:33:01 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-11-11 16:33:01 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 2 add-ons
21-11-11 16:33:01 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_configurator application
21-11-11 16:33:05 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-configurator with version 5.3.3
21-11-11 16:33:05 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_a0d7b954_logviewer application
21-11-11 16:33:09 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/log-viewer/amd64 with version 0.12.0
21-11-11 16:33:14 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-11-11 16:33:14 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-11-11 16:33:14 INFO (MainThread) [supervisor.host.info] Updating local host information
21-11-11 16:33:14 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-11-11 16:33:14 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-11-11 16:33:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-11-11 16:33:14 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-11 16:33:15 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-11 16:33:16 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-11 16:33:16 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-11 16:33:16 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-11 16:33:16 INFO (MainThread) [supervisor.host.services] Updating service information
21-11-11 16:33:16 INFO (MainThread) [supervisor.host.network] Updating local network information
21-11-11 16:33:17 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-11-11 16:33:17 INFO (MainThread) [supervisor.host.manager] Host information reload completed
```

### Anything in the Host logs that might be useful for us?

```txt
I can't access logs atm.
```

### System Health information

<html>
<body>

Version | core-2021.11.1
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.62
CPU Architecture | x86_64

</body>
</html>

**Comment by agners** [comment]
> What operating system image do you use?
> 
> generic-x86-64 (Generic UEFI capable x86-64 systems)

That image is meant for bare-metal machines. Try using the OVA (open virtualization appliance) images.

**Comment by vandad51** [comment]
Ok sorry. I see haos_ova-6.1.vdi is that what you’re referring to?

**Comment by vandad51** [comment]
I did seem to find a correlation to what starts the high CPU usage. Below is my supervisor log. After doing a complete system reboot, it runs fines until it says "Starting system checks with state CoreState.RUNNING". It seems like the high usage starts as soon as the first check happens, and then it stays high. This is while my tablet is idle at home, me not tinkering on it.

21-11-12 11:52:47 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-12 11:52:47 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-12 11:53:18 INFO (MainThread) [supervisor.host.info] Updating local host information
21-11-12 11:53:19 INFO (MainThread) [supervisor.host.services] Updating service information
21-11-12 11:53:19 INFO (MainThread) [supervisor.host.network] Updating local network information
21-11-12 11:53:19 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-11-12 11:53:19 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-11-12 11:54:16 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 12:24:16 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-12 12:52:47 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-12 12:53:05 INFO (MainThread) [supervisor.backups.manager] Found 11 backup files
21-11-12 12:53:07 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-11-12 12:54:17 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 13:24:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-12 13:52:47 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-12 13:53:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-11-12 13:53:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-11-12 13:53:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 62 all - 0 new - 0 remove
21-11-12 13:53:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 62 all - 0 new - 0 remove
21-11-12 13:54:19 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 13:59:59 INFO (MainThread) [supervisor.host.info] Updating local host information
21-11-12 14:00:00 INFO (MainThread) [supervisor.host.services] Updating service information
21-11-12 14:00:00 INFO (MainThread) [supervisor.host.network] Updating local network information
21-11-12 14:00:00 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-11-12 14:00:00 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-11-12 14:24:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-12 14:52:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-11-12 14:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-11-12 14:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-11-12 14:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-11-12 14:52:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-12 14:52:48 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-12 14:53:07 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-11-12 14:54:21 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

**Comment by vandad51** [comment]
![713DF9A7-B647-4562-9CDB-473A9405B0D4](https://user-images.githubusercontent.com/88515012/141649346-52caa94f-76ce-4369-ae93-5a7841d99b92.jpeg). I did find this interesting though. Not sure if that’s home assistant using the CPU or Linux

**Comment by agners** [comment]
> Ok sorry. I see haos_ova-6.1.vdi is that what you’re referring to?

My point is, you claim you are using `generic-x86-64`. You should not be using the `generic-x86-64` images for virtualization, but the `ova` images. The complete system health should tell what image you are exactly using.

**Comment by vandad51** [comment]
My issue ended up being a Vm issue with hypervisor being enabled on my PC, and vbox out dated by one version. I disabled hypervisor and updated vbox and my problems have stayed away now for several weeks now.

**Comment by agners** [comment]
Thanks for the update! I guess with hypervisor you mean Microsoft's Hyper-V?

**Comment by vandad51** [comment]
Oh yes. Sorry, I’ve seen hypervisor around the web lately and forgot it’s called Hyper-V
