### ISSUE TITLE
Latest update version 7.0 fails to update from 6.6

### ISSUE THREAD

**Issue by NVader2000** [home-assistant/operating-system#1662]
### Describe the issue you are experiencing

When I click on update now it appears to go through the steps to update but never completes. Logs do not appear to show anything wrong.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

6.6

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Clicked Update now.
2. Waiting, waiting, waiting...

### Anything in the Supervisor logs that might be useful for us?

```txt
Not that I can see
```

### Anything in the Host logs that might be useful for us?

```txt
Not that I can see
```

### System Health information

  Not that I can see

### Additional information

  Not that I can see

**Comment by vikdb** [comment]
Have the same problem, keeps failing to update and no errors in supervisor log.
( also cant disable the backup, i have a feeling its backup related )

**Comment by Zahnweh** [comment]
Same here.

**Comment by jlt24** [comment]
Same Here

**Comment by gfn256** [comment]
Same here

**Comment by drMaxxi** [comment]
Here too

**Comment by jlt24** [comment]
When I try to install again I get the message
"Version 7.0 is already installed"

**Comment by Tykwondo1** [comment]
Same here

**Comment by Tykwondo1** [comment]
After several try with my PC, I tried with my ipad app and it worked

**Comment by NVader2000** [comment]
Tykwondo1, are you trying to update the mobile app or the Core OS for HA? People here are having issue with the Core OS. I tried to update the Core OS using my mobile device, same issue. Also, tried InPrivate and a different browser. Apparently, there is a bug.

**Comment by NVader2000** [comment]
Apparently, this is not isolated to Pi. I see other post for other platforms having similar issue. However, some are successful, but breaks other stuff. Do not think that 7.0 is a good build and I will wait for the devs to fix this before installing.

**Comment by obfri** [comment]
same here, backups were generated  but looks that update stops after backup. No entries in log showing download activity.

**Comment by chrisrock1984** [comment]
#me too

**Comment by NVader2000** [comment]
Apparently, this is not isolated to Pi. I see other post for other platforms have similar issue. However, some are successful, but breaks other stuff. Do not think that 7.0 is a good build and I will wait for the devs to fix this before installing.

**Comment by nunosousa76** [comment]
Same issue with upgrade except mine is from rc1

**Comment by Tarabozo** [comment]
Same issues. VM with HA on Windows NUC. The update to 7.0 is automatically starts a backup first. This backup takes 40-45 minutes, but after that the update it's not done. I see no errors in the logs. I tried twice, same situation. I see 2 new backups, but the update is not done.
Maybe if we have the manual option to skip the backup, the update process will start.

**Comment by agners** [comment]
Some browsers (especially Firefox) sometimes don't update the frontend correctly after the intsallation. Try Ctrl+F5 to force a refresh and check the installed version again.

If that does not help, then please share the Supervisor log so we can better analyze the problem.

**Comment by obfri** [comment]
tried it again, now it works. Even core update to 12.0 and supervisor to 12.1 works. Only missing http://192.168.xxx.xxx:8123/hassio/dashboard ("Supervisor") at sidebar.

**Comment by Xerionty** [comment]
> tried it again, now it works. Even core update to 12.0 and supervisor to 12.1 works. Only missing http://192.168.xxx.xxx:8123/hassio/dashboard ("Supervisor") at sidebar.

https://www.home-assistant.io/blog/2021/12/11/release-202112/#brand-new-configuration-panel

**Comment by NVader2000** [comment]
Nope, still not work for me. Are the devs looking at this?

**Comment by ahvink** [comment]
same here.....

**Comment by OrionVIII** [comment]
tried again, still the same (RPi3 with 64GB SD card). More than 40GB free space. The backup is created and then nothing happens, no hint in the logfile.

**Comment by Sailman83** [comment]
Same here with Rasperry Pi 3B

**Comment by aee74** [comment]
Same issue. Creating backup ...  waiting. Nothing

**Comment by elcatedratico** [comment]
Same problem here... tried to upgrade from 6.2 to 7.0 several times. Its just creating a backup (can't unselect this option) an then it stops

Log:
21-12-12 19:17:18 INFO (SyncWorker_0) [supervisor.backups.backup] Backup folder homeassistant done
21-12-12 19:19:18 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 51335fdd completed
21-12-12 19:19:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-12-12 19:31:18 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete

**Comment by MB901** [comment]
Finally worked for me after several try and a host reboot ! (RPI4)

**Comment by NVader2000** [comment]
Yup, got past this finally. Created full backup, wiped MicroSD, and reinstall HA version 7.0, restore from backup. Done!

**Comment by mdehaas** [comment]
No issues with the update on the beta channel on HA Blue

**Comment by agners** [comment]
@elcatedratico thanks for the logs!

Do you have maybe also a time stamp when the backup started? How long did the backup take?

**Comment by agners** [comment]
It seems that the issue is related to the backup happening before the update.

If the update through the UI fails, can affected people try to use the Terminal Add-on and the command `ha os update --version 7.0` instead of the UI?

**Comment by duncanbarnes** [comment]
> It seems that the issue is related to the backup happening before the update.
> 
> If the update through the UI fails, can affected people try to use the Terminal Add-on and the command `ha os update --version 7.0` instead of the UI?

This seems to have worked for me!

**Comment by Tarabozo** [comment]
> It seems that the issue is related to the backup happening before the update.
> 
> If the update through the UI fails, can affected people try to use the Terminal Add-on and the command `ha os update --version 7.0` instead of the UI?

This worked for me also. Thank you.

**Comment by johnjoemorgan** [comment]
> It seems that the issue is related to the backup happening before the update.
> 
> If the update through the UI fails, can affected people try to use the Terminal Add-on and the command `ha os update --version 7.0` instead of the UI?

This failed for me.  I'm on 

core-2021.12.0
supervisor-2021.12.1

Supervisor log shwows an end of file error:

`21-12-13 11:38:52 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/zerotier/armv7 with version 0.12.1
21-12-13 11:38:52 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/log-viewer/armv7 with version 0.12.1
21-12-13 11:38:52 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-mosquitto with version 6.0.1
21-12-13 11:38:52 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-samba with version 9.5.1
21-12-13 11:38:52 INFO (SyncWorker_9) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/motioneye/armv7 with version 0.16.0
21-12-13 11:38:53 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/armv7 with version 9.1.1
21-12-13 11:38:53 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/grafana/armv7 with version 7.3.2
21-12-13 11:38:53 INFO (SyncWorker_8) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/influxdb/armv7 with version 4.3.0
21-12-13 11:38:53 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/phpmyadmin/armv7 with version 0.6.0
21-12-13 11:38:53 INFO (SyncWorker_10) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-mariadb with version 2.4.0
21-12-13 11:38:53 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-edge-armv7 with version edge
21-12-13 11:38:53 INFO (SyncWorker_11) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-configurator with version 5.3.3
21-12-13 11:38:53 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to sabeechen/hassio-google-drive-backup-armv7 with version 0.105.2
21-12-13 11:38:53 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to homeassistant/armv7-addon-check_config with version 3.9.0
21-12-13 11:38:53 INFO (MainThread) [supervisor.backups.manager] Found 3 backup files
21-12-13 11:38:53 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/backup/33acc5f9.tar: unexpected end of data
21-12-13 11:38:53 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
21-12-13 11:38:53 INFO (MainThread) [supervisor.ingress] Loaded 3 ingress sessions
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-13 11:38:53 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-12-13 11:38:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-13 11:38:53 INFO (MainThread) [__main__] Running Supervisor
21-12-13 11:38:53 INFO (MainThread) [supervisor.os.manager] Rauc: B - marked slot kernel.1 as good
21-12-13 11:38:53 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-12-13 11:38:53 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 3 add-ons`

**Comment by johnjoemorgan** [comment]
Sorry Code insert's not working correctly for me

Error line is

21-12-13 11:38:53 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/backup/33acc5f9.tar: unexpected end of data

**Comment by johnjoemorgan** [comment]
The CLI breaks my install and the restart fails even before I can get a SSL link up.  I have to disconnect power from the XU4 and power up again to get it to restart.

Supervisor and general log show no errors relating to the OS

**Comment by elcatedratico** [comment]
Update by unsing the Terminal worked for me! (Had problems with the Terminal under MacOS and iOS, WinOS was fine)

**Comment by vlad36N** [comment]
Same here, backups were generated but looks that update stops after backup. No entries in log showing download activity.

**Comment by mrkaqz** [comment]
> ha os update --version 7.0

Yes, this is problem for me for awhile. 
As before I always skip backup and go ahead for an update in previous UI.
But after latest update it has no option to skip backup. 

I have tried many times but stuck at backup and gave error.

Finally using Terminal and update command to successfully update to 7.0

**Comment by obfri** [comment]
does mandatory update make sense? Not for me - I'm running daily updates by "Home Assistant Google Drive Backup". And these mandatory updates are deleting other full updates ...

**Comment by aee74** [comment]
> > ha os update --version 7.0
> 
> 
> 
> Yes, this is problem for me for awhile. 
> 
> As before I always skip backup and go ahead for an update in previous UI.
> 
> But after latest update it has no option to skip backup. 
> 
> 
> 
> I have tried many times but stuck at backup and gave error.
> 
> 
> 
> Finally using Terminal and update command to successfully update to 7.0
> 
> 

How to update from terminal

**Comment by agners** [comment]
> does mandatory update make sense? Not for me - I'm running daily updates by "Home Assistant Google Drive Backup". And these mandatory updates are deleting other full updates ...

Mandatory updates? I guess you meant mandatory backup.

That seems to be a problem in the frontend. It [just got fixed](https://github.com/home-assistant/frontend/pull/10886), so with the next Supervisor update it should no longer make a backup on OS updates.

**Comment by agners** [comment]
> How to update from terminal

See https://github.com/home-assistant/operating-system/issues/1662#issuecomment-991976712

**Comment by johnjoemorgan** [comment]
@agners They are referring to the the using command line code via a SSL terminal.  Explaining what that is and how to use it is not for here but you can look at official addons for the SSL && Web Terminal addon or the hit-hub page here: https://github.com/hassio-addons/addon-ssh

**Comment by johnjoemorgan** [comment]
Manual update using terminal does not work (via the UI or Putty) for the Odroid XU4

**Comment by phcella** [comment]
Update via terminal worked for me. I guess the problem is the mandatory backup. 
I have problems when I try to update core with backup. When I disable the backup, it updates normally

**Comment by dgultig** [comment]
Update via terminal did the job for me as well.

Still missing the Supervisor icon in the sidebar though.

**Comment by AlecRust** [comment]
> Still missing the Supervisor icon in the sidebar though.

https://www.home-assistant.io/blog/2021/12/11/release-202112/#brand-new-configuration-panel

**Comment by dgultig** [comment]
My bad @AlecRust, thank you

**Comment by OrionVIII** [comment]
Yeah, `ha os update --version 7.0` via ssh worked! Thank you.

**Comment by nmsousa76** [comment]
a os update --version 7.0 via ssh worked for me as well

**Comment by Vaargk** [comment]
For me the command does not work:
![Screenshot from 2021-12-14 11-36-56](https://user-images.githubusercontent.com/50966627/145982440-ac228a33-731c-48de-bd1a-5e8e213a97c9.png)
![Screenshot from 2021-12-14 11-41-42](https://user-images.githubusercontent.com/50966627/145983333-4728e527-213d-41df-9200-5fd3e9ff257b.png)
![Screenshot from 2021-12-14 11-40-34](https://user-images.githubusercontent.com/50966627/145983348-0bf470c9-c9c2-4113-9052-7d6e08356db7.png)

And indeed the url is wrong [url](https://github.com/home-assistant/operating-system/releases/download/7.0/haos_rpi0-w-7.0.raucb). Does someone knows how to give HA the correct update URL?

**Comment by stigvi** [comment]
> For me the command does not work: ![Screenshot from 2021-12-14 11-36-56](https://user-images.githubusercontent.com/50966627/145982440-ac228a33-731c-48de-bd1a-5e8e213a97c9.png) ![Screenshot from 2021-12-14 11-41-42](https://user-images.githubusercontent.com/50966627/145983333-4728e527-213d-41df-9200-5fd3e9ff257b.png) ![Screenshot from 2021-12-14 11-40-34](https://user-images.githubusercontent.com/50966627/145983348-0bf470c9-c9c2-4113-9052-7d6e08356db7.png)
> 
> And indeed the url is wrong [url](https://github.com/home-assistant/operating-system/releases/download/7.0/haos_rpi0-w-7.0.raucb). Does someone knows how to give HA the correct update URL?

Same happens with a smal system I have. It is running on a Rpi Zero W. It fails with "Error raised from OTA Webserver: 404"

**Comment by NVader2000** [comment]
I have completely reflashed the HA OS 7.0 to my MicroSD card and started from scratch. Fortunately have all my stuff documented so I was able to manual rebuild everything without using backups.

However, I am finding a lot of issues/errors even with the supported integrations. HACS, is a nightmare to say the least. Almost, every HACS integration fails to show up as a card and/or entities. If you like your HACS integrations do not upgrade or rebuild to HA OS 7.0. Your mileage may vary.

**Comment by colotroy1** [comment]
I'm not able to update OS.  I never have since I initially installed 6.2.  I've tried using the GUI and CLI ha update os and that doesn't work either.   I wonder if this is because I'm using a RP4 and external SSD drive rather than a micro mem card?

I guess my option is to pull the SSD, whipe it and install OS 7.0, but I've tried to upgrade the OS before and it appears to work but on reboot it's always the same.   Could this be specific to using an external SSD in the RP4?

**Comment by colotroy1** [comment]
AH-HA!  Ok, No matter what I did I could not get an upgrade to work and when I'd login with SSH and enter ha os info it would tell me 6.2.  I starting thinking about the external SSD and I pulled the micro SSD and rebooted and it came up as 7.0!

So the upgrade worked!  However the core upgrade I'd done earlier, that worked, was now gone and I had to upgrade the core again.  It looks like there's an issue if you have the micro card in the RP4 AND are using an external SSD.  After pulling the micro card the upgrades worked for me.

**Comment by gcoupe** [comment]
@colotroy1 - thanks for this tip. You solved a mystery for me as well.

**Comment by agners** [comment]
The Frontend/Supervisor do not trigger a backup before update anymore, which should solve the problem for most of you. not 

The OP @NVader2000 solved it by reinstalling.

@colotroy1 are you using Firefox? The Frontend sometimes doesn't update properly with Firefox.

In any case, this wasn't a bug in OS itself and I consider the problem solved.
