### ISSUE TITLE
"Supervisor" (http://192.168.xxx.xxx:8123/hassio/dashboard) missing at sidebar

### ISSUE THREAD

**Issue by obfri** [home-assistant/operating-system#1667]
### Describe the issue you are experiencing

With latest update "supervisor" entry at sidebar is missing.
Environtent: Rpi 4
Home Assistant OS 7.0
supervisor-2021.12.1
core-2021.12.0
Even not selectable within user profile

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

7.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

update system to latest  versions

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by AlecRust** [comment]
It's now at `Configuration > Add-ons, Backups and Supervisor`.

Major new Home Assistant release yesterday. Please read the release notes:

https://www.home-assistant.io/blog/2021/12/11/release-202112/
