### ISSUE TITLE
Menu item same color as background (HACS) - UI Only

### ISSUE THREAD

**Issue by travisboss** [home-assistant/operating-system#1704]
### Describe the issue you are experiencing

Under HACS Integrations and Frontend, the none selected item is white and you cannot see it(this is only on the light theme, fine on dark theme).

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

7.0

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Enable light theme
2. Click HACS menu item
3. Click on Integrations or frontend
4. At top look for Frontend

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

## System Health

version | core-2021.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4940
Installed Version | 1.18.0
Stage | running
Available Repositories | 931
Installed Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 28.6 GB
disk_used | 3.0 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.2.0), Terminal & SSH (9.2.2), File editor (5.3.3), Google Assistant SDK (2.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

### Additional information

<img width="415" alt="Screen Shot 2022-01-04 at 8 33 58 AM" src="https://user-images.githubusercontent.com/16948721/148075544-17efc7f4-0b27-48fb-8b64-6c3b450531c0.png">

**Comment by agners** [comment]
It looks like this issue is related to Home Assistant Frontend. Please check the [Home Assistant Frontend](https://github.com/home-assistant/frontend/issues) repository, the issue might have been reported already. Open a new issue in that repository if you can't find a matching issue.
