### ISSUE TITLE
Cannot view full logs for add-ons

### ISSUE THREAD

**Issue by synio-wesley** [home-assistant/operating-system#1711]
### Describe the issue you are experiencing

When using Home Assistant OS, you cannot view the full logs for the add-ons which might make debugging very hard when a lot of information is being logged (especially when JSON is formatted and spanned over multiple lines). You can only view the last 100 lines or so. Using `ha addons logs` also limits to only about 100 lines.

It looks like we cannot access the full underlying Docker logs when using Home Assistant OS.

Can this be changed so we can view/access the full log somehow?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install an add-on
2. Make sure enough lines are being logged
3. View the log for the addon (or use `ha addons logs <addon>`) and you will see only the last lines

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
Getting access to more logs and logs of previous boots is something I am working on, see https://github.com/home-assistant/supervisor/issues/3309. The first step in OS is done (see #1627), but there is still work to do in Supervisor.

In any case I am closing this. Also, seems more like a feature request than a bug.
