### ISSUE TITLE
Home Assistant won't update

### ISSUE THREAD

**Issue by Ascc84** [home-assistant/operating-system#1721]
### Describe the issue you are experiencing

I currently have HA version 5.13 installed on my HA blue. It tells me to update it to 7.1. When I click update it says it's updating, it restarts but then when I open it up again it's still the old operating system.
I've tried updating from my phone, tablet and PC.

### What operating system image do you use?

odroid-n2 (Hardkernel ODROID-N2/N2+)

### What version of Home Assistant Operating System is installed?

5.13

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1.
2.
3.
...
5.13 came pre intalled

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Australia/Sydney

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 19.03.15
disk_total | 113.9 GB
disk_used | 9.4 GB
healthy | true
supported | failed to load: Unsupported
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.4.0), Nginx Proxy Manager (0.11.0), Studio Code Server (3.7.0), Samba share (9.5.1), Home Assistant Google Drive Backup (0.105.2), Node-RED (10.2.0), WireGuard (0.6.0), Mosquitto broker (6.0.1), TasmoBackup (1.04.26), ESPHome (2021.12.1), TasmoAdmin (0.16.0), deCONZ (6.10.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by agners** [comment]
I am aware of the problem (#1692). It will be fixed in 7.2 (which I hope will be out sometime next week). I planned to fix it in 7.1, but somehow missed backporting the fix :disappointed:
