### ISSUE TITLE
VMware Guest OS field broken display

### ISSUE THREAD

**Issue by ldymek** [home-assistant/operating-system#1730]
### Describe the issue you are experiencing

Hello, 

In VMware 6.7u3 and 7.0u2 I see guest os broken info:

`Linux 5.10.91 NAME="Home Assistant OS" VERSION="7.2 (Open Virtual Appliance)" ID=haos VERSION_ID=7.2 PRETTY_NAME="Home Assistant OS 7.2" CPE_NAME=cpe:2.3:o:home-assistant:haos:7.2:*:production:*:*:*:ova:* HOME_URL=https://hass.io/ VARIANT="Home Assistant OS Open Virtual Appliance" VARIANT_ID=ova SUPERVISOR_MACHINE=qemux86-64 SUPERVISOR_ARCH=amd64`

![Zrzut ekranu 2022-01-26 093603](https://user-images.githubusercontent.com/56914130/151130011-efaf091d-ac7a-4702-becb-b3d8cd7b43c7.png)

I assume here I should see preety_name value from above:

PRETTY_NAME="**Home Assistant OS 7.2**"

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

7.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Deploy ova to vmware
2. Navigate to VM Summary
3. Read Guest OS values

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't know what I should search there.
```

### Anything in the Host logs that might be useful for us?

```txt
I don't know what I should search there.
```

### System Health information

Version | core-2021.12.10
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.91
CPU Architecture | x86_64
Timezone | Europe/Warsaw

**Comment by tensor5g** [comment]
Same issue, running VCSA 7.0 U3c and ESXi 7.0U3c (both latest at time of writing)

![image](https://user-images.githubusercontent.com/74799905/159136976-fa0ccb65-a172-49ed-81b7-a3793554715f.png)
