### ISSUE TITLE
Home assistant 7.2 not working in Virtual box

### ISSUE THREAD

**Issue by DJAMIRSAM** [home-assistant/operating-system#1737]
### The problem

i cant get home assistant to work in  a windows VM after the update
i keep getting the error https://cdn.discordapp.com/attachments/705503647135432754/937918802132357130/unknown.png
I have had HA working in this computer before with the same method, i have restarted it and re installed it but nothing works
i have a backup so im fine with deleting stuff
pls ping me when responding i have this server set to ping only

### What version of Home Assistant Core has the issue?

The one off the website (7.2)

### What was the last working version of Home Assistant Core?

7.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

None

### Anything in the logs that might be useful for us?

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/78499690/152829995-4fd88c1f-feb5-48c9-aebb-41213e465511.png">

**Comment by agners** [comment]
@DJAMIRSAM can you try OS 7.3 on beta channel? It comes with a new stable release Linux kernel, maybe something was buggy with the kernel in OS 7.2.

To enable beta channel, use

```
ha su options --channel beta
ha su reload
ha os update
```

**Comment by DJAMIRSAM** [comment]
Is there anyone with the beta .vdi file?

**Comment by agners** [comment]
@DJAMIRSAM you can find images of the latest beta here: https://github.com/home-assistant/operating-system/releases/tag/7.3

**Comment by DJAMIRSAM** [comment]
The boot up worked fine but after boot up everything when back to the way it was (7.3) and there is no backup

**Comment by DJAMIRSAM** [comment]
![68434615-26C7-48F4-B270-D0614DACCB6A](https://user-images.githubusercontent.com/78499690/152711241-3b461073-2275-4ebf-af98-c186b20ee870.jpeg)
This is what it shows after leaving it on for 5 hours

**Comment by agners** [comment]
What VirtualBox version are you using? Can you also share the virtual machine settings?

**Comment by malosaa** [comment]
i had this problem one time aswell, it was my hdd and changed it and worked again.
but for you it could be something else, but it looks like its to slow to load, like i had.

@DJAMIRSAM try on a other PC/Server and see if that works.
Or try loading the vdi on a other hdd.

Be sure u have this enabled in virtualbox:
Enable EFI
and use atleast 3gb of memory.
enable 2x cpu or higher
Execution cap 100%
Just for now disable usb controller in virtualbox

and try again, that helped me before

**Comment by DJAMIRSAM** [comment]
> What VirtualBox version are you using? Can you also share the virtual machine settings?

It’s 6.1.32
![CDDF147B-4EE0-44EA-82AA-16034C2402CF](https://user-images.githubusercontent.com/78499690/152819904-c6936bf4-a15c-4a28-91b4-80e0c83e766e.jpeg)

**Comment by DJAMIRSAM** [comment]
> i had this problem one time aswell, it was my hdd and changed it and worked again. but for you it could be something else, but it looks like its to slow to load, like i had.
> 
> @DJAMIRSAM try on a other PC/Server and see if that works. Or try loading the vdi on a other hdd.
> 
> Be sure u have this enabled in virtualbox: Enable EFI and use atleast 3gb of memory. enable 2x cpu or higher Execution cap 100% Just for now disable usb controller in virtualbox
> 
> and try again, that helped me before

how can it be a HDD issue? it says cpu stall 
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/78499690/152828267-aeb29b2f-7ac7-4b16-aa4d-99e2e0df9b0e.png">
im gonna try it anyways

**Comment by agners** [comment]
@DJAMIRSAM RCU callbacks are executed periodically, stalls are reported when those callbacks are not executed for quite a while for some reason. The culprit can be many things, e.g. software bugs but also very slow/stuck hardware (e.g. SD cards/HDDs). In virtualization it could also be that the timing/timers are off/not working correctly.

This is a bit a shot in the dark, but can you try different "Paravirtualization Interface" settings (in System -> Acceleration)?

There have been other reports of rcu_sched stalls like this issue https://www.virtualbox.org/ticket/20131. Probably worth posting in the VirtualBox forums (ideally attach the VirtualBox logs), they might have some hints what could be the culprit.

**Comment by malosaa** [comment]
I found the issue, a guy had exactly the same problem with hass on virtualbox

https://github.com/home-assistant/operating-system/issues/1705

read this and it should be fixed.
@DJAMIRSAM

**Comment by DJAMIRSAM** [comment]
ok so it kinda worked but after a restart its back to freezing but i had to restart due to freezing

**Comment by DJAMIRSAM** [comment]
its stuck on 
![image](https://user-images.githubusercontent.com/78499690/153093293-b3561f04-511f-454d-8b31-920c04f9db4f.png)

**Comment by malosaa** [comment]
> its stuck on ![image](https://user-images.githubusercontent.com/78499690/153093293-b3561f04-511f-454d-8b31-920c04f9db4f.png)

Did u try on an other machine ? if i look at the error you describe i see many people with hdd errors/memory errors.
Otherwise download an older version and see if its gone..


Its odd this also doesnt work on a other machine, i have many versions running, none of them have that issue, but i have installed the extra additions to it (the addons)

1 machine is a 8gb quadcore  thin client (ssd 120gb) with windows 10 pro  (virtualbox with 7.0 Hass)
1 machine a 16gb Quadcore Laptop with ssd on windows 10 pro   (virtualbox 7.1 HASS)
1 machine 16gb laptop quadcore  with ssd (250gb) windows 11. (virtualbox 7.3 HASS)

all no problems, i wish i could help u but i have no idea how

regards

**Comment by DJAMIRSAM** [comment]
So for now it seems to be working, I fixed it by deleting docker desktop from the pc an setting the accelerator to kvm but if it continues I will try that. I currently have an issue which is a VMBOX issue but since this exists I might as swell put it out there. The usb connects keeps disconnecting (I have 2 and they both do it at the same time)

**Comment by degreal** [comment]
I updated windows and virtualbox 6.1.30 -> 6.1.32 at same time.
Zigbee USB dongle stopped working. "self-detected stall on CPU" error spamming. Virtualbox taking 30 min to get up, "Journal" errors.

I did fresh install but still getting stall errors.
I downgraded VirtualBox back to 6.1.30 and everything is working now!

**Comment by DJAMIRSAM** [comment]
So fun fact the issue came back today so this reply came in clutch, I’m gonna downgrade vbox

**Comment by degreal** [comment]
> So fun fact the issue came back today so this reply came in clutch, I’m gonna downgrade vbox

Nevermind, Today I started getting stall errors again. Downgrading to 6.1.30 does not seem to help perfectly.

**Comment by DJAMIRSAM** [comment]
> > So fun fact the issue came back today so this reply came in clutch, I’m gonna downgrade vbox
> 
> Nevermind, Today I started getting stall errors again. Downgrading to 6.1.30 does not seem to help perfectly.

Try setting the paravirtualization as mentioned above to KVM it seems to work the best right now

**Comment by frederikrooms** [comment]
> > > So fun fact the issue came back today so this reply came in clutch, I’m gonna downgrade vbox
> > 
> > 
> > Nevermind, Today I started getting stall errors again. Downgrading to 6.1.30 does not seem to help perfectly.
> 
> Try setting the paravirtualization as mentioned above to KVM it seems to work the best right now

@degreal 
Did the paravirtualization change to KVM work for you? I'm having the same problem with the exact setup, and I do hope the downgrade to 6.30 works. I'm sceptical because earlier today I ran into an USB problem (OHI-PCI problem) while running 6.30. So neither of the options seems to provide me a smooth working Home Assistant. It all seems very messy with the update strategy this year, I hope my monthly fee will provide a more stable platform in the future...

**Comment by degreal** [comment]
> > > > So fun fact the issue came back today so this reply came in clutch, I’m gonna downgrade vbox
> > > 
> > > 
> > > Nevermind, Today I started getting stall errors again. Downgrading to 6.1.30 does not seem to help perfectly.
> > 
> > 
> > Try setting the paravirtualization as mentioned above to KVM it seems to work the best right now
> 
> @degreal Did the paravirtualization change to KVM work for you? I'm having the same problem with the exact setup, and I do hope the downgrade to 6.30 works. I'm sceptical because earlier today I ran into an USB problem (OHI-PCI problem) while running 6.30. So neither of the options seems to provide me a smooth working Home Assistant. It all seems very messy with the update strategy this year, I hope my monthly fee will provide a more stable platform in the future...

No it didn't. "6.30+KVM" combo fails once every 3 days. I would test "6.32+KVM" but I cannot have downtime right now, lot is riding on this setup.

**Comment by DJAMIRSAM** [comment]
Let me clarify something, I does not need to be kvm, you can change it to something else, kvm is the one what worked for me but every computer is different

**Comment by SilentT-FR** [comment]
Same issue in 6.1.32

**Comment by DJAMIRSAM** [comment]
> Same issue in 6.1.32

Try setting the paravirtualization as mentioned above to KVM it seems to work the best right now.
Let me clarify something, I does not need to be kvm, you can change it to something else, kvm is the one what worked for me but every computer is different

**Comment by SilentT-FR** [comment]
Thanks for the tips
For me the KVM not work but the minimum works
