### ISSUE TITLE
Install hangs after initial login

### ISSUE THREAD

**Issue by Raulnj** [home-assistant/operating-system#1755]
### Describe the issue you are experiencing

On new 2.9 release HA for NUC, install hangs oon "Getting HA ready screen". May be a DNS issue.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

2.9

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.flash intel NUC
2. Log in to HA via web browser
3. Enter name, user name, password
.4.  You will see "Getting HA ready. Pls wait (wait forever)

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
2.9? That is a veeery old release.

Please install the latest 7.4 release with the name `generic-x86-64` (we have now one image to support all x86-64 machines, including Intel NUC).
