### ISSUE TITLE
Update to build `dev20220227` failed because `RAUC_SLOT_BOOTNAME` is empty

### ISSUE THREAD

**Issue by bram-pkg** [home-assistant/operating-system#1771]
### Describe the issue you are experiencing

I'm trying to upgrade my `dev20220225` build to `dev20220227`. It seems the `RAUC_SLOT_BOOTNAME` is empty, because it failed on the `cp` command from line 60 of the RAUC hook file.

The same happens when trying to upgrade HASSOS 7.4 to `dev20220227`.

![image](https://user-images.githubusercontent.com/13304739/156011471-c1e3ad8d-1eda-452b-8d42-8fcf8b7565fd.png)

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

7.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Run HASSOS 7.4 or `dev20220225`.
2. Upgrade to `dev20220227`.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-02-28 16:21:19 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://os-builds.home-assistant.io/8.0.dev20220227/haos_ova-8.0.dev20220227.raucb
22-02-28 16:21:25 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-8.0.dev20220227.raucb
22-02-28 16:21:33 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

## System Health

version | core-2022.4.0.dev20220228
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | dev
supervisor_version | supervisor-2022.02.dev2801
docker_version | 20.10.9
disk_total | 31.3 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Terminal & SSH (9.3.0), Studio Code Server (4.1.0), Mosquitto broker (6.0.1), Zigbee2mqtt (1.23.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

**Comment by bram-pkg** [comment]
Thanks for the quick response! Glad I'm not crazy.

**Comment by bram-pkg** [comment]
There also seems to be a left-over file in the os-builds repo: <https://os-builds.home-assistant.io/>

**Comment by r3mcos3** [comment]
For me the problem still exist with new version 

`22-03-01 17:41:24 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://os-builds.home-assistant.io/8.0.dev20220301/haos_ova-8.0.dev20220301.raucb
22-03-01 17:41:27 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-8.0.dev20220301.raucb
22-03-01 17:41:29 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1`

**Comment by bram-pkg** [comment]
Seems to work for me now: 

![image](https://user-images.githubusercontent.com/13304739/156226499-1f90c199-1c30-4ab8-9b1b-f8d8dc7b5b84.png)

**Comment by agners** [comment]
@r3mcos3 hm, that is weird. Can you login to that system on OS level via SSH? Can you check what is in `/mnt/boot`?

**Comment by bram-pkg** [comment]
Since I tried manually correcting the error by creating the files in `/tmp/boot-new`, the permissions were incorrect. Manually removed them and that fixed it.

**Comment by agners** [comment]
@bram-pkg hm, you mean there could be stale files in @r3mcos3 case? `/tmp` is a zram device, a reboot should clear it.

@r3mcos3 can you try reboot and then do the update again?

**Comment by bram-pkg** [comment]
Yeah, I didn't reboot so manually cleared the tmp folder. A reboot should
clear it too.

**Comment by r3mcos3** [comment]
a restart doesn't fix the problem,

the boot folder is empty.

and journalctl not valid command

**Comment by r3mcos3** [comment]
![journalctl](https://user-images.githubusercontent.com/45529818/156374590-c7aa11e9-51ac-4549-aeea-572e0c44602e.jpg)

**Comment by bram-pkg** [comment]
Yeah, you need to log in as root using the OS SSH and remove the /tmp/boot-new directory.

**Comment by agners** [comment]
Hm, it seems that something was still mounted at `/tmp/boot-new`. A reboot should have cleaned that. Is this log maybe from the second try after reboot?

@r3mcos3 can you try a system reboot again, then update and then getting the logs from rauc.service?

**Comment by agners** [comment]
@r3mcos3 assuming update worked then?

**Comment by r3mcos3** [comment]
yes it updated fine.

**Comment by RobertGetzner** [comment]
I had the same issue "ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1"when updating from OS 6.6 to 7.6     removing /tmp/boot-new did the trick
from CLI: 

- `login`
- `rmdir /tmp/boot-new`

supervisor already was on 2022.10.2, core on 2022.11.1
