### ISSUE TITLE
Add ipset to kernel modules

### ISSUE THREAD

**Issue by he2ss** [home-assistant/operating-system#1778]
### Describe the issue you are experiencing

Hi,

We added [crowdsec](https://github.com/crowdsecurity/crowdsec) as an [addon](https://github.com/crowdsecurity/home-assistant-addons/tree/main/crowdsec). And we wanted to add the [cs-firewall-bouncer](https://github.com/crowdsecurity/cs-firewall-bouncer), and at that moment we realized that ipset is missing in the OS.

It’s possible to add ipset to the home assistant OS ?

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

7.4

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

No steps, just the ipset module that is not present in the OS.
Basically, we tried to run [cs-firewall-bouncer](https://github.com/crowdsecurity/cs-firewall-bouncer) as an addon. It use iptables with ipset. the addon is running with NET-ADMIN capability so it can add rules to iptables with ipset. As the ipset is not available in the host kernel modules, it fails.

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
time="02-03-2022 11:20:19" level=error msg="error while removing set entry in iptables : exit status 2 --> iptables v1.8.7 (nf_tables): Couldn't load match `set':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n"
time="02-03-2022 11:20:19" level=info msg="iptables clean-up : /usr/sbin/iptables -D FORWARD -m set --match-set crowdsec-blacklists src -j DROP"
time="02-03-2022 11:20:19" level=error msg="error while removing set entry in iptables : exit status 2 --> iptables v1.8.7 (nf_tables): Couldn't load match `set':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n"
time="02-03-2022 11:20:19" level=info msg="ipset clean-up : /usr/sbin/ipset -exist destroy crowdsec-blacklists"
time="02-03-2022 11:20:19" level=error msg="set destroy error : exit status 1 - ipset v7.10: Kernel error received: Invalid argument\n"
time="02-03-2022 11:20:19" level=info msg="Checking existing set"
time="02-03-2022 11:20:19" level=info msg="ipset set-up : /usr/sbin/ipset -exist create crowdsec-blacklists nethash timeout 300"
time="02-03-2022 11:20:19" level=fatal msg="iptables init failed: error while creating set : exit status 1 --> ipset v7.10: Kernel error received: Invalid argument\n"
time="02-03-2022 11:20:19" level=fatal msg="iptables init failed: error while creating set : exit status 1 --> ipset v7.10: Kernel error received: Invalid argument\n"
```
```


### System Health information

_No response_

### Additional information

_No response_

**Comment by agners** [comment]
IP set support will be available in OS 8.0 and newer.
