### ISSUE TITLE
Is /etc/udev persistent?

### ISSUE THREAD

**Issue by orandasoft** [home-assistant/operating-system#1789]
### Feedback

The documentation states /etc/udev is persistent. However, when I reboot the directory gets wiped. I am running HAOS 7.1.

### URL

https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md

### Version

2021.12

### Additional information

Want to set up a number of udev rules.

**Comment by agners** [comment]
The documentation states `/etc/udev/rules.d` is persistent (not `/etc/udev`). Rules should indeed be persistent.
