### ISSUE TITLE
custom icon on dashboards

### ISSUE THREAD

**Issue by MrThiemann** [home-assistant/operating-system#1791]
### Describe the issue you are experiencing

I noticed that you can't use custom icons for your dashboard at the moment.
A few versions before that still worked ;)
Today's update hasn't fixed it either.
That's why I'm writing to you, because I don't know if you already know it.

<img width="479" alt="Bildschirmfoto 2022-03-13 um 15 28 58" src="https://user-images.githubusercontent.com/54147030/158064401-e1883899-9f38-44de-b692-b60d28e40f8d.png">

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

2022.3.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

change dashboard icon

### Anything in the Supervisor logs that might be useful for us?

```txt
nothing
```

### Anything in the Host logs that might be useful for us?

```txt
i dont know
```

**Comment by Johnyboy1984** [comment]
Thank you.

**Comment by agners** [comment]
This is not an operating system issue, but a front-end issue. It is likely fixed by home-assistant/frontend#12038.
