### ISSUE TITLE
USB problem after last update

### ISSUE THREAD

**Issue by malosaa** [home-assistant/operating-system#1800]
### Describe the issue you are experiencing

Well i did experience an issue with my rfxcom device, but now also with other usb devices.

When i restart homeassistant from the gui the usb disconnects and i get this error:
![image](https://user-images.githubusercontent.com/13116501/158832440-9c9e342b-5fea-4828-99d3-43fae6263efa.png)

i have 3 usb devices connected: 
1. rfxtrx
2. plugwise usb
3. zigbee2mqtt (never disconnects)

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

7.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. reboot homeassistant from the gui
2. 2 usb devices get disconnected.

### Anything in the Supervisor logs that might be useful for us?

```txt
yes see above message
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
Can you try downgrade again to see if the issue indeed disappears?

```
ha os update --version 7.4
```

**Comment by malosaa** [comment]
Hi @agners 

Well i did restart 2x from gui with 1 hour between it, and it did not happen.
I dont know why it did happen before.

On 7.2 - 7.4 it did happen aswell but many times on the rfxcom device, same usb error.
Mostly it just stops working when there is no restart.

**Comment by malosaa** [comment]
I always had this issue, but i thought it was the rfxcom, but Bert the creator of the rfxcom said, please run it into the rfxmgr for a couple of days and see if there is a disconnect.
But there is no disconnect for 3 days.

A long time ago i had the issue with the zigbee2mqtt usb, i always got that error like above and it stopped working, than after some new versions it got fixed and it never happened anymore.

But yesterday somehow after the first time i update to 7.5 2 usb failed with that error, but it did not happen again.
When there is another core update i let homeassistant restart again and see if it happens again.

I really don't know if this is a OS problem or just the RFXCOM/PLUGWISE problem.

regards

**Comment by malosaa** [comment]
![image](https://user-images.githubusercontent.com/13116501/159114259-624d335b-343e-4efb-9834-a8c7143a57a4.png)


@agners
this happens after a full restart, this is my full restart in 2 months.
regards

**Comment by malosaa** [comment]
Well, magically it still working, probably some new versions HASS dit fix it.
I think you maybe can close this issue, as i think its solved :)
