### ISSUE TITLE
High RAM usage on version 7.5

### ISSUE THREAD

**Issue by Twanne** [home-assistant/operating-system#1809]
### Describe the issue you are experiencing

On the previous version of the OS, my RAM usage was stable around 1.6GB.
Since the update it increased immediately to 2.9GB out of 3GB allocated in Proxmox.
I've increased the allotted RAM to 4GB, but this just increased the usage further to 3.5-3.7GB used.
It seems to just fill up the available RAM without explanation.

There are however no noticeable side effects during use. Everything runs smoothly so far.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade from 7.4 to 7.5 from the UI.
2. Have lots of RAM eaten up.

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
The only think which changed between 7.4 and 7.5 was the updated Linux stable kernel. It seems unlikely to me that this changes behavior of memory management.

Can you try downgrading to proof its really the OS and not some other component?

```
ha os update --version 7.4
```
