### ISSUE TITLE
Missing firmware for Intel Wireless WiFi Link 4965AGN (x86 platform)

### ISSUE THREAD

**Issue by Kiron21** [home-assistant/operating-system#1826]
### Describe the issue you are experiencing

There is no firmware for this WiFI/BT card.

Is there any chance to add that? Or we must switch to standard linux distro?

Thanks.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Try any BT WiFi card on PC.

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
This will be resolved in OS 8.0.
