### ISSUE TITLE
ODROID-N2 installation image on SD CARD does not boot

### ISSUE THREAD

**Issue by alijani1** [home-assistant/operating-system#1838]
### Describe the issue you are experiencing

When installing for first time on an odroid n2+ SD card,  using V7.6 image for system tries to boot and gets an IP address you can see in the console but then it errors out with serverip not set error and it does not continue with the install. 

NOTE: It works fine when using an emmc card but not SD card.  See attached image for errors.

Got image from https://github.com/home-assistant/operating-system/releases/download/7.6/haos_odroid-n2-7.6.img.xz per instructions.

### What operating system image do you use?

odroid-n2 (Hardkernel ODROID-N2/N2+)

### What version of Home Assistant Operating System is installed?

7.6

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. download Odroid home assistance image file from https://github.com/home-assistant/operating-system/releases/download/7.6/haos_odroid-n2-7.6.img.xz
2. flash on SD card  (not emmc)
3. insert in Odroid n2+
4. attach network cable on n2+ and power on
5. system boots, even gets IP address, but then errors with serverip not set error

See attached screenshot.

...
![20220408_083737](https://user-images.githubusercontent.com/5728516/162439290-b8c5dd95-4a2c-41d4-9dcb-f9b74a246157.jpg)

### Anything in the Supervisor logs that might be useful for us?

```txt
na
```

### Anything in the Host logs that might be useful for us?

```txt
na
```

### System Health information

na

**Comment by alijani1** [comment]
BTW, this same process works with MMC.  It only fails when using SD Card

**Comment by agners** [comment]
What you are seeing is U-Boot trying to boot through network since it wasn't able to find the OS on the SD card. So the root problem is that U-Boot can't seem to read from the SD-card.

**Comment by n2aws** [comment]
If it helps,  I have an odroid-n2+,  I wrote the 7.6 image to an sd-card,  and was able to boot successfully from it.  (I do not have an emmc)

This is most likely a hardware issue with the SD Card.

**Comment by Tijgerd** [comment]
I fixed/bypassed this issue by installing an older version on the SD card and updating it within Home Assistant itself.
