### ISSUE TITLE
Cannot mount Data partition after ha os datadisk move

### ISSUE THREAD

**Issue by Vagabond80** [home-assistant/operating-system#1844]
### Describe the issue you are experiencing

I did a fresh install of Home Assistant OS on my Raspberry Pi4 and performed a `ha os datadisk move /dev/sda` immediately after onboarding. The system boots but does not come up anymore. Please excuse the photos, but I had no other access to the Console. It stops booting with the following error message.
![IMG_2849 MOV](https://user-images.githubusercontent.com/102099720/163210719-24c3cd62-a0bf-40ee-9975-281e8fc20eac.jpg)
A fsck does not help.
![IMG_2856 MOV](https://user-images.githubusercontent.com/102099720/163211959-0134c5a7-f940-4585-adfd-c84e9887b553.jpg)
After rebooting it fails to mount the data partition
![IMG_2855 MOV](https://user-images.githubusercontent.com/102099720/163212329-300804c6-fe93-44b7-8e77-835731f2fa8b.jpg)
an fdisk still shows all disks present
![IMG_2854 MOV](https://user-images.githubusercontent.com/102099720/163212672-9d8b56fd-c998-4d10-8fe8-ee237b23be82.jpg)

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

7.6

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. freshly install HASSOS on a SD Card for Raspberry Pi with a SD Card Imager
2. Insert SD Card and USB-SSD Drive into the Pi and boot
3. Perform Onboarding Steps
4. on console enter `ha os datadisk list` to check for the SSD name
5. on console enter `ha os datadisk move <diskname>` to move the data partition to the SSD

### Anything in the Supervisor logs that might be useful for us?

```txt
not accessible
```

### Anything in the Host logs that might be useful for us?

```txt
not accessible
```

### System Health information

not accessible

### Additional information

used hardware:
Raspberry Pi 4B 4GB RAM
Hama 128GB SD Card
SanDisk Extreme PRO USB 3.2 Solid State Flash-Drive 256 GB

**Comment by agners** [comment]
Is this a UAS USB drive? Can you check the USB vendor/product id? There is a known problem with some drives (see #1743).

**Comment by Vagabond80** [comment]
It is a SanDisk Extreme Pro USB 3.2 Solid State Flash-Drive 256 GB
SDCZ880-256G-G46
and it supports UAS(P).
I installed HASSOS now completely on the SSD and am booting from USB with the Pi4 and it works without issues so far. I also cannot find any UAS related error logs on the system so far. Might need some reboots, since it does not happen every time from what I understand in #1743
