### ISSUE TITLE
HAOS 8.0 fails to boot after update on CM4 with NVMe SSD

### ISSUE THREAD

**Issue by Doridian** [home-assistant/operating-system#1911]
### Describe the issue you are experiencing

I am running HAOS on a CM4 with an NVMe SSD.
After updating from HAOS 7.6 to 8.0 in the GUI, HomeAssistant fails to come up.
It does request an IP via DHCP on boot and will respond to pings on it, however, according to my DHCP server logs, those requests only ever come from `U-Boot.armv8`, not the actual OS.
Plugging in a screen, I see absolutely nothing.

Even repeated reboot attempts get me absolutely nowhere, not back to 7.6, no logs, nothing.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

8.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Use NVMe SSD with HAOS 7.6
2. Update to 8.0 in the GUI
3. Stopped booting

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing
```

### Anything in the Host logs that might be useful for us?

```txt
Nothing
```

**Comment by Doridian** [comment]
Adding to this:
- Fresh install of HAOS 8.0 to NVMe SSD -> Same symptoms, complete boot fail
- Fresh install of HAOS 7.6 to the same NVMe SSD -> Immediate boot success

**Comment by Doridian** [comment]
> Any idea how we can get it to run?
> 
> Its complete dead, no SSH nothing

Only way I could recover mine is pull SSD, reflash it with 7.6, restore backup.

**Comment by KartoffelToby** [comment]
@Doridian did you know were the backups are stored on the nvme? :D

**Comment by Doridian** [comment]
> @Doridian did you know were the backups are stored on the nvme? :D

I always download them to my NAS (so I have them ready in case of drive failure).
But I'd go digging around on the last partition of the NVMe, that seems to contain everything.
If you can't find anything there, maybe just image the whole partition and restore it, no idea how good that is as a solution, however.

**Comment by agners** [comment]
@KartoffelToby You can replace the `u-boot.bin` file on the first partition with the version from OS 7.6. For your continence, I extracted it from HAOS 7.6: [rpi4-64 u-boot.img.tar.gz from HAOS 7.6](https://github.com/home-assistant/operating-system/files/8702067/u-boot.img.tar.gz)

**Comment by pickonedev** [comment]
If I try update to 8.0, the computer will restart, then it will try boot on Slot B, which fails... If I restart and boot from slot A, I am back to 7.6 ...

Big Fail, any solution?

**Comment by th0m4sek** [comment]
updating eeprom fixed problem in my case

**Comment by raforo** [comment]
> @KartoffelToby You can replace the `u-boot.bin` file on the first partition with the version from OS 7.6. For your continence, I extracted it from HAOS 7.6: [rpi4-64 u-boot.img.tar.gz from HAOS 7.6](https://github.com/home-assistant/operating-system/files/8702067/u-boot.img.tar.gz) (unpack before copying to the first FAT partition).

I had the same problem, but  your fix didn't work for me.
R
![Screenshot_20220517-221947_Video_Player 1](https://user-images.githubusercontent.com/91435639/168909169-6ba31120-c1a0-4da5-94f8-7f2929fc5a7e.jpg)
eboot stops and shows this screen and reboots again

**Comment by bruvv** [comment]
8.1 fixed this probably please try it.

**Comment by agners** [comment]
Unfortunately, I forgot to include the patches for all Raspberry Pi's in 8.1 :see_no_evil: next release! :crossed_fingers: 

@raforo this is about Compute Module 4 which have a NVMe PCIe directly connected. You report using Raspberry PI 4, hence that is a different problem. It looks a bit like what https://github.com/home-assistant/operating-system/issues/1909#issuecomment-1127830561 reported, but that problem disappeared. Can you open a new issue in case your problem persists?

**Comment by raforo** [comment]
> Unfortunately, I forgot to include the patches for all Raspberry Pi's in 8.1 🙈 next release! 🤞
> 
> @raforo this is about Compute Module 4 which have a NVMe PCIe directly connected. You report using Raspberry PI 4, hence that is a different problem. It looks a bit like what [#1909 (comment)](https://github.com/home-assistant/operating-system/issues/1909#issuecomment-1127830561) reported, but that problem disappeared. Can you open a new issue in case your problem persists?

Thanks, I figured that out and I opened new issue #1917

**Comment by dvisser** [comment]
Confirming this is still present with 8.1 regarding a CM4 with nvme storage directly connected. 

Fingers crossed for a fix in the next release! 

I had to restore back to 7.6 to bring mine back to life.

**Comment by agners** [comment]
This should be resolved with HAOS 8.2.
