### ISSUE TITLE
HA 8.0 fails to boot (incorrect compressed chunk)

### ISSUE THREAD

**Issue by Th3M1k3y** [home-assistant/operating-system#1912]
### Describe the issue you are experiencing

Can't boot from neither Slot A or Slot B

![2022-05-16 17 10 56](https://user-images.githubusercontent.com/29869794/168625885-37580c39-c622-4330-b13b-f6a4f34eae3a.jpg)

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

8.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Press update to 8.0
2. Wait for it to not come online

### Anything in the Supervisor logs that might be useful for us?

```txt
Can't boot
```

### Anything in the Host logs that might be useful for us?

```txt
Can't boot
```

### Additional information

Running on a Lenovo M710q Tiny

**Comment by agners** [comment]
There were several reports about sectors not reading correctly during RC phase (see #1830). However, this seems different. I wonder if it reads the sector, just not quite right this time? Maybe a BIOS update helps?

> I got it to boot after enabling Compatibility Support Module (CSM) in bios.

Uh that is interesting, I wonder if that changes the UEFI BIOS in some way how IO is handled.

**Comment by Sangoku** [comment]
Same here. I reported it on the release.
 What fixed it for me was that i disabled uefi boot and reanabled it after restart.

**Comment by pete-leese** [comment]
yep same issue here

**Comment by agners** [comment]
@pete-leese does using CSM solve it for you as well?

What hardware are you using exactly (exact machine type + hard drive)?

I'd really like to reproduce this here to actually debug what goes wrong in GRUB2.

**Comment by evilknivel** [comment]
Hi, i have the same peoblem using a Lenovo ThinkPad with nvme hdd. The CSM option sadly changes nothing to me. Any option i can Boot the system using the grub 2 command line?

**Comment by Th3M1k3y** [comment]
> 

Not sure if you can use my specs for anything, but mine is a Lenovo M710q Tiny booting of a Samsung SSD 950 PRO 512GB

**Comment by Sangoku** [comment]
Mine is Intel NUC [BOXNUC7I3BNH](https://www.amazon.de/-/en/gp/product/B01N6SG8DP/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) with a SSD M.2 256GB Samsung MZ-V5P256BW 950PRO PCIe 950 PRO

**Comment by TechInfoQc** [comment]
> Partition 5/6 contain the `B` installation of HAOS. When you install HAOS the first time, it contains only one installation (the `A` installation). So yes, this is normal on a new installation.
> 
> Does setting CSM mode in BIOS helps in your case maybe too?

Don't have this options in this particular bios, I've tried enabling/disabling UEFI, Legacy boot, secure boot etc..

**Comment by pickonedev** [comment]
If I try update to 8.0, the computer will restart, then it will try boot on Slot B, which fails... If I restart and boot from slot A, I am back to 7.6 ...

Big Fail, any solution?

**Comment by evilknivel** [comment]
For ne None of them work Slot a nor slot b. Any solution to fix and keep my settings?

**Comment by agners** [comment]
> Big Fail, any solution?

It call that big win, the fallback did work and your system is still running!

> If I try update to 8.0, the computer will restart, then it will try boot on Slot B, which fails...

How odes it fail exactly? Any specific error message showing up?

**Comment by agners** [comment]
What are the errors? Do you have CSM option in your BIOS?

**Comment by evilknivel** [comment]
@agners Hi, yes i do have the CSM option and tried every combination with and without CSM, leagcy and uefi. Nothing helpt so far. Any solution idears?

**Comment by agners** [comment]
@evilknivel do you get the same error message as the original post (`error: incorrect compressed chunk`)?

What type of system and hard drive do you use?

**Comment by egnerfl** [comment]
I had the exact same issue on my `HP ProDesk 600 G3` and an NVME drive. 
I played around with all relevant legacy boot settings and tried all available secure boot options. 

Unfortunately none of the sectors worked and also manual recovery with the super-blocks with a Ubuntu Live USB Stick failed. 

I did a fresh install and ran into the same issues so had to downgrade to 7.7 and recover a backup.

![image](https://user-images.githubusercontent.com/4058299/168978122-11647068-406c-4a17-ad5c-1398ee2ed4f2.png)

**Comment by agners** [comment]
Can someone try [bootx64.tar.gz](https://github.com/home-assistant/operating-system/files/8714883/bootx64.tar.gz) GRUB2 binary instead of the one supplied by HAOS 8.0? Probably the easiest way is to use a Ubuntu Live System to boot into the system, and replace `EFI/BOOT/BOOTX64.EFI` in the first boot  partition (EFI System Partition). Don't forget to unpack (`tar xzf boot64.tar.gz`).

**Comment by pickonedev** [comment]
> @pickonedev
> 
> > Big Fail, any solution?
> 
> It call that big win, the fallback did work and your system is still running!
> 
> > If I try update to 8.0, the computer will restart, then it will try boot on Slot B, which fails...
> 
> How odes it fail exactly? Any specific error message showing up?

Well... I just click on install from Home Assistant, then the computer restarts and shows me two different boot options, where the computer it is selecting the Slot B, instead Slot A. After this, the computer freezes with a screen where the text it is cutted. 
After this, I force restart the computer and HA it is still on v7.6 
Please, take a look at how the computer is after it is trying to update.
![2](https://user-images.githubusercontent.com/34201387/169017802-691711c9-b15b-4aa7-9409-0dd0189ea7ed.jpeg)
![1](https://user-images.githubusercontent.com/34201387/169017819-f01d46bd-5427-48dd-ae8b-f3f9e3824b32.jpeg)

**Comment by Apinyot** [comment]
> > @pickonedev
> > > Big Fail, any solution?
> > 
> > 
> > It call that big win, the fallback did work and your system is still running!
> > > If I try update to 8.0, the computer will restart, then it will try boot on Slot B, which fails...
> > 
> > 
> > How odes it fail exactly? Any specific error message showing up?
> 
> @agners Well... I just click on install from Home Assistant, then the computer restarts and shows me two different boot options, where the computer it is selecting the Slot B, instead Slot A. After this, the computer freezes with a screen where the text it is cutted. After this, I force restart the computer and HA it is still on v7.6 . I have even updated my bios to the last version available. I am using a DELL 3090 MFF Please, take a look at how the computer is after it is trying to update. ![2](https://user-images.githubusercontent.com/34201387/169017802-691711c9-b15b-4aa7-9409-0dd0189ea7ed.jpeg) ![1](https://user-images.githubusercontent.com/34201387/169017819-f01d46bd-5427-48dd-ae8b-f3f9e3824b32.jpeg)

Exactly the same problem here, non-readable message and computer freeze. Using a Lenovo Yoga and HAOS at 7.6 verision. Any solution?

**Comment by agners** [comment]
> Well... I just click on install from Home Assistant, then the computer restarts and shows me two different boot options, where the computer it is selecting the Slot B, instead Slot A.

That is by design: HAOS has two slots, `A` and `B`. On every update, the "other" not currently active slot is updated. The OS starts with slot `A`. E.g. you start with 7.5 `A`, update to 7.6 on slot `B`, then update to 8.0 it would be slot `A` again. This system allows us to boot the last version, in case the new version has a problem, like in your case.

@Apinyot this is different to the issue tracked here as this issue is a bootloader problem. In your case, it seems the new kernel breaks sometime later at boot-up. I created a new issue #1920 let's continue discussion in that thread.

**Comment by grammesm** [comment]
Adding to the mix here - HP 800 g2 mini - clicked update from HA companion app and computer never restarted.  Same compressed chunk error. Tried all the legacy boot/secure boot option and nothing.

![image](https://user-images.githubusercontent.com/24898201/169122168-290ac6f3-f404-4ba1-94cb-13ee5dfd4c36.png)
![image](https://user-images.githubusercontent.com/24898201/169122228-e3e9d1c6-6a70-43e2-8f02-d4198304bd35.png)


Is there any way to recover the old version?  I didn't have drive backups installed an I'm really kicking myself for that.

**Comment by grammesm** [comment]
I was at least able to boot up a live ubuntu system and copy out all my backups from when I tried the upgrade - although they are partial.  The last full backup I have is oooold. Hopefully I can recover enough data

**Comment by agners** [comment]
@grammesm did you try the GRUB2 binary I uploaded in https://github.com/home-assistant/operating-system/issues/1912#issuecomment-1129771297? Its just a simple copy and it might fix the problem.

Unfortunately, I don't have a system to test, so I really rely on someone with an affected system to test.

**Comment by agners** [comment]
@grammesm it goes to the first partition, named `hassos-boot`. You might need to mount it manually in "Disks" (press the play button). Unpack the file and store it under `EFI/BOOT/`. 

![image](https://user-images.githubusercontent.com/34061/169168279-a812d5c8-45cf-49c2-bd92-dc3b6fe4bbaa.png)

**Comment by TechInfoQc** [comment]
> Can someone try [bootx64.tar.gz](https://github.com/home-assistant/operating-system/files/8714883/bootx64.tar.gz) GRUB2 binary instead of the one supplied by HAOS 8.0? Probably the easiest way is to use a Ubuntu Live System to boot into the system, and replace `EFI/BOOT/BOOTX64.EFI` in the first boot partition (EFI System Partition). Don't forget to unpack (`tar xzf boot64.tar.gz`).

I can confirm, that this boot loader is working on my EliteDesk 800 G3 mini

**Comment by evilknivel** [comment]
> Can someone try [bootx64.tar.gz](https://github.com/home-assistant/operating-system/files/8714883/bootx64.tar.gz) GRUB2 binary instead of the one supplied by HAOS 8.0? Probably the easiest way is to use a Ubuntu Live System to boot into the system, and replace `EFI/BOOT/BOOTX64.EFI` in the first boot partition (EFI System Partition). Don't forget to unpack (`tar xzf boot64.tar.gz`).

@agners Hi i exchaned the bootx64.efi with the one you provided and now it boots again. Thankyou very much!

**Comment by grammesm** [comment]
@agners Like the others - replacing the bootloader worked for me too on HP EliteDesk 800 G2 mini

**Comment by agners** [comment]
@grammesm @evilknivel thanks for confirmation. I've add that fix in #1929 and will make it part of 8.1.

**Comment by luisfmrosa** [comment]
I'm just feeling very bad here: just bricked my NUC.

I have a NUC8i3BEH with m.2 nvme + Samsung pro 950.

Got same error: incorrect compressed chunk...

Didn't find the option CSM in BIOS.

Then I stupidly tried to activate Legacy Boot flag while keeping UEFI boot on.

As a result, my computer now simply does not boot: it hangs on the menu "F2 to Enter Setup, F7 to Update Bios, F10 to Boot Menu."

Pressing F2, F7 or F10 has simply no effect. But I can do ctrl + alt + del just to come back to the same point...

**Comment by agners** [comment]
The fix is now part of Home Assistant OS 8.1 currently on beta channel. For those affected by this issue, can you join the beta channel to update to HAOS 8.1 and confirm that its indeed working for your case? Thanks!

**Comment by evilknivel** [comment]
@agners Hi i installed 8.1 beta and IT works great!

**Comment by meceo** [comment]
I confirm the fix in 8.1 beta works on HP t620

**Comment by Sangoku** [comment]
Now on 8.1 and the front USBs wont work anymore. on my [BOXNUC7I3BNH 3](https://www.amazon.de/-/en/gp/product/B01N6SG8DP/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)
Which is really bad! Usb hubs dont work anymore to.  so im stuck with only 2 usbs in the back.

**Comment by agners** [comment]
@Sangoku honestly, this seems quite weird as this are likely the very same USB host controllers. It seems weird that this would be caused by a software problem. Can you verify that this is related to the update by downgrading to 7.6 (using `ha os update --version 7.6`)? If the problem is really related to the upgrade, can you open a new issue with full dmesg and logs, along with information what kind of device you have plugged in?

**Comment by Sangoku** [comment]
@agners ye can't reproduce it. 
I restarted the NUC by unplugging it from power and after that the serial is working... 
really weird. 

Wanted to delete the comment but you beat me to it. 
Seamed similar to the zigby dongle bug some ppl had.

Sadly cant reproduce it. It works now... dont ask me how... pixy dust? 💯
