### ISSUE TITLE
Did name of interface changed with upgrade form 7.6 to 8.0?

### ISSUE THREAD

**Issue by errellion** [home-assistant/operating-system#1924]
Hello, I don't know if this is related only to my setup or global problem with 8.0, but here me out. I was running HassOS 7.6 with nevest HA as VM on XCP-NG 8.2.1. Everything was fine up to update of HassOS to 8.0. 

My normally static IP changed to DHCP, no big deal, but I can't switch it back to static, because of this error.

![obraz](https://user-images.githubusercontent.com/55739518/169092835-a2f35bb4-a479-4f13-af9d-11e92c4505e8.png)

While inspecting HassOS console i noticed that interface has name enX0 instead of enx0, but frankly I don't know if it was enX or enx before.

![obraz](https://user-images.githubusercontent.com/55739518/169095206-0d2a1d6a-3fa5-456a-b4e8-a757492946b9.png)

Also I don't know if this is related, but my AdGuard also stopped working and probably because same issue with interface naming:

LOG from AdGuard:
```
[cont-init.d] adguard.sh: executing... 
[18:14:29] ERROR: Got unexpected response from the API: Interface enx0 does not exist
[cont-init.d] adguard.sh: exited 0.
```
And it only binds to 127.0.0.1:53 and some internal docker address of 172.30.32.1:53 (no LAN address from 10.1.78.0/24 network)

I did clean install of HassOS with vmdk image, and it is enX0 even after vanilla install. And same error in HA are present.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Clean install on XCP-NG
2. Examine name of interface

### Anything in the Supervisor logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-05-18 11:40:17 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/interface/enX0/update - Interface enx0 does not exist
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Unable to find configuration. Creating default one in /config
[finish] process exit code 0
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-05-18 11:52:06 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/interface/enX0/update - Interface enx0 does not exist
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[finish] process exit code 0
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

### Anything in the Host logs that might be useful for us?

```txt
Nothing
```

### System Health information

Wersja 	core-2022.5.4
Typ instalacji 	Home Assistant OS
Wersja deweloperska 	false
Supervisor 	true
Docker 	true
Użytkownik 	root
Środowisko wirtualne 	false
Wersja Pythona 	3.9.9
Rodzina systemu operacyjnego 	Linux
Wersja systemu operacyjnego 	5.15.38
Architektura procesora 	x86_64
Strefa czasowa 	Europe/Warsaw

Home Assistant Supervisor
System operacyjny hosta 	Home Assistant OS 8.0
Kanał aktualizacji 	stable
Wersja Supervisora 	supervisor-2022.05.2
Wersja Dockera 	20.10.14
Pojemność dysku 	30.8 GB
Pojemność użyta 	2.1 GB
Zdrowy 	true
Wspierany 	true
Układ 	ova
API Supervisora 	ok
Wersja API 	ok
Zainstalowane dodatki 	AdGuard Home (4.5.1)

**Comment by agners** [comment]
This is a Supervisor issue tracked here: https://github.com/home-assistant/supervisor/issues/3645

It might be that the new OS caused a new name for that interface. But the Supervisor should be able to handle it.
