### ISSUE TITLE
VM on proxmox fails to start after 8.1 upgrade

### ISSUE THREAD

**Issue by sinmaniphel** [home-assistant/operating-system#1939]
### Describe the issue you are experiencing

Yesterday I tried to update my Proxmox hosted Home Assistant OS to 8.1.

To my dismay, after restart, the VM goes 100% CPU and stalls even before having a TTY or a network interface up and running. Essentially it's bricked and I don't have a clue as to what is happening

AFAIK the problem is not universal since a friend of mine with such a setup did not find any issue. 

Luckily the VM has a backup so I could restore my HA instance, but it can be quite the severe issue otherwise.

I am very sorry for such a shallow bug report, I will try anything you throw at me to get a deeper understanding of what's happening. 

### What operating system image do you use?

Open Virtual Appliance (haos_ova)

### What version of Home Assistant Operating System is installed?

8.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade the OS to 8.1
2. Watch the VM failing to start while hanging at 100% CPU

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

### Additional information

N/A

**Comment by agners** [comment]
Thanks for the report, yeah with the current information its not really possible to do much. If the machine gets completely unresponsive, it sounds as if the kernel is at fault. However, we use the latest upstream Vanilla Linux kernel 5.15.41, it would surprise me if it causes issues with Proxmox.

**Comment by sinmaniphel** [comment]
I would like to propose for this bug to stay open for a given time to make sure it's not "common" since the release is still a bit fresh. 

If I'm the only one, so be it (hoping it won't happen with future releases), if not maybe with some more use cases we can guess something. 

Thanks anyway

**Comment by garylovesbeer** [comment]
Possibly unrelated but I am unable to upgrade my Proxmox HA install from OS7.6 to 8.1. The logs contain this error

`
ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed marking slot kernel.0 non-bootable: Failed marking 'kernel.0' as bad: Failed to run barebox-state: Child process exited with code 1
`

**Comment by tteck** [comment]
> generic-x86-64 (Generic UEFI capable x86-64 systems)

You did't use the `haos_ova-8.1.qcow2.xz` image?

**Comment by tteck** [comment]
Have you tried to create a new VM lately (the script has changed)?

**Comment by sinmaniphel** [comment]
`pve-manager/7.1-12/b3c09de3 (running kernel: 5.13.19-2-pve)`

yeah no, I'll start with that as soon as I have a minute. Thanks for the tip

**Comment by sinmaniphel** [comment]
I could successfully update to 8.2 so, without much more info of life on this bug, I consider it closed.

Thank you for your help and attention fellas
