### ISSUE TITLE
~Random Crashes (Cascade Failures ?) Making Home Assistant Unreliable.

### ISSUE THREAD

**Issue by RJ-Make** [home-assistant/operating-system#1944]
### Describe the issue you are experiencing

I'm new to Home Assistant (moved from HomeSeer late last year) so I'm not sure if this is the correct place to post a problem like this.  If not please direct me where I need to go.  

When starting out; these "Lockups" (ie: Loss all function In or Out) only happened once or twice, but now that I'm fully moved over to HA, I'm experiencing them more frequently.

Up until now, I've never been able to access the system to pull any information, and when I restart the VM the logs don't reflect what happened. (Why is that anyway? Shouldn't logs always be persistent through restarts?)

Setup:
VirtualBox VM Has 4GB Ram and 3 vCores
Windows 10 Host (Intel i7-8700K CPU @ 3.70GHz   3.70 GHz With 32GB Ram)

This morning, I was actually able to get into the UI and pull some logs. 

This is a screen shot of what I was looking at.

<img width="1723" alt="2022-05-26_5-01-06" src="https://user-images.githubusercontent.com/8496835/170570617-a327ddcc-88b9-4da4-b85a-940a5bbf58a6.png">

<img width="354" alt="2022-05-26_4-54-57" src="https://user-images.githubusercontent.com/8496835/170570168-32cff9dd-8e11-4b19-acbd-3074dd4a5058.png">

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

7.6

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

There are no reproduction steps, this is completely random. The only non-random part of these crashes are they mainly take place at night (between 11 and 5 am (using z-wave temperature devices history to determine approximate failure)

### Anything in the Supervisor logs that might be useful for us?

```txt
The system page would not open during this state. I've included the logs I could get to below
```

### Anything in the Host logs that might be useful for us?

```txt
I've included the logs I could get to below
```

### System Health information

I don't believe I could reach the Health Information page

### Additional information

[home-assistant.log](https://github.com/home-assistant/operating-system/files/8781878/home-assistant.log)
[home-assistant_1.log](https://github.com/home-assistant/operating-system/files/8781883/home-assistant_1.log)
[home-assistant_Fault.log](https://github.com/home-assistant/operating-system/files/8781885/home-assistant_Fault.log)
[zwavejs2mqtt-store(1).zip](https://github.com/home-assistant/operating-system/files/8781886/zwavejs2mqtt-store.1.zip)

**Comment by agners** [comment]
> Fatal Python error: Segmentation fault

It seems that Home Assistant (presumably Core) really crashed in that instance.

It is hard to tell from all this logs what the root cause of your stability probolems are. I've read quite some VirtualBox issues recently, especially with the latest releases. I guess if its related to the OS, you should see some kernel logs/stack traces on the VM console. Is the system responding on the VM console in those failure cases? If so, can you use `login` and then `dmesg` to get the kernel logs?

**Comment by RJ-Make** [comment]
> > Fatal Python error: Segmentation fault
> 
> It seems that Home Assistant (presumably Core) really crashed in that instance.
> 
> It is hard to tell from all this logs what the root cause of your stability probolems are. I've read quite some VirtualBox issues recently, especially with the latest releases. I guess if its related to the OS, you should see some kernel logs/stack traces on the VM console. Is the system responding on the VM console in those failure cases? If so, can you use `login` and then `dmesg` to get the kernel logs?

Thanks for looking at the logs, On the next 'crash' I will attempt to use the VM console and run the requested command to get the logs.  You right about VirtualBox's recent releases (.32 and .34), but I'm running an older (.30), and from all internet accounts, a reliable build.

Is there a more reliable VM solution (that I can pass USB devices) that is recommended?

Normally, HA is completely 'dead in the water'. This was the first time (and perhaps unrelated to past crashes) I was able to get anything from HA.

**Comment by agners** [comment]
> Is there a more reliable VM solution (that I can pass USB devices) that is recommended?

Not sure, I am using Virtual Machine Manager (libvirt) on Linux mainly. I guess VMware should also work on Windows.

**Comment by RJ-Make** [comment]
Well that happened fast,. had to reboot the server for another program update and I'm now facing the same problem. I entered dmesg and a lot of text scrolled, but I don't know how to copy the text. I can't even scroll up.

**Comment by agners** [comment]
> I entered dmesg and a lot of text scrolled, but I don't know how to copy the text. I can't even scroll up.

The problem usually is at the bottom, if there is a kernel problem, so a screenshot might be sufficient. If you have Web frontend access, the "host" logs provide the full logs as text.

**Comment by RJ-Make** [comment]
I tried to take a series of of screen shots, I can upload those, I think this one is the last one or very close to it.  and of course I didn't think to grab the host logs via the UI. 

<img width="1037" alt="2022-05-27_9-23-17" src="https://user-images.githubusercontent.com/8496835/170712252-8feb07a4-3e3d-4bfe-96f2-a77584f6cd57.png">

**Comment by RJ-Make** [comment]
Here's the first, screen shot in that attempt, it shows some of the last attempt. 

<img width="1034" alt="2022-05-27_9-22-26" src="https://user-images.githubusercontent.com/8496835/170712514-71e9f731-93b6-44a8-a597-1c9f4cd5d7f1.png">

**Comment by RJ-Make** [comment]
I'm closing this for now as I've moved to VMware and spun up a new 8.1 install. I tell you what @agners the speed difference between vBox and VMware makes the move so much easier.. Thanks for the suggestion.

**Comment by agners** [comment]
If you have noticeable speed difference there was probably something wrong with VirtualBox. TBH, lately VirtualBox seems to be more and more problematic.
