### ISSUE TITLE
HA 8.1 unable to load firmware rtl8125b-2.fw

### ISSUE THREAD

**Issue by brijam** [home-assistant/operating-system#1972]
### Describe the issue you are experiencing

Installed HA 8.1 on an ASUS PN41, and get no internet connection.  This error appears in the startup sequence:

unable to load firmware rtl_nic/rtl8125b-2.fw (-2)

As I understand it the fix for a debian system is for non-free universe repo to be enabled and firmware-realtek to be installed.

What's the best way to fix this?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

8.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. flash PN41 with 8.1 according to instructions
2. boot

### Anything in the Supervisor logs that might be useful for us?

```txt
Unable to reach configuration panel as networking is not working
```

### Anything in the Host logs that might be useful for us?

```txt
Unable to reach configuration panel as networking is not working
```

**Comment by shajek** [comment]
this error show on Odroid XU4 too
