### ISSUE TITLE
Configuration missing from sidebar after upgrade

### ISSUE THREAD

**Issue by martinsbt** [home-assistant/operating-system#1983]
### Describe the issue you are experiencing

Configuration missing from sidebar after upgrade! this is annoying and i cannot get it back! How can i fix this please

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

8.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.be at version 7.4
2. upgrade core to 2022.6.7
3.then upgrade OS to 8.2
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
This is not related to the OS. The Core renamed the entry from Configuration to Settings already in 2022.5 (see https://www.home-assistant.io/blog/2022/05/04/release-20225/#reorganized-settings-menu).
