### ISSUE TITLE
Typo in Network Documentation 

### ISSUE THREAD

**Issue by Danny2100** [home-assistant/operating-system#1984]
### Feedback

Not sure how this wasn't caught in a pull request that was recently merged.

```
WiFi is discouraged for reliability reasons. However if you're still like to use WiFi, you can us the ha network command to set up WiFi (example for a Raspberry Pi 4, check ha network info to check if your board supports WiFi and the name of the WiFi device):
```

It should say "However, if you still want to use WiFi, you can use..." Or something to that effect.

### URL

https://github.com/home-assistant/operating-system/blob/33575b639e61e0082c14692642cd56b36c2a6023/Documentation/network.md

**Comment by agners** [comment]
Whops, didn't meant to edit that on dev directly :sweat_smile: 

Somehow the online editor allowed me to do this :man_shrugging: . Well, it's done now :sweat_smile: .
