### ISSUE TITLE
Can't install on VM using the last version 8.2

### ISSUE THREAD

**Issue by alfonsolsl** [home-assistant/operating-system#1995]
### Describe the issue you are experiencing

After my HA breaks cos the new 8.2 OS install i'm trying to fress install on a new VM but i have the same error i had before:

`systemd-journald[108]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected`

I get the host available even now but keeps on "Preparing Home Assistant" forever.

Tha same error keeps me out on my other VM and i did not change anything but upgrade the OS from 8.1 to 8.2.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.2

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Configure VM following official web instructions.
2. Turn on the VM and wait the installation
3. The Home assistant CLI starts
4. Then show the msg about the endpoint, not going further this point.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
i do not have access
```

### Anything in the Host logs that might be useful for us?

```txt
i already report it above.
```

**Comment by alfonsolsl** [comment]
I restarted and the message appears after a long time.

The observer says:

<html>
<body>
<h1 style="margin-top: 8px; color: rgb(33, 33, 33); font-family: Roboto, &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Home Assistant observer</h1>

Supervisor: | Connected
-- | --
Supported: | Supported
Healthy: | Healthy


</body>
</html>

but i can not access HA

**Comment by alfonsolsl** [comment]
after a while and several autoreboots...
![image](https://user-images.githubusercontent.com/6255385/176271924-eb54a891-1eb1-43fb-b95b-a4fd4427e1c1.png)

**Comment by alfonsolsl** [comment]
Finally... Breaks..
![image](https://user-images.githubusercontent.com/6255385/176275773-9a0cdfed-a4ed-4300-9af6-411af00bb231.png)

**Comment by alfonsolsl** [comment]
i tried in another server and works as expected, the old one was totally unattended and any part was updated, so this it's happening by itself. 

I remove virtualbox and installed 6.1.30 version and the issue persist in a new installation.

**Comment by teji24** [comment]
same problem !
