### ISSUE TITLE
VirtualBOX VM starting up but no UI access

### ISSUE THREAD

**Issue by MihleTX** [home-assistant/operating-system#2004]
### Describe the issue you are experiencing

I see that others are having other issues with Virtual Box VMs, but in my case the VM was working just fine, then the connection to the server via the IP address shows refused.

 In my case, the VM is getting an IP just fine, and it looks just like it normally does when I boot up, but when I try to access the HA address, the connection says it is refused. I even spun up a new VM, with native out of the box new instance, and I get the same thing, I get an IP, but the server for the UI never resolves. It just happened out of no where. Working one day, gone the next with no changes. I figured I could solve it by spinning up the new VM, but when that did not work, I decided to just try a virgin install, but that did not work either.

I went in to look at the supervisor logs. They look fine,

When I go to look at the Core logs, I am getting some errors and it shows that the core is shutting down - exit code 1

Process exit code 256
Core process received signal 15

I cant interpret those however…

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

6.7

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Start up the VM with the software
2.Start up looks complete and shows local IP
3. No UI ever becomes present.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I cannot get to the supervisor logs, but via the ssh, I see no issues in the logs
```

### Anything in the Host logs that might be useful for us?

```txt
The Core - shows logs that have this:

When I go to look at the Core logs, I am getting some errors and it shows that the core is shutting down - exit code 1

Process exit code 256
Core process received signal 15
```

### Additional information

Overall - the system was operating just fine and then just stopped.

I tried also to just spin up a new VM with a base OS and it did that just fine, but again - same issue with no UI access to the system
![Screen Shot 2022-07-05 at 9 45 19 AM](https://user-images.githubusercontent.com/44853368/177355916-31e86412-b7ab-40de-9a35-ef4b0adf8231.png)
.

**Comment by agners** [comment]
It seems your entity registry got corrupted. Maybe its only a small thing, but hard to tell. Can you check line 40994 of `/mnt/data/supervisor/homeassistant/.storage/core.entity_registry`.

**Comment by MihleTX** [comment]
Yes - I just ran a core check and it shows a general error on that line.

Should I just try and rebuild an entirely new VM instance with a new core and try and update from backup?


Thanks

M

**Comment by agners** [comment]
Hm, looks like data corruption occurred then :cry: 

> Should I just try and rebuild an entirely new VM instance with a new core and try and update from backup?

Probably the best way forward yes.
