### ISSUE TITLE
[Rpi 3+ Rev. B] Webinterface never gets ready on fresh 8.2 image

### ISSUE THREAD

**Issue by erdnuesse** [home-assistant/operating-system#2016]
### Describe the issue you are experiencing

64-bit: waiting for Web interface to become available. 
Web interface loads, but never gets ready. 

Looked at this
[https://community.home-assistant.io/t/solution-to-a-hanged-preparing-home-installation-screen-during-new-install-on-a-raspberry-pi-4-dns-fix/273803](https://community.home-assistant.io/t/solution-to-a-hanged-preparing-home-installation-screen-during-new-install-on-a-raspberry-pi-4-dns-fix/273803)

Puzzled by hardcoded DNS servers - I thought HA.io would be most interesting for ppl who want to keep most services internally and not anticipating self-hosted DNS servers or at least use the ones pushed from my gateway was mildly confusing.

Same goes for timeservers. 

Fixed both, but worse, the web interface didn't come up at all after reboot, as if the webserver crashed. 
Additionally, there is no command "network" that was mentioned in the post^

Gave up - tried the 32-bit variant after I found the other post.

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

haos_rpi3-64-8.2

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Install HASSOS 64 bit on Rpi 3+ rev. B
2. 
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no idea. didn't know what to look for.
It was right after installation / image pushing, first boots, so I had to assume a not working image tbh.
```

### Anything in the Host logs that might be useful for us?

```txt
no idea. didn't know what to look for.
It was right after installation / image pushing, first boots, so I had to assume a not working image tbh.
```

### System Health information

mi pi runs a bit hot sometimes currently. 

### Additional information

I looked at [https://github.com/home-assistant/operating-system/issues/1999](https://github.com/home-assistant/operating-system/issues/1999) and tried out the 32-bit variant. Opening a separate issue on that. 

I have a Homelab, and I block outbound DNS and NTP from any devices that are not my internal DNS or NTP servers.

**Comment by erdnuesse** [comment]
Update:
Did some "debugging" as in, tried different versions, checked temparatures, put it in front of my fan, different SD cards. 

As soon as I removed my RaspBee II - it booted up. 
Looks like that thing prevented the services from loading up properly. 

I have no idea if that's now permanent, or just been a glitch; I'll gladly try and reproduce for potential debugging, if needed.

**Comment by agners** [comment]
> As soon as I removed my RaspBee II - it booted up. (and yes, I didn't mention it, because frankly, I forgot.)

Are you sure this is the cause, and not just a coincidence?

Maybe for better understanding, by default, the OS only ships with a minimal frontend called "landingpage" (which acts as webserer by default).

The Supervisor then will download Home Assistant Core. The Core will provide the full web interface once downloaded. When switching between landingpage and core there can be a slight hickup. In restricted network environments (as you seem to use) this might cause hickups as well. It is hard to tell without logs what exactly was going on in your case, I am sorry.

**Comment by edurenye** [comment]
Seems like with 32bit restarting the device make it work
