### ISSUE TITLE
Home assistant error every home assistant core update notification 

### ISSUE THREAD

**Issue by broekp** [home-assistant/operating-system#2027]
### Describe the issue you are experiencing

I noticed that my home assistant energy dashboard and other features stop working after one or more days last 8 to 10 weeks
After checking the host logs when this happens ii noticed that the filesystem was read only and a reboot of my home assistant solves the issue.... temporarily.

After some time i noticed that the error always _seems_ to coincide with receiving an update notification for home assistant core (or possible even another update) and this seems to be happening since a month or 2 now so not sure when it started.

It looks 100% reproducable and seems to be triggered by the notification of updates. 

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Make every thing work fine 
2. Wait for update of a home assistant core 
3. Tadaaa
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Not that i can tell
```

### Anything in the Host logs that might be useful for us?

```txt
host logs shows that file system is read only when this happens but i read that that is what happens when home assistant has a fatal error. Willig to upload a host log after this happens.
```

## System Health

version | core-2022.7.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.45
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4842
Installed Version | 1.25.5
Stage | running
Available Repositories | 1071
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 70.2 GB
disk_used | 17.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), MariaDB (2.5.0), SSH & Web Terminal (11.0.2), Eufy Security Add-on (0.9.2), RTSP Simple Server Add-on (v0.17.6), AdGuard Home (4.6.1), UniFi Network Application (2.3.0), ESPHome (2022.6.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 16
views | 16
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 juli 2022 om 06:40
-- | --
current_recorder_run | 21 juli 2022 om 16:55
estimated_db_size | 428.50 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Additional information

Using a vm install on proxmox, used to work fine for a few months at least.

**Comment by agners** [comment]
> After checking the host logs when this happens ii noticed that the filesystem was read only and a reboot of my home assistant solves the issue.... temporarily.

The root file system is on purpose read-only: We use a read-only squashfs image. Only the containers and data is written to a read-write mounted partition.

Your poblem is likely related to the Core. Please check the Core logs when the issue starts, I'd expect you'll see some warnings or errors in there.
