### ISSUE TITLE
Bug? Using OS 8.2, and could not get OS release upgrade notification 8.3 and 8.4 

### ISSUE THREAD

**Issue by k8gg** [home-assistant/operating-system#2029]
### Describe the issue you are experiencing

Started a thread here: https://community.home-assistant.io/t/ha-os-not-getting-update-notification-since-8-2/443253
and noticed that I'm not alone.

HA OS not getting update notification beyond 8.2

If I force the OS to update to 8.4, using `ha os update --version=8.4`, and then do the `ha os info` command again, I would get this: 
https://community-assets.home-assistant.io/original/4X/5/f/0/5f05664563f081f13bf951b4d1140a829fbb32bc.png

The upgrade from 8.2 to 8.4 went fine.

And then if I do `ha os update` on OS 8.4, it would bring the OS back to 8.2.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.2.

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. open CLI to the HAOS VM
2. use `ha os info` command
3. the output reads `version_latest: "8.2"` today (25-Jul-2022). However, OS 8.4 was released on 23-Jul-2022, and OS 8.3 was released on 7-Jul-2022.
4. if I force the OS to update to 8.4, using `ha os update --version=8.4`, and then do the `ha os info` command again, I would get this: 
https://community-assets.home-assistant.io/original/4X/5/f/0/5f05664563f081f13bf951b4d1140a829fbb32bc.png

### Anything in the Supervisor logs that might be useful for us?

```txt
nothing stands out
But Supervisor 2022.07.0
```

### Anything in the Host logs that might be useful for us?

```txt
nothing stands out here either
```

## System Health

version | core-2022.7.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.45
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4866
Installed Version | 1.26.2
Stage | running
Available Repositories | 1070
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 48.5 GB
disk_used | 10.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Mosquitto broker (6.1.2), File editor (5.3.3), Check Home Assistant configuration (3.11.0), Studio Code Server (5.2.0), AirCast (3.4.0), AdGuard Home (4.6.1), SSH & Web Terminal (11.0.2), motionEye (0.18.0), MariaDB (2.5.0), ZeroTier One (0.15.1), Zigbee2MQTT (1.26.0-1), Home Assistant Google Drive Backup (0.108.2), Cloudflared (2.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 17, 2022 at 23:18
-- | --
current_recorder_run | July 25, 2022 at 22:38
estimated_db_size | 48.69 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Sonoff</summary>

version | 3.1.0 (3871c0b)
-- | --
cloud_online | 0 / 1
local_online | 1 / 1

</details>

**Comment by frenck** [comment]
> HA OS not getting update notification beyond 8.2

That is correct, 8.2 is what is currently available as stable.
8.3 hasn't come out of beta (and had issues), 8.4 is currently being tested.

See also: <https://version.home-assistant.io/stable.json>
