### ISSUE TITLE
HA restart fail using certain characters in an AppleID password

### ISSUE THREAD

**Issue by zippety-stu** [home-assistant/operating-system#2071]
### Describe the issue you are experiencing

Using iCloud3 for person location.
Using my Apple ID e-mail and password in 'secrets.yaml'
My AppleID password starts with '+' and ends with '!'
Get a restart failure, see screenshot:
"<img width="567" alt="HA restart failure" src="https://user-images.githubusercontent.com/98122369/185364653-9003c8e3-4226-4c0a-8594-52a7d22e9bae.png">

I overcame this issue with a password change to remove the '!' and '+', but this is not helpful for me.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Supervisor 2022.08.3 / OS 8.4 / Frontend 20220802.0

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Use an AppleID password starting with '!' and ending with '+' (I'm not a software guy, but I guess there may be other special characters that do this. I don't know which - '!' or '+', or both - is throwing the error)
2. Enter these in 'secrets.yaml'  
3. Use iCloud3 (or any thing else that uses AppleID, I guess) and refer to 'secrets.yaml' for AppleID username and password
4.  Attempt to restart HA using System-Restart
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Three HA Core log error messages:

1) This error originated from a custom integration.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:1498 
Integration: icloud3 (documentation, issues) 
First occurred: 10:48:11 (1 occurrences) 
Last logged: 10:48:11

iCloud3 Error > An error occurred authenticating <my AppleID username>. The iCloud Web Services may be down or the Username/Password may be invalid. The iCloud Location Services tracking method is disabled and the iOS App tracking method will be used. . The authentication will be retried in 15 min at 11:03:11.

(NB - iCloud Web Services were running without issues when this occurred)

2)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:705 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10:36:13 (1 occurrences) 
Last logged: 10:36:13

[139778497164624] The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: could not determine a constructor for the tag '!<rest of my AppleID password>+' in "/config/secrets.yaml", line 10, column 33
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 705, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: could not determine a constructor for the tag '!<rest of my AppleID password>+'
  in "/config/secrets.yaml", line 10, column 33


3) Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:694 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 10:36:13 (1 occurrences) 
Last logged: 10:36:13

The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: could not determine a constructor for the tag '!<rest of my AppleID>+' in "/config/secrets.yaml", line 10, column 33
```

### Anything in the Host logs that might be useful for us?

```txt
I can't see anything referring to the restart issue
```

### System Health information

I can't see System Health anywhere. Maybe it got moved in a previous update?

**Comment by agners** [comment]
In fact, this is probably not a Core issue. but an issue of the custom component you are using (`custom_components.icloud3.device_tracker`). Please report your problem to the author of that component.
