### ISSUE TITLE
home-assistant.log.fault after restore

### ISSUE THREAD

**Issue by repiuk** [home-assistant/operating-system#2080]
### Describe the issue you are experiencing

Restored from the latest backup by installing a fresh HA OS. copying the backup tar and starting the restore. I noticed all recording and history (energy) was gone. home-assistant_v2.db (13Gb) is restored. I also see a home-assistant.log.fault file of 0b

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

8.5

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. fresh ha install
2.restore backup
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.recorder.util
Source: components/recorder/util.py:209
Integration: Recorder (documentation, issues)
First occurred: 13:12:29 (1 occurrences)
Last logged: 13:12:29
The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
The `home-assistant.log.fault` is a log file generated by Home Assistant Core when it crashes. 

Since the database file seems to be restored, this is unlikely a HA OS issue. I recommend opening a Core issue and attaching the fault file.
