### ISSUE TITLE
Can't Disable PWR LED of a Raspberry Pi4b 8Gb 

### ISSUE THREAD

**Issue by scxs535** [home-assistant/operating-system#2132]
### Describe the issue you are experiencing

I use follow code to disable the PWR LED of Raspberry Pi4b 8Gb with HA OS ( core 9.4) in boot/config.txt file
dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off
it works fine still with operating system to 8.5

but it doesn't work anymore after upgrade operating system to 9.0 

maybe it has something to do with the change #2038 .
https://github.com/home-assistant/operating-system/pull/2038

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

I use follow code to disable the PWR LED of Raspberry Pi4b 8Gb with HA OS ( core 9.4) in boot/config.txt file
dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off
it works fine still with operating system to 8.5

but it doesn't work anymore after upgrade operating system to 9.0 

maybe it has something to do with the change #2038 .
https://github.com/home-assistant/operating-system/pull/2038

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by TeleRocker22** [comment]
What does your `/boot/config.txt` look like? I had the same problem with my Pi 3B+ and I found the solution on the following page.

[https://github.com/raspberrypi/firmware/issues/1742](https://github.com/raspberrypi/firmware/issues/1742)

I put the SD card in my laptop, mounted the boot partition, and commented out the following line in my config.txt file:

`#dtparam=pwr_led_trigger=none`

Leave the `dtparam=pwr_led_activelow=off`

I hope this helps!

**Comment by agners** [comment]
Hm, I see, this fix has actually been triggered by a problem I observed on Yellow, see https://github.com/raspberrypi/linux/issues/5107 :see_no_evil: 

In any case, this was a bug in the old firmware, and with the new firmware the following is the recommended method to disable (see https://github.com/raspberrypi/firmware/issues/1742#issuecomment-1225910618):

```
dtparam=pwr_led_trigger=default-on   # The default
dtparam=pwr_led_activelow=off
```

**Comment by agners** [comment]
In the end, this change is necessary because of a bug in the Raspberry Pi firmware, which has been fixed with the latest release (and made it into HAOS 9.0). Nothing we can do from HAOS side. Please update your `config.txt` accordingly.

**Comment by scxs535** [comment]
thanks guys, 
it works now perfect with only this code on operating system 9.0: 
dtparam=pwr_led_activelow=off
