### ISSUE TITLE
HA Linux OS broken after 8.5 -> 9.0 update

### ISSUE THREAD

**Issue by ramphex** [home-assistant/operating-system#2136]
### Describe the issue you are experiencing

After starting the update in the GUI from 8.5 to 9.0, the server never booted back up.

After accessing the VM console in Proxmox, I'm presented with an UEFI shell (screen shot below)

<img width="1039" alt="Screen Shot 2022-09-16 at 15 50 11" src="https://user-images.githubusercontent.com/43665314/190719446-0918b414-c9ea-4de4-b391-d892418243af.png">

No other configuration changes were made. Just launched the update and the system broke.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

8.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Launched 8.5 -> 9.0 update
2. Fail

### Anything in the Supervisor logs that might be useful for us?

```txt
No access to Supervisor
```

### Anything in the Host logs that might be useful for us?

```txt
No access to HA settings
```

### Additional information

<img width="899" alt="Screen Shot 2022-09-16 at 15 52 33" src="https://user-images.githubusercontent.com/43665314/190720172-5005d24b-7f18-4910-95c9-8071d6feb11f.png">

<img width="951" alt="Screen Shot 2022-09-16 at 15 52 57" src="https://user-images.githubusercontent.com/43665314/190720323-2e81b9c8-cf48-4d6f-80b2-58d502b2f39e.png">

Secure Boot is Disabled.

**Comment by agners** [comment]
Are you indeed using the generic-x86-64 image or the ova?

Hm, it seems that the boot partition got corrupted somehow. Can you download an Ubuntu Live image and boot into it? I wonder if the files on the first partition are intact. This is from a working ova installation:

```
EFI
EFI/BOOT
EFI/BOOT/grubenv-B
EFI/BOOT/grubenv-A
EFI/BOOT/bootx64.efi
EFI/BOOT/grub.cfg
EFI/BOOT/grubenv
cmdline.txt
```

You can restore the boot partition with a process along these lines (make sure to create a snapshot first!):
https://github.com/home-assistant/operating-system/issues/1913#issuecomment-1128642946

**Comment by agners** [comment]
FWIW, I recommend using a SCSI hard disk over S-ATA, as it has usually better virtualization support. That said, just using S-ATA  should not lead to such a corruption :(

**Comment by agners** [comment]
We had similar reports in the past, e.g. #1125. However, despite checking that everything is getting unmounted correctly and even syncing the FAT partition, we do get these reports from time to time. Did the update run through without hickup? Did you had to force a reboot or similar or did it reboot on its own?

**Comment by ramphex** [comment]
> We had similar reports in the past, e.g. #1125. However, despite checking that everything is getting unmounted correctly and even syncing the FAT partition, we do get these reports from time to time. Did the update run through without hickup? Did you had to force a reboot or similar or did it reboot on its own?

The update was going through, then the prompt for "reconnecting" came up, and the page never reloaded. Upon inspecting the console on Proxmox, it presented me with the UEFI Shell. I'm assuming it rebooted on it's own. I have not been able to get out of that shell, nor am I familiar with how to navigate it. Checked the boot settings as per some other threads to make sure the Secure Boot is indeed disabled.

**Comment by ramphex** [comment]
> Are you indeed using the generic-x86-64 image or the ova?
> 
> Hm, it seems that the boot partition got corrupted somehow. Can you download an Ubuntu Live image and boot into it? I wonder if the files on the first partition are intact. This is from a working ova installation:
> 
> ```
> EFI
> EFI/BOOT
> EFI/BOOT/grubenv-B
> EFI/BOOT/grubenv-A
> EFI/BOOT/bootx64.efi
> EFI/BOOT/grub.cfg
> EFI/BOOT/grubenv
> cmdline.txt
> ```
> 
> You can restore the boot partition with a process along these lines (make sure to create a snapshot first!): [#1913 (comment)](https://github.com/home-assistant/operating-system/issues/1913#issuecomment-1128642946)

It might be OVA. I installed this a while ago and it has been running and upgrading through versions without any issues. First time any issue occurred.

**Comment by agners** [comment]
> How would I access this VM's EFI partition to verify the file content?

You need to download a live image, e.g. Ubuntu from [here](https://ubuntu.com/download/desktop/thank-you?version=22.04.1&architecture=amd64), and attach that to your virtual machine. Then boot from that image. From the Ubuntu desktop you then can browse the HA disk. The first partition on the HA disk is the FAT boot partition.

**Comment by ramphex** [comment]
<img width="585" alt="Screen Shot 2022-09-16 at 16 46 40" src="https://user-images.githubusercontent.com/43665314/190729938-ab056abb-ec71-449e-9580-5676642bc5c9.png">

The EFI partition doesn't seem to be there. Just the main disk

**Comment by agners** [comment]
> The EFI partition doesn't seem to be there. Just the main disk

Uff that means the partition table got lost. Can you run `fdisk /dev/sda`? Maybe it can recover the partition table from the backup GPT

**Comment by ramphex** [comment]
<img width="962" alt="Screen Shot 2022-09-16 at 17 02 42" src="https://user-images.githubusercontent.com/43665314/190739011-eac7f393-55dd-4bdc-8657-aaa2409a303e.png">

**Comment by agners** [comment]
Doesn't seem to be the case then 😢

**Comment by agners** [comment]
Do you have a recent backup? If so probably starting over is the best solution. If not, you can try the approach documented here https://github.com/home-assistant/operating-system/issues/1913#issuecomment-1128642946

If you can share the current state of the disk image I'd be interested to analyze it a bit more.

**Comment by ramphex** [comment]
So what do I do now? Is there any way to recover the backup from it? Why would the updater break the partition table?

**Comment by ramphex** [comment]
<img width="796" alt="Screen Shot 2022-09-16 at 17 54 23" src="https://user-images.githubusercontent.com/43665314/190804860-8de7f048-ccd4-463e-8160-388c8245bbbb.png">
Tried making a backup of the VM in Proxmox :-\

**Comment by ramphex** [comment]
> Do you have a recent backup? If so probably starting over is the best solution. If not, you can try the approach documented here [#1913 (comment)](https://github.com/home-assistant/operating-system/issues/1913#issuecomment-1128642946) (using vdi from HAOS 9.0)
> 
> If you can share the current state of the disk image I'd be interested to analyze it a bit more.

The solution from that post worked. Is there anything else I should do now to ensure the outmost stability? Not sure how much this fix has affected the underlying system operation, seems pretty straightforward though.

**Comment by agners** [comment]
>  Is there anything else I should do now to ensure the outmost stability?

Unfortunately I don't really know. I am not exactly sure where these corruptions come from.

**Comment by thedead** [comment]
Happened to me going from 9.0 -> 9.2 on Proxmox.

Restoring my VM backup to the existing VM didn't work, nor did creating a new VM work.  

I had to follow the steps posted above in Linux to restore the boot partition.

**Comment by ioctl2** [comment]
I upgraded an 8.5 instance (also running on Proxmox) to 9.2 and did not experience this.

My VM settings:
![image](https://user-images.githubusercontent.com/111940467/196325402-d4088bad-fda3-446e-9436-fd601b38f511.png)
![image](https://user-images.githubusercontent.com/111940467/196325516-13d17637-5c64-431e-8447-592587dca3a4.png)

**Comment by brainrecall** [comment]
I recently got this as well, upgraded to 9.2 and the VM would not boot. The proxmox UEFI could not see the drive as a bootable disk. Doing fdisk from proxmox it recognized the MBR was corrupt, and I was able to write it back. Then it started fine.

I have had several other VMs on that machine for years, and none of them managed to corrupt the MBR. I think this is specific to HAOS .

**Comment by thedead** [comment]
Happened to me again today
