### ISSUE TITLE
8.X 9.X problems with multiple bluetooth adapters

### ISSUE THREAD

**Issue by 50494554524F** [home-assistant/operating-system#2143]
### Describe the issue you are experiencing

when i add an asus bt-400 to the raspberry it can be recognized (not always) and it goes on hci1, ok.

if i try to reboot the host then it goes on hci0 like the internal adapter, they conflicts, so things are messed up.

~~if i accept to use it on hci0 bluetooth devices turn unavailable after a while, i.e. a switchbot bot.~~ (switchbot integration bug)

(could be useful reinstalling the os from scratch?!)

thanks

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

8.X 9.X

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. boot without the asus bt-400
2. insert the asus bt-400
3. if recognized, select hci1 from the bluetooth integration (core 2022.8.X)
4. reboot the host
5. bluetooth integration now gives an error, the internal adapter it's not recognized, asus bt-400 goes on hci0

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

[    7.521589] Bluetooth: Core ver 2.22
[    7.522366] Bluetooth: HCI device and connection manager initialized
[    7.522383] Bluetooth: HCI socket layer initialized
[    7.522392] Bluetooth: L2CAP socket layer initialized
[    7.522419] Bluetooth: SCO socket layer initialized
[    7.661356] Bluetooth: hci0: BCM: chip id 63
[    7.664357] Bluetooth: hci0: BCM: features 0x07
[    7.682381] Bluetooth: hci0: BCM20702A
[    7.682399] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[    7.684435] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[    7.684471] Bluetooth: hci0: BCM: 'brcm/BCM20702A1-0b05-17cb.hcd'
[    7.684481] Bluetooth: hci0: BCM: 'brcm/BCM-0b05-17cb.hcd'
[   14.313621] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   14.313633] Bluetooth: BNEP filters: protocol multicast
[   14.313647] Bluetooth: BNEP socket layer initialized
[  109.991728] Bluetooth: RFCOMM TTY layer initialized
[  109.991754] Bluetooth: RFCOMM socket layer initialized
[  109.991785] Bluetooth: RFCOMM ver 1.11
[  496.941886] Bluetooth: hci0: BCM: chip id 63
[  496.944880] Bluetooth: hci0: BCM: features 0x07
[  496.962878] Bluetooth: hci0: BCM20702A
[  496.962898] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[  496.965973] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[  496.966003] Bluetooth: hci0: BCM: 'brcm/BCM20702A1-0b05-17cb.hcd'
[  496.966022] Bluetooth: hci0: BCM: 'brcm/BCM-0b05-17cb.hcd'
[  644.947653] Bluetooth: hci0: BCM: chip id 63
[  644.950641] Bluetooth: hci0: BCM: features 0x07
[  644.968647] Bluetooth: hci0: BCM20702A
[  644.968667] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[  644.969734] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[  644.969768] Bluetooth: hci0: BCM: 'brcm/BCM20702A1-0b05-17cb.hcd'
[  644.969788] Bluetooth: hci0: BCM: 'brcm/BCM-0b05-17cb.hcd'
[  651.340545] Bluetooth: hci0: BCM: chip id 63
[  651.342533] Bluetooth: hci0: BCM: features 0x07
[  651.360600] Bluetooth: hci0: BCM20702A
[  651.360620] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[  651.362628] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[  651.362662] Bluetooth: hci0: BCM: 'brcm/BCM20702A1-0b05-17cb.hcd'
[  651.362683] Bluetooth: hci0: BCM: 'brcm/BCM-0b05-17cb.hcd'

**Comment by agners** [comment]
Linux does not have a guaranteed order of devices, the device names get assigned whatever comes first, and it seems that in your system that ends up to be random :disappointed: 

If you don't use the internal Bluetooth, probably disabling it is the best approach. You have to edit the `config.txt` file in the first partition of the SD card, add the following at the end of that file:

```
dtoverlay=disable-bt
```

**Comment by 50494554524F** [comment]
> Linux does not have a guaranteed order of devices, the device names get assigned whatever comes first, and it seems that in your system that ends up to be random 😞
> 
> If you don't use the internal Bluetooth, probably disabling it is the best approach. You have to edit the `config.txt` file in the first partition of the SD card, add the following at the end of that file:
> 
> ```
> dtoverlay=disable-bt
> ```

it's not recognized after reboot, the two adapters conflicts... this is a bug to me... btw, thanks for the tip (i'm not a linux expert yet), i'm going to try to disable the internal bluetooth

**Comment by ioctl2** [comment]
> Linux does not have a guaranteed order of devices, the device names get assigned whatever comes first, and it seems that in your system that ends up to be random 😞

Perhaps it would be possible to create sticky names on first run / device install?
