### ISSUE TITLE
Upgrade from 8.5 to 9.0 fails on RPi4/64

### ISSUE THREAD

**Issue by sihagen** [home-assistant/operating-system#2154]
### Describe the issue you are experiencing

After starting the upgrade via the web interface the pi reboots but is not accessible anymore (no ping/ssh/web). When using a monitor the following error message shows up and the system is repeating it endlessly.
Rebooting the Pi without ethernet connected seemed to get it working again to boot into the "old" 8.5 OS version.

![homeassistant_os_upgrade_error](https://user-images.githubusercontent.com/18207583/192009071-6a15eceb-bc4d-4819-82bb-86767e593622.jpg)

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

8.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

See issue description

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
This very much sounds like a broken SD card 😢

**Comment by sergvanros** [comment]
The same thing happened to me tomorrow. But I did not connect HDMI monitor. After several reboots RPI starting with 8.5. I tried to update via terminal (ha os update) - again.

**Comment by sihagen** [comment]
> This very much sounds like a broken SD card 😢

Thanks for the fast reply. That would be too bad of course, but why is everything else running fine? There are no errors in the logs hinting at disk failures, Homeassistant Updates 2022.9.6 etc. are running smoothly as well.

**Comment by agners** [comment]
SD cards can fail in weird ways. Often some writes start to fail, while reads still succeed.

> There are no errors in the logs hinting at disk failures,

Well, the kerne logs above very much point to a SD card failure (or communication error with it).

**Comment by sihagen** [comment]
You were right, was a SD card failure - therefore closing this issue.
