### ISSUE TITLE
Home Assistant OS 9.0 appears to ignore config.txt on raspberry pi

### ISSUE THREAD

**Issue by JeffreyFalgout** [home-assistant/operating-system#2156]
### Describe the issue you are experiencing

I've added the following to my boot partition's config.txt to turn off the raspberry PI's activity LEDs (full [config.txt](https://github.com/home-assistant/operating-system/files/9637399/config.txt) attached):

```
dtparam=act_led_trigger=none
dtparam=act_led_activelow=off

dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off
```

This config doesn't seem to have any affect on Home Assistant 9.0. The config works again if I downgrade to 8.5.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Add something to your config.txt (accessible at /mnt/boot/config.txt via port 22222), like turning off the activity LEDs
2. Restart the raspberry pi
3. Note how the config change doesn't do anything
4. Downgrade to 8.5
5. Note how the config change starts working

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't think so... diffing the logs shows that the only real difference is that 8.5 is running on boot slot B and 9.0 is running on boot slot A
```

### Anything in the Host logs that might be useful for us?

```txt
The most interesting thing I found to my eye is this:

OS 8.5:


raspberrypi-firmware soc:firmware: Attached to firmware from 2022-03-24T13:19:26, variant start
raspberrypi-firmware soc:firmware: Firmware hash is e5a963efa66a1974127860b42e913d2374139ff5
```

OS 9.0:
```
raspberrypi-firmware soc:firmware: Attached to firmware from 2022-08-26T14:03:16, variant start
raspberrypi-firmware soc:firmware: Firmware hash is 102f1e848393c2112206fadffaaf86db04e98326
```

Happy to upload the full logs (for the supervisor too), if that'll help.
```


### System Health information

I don't see a copy icon at the top right

```
Home Assistant 2022.9.2
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.0 - latest
```

### Additional information

_No response_

**Comment by agners** [comment]
See https://github.com/home-assistant/operating-system/issues/2132.
