### ISSUE TITLE
haos_ova-9.0 in bootloop on Virtualbox if only 1 processor defined

### ISSUE THREAD

**Issue by rakoivun** [home-assistant/operating-system#2159]
### Describe the issue you are experiencing

When starting image in Virtual box the OS goes in to a boot loop. I can see first menu appearing in virtual box after boot and then second text screen then return to first one. Loop around this. I observed 5 rounds and then I interrupted the loop.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.7

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Follow instructions on https://www.home-assistant.io/installation/windows/ to install image on Virtual box.
2. Installation is succesfull and image starts booting.
3. Virtual machine ends up to a bootloop

*
 Note: Number of processors is by default 1 in VirtualBox.
Way to get around the problem. Raise processor count to 2. Image boots up succesfully.
Solution presented also here:
https://community.home-assistant.io/t/virtualbox-haos-ova-8-4-vdi-wont-boot/447485

Opening this bug per suggestion on my bug against documentation (I thought this is just a documentation issue):
https://github.com/home-assistant/home-assistant.io/issues/24260

I don't know if SW should boot up with only 1 processor set up in Virtual box.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Virtualbox 6.1
Home Assistant 2022.9.7 Supervisor 2022.09.1 Operating System 9.0 Frontend 20220907.2 - latest 
Windows 11
```

### Anything in the Host logs that might be useful for us?

```txt
(empty)
```

### System Health information

(empty)

### Additional information

(empty)

**Comment by agners** [comment]
> What operating system image do you use?
>
> generic-x86-64 (Generic UEFI capable x86-64 systems)

We have a dedicated image type for virtualization called `ova`. Are you indeed using `generic-x86-64` for virtualization? That is not recommended.

> Way to get around the problem. Raise processor count to 2. Image boots up succesfully.

Uh that is interesting, there are reports where [the opposite](https://github.com/home-assistant/operating-system/issues/1705#issuecomment-1235080024) helped: Setting the CPU to 1.
