### ISSUE TITLE
Proxmox - OVA - Operating System 9.2 - wrong RAM

### ISSUE THREAD

**Issue by euDominic** [home-assistant/operating-system#2187]
### Describe the issue you are experiencing

Hello.

I am running a Home Assistant 2022.10.3 instant with new Operating System 9.2 on a Proxmox server. 
PVE-Manager-Version: pve-manager/7.2-11/b76d3178
Kernel version: Linux 5.15.60-1-pve #1 SMP PVE 5.15.60-1 (Mon, 19 Sep 2022 17:53:17 +0200

I have assigned 4GB RAM to the instance and 1 CPU with 3 cores.

However, only 1GB RAM is displayed in Home Assistant.
Shouldn't the update to Operating System 9.2 solve this problem?
Or was this assumption wrong?

https://github.com/home-assistant/operating-system/pull/2138
 
Regardless, is there a fix in the works and/or does this bug affect the performance of the system when more than 1GB is used in Home Assistant?

![homeassistant1](https://user-images.githubusercontent.com/88461637/195789176-8b4effb5-41eb-4f17-93b4-7f99dcdb933a.JPG)
![homeassistant2](https://user-images.githubusercontent.com/88461637/195789276-4eaecece-fbfd-4069-9b9c-2fda48ffb98d.JPG)
![homeassistant3](https://user-images.githubusercontent.com/88461637/195790041-4bc349c4-9e68-46f5-bd5f-067e66c89682.JPG)
![homeassistant4](https://user-images.githubusercontent.com/88461637/195790153-aafd4c94-ba8e-48b3-b009-88b4e98146a8.JPG)

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Operating System 9.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

-

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by agners** [comment]
What memory usage is reported by Proxmox? Is maybe memory ballooning active? If that is the case, the VM will only allocate as much memory as necessary, and grow memory if needed.

**Comment by euDominic** [comment]
![home1](https://user-images.githubusercontent.com/88461637/195818782-0b541182-3b00-4ed9-ab43-075d880d54df.JPG)
![home2](https://user-images.githubusercontent.com/88461637/195818792-675b5c90-461d-4cdc-acb8-ae3246218848.JPG)
![home3](https://user-images.githubusercontent.com/88461637/195818796-2caefe22-feec-494b-97fd-aee247bfbd56.JPG)

**Comment by agners** [comment]
Yeah, so when memory ballooning is enabled, this is expected behavior. Shutdown the machine, disable memory balloning and the VM should get a fixed allocation of 4GB.

**Comment by euDominic** [comment]
Does memory ballooning have any effect on the stability of the system?
Should memory ballooning always be deactivated with home assistant?

**Comment by LucidityCrash** [comment]
I've got ballooning enabled on my Proxmox VM but the full 4G gets seen ... I believe the issue is actually the hotplug setting 
![image](https://user-images.githubusercontent.com/49124523/198821777-f562c72f-51ea-4351-a16f-e39c1c63e506.png)
Disable the memory hotplug (not sure about CPU but I did that anyway) and the VM should see all the memory.
I too thought this was fixed in 9 but I guess not in all cases.

**Comment by michaelw** [comment]
I don't see the udev support for hotplug, this might explain it:

can we get this added?
```
/lib/udev/rules.d/80-hotplug-cpu-mem.rules

SUBSYSTEM=="cpu", ACTION=="add", TEST=="online", ATTR{online}=="0", ATTR{online}="1"
SUBSYSTEM=="memory", ACTION=="add", TEST=="state", ATTR{state}=="offline", ATTR{state}="online"
```
