### ISSUE TITLE
HassOS - ohci-pci HC died; cleaning up => USB devices disconnecting

### ISSUE THREAD

**Issue by Torgrima** [home-assistant/operating-system#2193]
### Describe the issue you are experiencing

I have struggled with my internal bluetooth disconnecting, same with my Z-wave dongle.

This is the error message I get:
ohci-pci 0000:00:06.0 frame counter not updating: disabled
ohci-pci 0000:00:06.0: HC died; cleaning up 

When I restart it will be normal but after some hours it will disconnect. 

Is there any I can do to resolve it?

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

core-2022.10.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. All I do is restart the PC, 
2. I start my Oracle VM virtualBox, all works normal with out errors. 
3. After about 1 hour to more then 36 hours, it will disconnect my z-wave USB dongle

### Anything in the Supervisor logs that might be useful for us?

```txt
22-10-17 17:26:54 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Z-Wave JS is stopped, restarting...
22-10-17 17:26:54 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
22-10-17 17:26:55 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js has invalid options: Device '/dev/serial/by-id/usb-0658_0200-if00' does not exist in Z-Wave JS (core_zwave_js). Got {'device': '/dev/serial/by-id/usb-0658_0200-if00', 'log_level': 'info', 's0_legacy_key': '96BD6FB5F26A760454AFAB6286AA64EA', 's2_access_control_key': '3EA2AB5C4D65D4AD181C45076D756E75', 's2_authenticated_key': '0B5D59ABAFA3A9B01BF193A0870DE225', 's2_unauthenticated_key': 'EC4638D397FBCDA5B23FF819BF6774A9', 'network_key': '96BD6FB5F26A760454AFAB6286AA64EA'}
22-10-17 17:26:55 ERROR (MainThread) [supervisor.addons.addon] Watchdog restart of addon Z-Wave JS failed!
22-10-17 17:26:55 ERROR (MainThread) [supervisor.utils.dbus] D-Bus method org.freedesktop.DBus.Properties.call_get_all not exists!
22-10-17 17:26:55 WARNING (MainThread) [supervisor.dbus.network] Can't process /org/freedesktop/NetworkManager/Devices/26: 
22-10-17 17:26:55 ERROR (MainThread) [supervisor.utils.dbus] D-Bus method org.freedesktop.DBus.Properties.call_get_all not exists!
22-10-17 17:26:55 WARNING (MainThread) [supervisor.dbus.network] Can't process /org/freedesktop/NetworkManager/Devices/26: 
22-10-17 17:26:56 ERROR (MainThread) [supervisor.utils.dbus] D-Bus method org.freedesktop.DBus.Properties.call_get_all not exists!
22-10-17 17:26:56 WARNING (MainThread) [supervisor.dbus.network] Can't process /org/freedesktop/NetworkManager/Devices/42:
```

### Anything in the Host logs that might be useful for us?

```txt
`[    0.000000] Linux version 5.15.72 (builder@feb0a1d4a260) (x86_64-buildroot-linux-gnu-gcc.br_real (Buildroot -g5468d36a2) 9.4.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP Fri Oct 7 09:19:22 UTC 2022
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt4)/bzImage root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 rootwait zram.enabled=1 zram.num_devices=3 apparmor=1 security=apparmor systemd.machine_id=0f90f65638dd4be2aac9c1170288c981 fsck.repair=yes console=tty1 rauc.slot=B
[    0.000000] x86/fpu: x87 FPU will use FXSAVE
[    0.000000] signal: max sigframe size: 1440
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000ddd5afff] usable
[    0.000000] BIOS-e820: [mem 0x00000000ddd5b000-0x00000000ddd5bfff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000ddd5c000-0x00000000dde90fff] usable
[    0.000000] BIOS-e820: [mem 0x00000000dde91000-0x00000000ddf1afff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000ddf1b000-0x00000000def9afff] usable
[    0.000000] BIOS-e820: [mem 0x00000000def9b000-0x00000000defcafff] type 20
[    0.000000] BIOS-e820: [mem 0x00000000defcb000-0x00000000deff2fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000deff3000-0x00000000deffafff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000deffb000-0x00000000deffefff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x00000000defff000-0x00000000df46afff] usable
[    0.000000] BIOS-e820: [mem 0x00000000df46b000-0x00000000dff6afff] type 20
[    0.000000] BIOS-e820: [mem 0x00000000dff6b000-0x00000000dffeefff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000dffef000-0x00000000dffeffff] type 20
[    0.000000] BIOS-e820: [mem 0x00000000ffc00000-0x00000000ffffffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x00000001675fffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] efi: EFI v2.70 by EDK II
[    0.000000] efi: ACPI=0xdeffa000 ACPI 2.0=0xdeffa014 SMBIOS=0xdeffd000 
[    0.000000] SMBIOS 2.5 present.
[    0.000000] DMI: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[    0.000000] Hypervisor detected: KVM
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 329b5001, primary cpu clock
[    0.000005] kvm-clock: using sched offset of 8896536704 cycles
[    0.000012] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000019] tsc: Detected 1596.372 MHz processor
[    0.007204] e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
[    0.007216] e820: remove [mem 0x000a0000-0x000fffff] usable
[    0.007230] last_pfn = 0x167600 max_arch_pfn = 0x400000000
[    0.007396] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT  
[    0.007470] e820: update [mem 0xdfff0000-0x1675fffff] usable ==> reserved
[    0.007478] WARNING: BIOS bug: CPU MTRRs don't cover all of memory, losing 1654MB of RAM.`
```

## System Information

version | core-2022.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.2
Stage | running
Available Repositories | 1126
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 15.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | RPC Shutdown (2.2), Grocy (0.18.2), motionEye (0.18.0), Grafana (8.0.2), phpMyAdmin (0.8.1), MariaDB (2.5.1), deCONZ (6.16.0), Mosquitto broker (6.1.3), Dnsmasq (1.5.1), NGINX Home Assistant SSL proxy (3.1.5), Plex Media Server (3.1.1), Z-Wave JS (0.1.74), Node-RED (13.4.0), WireGuard (0.7.0), ESPHome (2021.12.1), Glances (0.16.0), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.108.4), Zigbee2MQTT (1.28.0-1), Samba share (10.0.0), Studio Code Server (5.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 10
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. oktober 2022 kl. 08:43
-- | --
current_recorder_run | 17. oktober 2022 kl. 17:26
estimated_db_size | 341.23 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Additional information

![Skjermbilde 2022-10-17 182146](https://user-images.githubusercontent.com/39237501/196230630-6f6dcbca-8e53-45b6-91ca-14019ba024a9.png)

**Comment by agners** [comment]
What kind of host operating system are you using?

Do you use the VirtualBox Extension Pack?

**Comment by Torgrima** [comment]
Yes it is Oracle VM VirtualBox with Oracle VM VirtualBox Extension Pack 6.1.22r144080

I will update to 6.1.38 of virtualbox and see if there is a diffrence.

**Comment by amsterdam36** [comment]
Same problem. On virtualbox 6.1.38 r153438, but no extension packs installed/active, mac mini intel as a host machine. HassOS 9.2, core 2022.10.4.
Last week (I think on friday) this happened for the first time, since then 3 times now, seemingly at random.

**Comment by agners** [comment]
@amsterdam36 did you use the same setup before? Are you forwarding a Z-Wave dongle as well?

Does a older HAOS release behave different? You can downgrade using

```
ha os update --version 9.0
```

**Comment by amsterdam36** [comment]
I’ve used this setup for two months now, no other connected devices through the host machine. I’ve looked closer at the time this problem first occurred, this was october 15th, a few hours after a HA Core update from 2022.10.3 to the newest version, 2022.10.3. Is it also possible to downgrade Core? Or is it more helpful to downgrade OS and see if it works?

**Comment by agners** [comment]
> Is it also possible to downgrade Core? 

Yes, by using
```
ha core update --version 2022.9.7
```

But make sure to take and download a backup first, in case it causes issues.

> Or is it more helpful to downgrade OS and see if it works?

Downgrading OS is a bit less risky, as it has not much state/configuration. The Core database gets updated, a downgraded version might have problems with that newer/upgraded database, I think.

**Comment by d4icon** [comment]
Hello
I am having the same problems described here.

I'm not sure exactly how long it has been going on, but approximately 1 to 2 months.
I periodically update HA.

My system is:
Host win 10.
Hassio (VirtualBox 6.1)

The usb error cp2110 can be ignored, as I understand that it is a consequence of the usb disconnection.

What Happend ???? :_(



![image](https://user-images.githubusercontent.com/5176086/214529728-68e4a850-6480-4259-80a0-104617b519d3.png)

**Comment by Torgrima** [comment]
I still get this issue, big frustration for the family when the heating don't work in the morning.

I think I will need to try to format and install home-assistant agan.

![image](https://user-images.githubusercontent.com/39237501/215684574-86918a1d-1a4b-4df0-a0d3-15b16f9b73a4.png)

**Comment by wilwizard1979** [comment]
Same Problem for me.
It started happening after upgrading to HAC 2023.1.7
I have the same configuration running VM in Oracle Virtual Box under Windows
It is clearly disconnecting the USB to the Virtual Machine and from it to the Home Assistant.
I will update to the newest Version of HA (already pending 2023.2.0) and of the Virtual Box to 7.0.6 (currently at 6.1.40). Will report in case it turns to happen again after the upgrades.

**Comment by d4icon** [comment]
> 

I update VB last version.
Change this opcion:
![image](https://user-images.githubusercontent.com/5176086/216602535-be29f692-7138-453b-a7ef-cb0ab890aa15.png)

before I could only select control 1.0.

Now I have changed to 3.

I haven't had the error for 2 weeks now.

I am not sure why, but I read somewhere that it could be related.

**Comment by Torgrima** [comment]
[d4icon](https://github.com/d4icon) thanks, your solution seams to solve my issue

**Comment by agners** [comment]
> before I could only select control 1.0.

In older versions the extension pack was necessary. With VirtualBox 7.0 this got part of the regular version, from the changelog:

> Devices: The EHCI and XHCI USB controller devices are now part of the open source base package 

Thanks for the update, I am closing the issue then.
