### ISSUE TITLE
Bluetooth errors

### ISSUE THREAD

**Issue by jamesreid01** [home-assistant/operating-system#2217]
### Describe the issue you are experiencing

Following completion of my build:
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest
On Intel x86 hardware

I’m getting the following error continuously:

Bluetooth: hci0: unexpected event for opcode 0x2005

The computer BIOS does not provide an option to turn off the built in bluetooth.

I’ve not got any bluetooth devices connect to HA, but do have some nearby.

I can see that there were some major updates done to bluetooth recently that look like they should have fixed this - any ideas?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Power on
2. Wait around 30 seconds after login screen appears
3. Error appears every 1-2 seconds
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing
```

### Anything in the Host logs that might be useful for us?

```txt
Nov 04 15:16:21 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:16:32 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:16:43 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:16:54 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:17:04 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:17:15 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:17:26 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
Nov 04 15:17:37 homeassistant kernel: Bluetooth: hci0: unexpected event for opcode 0x2005
```

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 234.0 GB
disk_used | 3.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Log Viewer (0.14.0), Studio Code Server (5.4.0), Samba share (10.0.0), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 November 2022 at 18:22
-- | --
current_recorder_run | 4 November 2022 at 13:47
estimated_db_size | 0.78 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
What kind of hardware is that exactly? Especially what Bluetooth hardware is in use?

I'd guess this is caused by a periodical Bluetooth scan by Home Assistant Core. If you disable the Bluetooth integration (hci0), do the messages stop?

**Comment by jamesreid01** [comment]
Hi Stefan,

I’ve got the following hardware:
https://store.chuwi.com/products/chuwi-herobox
https://www.amazon.co.uk/gp/product/B083LGWNQT

I’ve tried to find details on the specific Bluetooth chip used in it but can’t find anything (and it’s not possible to turn it on/off in the bios)

How do I turn the Bluetooth integration on/off in HA?

Note: I’m now running 2022.11.4 – this has not had an impact on this particular issue.

Regards,
James
Mobile / Whatsapp 07453 296 885

**Comment by agners** [comment]
Check Settings -> Devices & Services, there should be something "Bluetooth". Press the three dots and then Disable or Delete.

**Comment by agners** [comment]
I guess there is a problem with the firwmare/kernel driver for this platform. To debug it, I'd need hardware etc. 

But since you seem to be using the Bluetooth functionality, is it ok for you to close this issue?

**Comment by jamesreid01** [comment]
I’m not using Bluetooth today, but do have plans to use it in the future.

I’m quite willing to do anything to help debug it.

**Comment by stefanes** [comment]
I also see this on my instance of Home Assistant on Virtual Box. I have a ASUS USB-BT500 connected and passed thru to HA.

I used to have a few BT sensors connected and they seemed to work just fine.

**Comment by Dvalin21** [comment]
> I also see this on my instance of Home Assistant on Virtual Box (OS 9.4 and latest Core, saw the same error on OS 9.3). I have a ASUS USB-BT500 connected and passed thru to HA.
> 
> I have a few BT sensors connected and they seemed to work just fine though.

I have Virtualbox version of HAOS as well, all latest updates. I was able to  unplug and then replug usb bluetooth adapter and it connected for a short period of time.  Then I get this
Update of light.keith_s_lamp is taking over 10 seconds
7:35:31 PM – (WARNING) helpers/entity.py - message first occurred at December 15, 2022 at 11:30:45 PM and shows up 1099 times
hci0 (08:BE:AC:30:D6:60): Failed to restart Bluetooth scanner: hci0 (08:BE:AC:30:D6:60): Failed to start Bluetooth: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
7:35:28 PM – (ERROR) Bluetooth - message first occurred at 11:28:03 AM and shows up 976 times
Bluetooth adapter hci0 [08:BE:AC:30:D6:60] could not be reset due to timeout
7:35:26 PM – (WARNING) components/bluetooth/util.py - message first occurred at 11:28:00 AM and shows up 1951 times
Connection: BleakError: F8:24:41:E6:5B:1C - F8:24:41:E6:5B:1C: Failed to connect:
7:35:07 PM – (ERROR) Yeelight bluetooth (custom integration) - message first occurred at December 15, 2022 at 11:31:54 PM and shows up 1548 times
Updating yeelight_bt light took longer than the scheduled update interval 0:00:30
7:34:51 PM – (WARNING) Light - message first occurred at December 15, 2022 at 11:32:35 PM and shows up 1130 times

**Comment by geoffm39** [comment]
> I also see this on my instance of Home Assistant on Virtual Box (OS 9.4 and latest Core, saw the same error on OS 9.3). I have a ASUS USB-BT500 connected and passed thru to HA.
> 
> I have a few BT sensors connected and they seemed to work just fine though.

I have the same issue

**Comment by Dvalin21** [comment]
I recently went to the ASUS BT400 and it actually works worse than what I had. Still not connecting or staying connected as it should
