### ISSUE TITLE
Problem with Filesystem on VM

### ISSUE THREAD

**Issue by enwi** [home-assistant/operating-system#2218]
### Describe the issue you are experiencing

Home assistant does not function correctly due to errors with the filesystem.

![temp2](https://user-images.githubusercontent.com/25170066/200130025-98d73c56-e999-47ec-9ac6-414c82531977.png)
![temp](https://user-images.githubusercontent.com/25170066/200130046-b5c7dab7-27dd-4fec-8c51-ca55301937ab.png)

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Let HA run for a few weeks

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
see images
```

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4856
Installed Version | 1.28.3
Stage | running
Available Repositories | 1133
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 10.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.5.1), File editor (5.4.1), Node-RED (13.5.1), Terminal & SSH (9.6.1), Cloudflared (4.0.3), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 9
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 25, 2022 at 19:23
-- | --
current_recorder_run | November 5, 2022 at 17:47
estimated_db_size | 3557.09 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Additional information

![temp](https://user-images.githubusercontent.com/25170066/200131084-50e3dc6e-d9a0-4af2-9999-939e94d9d475.png)
![temp2](https://user-images.githubusercontent.com/25170066/200131086-fe7d2907-77b1-4b1e-b857-4efd5b7d20bb.png)
![temp3](https://user-images.githubusercontent.com/25170066/200131087-6dc30413-7017-4bc8-9fcb-94d692589356.png)

**Comment by enwi** [comment]
Might be related with #2216

**Comment by agners** [comment]
What Hypervisor is this? IDE is a rather outdated and not well supported interface for hard drives these days, can you choose something else (e.g. SCSI)?

**Comment by enwi** [comment]
When I select `SCSI` HAOS does not start at all, `SATA` on the other hand works

**Comment by enwi** [comment]
I will update this issue if I see the error again, but this might take a few weeks

**Comment by enwi** [comment]
The system is more stable than before, but now I get the follwoing errror from time to time, but it does not crash HA completely.
![image](https://user-images.githubusercontent.com/25170066/205040464-ac4d6357-110e-4eca-acbc-9da20960c00d.png)

**Comment by enwi** [comment]
Update after a restart of the VM HA does not start anymore, filesystem seems to be broken
