### ISSUE TITLE
Bluetooth usb adapter disconnects from Synology VM

### ISSUE THREAD

**Issue by Dvalin21** [home-assistant/operating-system#2242]
### Describe the issue you are experiencing

II have Home Assistant installed on Synology VM. I have connected a EDiMax BT-8500 Bluetooth Adapter. When I connect it, it works. I forward the usb adapter to the VM. After a few hours it seems to disconnect. This is the errors I receive. 

Bluetooth: hci0: ACL packet for unknown connection handle 16

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Attach usb bluetooth adapter to OS
2. Few hours later it disconnects
3. 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-11-22 10:14:57.812 ERROR (MainThread) [custom_components.yeelight_bt.yeelightbt] The pairing request returned unexpected results. Please reset the lamp (https://www.youtube.com/watch?v=PnjcOSgnbAM) and the pairing process will be attempted again on next connection.
2022-11-22 10:14:59.298 ERROR (MainThread) [custom_components.yeelight_bt.yeelightbt] Pairing: BleakError: [org.bluez.Error.Failed] Not connected

2022-11-22 10:16:13.095 ERROR (MainThread) [custom_components.yeelight_bt.yeelightbt] Connection: BleakError: F8:24:41:E6:5B:1C - F8:24:41:E6:5B:1C -> /org/bluez/hci0: Failed to connect: [org.bluez.Error.Failed] le-connection-abort-by-local: Interference/range; External Bluetooth adapter w/extension may help; Extension cables reduce USB 3 port interference
```

### Anything in the Host logs that might be useful for us?

```txt
Nov 22 21:41:10 homeassistant kernel: usb 3-1: USB disconnect, device number 10
Nov 22 21:41:10 homeassistant systemd[1]: Stopped target Bluetooth Support.
Nov 22 21:41:11 homeassistant bluetoothd[357]: Endpoint unregistered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc
Nov 22 21:41:11 homeassistant bluetoothd[357]: Endpoint unregistered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc
Nov 22 21:42:01 homeassistant kernel: usb 3-1: new full-speed USB device number 11 using uhci_hcd
Nov 22 21:42:01 homeassistant kernel: usb 3-1: New USB device found, idVendor=7392, idProduct=c611, bcdDevice= 2.00
Nov 22 21:42:01 homeassistant kernel: usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Nov 22 21:42:01 homeassistant kernel: usb 3-1: Product: Edimax Bluetooth Adapter
Nov 22 21:42:01 homeassistant kernel: usb 3-1: Manufacturer: Realtek
Nov 22 21:42:01 homeassistant kernel: usb 3-1: SerialNumber: 00E04C239987
Nov 22 21:42:01 homeassistant systemd[1]: Reached target Bluetooth Support.
Nov 22 21:42:03 homeassistant bluetoothd[357]: Loading LTKs timed out for hci0
Nov 22 21:42:03 homeassistant bluetoothd[357]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc
Nov 22 21:42:03 homeassistant bluetoothd[357]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc
usb 3-2: can't set config #1, error -32
```

## System Information

version | core-2022.11.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4942
Installed Version | 1.28.3
Stage | running
Available Repositories | 1221
Downloaded Repositories | 8

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.4.1), Terminal & SSH (9.6.1), Samba Backup (5.2.0), Home Assistant Google Drive Backup (0.109.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 12, 2022 at 10:01 PM
-- | --
current_recorder_run | November 22, 2022 at 10:14 AM
estimated_db_size | 76.62 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Additional information

NA

**Comment by agners** [comment]
There seem to be a low level disconnect happening:

```
Nov 22 21:41:10 homeassistant kernel: usb 3-1: USB disconnect, device number 10
...
Nov 22 21:42:01 homeassistant kernel: usb 3-1: new full-speed USB device number 11 using uhci_hcd
```

Not sure why that is happening, but I'd blame the hypervisor... Do you get any logs on the host system regarding that USB device?

It might also be the USB device just crashing, and therefor disconnecting/reconnecting. Maybe a different dongle helps?
