### ISSUE TITLE
Raspberry Pi Power LED got turned on after update to >9.0

### ISSUE THREAD

**Issue by Timwun** [home-assistant/operating-system#2247]
### Describe the issue you are experiencing

Hey,

Since the update to HAOS 9.0 (I‘m currently running 9.3 which is the latest to the creation date of this issue) the Raspberry Pi 4 (4GB) PowerLED (The red one) got turned on again. 

I disabled it via config.txt in /mnt/boot/config.txt
![C0D4997E-9095-4888-B9C0-E1B10F701779](https://user-images.githubusercontent.com/13067978/204139551-8d0129c3-2b05-4914-bd54-ef43a3efb0e0.png)

The activity LED and the Ethernet LEDs are still turned off.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Disable PWR LED via /boot/config.txt 
2. Use HAOS 9.X
3. Reboot and check if it‘s still on or not
...

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2022.11.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.3
Stage | running
Available Repositories | 1149
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 28.5 GB
disk_used | 12.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), AirCast (3.5.0), AdGuard Home (4.7.5), NGINX Home Assistant SSL proxy (3.1.5), WireGuard Client (0.2.0), ESPHome (2022.11.3), Studio Code Server (5.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 11
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18. November 2022 um 06:38
-- | --
current_recorder_run | 23. November 2022 um 16:00
estimated_db_size | 265.09 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Additional information

Raspberry PI 4 (4GB)

**Comment by agners** [comment]
This has been cause by a change in the Raspberry Pi firmware. For details see #2132. The recommended method to disable the power LED today is:

```
dtparam=pwr_led_trigger=default-on   # The default
dtparam=pwr_led_activelow=off
```
