### ISSUE TITLE
ASUS BT-500 not being recognized HA OS 9.4

### ISSUE THREAD

**Issue by gui28347** [home-assistant/operating-system#2282]
### Describe the issue you are experiencing

Trying to configure Asus Bluetooth usb adapter BT-500 in HA and it is not being recognized.

![image](https://user-images.githubusercontent.com/8279438/208804624-5b7e2831-a6c4-4ae2-a52d-464e50d54eda.png)

In all hardware it is able to recognize : 
BUSNUM: '002'
DEVNAME: /dev/bus/usb/002/002
DEVNUM: '002'
DEVPATH: /devices/pci0000:00/0000:00:04.0/usb2/2-1
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: ASUS_USB-BT500
ID_MODEL_ENC: ASUS\x20USB-BT500
ID_MODEL_ID: 190e
ID_PATH: pci-0000:00:04.0-usb-0:1
ID_PATH_TAG: pci-0000_00_04_0-usb-0_1
ID_REVISION: '0200'
ID_SERIAL: Realtek_ASUS_USB-BT500_00E04C239987
ID_SERIAL_SHORT: 00E04C239987
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: Realtek
ID_VENDOR_ENC: Realtek
ID_VENDOR_ID: 0b05
MAJOR: '189'
MINOR: '129'
PRODUCT: b05/190e/200
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '4618312'

When I try to add the Bluetooth integration it says that there is no usb available for configuring. I am not able to see any bluetooth integration.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Install HA latest version, plug the Asus BT-500, restart host, restart core, dmesg | grep hci

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
BUSNUM: '002'
DEVNAME: /dev/bus/usb/002/002
DEVNUM: '002'
DEVPATH: /devices/pci0000:00/0000:00:04.0/usb2/2-1
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: ASUS_USB-BT500
ID_MODEL_ENC: ASUS\x20USB-BT500
ID_MODEL_ID: 190e
ID_PATH: pci-0000:00:04.0-usb-0:1
ID_PATH_TAG: pci-0000_00_04_0-usb-0_1
ID_REVISION: '0200'
ID_SERIAL: Realtek_ASUS_USB-BT500_00E04C239987
ID_SERIAL_SHORT: 00E04C239987
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: Realtek
ID_VENDOR_ENC: Realtek
ID_VENDOR_ID: 0b05
MAJOR: '189'
MINOR: '129'
PRODUCT: b05/190e/200
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '4618312'
```

## System Information

version | core-2022.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4579
Installed Version | 1.29.0
Stage | running
Available Repositories | 1195
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 15, 2023 at 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 30.8 GB
disk_used | 13.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), File editor (5.4.2), Log Viewer (0.14.0), chrony (2.4.0), TasmoAdmin (0.22.0), Node-RED (14.0.0), SSH & Web Terminal (13.0.0), Studio Code Server (5.5.0), Genie - Edge (edge-0c63b72), ESPHome (2022.12.3), Mosquitto broker (6.1.3), Matter Server (1.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 22, 2022 at 3:44 PM
-- | --
current_recorder_run | December 20, 2022 at 5:50 PM
estimated_db_size | 1274.86 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by agners** [comment]
I happen to have exactly that model here. When I press Add integration -> Bluetooth, I get this prompt:

![image](https://user-images.githubusercontent.com/34061/209144998-46f3baff-ce10-48ef-8218-3a43c6b520ce.png)

After submit I see the Bluetooth device.

![image](https://user-images.githubusercontent.com/34061/209145154-d7253f45-dee8-4225-a6ca-7e88bf791357.png)


Maybe your unit is defective? Can you try a different USB port or even machine?
