### ISSUE TITLE
Bluetooth keeps throwing errors, disconnecting devices

### ISSUE THREAD

**Issue by Dvalin21** [home-assistant/operating-system#2297]
### Describe the issue you are experiencing

Bluetooth devices keep disconnecting. Never reconnecting until the BT Adapter is disconnected and then reconnected after the VM is restarted. I've tried downgrading to 9.3 which on this version I didn't have the issue. But the issue remained. I'm for certain that the BT adapter is working and has a range of 130ft (BT 5.0)

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

In order to connect back to the devices (for the 5 minutes they are connected)
I have to disconnect the BT Adapter from the VM
Restart the HAOS
Reconnect BT Adapter back to VM
Then everything is connected for a short period of time.

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-05 12:57:30 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-05 12:57:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-05 12:57:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-05 12:57:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-05 12:57:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-05 12:57:31 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-05 12:59:22 INFO (MainThread) [supervisor.backups.manager] Found 24 backup files
23-01-05 12:59:37 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-05 12:59:56 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-05 12:59:56 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-05 13:00:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-05 13:31:02 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-05 13:57:31 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-05 13:59:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-05 13:59:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
23-01-05 13:59:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-01-05 13:59:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-01-05 13:59:29 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-01-05 13:59:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
23-01-05 13:59:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
23-01-05 13:59:58 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-05 13:59:58 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-05 14:01:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-05 14:06:05 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-05 14:06:06 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-05 14:06:06 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-05 14:06:06 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-05 14:06:06 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-05 14:31:06 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-05 14:57:31 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-05 14:59:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-05 15:00:00 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-05 15:00:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-05 15:01:08 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### Anything in the Host logs that might be useful for us?

```txt
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.058:320): prog-id=0 op=UNLOAD
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.058:321): prog-id=0 op=UNLOAD
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.058:322): prog-id=0 op=UNLOAD
Jan 05 09:33:14 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.198:323): prog-id=0 op=UNLOAD
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.198:324): prog-id=0 op=UNLOAD
Jan 05 09:33:14 homeassistant kernel: audit: type=1334 audit(1672911194.198:325): prog-id=0 op=UNLOAD
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.221:326): prog-id=105 op=LOAD
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.221:327): prog-id=106 op=LOAD
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.221:328): prog-id=107 op=LOAD
Jan 05 11:39:24 homeassistant systemd[1]: Starting Hostname Service...
Jan 05 11:39:24 homeassistant systemd[1]: Started Hostname Service.
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.385:329): prog-id=108 op=LOAD
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.386:330): prog-id=109 op=LOAD
Jan 05 11:39:24 homeassistant kernel: audit: type=1334 audit(1672918764.386:331): prog-id=110 op=LOAD
Jan 05 11:39:24 homeassistant systemd[1]: Starting Time & Date Service...
Jan 05 11:39:24 homeassistant systemd[1]: Started Time & Date Service.
Jan 05 11:39:54 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.417:332): prog-id=0 op=UNLOAD
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.417:333): prog-id=0 op=UNLOAD
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.417:334): prog-id=0 op=UNLOAD
Jan 05 11:39:54 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.561:335): prog-id=0 op=UNLOAD
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.561:336): prog-id=0 op=UNLOAD
Jan 05 11:39:54 homeassistant kernel: audit: type=1334 audit(1672918794.561:337): prog-id=0 op=UNLOAD
Jan 05 12:37:00 homeassistant systemd-journald[145]: Data hash table of /var/log/journal/3ba528e4a0604137adaf9706bfedb393/system.journal has a fill level at 75.0 (174763 of 233016 items, 134217728 file size, 767 bytes per hash table item), suggesting rotation.
Jan 05 12:37:00 homeassistant systemd-journald[145]: /var/log/journal/3ba528e4a0604137adaf9706bfedb393/system.journal: Journal header limits reached or header out-of-date, rotating.
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.600:338): prog-id=111 op=LOAD
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.601:339): prog-id=112 op=LOAD
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.601:340): prog-id=113 op=LOAD
Jan 05 13:46:04 homeassistant systemd[1]: Starting Hostname Service...
Jan 05 13:46:04 homeassistant systemd[1]: Started Hostname Service.
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.777:341): prog-id=114 op=LOAD
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.778:342): prog-id=115 op=LOAD
Jan 05 13:46:04 homeassistant kernel: audit: type=1334 audit(1672926364.778:343): prog-id=116 op=LOAD
Jan 05 13:46:04 homeassistant systemd[1]: Starting Time & Date Service...
Jan 05 13:46:04 homeassistant systemd[1]: Started Time & Date Service.
Jan 05 13:46:34 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.819:344): prog-id=0 op=UNLOAD
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.819:345): prog-id=0 op=UNLOAD
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.819:346): prog-id=0 op=UNLOAD
Jan 05 13:46:34 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.975:347): prog-id=0 op=UNLOAD
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.975:348): prog-id=0 op=UNLOAD
Jan 05 13:46:34 homeassistant kernel: audit: type=1334 audit(1672926394.975:349): prog-id=0 op=UNLOAD
Jan 05 15:52:44 homeassistant kernel: audit: type=1334 audit(1672933964.995:350): prog-id=117 op=LOAD
Jan 05 15:52:44 homeassistant kernel: audit: type=1334 audit(1672933964.996:351): prog-id=118 op=LOAD
Jan 05 15:52:44 homeassistant kernel: audit: type=1334 audit(1672933964.996:352): prog-id=119 op=LOAD
Jan 05 15:52:44 homeassistant systemd[1]: Starting Hostname Service...
Jan 05 15:52:45 homeassistant systemd[1]: Started Hostname Service.
Jan 05 15:52:45 homeassistant kernel: audit: type=1334 audit(1672933965.167:353): prog-id=120 op=LOAD
Jan 05 15:52:45 homeassistant kernel: audit: type=1334 audit(1672933965.168:354): prog-id=121 op=LOAD
Jan 05 15:52:45 homeassistant kernel: audit: type=1334 audit(1672933965.168:355): prog-id=122 op=LOAD
Jan 05 15:52:45 homeassistant systemd[1]: Starting Time & Date Service...
Jan 05 15:52:45 homeassistant systemd[1]: Started Time & Date Service.
Jan 05 15:53:15 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.211:356): prog-id=0 op=UNLOAD
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.211:357): prog-id=0 op=UNLOAD
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.211:358): prog-id=0 op=UNLOAD
Jan 05 15:53:15 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.374:359): prog-id=0 op=UNLOAD
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.374:360): prog-id=0 op=UNLOAD
Jan 05 15:53:15 homeassistant kernel: audit: type=1334 audit(1672933995.374:361): prog-id=0 op=UNLOAD
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.396:362): prog-id=123 op=LOAD
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.397:363): prog-id=124 op=LOAD
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.397:364): prog-id=125 op=LOAD
Jan 05 17:59:25 homeassistant systemd[1]: Starting Hostname Service...
Jan 05 17:59:25 homeassistant systemd[1]: Started Hostname Service.
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.565:365): prog-id=126 op=LOAD
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.566:366): prog-id=127 op=LOAD
Jan 05 17:59:25 homeassistant kernel: audit: type=1334 audit(1672941565.566:367): prog-id=128 op=LOAD
Jan 05 17:59:25 homeassistant systemd[1]: Starting Time & Date Service...
Jan 05 17:59:25 homeassistant systemd[1]: Started Time & Date Service.
Jan 05 17:59:55 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.611:368): prog-id=0 op=UNLOAD
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.611:369): prog-id=0 op=UNLOAD
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.611:370): prog-id=0 op=UNLOAD
Jan 05 17:59:55 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.760:371): prog-id=0 op=UNLOAD
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.760:372): prog-id=0 op=UNLOAD
Jan 05 17:59:55 homeassistant kernel: audit: type=1334 audit(1672941595.760:373): prog-id=0 op=UNLOAD
Jan 05 18:28:32 homeassistant systemd-journald[145]: Data hash table of /var/log/journal/3ba528e4a0604137adaf9706bfedb393/system.journal has a fill level at 75.0 (174763 of 233016 items, 134217728 file size, 767 bytes per hash table item), suggesting rotation.
Jan 05 18:28:32 homeassistant systemd-journald[145]: /var/log/journal/3ba528e4a0604137adaf9706bfedb393/system.journal: Journal header limits reached or header out-of-date, rotating.
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.782:374): prog-id=129 op=LOAD
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.782:375): prog-id=130 op=LOAD
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.783:376): prog-id=131 op=LOAD
Jan 05 20:06:05 homeassistant systemd[1]: Starting Hostname Service...
Jan 05 20:06:05 homeassistant systemd[1]: Started Hostname Service.
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.944:377): prog-id=132 op=LOAD
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.945:378): prog-id=133 op=LOAD
Jan 05 20:06:05 homeassistant kernel: audit: type=1334 audit(1672949165.945:379): prog-id=134 op=LOAD
Jan 05 20:06:05 homeassistant systemd[1]: Starting Time & Date Service...
Jan 05 20:06:06 homeassistant systemd[1]: Started Time & Date Service.
Jan 05 20:06:35 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 05 20:06:35 homeassistant kernel: audit: type=1334 audit(1672949195.980:380): prog-id=0 op=UNLOAD
Jan 05 20:06:35 homeassistant kernel: audit: type=1334 audit(1672949195.980:381): prog-id=0 op=UNLOAD
Jan 05 20:06:35 homeassistant kernel: audit: type=1334 audit(1672949195.980:382): prog-id=0 op=UNLOAD
Jan 05 20:06:36 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 05 20:06:36 homeassistant kernel: audit: type=1334 audit(1672949196.140:383): prog-id=0 op=UNLOAD
Jan 05 20:06:36 homeassistant kernel: audit: type=1334 audit(1672949196.140:384): prog-id=0 op=UNLOAD
Jan 05 20:06:36 homeassistant kernel: audit: type=1334 audit(1672949196.140:385): prog-id=0 op=UNLOAD
```

## System Information

version | core-2023.1.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4927
Installed Version | 1.29.0
Stage | running
Available Repositories | 1273
Downloaded Repositories | 9

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 46

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 30.8 GB
disk_used | 7.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.5.1), Terminal & SSH (9.6.1), Home Assistant Google Drive Backup (0.109.2), Z-Wave JS (0.1.74)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 27, 2022 at 9:03 PM
-- | --
current_recorder_run | January 4, 2023 at 4:59 PM
estimated_db_size | 123.04 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Additional information

Update of light.lorri_s_lamp is taking over 10 seconds
3:07:12 PM – (WARNING) helpers/entity.py - message first occurred at January 4, 2023 at 5:00:35 PM and shows up 1708 times
Connection: BleakError: F8:24:41:E6:5B:1C - F8:24:41:E6:5B:1C: Failed to connect:
3:07:03 PM – (ERROR) Yeelight bluetooth (custom integration) - message first occurred at January 4, 2023 at 5:18:16 PM and shows up 3277 times
Updating yeelight_bt light took longer than the scheduled update interval 0:00:30
3:06:57 PM – (WARNING) Light - message first occurred at January 4, 2023 at 5:02:27 PM and shows up 2461 times
hci0 (08:BE:AC:30:D6:60): Failed to restart Bluetooth scanner: hci0 (08:BE:AC:30:D6:60): Failed to start Bluetooth: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
3:06:56 PM – (ERROR) Bluetooth - message first occurred at 1:36:01 AM and shows up 1623 times
Bluetooth adapter hci0 [08:BE:AC:30:D6:60] could not be reset due to timeout
3:06:55 PM – (WARNING) components/bluetooth/util.py - message first occurred at January 4, 2023 at 5:23:27 PM and shows up 3246 times
Error fetching x.x.x.x data: x.x.x.x: Bulb not responding, too soon to retry
3:06:26 PM – (ERROR) Magic Home - message first occurred at January 4, 2023 at 5:01:14 PM and shows up 827 times
Attempting to login again.
2:40:15 PM – (ERROR) /usr/local/lib/python3.10/site-packages/somecomfort/client.py - message first occurred at January 4, 2023 at 10:04:44 PM and shows up 13 times
Connection Error occurred.
2:40:15 PM – (ERROR) /usr/local/lib/python3.10/site-packages/somecomfort/client.py - message first occurred at January 4, 2023 at 10:04:44 PM and shows up 13 times
Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
9:58:41 AM – (ERROR) Roku - message first occurred at 4:17:12 AM and shows up 2 times
[TVision HUB(x.x.x.x):8009] Failed to connect to service ServiceInfo(type='host', data=('x.x.x.x', 8009)), retrying in 5.0s
4:17:50 AM – (ERROR) /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py
[TVision HUB(x.x.x.x):8009] Heartbeat timeout, resetting connection
4:17:20 AM – (WARNING) /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py
Error doing job: Task was destroyed but it is pending!
2:59:46 AM – (ERROR) runner.py - message first occurred at 2:59:46 AM and shows up 2 times
Error fetching AP-91054500ACE0 data: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
1:36:38 AM – (ERROR) LED BLE - message first occurred at January 4, 2023 at 9:04:41 PM and shows up 3 times
Unexpected error while attempting USB reset of hci0: [Errno 19] No such device
1:35:59 AM – (ERROR) /usr/local/lib/python3.10/site-packages/bluetooth_auto_recovery/recover.py
AP-91054500ACE0: Device unexpectedly disconnected; RSSI: -54
1:35:53 AM – (WARNING) runner.py - message first occurred at January 4, 2023 at 5:11:24 PM and shows up 29 times
Failed to cast media http://x.x.x.x:8123/api/frigate/frigate/vod/event/1672891693.120824-vxnjsp/index.m3u8?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZjQ3ZDQxMzNlN2Q0OGUxOGU5Njc5OTdjNDI5N2QxYiIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS92b2QvZXZlbnQvMTY3Mjg5MTY5My4xMjA4MjQtdnhuanNwL2luZGV4Lm0zdTgiLCJwYXJhbXMiOnt9LCJpYXQiOjE2NzI5MDM5MjksImV4cCI6MTY3Mjk5MDMyOX0.JCoWACx_O4Spe5IrGBUM4ETwPUQ0rxynUAV2agDtycI from internal_url (http://x.x.x.x:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
1:32:25 AM – (ERROR) Google Cast - message first occurred at 1:32:14 AM and shows up 2 times
Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")
1:29:59 AM – (WARNING) helpers/frame.py
Config entry '08:BE:AC:30:D6:60' for bluetooth integration not ready yet: Bluetooth adapter None with address 08:BE:AC:30:D6:60 not found; Retrying in background
January 4, 2023 at 4:59:37 PM – (WARNING) config_entries.py - message first occurred at January 4, 2023 at 4:59:25 PM and shows up 4 times
Setup of config is taking over 10 seconds.
January 4, 2023 at 4:58:59 PM – (WARNING) runner.py - message first occurred at January 4, 2023 at 4:58:58 PM and shows up 2 times

**Comment by mcc05** [comment]
Same setup VM(Oracle Virtual Box 7) on Windows,  This is not just bluetooth devices it happens on my Sonoff Zigbee 3, usb device also. I have tried to downgrade to HAS OS 9.0 same problem but less frequent, gone back to 8.5 and appears to be rock solid.

**Comment by Kaisarion** [comment]
can reproduce on latest.

**Comment by Dvalin21** [comment]
> can reproduce on latest.

Same

Update of light.lorri_s_lamp is taking over 10 seconds
1:54:45 PM – (WARNING) helpers/entity.py - message first occurred at 12:33:44 PM and shows up 51 times
AP-91054500ACE0: Device unexpectedly disconnected; RSSI: -48
1:54:30 PM – (WARNING) runner.py - message first occurred at 12:33:48 PM and shows up 10 times
Connection: BleakError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
1:54:15 PM – (ERROR) Yeelight bluetooth (custom integration) - message first occurred at 12:35:12 PM and shows up 19 times
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:822
Integration: Light (documentation, issues)
First occurred: 12:41:34 PM (5 occurrences)
Last logged: 1:54:04 PM

Updating yeelight_bt light took longer than the scheduled update interval 0:00:30

It did however last for a full day or so before disconnecting. Thats a new record!

**Comment by Dvalin21** [comment]
I'm going to close this as bluetooth has been running AMAZING!!!  Even with the Edimax bluetooth 5.

**Comment by BoneheadFraggle** [comment]
> I'm going to close this as bluetooth has been running AMAZING!!! Even with the Edimax bluetooth 5.

I am seeing the same problems but with Proxmox. 
Bluetooth stops working after a few days. Restarting HA doesn't help, but restarting the VM does.
I never need to restart Proxmox or the host computer, so it seems related to HA Supervisor?

What did you do to solve the issue?

**Comment by Dvalin21** [comment]
> > I'm going to close this as bluetooth has been running AMAZING!!! Even with the Edimax bluetooth 5.
> 
> I am seeing the same problems but with Proxmox. Bluetooth stops working after a few days. Restarting HA doesn't help, but restarting the VM does. I never need to restart Proxmox or the host computer, so it seems related to HA Supervisor?
> 
> What did you do to solve the issue?

I've actually been having the same issue again after this last update.

**Comment by sairon** [comment]
When the issue happens, please share `dmesg` output from HAOS, and if the host system is Linux as well, please do share the same output from the host system too. Adding the `lsusb` output would help too, so we know what adapter exactly are you using.

When you're experiencing generic disconnects of USB devices, I have a suspicion whether something in the host system isn't interfering - generally it's a good idea to have the host system as plain as possible to avoid it. I'm not familiar with the Windows/Virtualbox USB stack though to give any hints, but a random search shows [it may happen](https://forums.virtualbox.org/viewtopic.php?p=520723#p520723).

**Comment by BoneheadFraggle** [comment]
I have activated a push notification when the state changes on one of the devices that lose contact when Bluetooth disconnects. Hopefully, this will make it possible to get fresh logs next time.

Since the disconnects seems kind of random, does anyone know if it is possible to do an automation that runs dmesg and saves the output?
