### ISSUE TITLE
More graceful handling of memory pressure

### ISSUE THREAD

**Issue by NeilRickards** [home-assistant/operating-system#2298]
### Describe the issue you are experiencing

I am experience system instability similar to https://github.com/home-assistant/operating-system/issues/1999

This is a separate ticket to track the feature request of being generally more resilient and having an improved failure mode in the case of memory pressure.

Ideas:
* Even if we require >1GB RAM for 64-bit OS (and hence drop support for RPI3), it would still be good to fail more gracefully under memory pressure.
* Swapping to disk may be undesirable as we'll often be running on an SD card which could degrade under heavy writes.
* Can we protect the core at the expense of restarting or terminating add-ins?
* Can we protect the supervisor and at least trigger a restart of HA?
* Are there any memory leaks that can be identified in HA or it's add-ins - the problem seems to happen over time?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

System crashes while running overnight and must be power-cycled to restart

### Anything in the Supervisor logs that might be useful for us?

```txt
Logs lost on reboot, but there was nothing relevant in /var/log/journal - the logs simply stop
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by agners** [comment]
> * Can we protect the core at the expense of restarting or terminating add-ins?

We already guarantee this to some degree by tweaking the OOM score in favor of Core, see https://github.com/home-assistant/operating-system/issues/2298.

With Multi-Gen LRU and thrashing prevention enabled (see https://github.com/home-assistant/operating-system/pull/2392) HAOS will not get stuck as much when memory runs out. That will make it quicker to recover from a situation where it runs into memory pressure, which is already a huge benefit IMHO.

Ideally we would still offer some tools/logs/information on what exactly is causing memory pressure.
