### ISSUE TITLE
Can't write citation marks in cli. And how to install guest additions?

### ISSUE THREAD

**Issue by jhaggle** [home-assistant/operating-system#2299]
### Describe the issue you are experiencing

I run HA in virtual box on windows. I need to use the cli but cant write citation marks - i.e. ". 
Instead i get @.
Also, how to install guest additions?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Cant see

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install in virtualbox on windows 10.
2. Try to write "

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
> I run HA in virtual box on windows. I need to use the cli but cant write citation marks - i.e. ".
> Instead i get @.

HAOS uses the US keyboard layout by default. There are currently no plans to make this configurable as the console is only meant for debugging and for recovery if there is some type of serious system issues.

> Also, how to install guest additions?

For virtual machines the OVA image should be used. It comes with guest additions pre-installed.
