### ISSUE TITLE
HA OS 9.4 won't boot with HDMI monitor display connected to Raspberry PI 4

### ISSUE THREAD

**Issue by benjwaechter** [home-assistant/operating-system#2303]
### Describe the issue you are experiencing

When connecting a screen to my Raspberry PI 4, the system start booting and crashes after scanning for bus xhci_pci. Then system reboots and it's an infinite loop. Note that connecting a keyboard to USB 2 or 3 port doesn't produce reboot, only a display to micro HDMI port (any of them). 
System logs during boot below :
>> Net:   eth0: ethernet@7d580000
>> PCIe BRCM:  link up, 5.0 Gbps x1 (SSC)
>> starting USB...
>> Bus xhci: Register 5000420 NbrPorts 5
>> Starting the controller
>> USB XHCI 1.00
>> scanning bus xhci_pci for devices... Unexpected XHCI event TRB, skipping...  (3affc6e0 00000000 01000000 01008401)
>> BUG at drivers/usb/host/xhci-ring.c:530/abort_td()!
>> BUG!

If I disconnect the monitor, the system boots properly.

### What operating system image do you use?

rpi4  (Raspberry Pi 4/400 32-bit OS)

### What version of Home Assistant Operating System is installed?

9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Connect a monitor display to Raspberry PI 4 with a SSD card containing HA OS 9.4
2. Power on the PI
3. See boot messages on screen
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No as superviser is not strated at this stage
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

## System Information

version | core-2023.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v7l
arch | armv7l
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4961
Installed Version | 1.29.1
Stage | running
Available Repositories | 1264
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 58.0 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.2), Terminal & SSH (9.6.1), Node-RED (14.0.1), Z-Wave JS UI (1.4.2), motionEye (0.18.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 14, 2023 at 18:57
-- | --
current_recorder_run | January 15, 2023 at 11:33
estimated_db_size | 260.06 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

![IMG_2441](https://user-images.githubusercontent.com/62692433/212537797-40771a12-8f1a-49b9-89f2-0dcfd5049067.JPEG)
![IMG_2442](https://user-images.githubusercontent.com/62692433/212537804-852175c5-3b57-47a3-a8ad-b2afcdc05a74.JPEG)
![IMG_2450](https://user-images.githubusercontent.com/62692433/212537806-0a45c784-d78d-4657-a440-1322cf622838.JPEG)

**Comment by agners** [comment]
> Note that connecting a keyboard to USB 2 or 3 port doesn't produce reboot

So you are saying connecting a keyboard makes the system boot normally?

Do you have anything else connected on one of the USB ports?

**Comment by benjwaechter** [comment]
Hi,

No, I'm saying that connecting a display screen on micro HDMI makes system to reboot.
The only peripheral connected is a keyboard on USB port.
If I unplug the display screen, the system boots normally.

Thanks

**Comment by agners** [comment]
Can you try the 64-bit version?

It could be power related, what kind of power supply are you using?

**Comment by benjwaechter** [comment]
My PI is 32-bit...
I use the power supllier supplied with the PI

**Comment by benjwaechter** [comment]
Yes connecting a keyboard makes the system boot normally. But if I connect a screen display on micro HDMI, it fails...
So having a PI with a keyboard but without screen is useless :-)

**Comment by agners** [comment]
> My PI is 32-bit...

All Raspberry Pi 4 support 32-bit or 64-bit.

Do you have a different monitor or HDMI cable you could try?

**Comment by wbarber69** [comment]
sounds like a power issue.

**Comment by benjwaechter** [comment]
> 

I've tried same HDMI cable, same monitor, same power supply with another PI, no issue. System boots properly...

**Comment by wbarber69** [comment]
When you say same power supply, are you talking about the supply to the pi or the monitor?

Sent from my iPhone

On Jan 30, 2023, at 5:00 AM, benjwaechter ***@***.***> wrote:

﻿

I've tried same HDMI cable, same monitor, same power supply with another PI, no issue. System boots properly...

**Comment by benjwaechter** [comment]
I say same PI power supply.
