### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rikigiano007** [home-assistant/operating-system#2309]
### Describe the issue you are experiencing

hi can anyone help me i installed home assistant on my rasbarry pi 4 via rasbarry pi os but when searching on the net i can't find it only find it from the app

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.error config
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
i don't
```

### Anything in the Host logs that might be useful for us?

```txt
i don't
```

**Comment by agners** [comment]
You can find Home Assistant installation instructions at https://www.home-assistant.io/installation/. This is not a help forum, this is an issue tracker for the Home Assistant OS specifically.
