### ISSUE TITLE
'raspistill' was not found

### ISSUE THREAD

**Issue by mgrman** [home-assistant/operating-system#2317]
### Describe the issue you are experiencing

When I try to activate Raspberry Pi 4 camera I get `'raspistill' was not found` error in logs.

I activated the correct firmware via https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b

Full error message
```
Logger: homeassistant.components.rpi_camera.camera
Source: components/rpi_camera/camera.py:53
Integration: Raspberry Pi Camera (documentation, issues)
First occurred: 6:52:40 PM (1 occurrences)
Last logged: 6:52:40 PM

'raspistill' was not found
```

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Apply correct firmware via https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b
2. Activate camera via https://www.home-assistant.io/integrations/rpi_camera
3. check logs at /config/logs 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No the log appears in `Home Assistant Core` logs
```

### Anything in the Host logs that might be useful for us?

```txt
No the log appears in `Home Assistant Core` logs
```

## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.8 GB
disk_used | 3.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.5.2), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 20, 2023 at 7:29 PM
-- | --
current_recorder_run | January 24, 2023 at 6:52 PM
estimated_db_size | 14.44 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by agners** [comment]
The error is printed by Home Assistant Core, which runs in its own environment.

The problem you describe has been previously reported in the Core repository: https://github.com/home-assistant/core/issues/51755
