### ISSUE TITLE
Operation System 9.5 tag as public but described as beta

### ISSUE THREAD

**Issue by HawkUser** [home-assistant/operating-system#2326]
### Describe the issue you are experiencing

"https://github.com/home-assistant/operating-system/releases/tag/9.5"

ℹ️ This release is currently on the beta channel ℹ️

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. https://github.com/home-assistant/operating-system/releases/tag/9.5
2.ℹ️ This release is currently on the beta channel ℹ️

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### System information

N/A

### Additional information

N/A

**Comment by mike-mo** [comment]
This is covered by #2323
