### ISSUE TITLE
Memoria Swap

### ISSUE THREAD

**Issue by Gmm21071995** [home-assistant/operating-system#2334]
### Describe the issue you are experiencing

Buenas tardes.
Tengo varias cámaras y dispositivos en HA que usan en consumo determinado de memoria swap (mas de 600 MiB).
Cada vez que actualizo el sistema operativo en mi Raspberry pi 3 +, el porcentaje de memoria swap alcanza el 100 % y HA se bloqua, dejando de funcionar.
Tengo que ampliar la memoria swap para que pueda funcionar.
Podrían ampliar este concepto en el sistema operativo para que no de problemas?
Gracias

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

6.6

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Buenas tardes.
Tengo varias cámaras y dispositivos en HA que usan en consumo determinado de memoria swap (mas de 600 MiB).
Cada vez que actualizo el sistema operativo en mi Raspberry pi 3 +, el porcentaje de memoria swap alcanza el 100 % y HA se bloqua, dejando de funcionar.
Tengo que ampliar la memoria swap para que pueda funcionar.
Podrían ampliar este concepto en el sistema operativo para que no de problemas?
Gracias

### Anything in the Supervisor logs that might be useful for us?

```txt
Buenas tardes.
Tengo varias cámaras y dispositivos en HA que usan en consumo determinado de memoria swap (mas de 600 MiB).
Cada vez que actualizo el sistema operativo en mi Raspberry pi 3 +, el porcentaje de memoria swap alcanza el 100 % y HA se bloqua, dejando de funcionar.
Tengo que ampliar la memoria swap para que pueda funcionar.
Podrían ampliar este concepto en el sistema operativo para que no de problemas?
Gracias
```

### Anything in the Host logs that might be useful for us?

```txt
Buenas tardes.
Tengo varias cámaras y dispositivos en HA que usan en consumo determinado de memoria swap (mas de 600 MiB).
Cada vez que actualizo el sistema operativo en mi Raspberry pi 3 +, el porcentaje de memoria swap alcanza el 100 % y HA se bloqua, dejando de funcionar.
Tengo que ampliar la memoria swap para que pueda funcionar.
Podrían ampliar este concepto en el sistema operativo para que no de problemas?
Gracias
```

### Additional information

Buenas tardes.
Tengo varias cámaras y dispositivos en HA que usan en consumo determinado de memoria swap (mas de 600 MiB).
Cada vez que actualizo el sistema operativo en mi Raspberry pi 3 +, el porcentaje de memoria swap alcanza el 100 % y HA se bloqua, dejando de funcionar.
Tengo que ampliar la memoria swap para que pueda funcionar.
Podrían ampliar este concepto en el sistema operativo para que no de problemas?
Gracias

**Comment by agners** [comment]
Please English only.
