### ISSUE TITLE
DS9490R USB adapter 1wire no added to Home Assistant

### ISSUE THREAD

**Issue by pepsonEL** [home-assistant/operating-system#2344]
### Describe the issue you are experiencing

 I have HASSOS… generic_x64-x86 version 9.5 and when connect DS9490R i see logs on logs HOST:
```
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: new full-speed USB device number 11 using xhci_hcd
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: New USB device found, idVendor=04fa, idProduct=2490, bcdDevice= 0.02
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Feb 05 11:54:26 homeassistant kernel: usbcore: registered new interface driver DS9490R
Feb 05 11:54:26 homeassistant kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 81.000000344670 crc 01
Feb 05 11:54:26 homeassistant kernel: w1_master_driver w1_bus_master1: Family 81 for 81.000000344670.01 is not registered.
Feb 05 12:05:36 homeassistant kernel: audit: type=1334 audit(1675598736.536:475): prog-id=157 op=LOAD
```

But it is no show on every USB in home assistant. It was crash about HASSOS 5.0 because before i use it. Is any chance to implement it and add to official version HA ?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

AFter connect it is show in logs host but no show in Home Assistant,

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: new full-speed USB device number 11 using xhci_hcd
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: New USB device found, idVendor=04fa, idProduct=2490, bcdDevice= 0.02
Feb 05 11:54:26 homeassistant kernel: usb 1-6.2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Feb 05 11:54:26 homeassistant kernel: usbcore: registered new interface driver DS9490R
Feb 05 11:54:26 homeassistant kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 81.000000344670 crc 01
Feb 05 11:54:26 homeassistant kernel: w1_master_driver w1_bus_master1: Family 81 for 81.000000344670.01 is not registered.
Feb 05 12:05:36 homeassistant kernel: audit: type=1334 audit(1675598736.536:475): prog-id=157 op=LOAD
```

**Comment by agners** [comment]
This is essentially a feature request, which should go to the community forum.

It seems the driver is present, but I guess userspace somehow needs to make use of it? If that is the case, this would be more something which would need support in HA Core. However, it seems a very niche application, I am not sure if it is worth investing time in support it.
