### ISSUE TITLE
I have an issue with boot HassOs 9.5 on Rpi4  from USB NVMe SSD - Black screen

### ISSUE THREAD

**Issue by Itzamna44** [home-assistant/operating-system#2350]
### Describe the issue you are experiencing

Raspberry Pi 4 Model B - 2GB
Enclosure - AgeStar M.2 NVME SSD 31UBNV1C
SSD - KingSpec M.2 SSD M2 - 128GB
But Raspbian 32 or 64 bit boot normal without issue.
On Ruspbian this device  detected as JMicron idVendor=152d, idProduct=0583
This is a log of booting HassOs:

`U-Boot 2022.01 (Jan 24 2023 - 22:21:00 +0000)

DRAM:  1.9 GiB
RPI 4 Model B (0xb03112)
MMC:   mmcnr@7e300000: 1, mmc@7e340000: 0
Loading Environment from nowhere.. OK
In:    serial
Out:   serial
Err:   serial
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices.. Device NOT ready
   Request Sense returned 02 04 01
3 USB Device(s) found
       scanning usb for storage devices.. 0 Storage Device(s) found
Card did not respond to voltage select! : -110
sdhci_set_clock: Timeout to wait cmd & data inhibit
sdhci_set_clock: Timeout to wait cmd & data inhibit
sdhci_set_clock: Timeout to wait cmd & data inhibit
sdhci_send_command: MMC: 1 busy timeout increasing to: 200 ms.
sdhci_send_command: MMC: 1 busy timeout increasing to: 400 ms.
sdhci_send_command: MMC: 1 busy timeout increasing to: 800 ms.
sdhci_send_command: MMC: 1 busy timeout increasing to: 1600 ms.
sdhci_send_command: MMC: 1 busy timeout increasing to: 3200 ms.
sdhci_send_command: MMC: 1 busy timeout.
MMC Device 2 not found
no mmc device at slot 2

Device 0: unknown device`

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

core-2023.2.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Boot from USB SSD 
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No log
```

### Anything in the Host logs that might be useful for us?

```txt
No log
```

**Comment by agners** [comment]
Thanks for the logs. It seems that U-Boot has a problem enumerating the USB device:

```
scanning bus xhci_pci for devices.. Device NOT ready
Request Sense returned 02 04 01
3 USB Device(s) found
scanning usb for storage devices.. 0 Storage Device(s) found
```

Ultimately, it can't access the USB drive, and therefor not boot.

This is likely a timing issue. U-Boot follows USB specs a bit more strict, and if the drive isn't ready within this time, it just moves on. You can try to add a USB hub in between, and/or change your power setup, as this can change/improve startup times.

Better yet just side step this USB SSD boot issue by using the data disk method (install HAOS on the SD card and move the data to the external disk).
