### ISSUE TITLE
Bluetooth disappears

### ISSUE THREAD

**Issue by mchicke** [home-assistant/operating-system#2363]
### Describe the issue you are experiencing

Bluetooth devices disappear after triggering system restarts and requires a hardware restart.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 9.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Navigate to System
2. Click Restart
3. Bluetooth device returns: "This entity is no longer being provided by the inkbird integration. If the entity is no longer in use, delete it in settings."
4. Navigate to Sysyem>Hardware and initiate reboot
5. Integration works, begins reporting data after reboot
...

### Anything in the Supervisor logs that might be useful for us?

```txt
NO
```

### Anything in the Host logs that might be useful for us?

```txt
not noticed
```

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 2, 2023 at 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 219.4 GB
disk_used | 9.3 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.2.2), File editor (5.5.0), Terminal & SSH (9.6.1), Home Assistant Google Drive Backup (0.110.1), Node-RED (14.0.2), Ring-MQTT with Video Streaming (5.1.3), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 8, 2023 at 5:50 PM
-- | --
current_recorder_run | February 18, 2023 at 8:52 AM
estimated_db_size | 165.52 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by itssimon** [comment]
Came here to post about the exact same issue. I have an Intel NUC with a built-in bluetooth adapter. Initially everything worked fine, but after restarting HA Core a couple of times the adapter is no longer recognized, not even by bluetoothctl in the terminal. Only a hardware reboot fixes it temporarily until it all happens again.

Thinking it might be an unsupported bluetooth chipset that's built-in, I bought a new external USB bluetooth adapter from the top performance list in the docs (Avantree DG40S), but I'm getting the same behaviour with that one too.

Below is the diagnostics file of the built-in bluetooth device when it was working:
[config_entry-bluetooth-647b03bed6bb0a85b9cca4961522996b.json.txt](https://github.com/home-assistant/operating-system/files/10819474/config_entry-bluetooth-647b03bed6bb0a85b9cca4961522996b.json.txt)

Happy to provide other logs etc. that might be helpful in debugging this.
