### ISSUE TITLE
Missing firmware for XBox TV Tuner USB Dongle

### ISSUE THREAD

**Issue by thatsthat** [home-assistant/operating-system#2397]
### Describe the issue you are experiencing

In order to use the TVHeadend add-on with an XBOX TV Tuner with Hassio OS, the following [file](http://palosaari.fi/linux/v4l-dvb/firmware/MN88472/02/latest/) is needed in /lib/firmware This as described [here](https://www.linuxtv.org/wiki/index.php/Xbox_One_Digital_TV_Tuner)

It would be great if that file could be included in HASSIO Operating System since manually adding the file after each upgrade is not an easy process.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install TVHeadEnd add-on
2. Plug-in an XBOX USB TV-Tunner connected to an aerial antenna
3. Check dmesg and search the message 'dvb-usb: found a 'Microsoft Xbox One Digital TV Tuner' in cold state, will try to load a firmware' to see how it fails to load the firmware due to a missing file.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

## System Information

version | core-2023.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 916.2 GB
disk_used | 7.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), InfluxDB (4.5.0), Grafana (8.2.0), Plex Media Server (3.2.2), Samba share (10.0.0), Alsa & PulseAudio Fix dev version (3.5), AdGuard Home (4.8.2), Z-Wave JS (0.1.76), ESPHome (2022.3.1), ArgonOne Active Cooling (29c), Tailscale (0.7.0), HassOS SSH port 22222 Configurator (0.9.1a), Terminal & SSH (9.6.1), TVHeadend (2.0.2-alpha)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 9, 2023 at 9:21 AM
-- | --
current_recorder_run | March 10, 2023 at 2:58 PM
estimated_db_size | 176.51 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
For license reasons, I hesitate to include just random firmware files. There are probably reasons why this firmware file is not part of the kernel.org firmware repository.

We are currently working on mechanism to upload firmwares, the first steps are implemented on the OS side (see #2225). Once this is available, you'll be able to add the firmware to HAOS in your installation.

**Comment by thatsthat** [comment]
Totally understand, thanks. And congrats for the great work on HA !

/Aram
