### ISSUE TITLE
CPU frequentie pinned at max after upgrade to OS 10.0.rc2

### ISSUE THREAD

**Issue by RemCom** [home-assistant/operating-system#2437]
### Describe the issue you are experiencing

CPU frequentie of Intel NUC pinned at max after update while before was correcly going between max and lowest frequentie. CPU usage in percentage is still ate the same level as before the update

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.0.rc2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Just do the update

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by RemCom** [comment]
Before vertical red line before update. After redline after update

<img width="465" alt="Screenshot 2023-03-28 at 21 26 58" src="https://user-images.githubusercontent.com/3468852/228346369-5e2e1d19-f9e1-42f6-914a-f11929d5a55c.png">

**Comment by agners** [comment]
Is the CPU load still low or also higher with 10.0.rc2?

I am not aware in any change which specifically could explain this. We use a newer Linux kernel which could change behavior, but such a drastic difference is somewhat unexpected.

**Comment by RemCom** [comment]
The load is actually the same. Also system power draw is the same so I can't really explain it. Maybe it's just an issue with monitoring?

**Comment by agners** [comment]
> The load is actually the same. Also system power draw is the same so I can't really explain it. Maybe it's just an issue with monitoring?

Hm yeah maybe, or the new kernel's cpufreq governor just decides its not worth down-clocking.

If you have OS shell access, you can check the following files on what is currently configured:

```
# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
```

**Comment by RemCom** [comment]
```
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor: schedutil
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq: 800000
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq: 2800000
```

Frequentie values look oke. maybe it default governor state is different are maybe just other behaviour the before

**Comment by nepozs** [comment]
I've downgraded to HAOS 9.5, but some day it was working using 10.0_rc1 and 10.0_rc2
![HAOS_10_0_2023-04-04_03-58](https://user-images.githubusercontent.com/56661567/229667395-828ff0c5-ac7f-4b3b-ad10-f77df25e2cdd.png)

Old AMD machine - looks similar, but temperature was affected too, so I'm sure the power draw is higher.

**Comment by agners** [comment]
@nepozs your case seems different as the CPU load (Processor uses in %) is higher.

Can you open a new issues with all the system details? Also, can you check what component is causing the higher CPU load (e.g. by comparing what is shown in the Glances add-on between 10.0.rc3 and 9.5).

**Comment by nepozs** [comment]
I've found reason - it is motionEye not working properly after system update.
It is just experimental installation, but I don't have enough free time lately, so I've missed problems with motionEye.

**Comment by agners** [comment]
If motionEye has some OS dependency which needs update then most likely this issue should go to https://github.com/hassio-addons/addon-motioneye/issues.
