### ISSUE TITLE
No communication to devices using mDNS after update to 10.0

### ISSUE THREAD

**Issue by Beestkiller** [home-assistant/operating-system#2481]
### Describe the issue you are experiencing

none of my devices using mDNS are reporting to homeassistant after the OS update to 10.0

like ESPhome and google media players running over a different Vlan as the homeassistant instans using mDNS 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. updated the OS to 10.0
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no errors shown
```

### Anything in the Host logs that might be useful for us?

```txt
Apr 18 22:04:16 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.TrVFGJ.mount: Deactivated successfully.
Apr 18 22:04:46 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.nNQwuJ.mount: Deactivated successfully.
Apr 18 22:05:16 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.DisTnZ.mount: Deactivated successfully.
Apr 18 22:05:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.elE83m.mount: Deactivated successfully.
Apr 18 22:06:17 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.Fg22KX.mount: Deactivated successfully.
Apr 18 22:06:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.QmtNNy.mount: Deactivated successfully.
Apr 18 22:08:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.5SVOF9.mount: Deactivated successfully.
Apr 18 22:10:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.HhJ2h6.mount: Deactivated successfully.
Apr 18 22:11:17 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.ifpBiz.mount: Deactivated successfully.
Apr 18 22:12:17 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.Y6CgoQ.mount: Deactivated successfully.
Apr 18 22:12:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.vloOna.mount: Deactivated successfully.
Apr 18 22:13:18 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.Qsv1Th.mount: Deactivated successfully.
Apr 18 22:13:48 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.JYcMKY.mount: Deactivated successfully.
Apr 18 22:14:18 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.PZc1HB.mount: Deactivated successfully.
Apr 18 22:14:48 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.a6Y6He.mount: Deactivated successfully.
Apr 18 22:17:18 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.t5yl6z.mount: Deactivated successfully.
Apr 18 22:17:48 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.WU1wvJ.mount: Deactivated successfully.
Apr 18 22:18:18 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.BPWQ6U.mount: Deactivated successfully.
Apr 18 22:18:48 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.9EXXWb.mount: Deactivated successfully.
Apr 18 22:19:18 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.3iBGjf.mount: Deactivated successfully.
Apr 18 22:21:19 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.gKppHz.mount: Deactivated successfully.
Apr 18 22:21:49 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.mk7Rxc.mount: Deactivated successfully.
Apr 18 22:22:19 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.TZFBd4.mount: Deactivated successfully.
Apr 18 22:22:49 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.SXjv0p.mount: Deactivated successfully.
Apr 18 22:23:19 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.6b2Rgi.mount: Deactivated successfully.
Apr 18 22:25:19 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.N5texf.mount: Deactivated successfully.
Apr 18 22:25:49 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.d2t3Tj.mount: Deactivated successfully.
Apr 18 22:26:19 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.zEO0so.mount: Deactivated successfully.
Apr 18 22:26:49 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.AuK0Wu.mount: Deactivated successfully.
Apr 18 22:27:50 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.WS5Qn7.mount: Deactivated successfully.
Apr 18 22:28:20 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.GS4pMr.mount: Deactivated successfully.
Apr 18 22:28:50 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.cJirlG.mount: Deactivated successfully.
Apr 18 22:29:20 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.F0Bv9U.mount: Deactivated successfully.
Apr 18 22:30:20 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-2bc339f1b33971afabed4a553d7bef6f1099eca6f08de69091344176c8bec7f4-runc.lG178F.mount: Deactivated successfully.
Apr 18 22:30:34 homeassistant kernel: audit: type=1334 audit(1681857034.408:900): prog-id=195 op=LOAD
Apr 18 22:30:34 homeassistant systemd[1]: Started Journal Gateway Service.
Apr 18 22:30:34 homeassistant systemd-timesyncd[415]: Network configuration changed, trying to establish connection.
Apr 18 22:30:34 homeassistant systemd-timesyncd[415]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).
Apr 18 22:30:34 homeassistant systemd-journal-gatewayd[31221]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
```

## System Information

version | core-2023.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4775
Installed Version | 1.31.0
Stage | running
Available Repositories | 1266
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 22 april 2023 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 8.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Studio Code Server (5.5.6), Mosquitto broker (6.2.0), Zigbee2MQTT (1.30.3-1), ESPHome (2023.3.2), TasmoAdmin (0.24.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 1
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7 maart 2023 om 15:48
-- | --
current_recorder_run | 18 april 2023 om 23:50
estimated_db_size | 1124.96 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
There hasn't been a change in mDNS handling really, this seems somewhat strange.

Also, I can ping `.local` addresses just fine here on my OS 10 installations.

If this problem persists, can you downgrade to 9.5 and see if this indeed fixes the problem again?

```
ha os update --version 9.5
```

**Comment by rover1955** [comment]
I can confirm I had the same issue.  Running HA on a PI4B
Version 2023.4.5
Supervisor 2023.04.0
Operating System 10.0

I run Dnsmasq to set local hosts as well as map my duckdns address to a local ip.

With OS 10.0 Dnsmasq gets stuck at 'Starting' and never progresses.  No .local works and neith does my duckdns address work locally.  

I tried uninstalling Dnsmasq, reboot and reinstall Dnsmasq but had the same issue.

When I downgraded to 9.5 Dnsmasq worked perfectly and all my .local addresses worked again.

**Comment by Zaude** [comment]
Same issue here. Running Dnsmasq & DuckDNS. It seems that Dnsmasq gets stuck. Had to revert back to 9.5 and everything works just fine after downgrading.

**Comment by rover1955** [comment]
After updating Dnsmasq this morning to the latest version (1.6.0), and then upgrading to OS 10.0, I can confirm all is working correctly.  
Many thanks for a quick response.

**Comment by agners** [comment]
@rover1955 glad the Dnsmasq add-on update resolved your problem (it likely will for @Zaude as well).

However, this is unlikely the problem @Beestkiller is seeing as he is not using that add-on (according to `installed_addons` information from the original post). I'll leave it open until we have more information from @Beestkiller.

**Comment by JacobMillward** [comment]
I'm having the same issue, rolling back to 9.5 fixes it. Running a Homeassistant Blue, without Dnsmasq.

**Comment by budswarez** [comment]
I'm having the same problem after the last update, I only use cloudflare tunnel, I don't use any other adon "AdGuard, dnsmask, nginx, duck, lets encrypt, none of these.

Home Assistant 2023.4.6
Supervisor 2023.04.0
Operating System 10.0
Frontend: 20230411.1 - latest

`Apr 23 20:54:35 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.2BhFc2.mount: Deactivated successfully.
Apr 23 20:55:35 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.D8YW8q.mount: Deactivated successfully.
Apr 23 20:56:36 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.jAmbUm.mount: Deactivated successfully.
Apr 23 20:58:06 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.cEtdRZ.mount: Deactivated successfully.
Apr 23 20:59:06 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.po3pJ8.mount: Deactivated successfully.
Apr 23 20:59:36 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.tNUoTI.mount: Deactivated successfully.
Apr 23 21:01:06 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.3FZDwE.mount: Deactivated successfully.
Apr 23 21:03:37 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.1ueuJG.mount: Deactivated successfully.
Apr 23 21:05:37 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.ZulKWu.mount: Deactivated successfully.
Apr 23 21:06:07 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.PtG6ps.mount: Deactivated successfully.
Apr 23 21:06:38 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.gkYPYV.mount: Deactivated successfully.
Apr 23 21:07:08 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.QiPutt.mount: Deactivated successfully.
Apr 23 21:08:08 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.3DGX2T.mount: Deactivated successfully.
Apr 23 21:09:08 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.W6K6Hy.mount: Deactivated successfully.
Apr 23 21:09:38 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.8kTVih.mount: Deactivated successfully.
Apr 23 21:11:39 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.wXUmFX.mount: Deactivated successfully.
Apr 23 21:13:09 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.50D6uq.mount: Deactivated successfully.
Apr 23 21:15:39 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.KnSdJq.mount: Deactivated successfully.
Apr 23 21:19:10 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.dk3HBW.mount: Deactivated successfully.
Apr 23 21:20:10 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.LNCsH8.mount: Deactivated successfully.
Apr 23 21:21:41 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.nHw4EH.mount: Deactivated successfully.
Apr 23 21:22:41 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.61H6uq.mount: Deactivated successfully.
Apr 23 21:23:11 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.Tajnoy.mount: Deactivated successfully.
Apr 23 21:23:41 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.OO5s9i.mount: Deactivated successfully.
Apr 23 21:26:42 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.YAeNLn.mount: Deactivated successfully.
Apr 23 21:27:42 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-cbeb2813c81047717097275881c4ae04cc490f56a8b89e7f5a409c55131a614d-runc.xsTpJu.mount: Deactivated successfully.`

**Comment by GoSpursGoNL** [comment]
At least with 10.1, not sure about 10.0, the [Homepod Connect ](https://community.home-assistant.io/t/homepod-connect-spotify-on-homepods-with-spotify-connect/482227/44)addon stopped working, also with an mDNS related error.
[2023-05-01 09:28:59] [FATAL] main: mDNS init failed
[2023-05-01 09:28:59] [ LOG] main: Exiting.

After downgrading to HA OS 9.5 the addon works again.

**Comment by GoSpursGoNL** [comment]
[Here](https://community.home-assistant.io/t/homepod-connect-spotify-on-homepods-with-spotify-connect/482227/44?u=gospursgonl) it is suggested that it could be related to the Docker version. Is there any way we could find that out?
Searching for docker + mdns on Google leads me to [this very old thread](https://github.com/moby/moby/issues/38531) but for some reason there is suddenly some activity in it again earlier this month.

**Comment by GoSpursGoNL** [comment]
The problem is not fixed with HA OS 10.4. Downgrading to 9.5
```
[2023-08-12 10:47:06] [  LOG]     main: OwnTone version 28.6 taking off
[2023-08-12 10:47:06] [  LOG]     main: Built with:
[2023-08-12 10:47:06] [  LOG]     main: - ffmpeg
[2023-08-12 10:47:06] [  LOG]     main: - Spotify
[2023-08-12 10:47:06] [  LOG]     main: - librespot-c
[2023-08-12 10:47:06] [  LOG]     main: - LastFM
[2023-08-12 10:47:06] [  LOG]     main: - Chromecast
[2023-08-12 10:47:06] [  LOG]     main: - MPD
[2023-08-12 10:47:06] [  LOG]     main: - Websockets
[2023-08-12 10:47:06] [  LOG]     main: - ALSA
[2023-08-12 10:47:06] [  LOG]     main: - Webinterface
[2023-08-12 10:47:06] [  LOG]     main: - Regex
[2023-08-12 10:47:06] [  LOG]     main: mDNS init
[2023-08-12 10:47:06] [FATAL]     main: mDNS init failed
[2023-08-12 10:47:06] [  LOG]     main: Exiting.
```

**Comment by iVolt1** [comment]
The problem is not fixed with HA OS 10.5 even with the 28.8 version of Homepod Connect. Downgrading to 9.5 allows the Homepod Connect 28.8 integration to work without the mdns init failllure

**Comment by giovanniro98** [comment]
I have the same issue here.

**Comment by GoSpursGoNL** [comment]
Issue still occurs with HA OS 11.1

**Comment by iVolt1** [comment]
Is there any way to escalate this issue?  A number of addons depend on mdns/avahi advertising that currently only work with with HAOS up to version 9.5 which is now two major versions behind.  

@agners - would you be able to dig deeper on this bug or contact the right people who could help track down the cause of this bug?

Thanks.

**Comment by myhades** [comment]
Any update on this one?

**Comment by agners** [comment]
@GoSpursGoNL @iVolt1 the original poster of this issue does not have the Homepod Connect add-on installed. Your problem is likely slightly different than the OP's issue. This probably is related to a compatibility issue with the new Docker engine. I posted a comment in the community post: https://community.home-assistant.io/t/homepod-connect-spotify-on-homepods-with-spotify-connect/482227.

@myhades @giovanniro98 do you have this issue with the Homepod Connect add-on installed?
