### ISSUE TITLE
Raspberry PI 4 cannot boot from USB clean install of 10.1

### ISSUE THREAD

**Issue by ocalvo** [home-assistant/operating-system#2482]
### Describe the issue you are experiencing

After clean install of 10.1:

Hangs waiting for USB:

![image](https://user-images.githubusercontent.com/2091582/234467595-6d15a0ba-8fd6-4e7f-8d81-894364126306.png)

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Clean install 10.1

### Anything in the Supervisor logs that might be useful for us?

```txt
Cannot access logs
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### System information

Cannot access system info

### Additional information

Cannot access system

**Comment by agners** [comment]
It doesn't boot beyond this point? This seems very strange, as this is before any of the files getting touched from HAOS (this screen is shown by the EEPROM). It seems as if HAOS vanished from the USB SSD?

Can you double check the content of the USB SSD (e.g. checking partition table using fdisk and check the content of the first partition).

This is essentially another variation of "boot from USB" issue on Rasberry Pi. As I've stated numerous times before, USB boot on Raspberry Pi is unfortunately notoriously unstable. I recommend booting from SD card, and use the SSD as data disk.

**Comment by agners** [comment]
Possibly duplicate of #2480.

**Comment by jurasjo** [comment]
Maybe updating bootloader can help? It looks like yours is quite old one.
https://pimylifeup.com/raspberry-pi-bootloader/

**Comment by cbird527** [comment]
I can confirm this happened to me as well after the update to 10.0. I also tried updating the boot loader to 8ba17717 2023/01/11 and a fresh image of HA OS 10.0 and it would not boot either.  After rolling back to 9.5 there are not issues.

My hardware is a Pi CM4 with 8Gb ram and booting off an NVMe drive.

**Comment by bcutter** [comment]
> This is essentially another variation of "boot from USB" issue on Rasberry Pi. As I've stated numerous times before, USB boot on Raspberry Pi is unfortunately notoriously unstable. I recommend booting from SD card, and use the SSD as data disk.

This is very interesting and helpful information.

As I don't want to hijack this issue but I think those questions are important to avoid future issues of this kind (on nearly every HA OS update there are reports of not booting Pi's/boards with SAD boot devices...), where can one find answers on these questions?
1. **What data _exactly_ will remain on the SD card (and therefore what will be outsourced) once the move data disk feature has been applied?** Docker containers, which parts of the OS, what about the Supervisor etc.
2. **Can this be undone, so can an outsourced data disk be sourced back in (everything back on internal SD card)?** Or is this feature a one way road?

**Comment by ocalvo** [comment]
If I disconnect the USB system drive and reconnect again, then the boot process continues:
![image](https://user-images.githubusercontent.com/2091582/234468312-c18f9593-d893-4125-9452-12395e9f6f53.png)

**Comment by ocalvo** [comment]
Maybe I am having a hardware issue, now I see this:
![image](https://user-images.githubusercontent.com/2091582/234476099-3baa391e-557a-4607-921b-e7b6f593680c.png)

**Comment by ocalvo** [comment]
I am losing my mind, after disconnection everything and flashing 10.1 again, the system was able to boot with every USB connected:
![image](https://user-images.githubusercontent.com/2091582/234480751-f89fd803-7c43-4515-91dc-d10d0573c3da.png)

**Comment by bschatzow** [comment]
@ocalvo 
I have had this same issue off and on with different releases.  My system is using a hub for my USB SSD.  It is only on a reboot, not an update and it is not every time.  Like you if I remove my hub and start the boot and then plug in it works every time.  I believe it is a timing issue that a small number of users see.  Now I never update unless I in home to monitor it.

**Comment by agners** [comment]
As @bschatzow says, some of the USB SSDs have a timing problem with the detection. The Linux kernel has quirks and hacks to restart detection etc. for devices which violate the USB spec. The Raspberry Pi firmware and the U-Boot USB stack (our bootloader) is not as forgiving. Quite likely that you see some kind of race condition here.

Also, I've seen [in-rush current](https://en.wikipedia.org/wiki/Inrush_current) problems with USB SSDs powered by USB only. Some of them restart again just because they don't get enough juice at first.

> usb 1-1-port4: over current-change #84

So this could be caused by in-rush current issue, or a generally underpowered SSD. To mitigate using a powered hub is most likely helpful.
