### ISSUE TITLE
After updating Operating System to 10.1 version, teslamate cannot start

### ISSUE THREAD

**Issue by raforo** [home-assistant/operating-system#2526]
### Describe the issue you are experiencing

After updating Operating System to 10.1 version, teslamate addon cannot start. Not other Home Assistant service affected, Grafana and Postgres are runing ok.

Multiple lines written in CLI, for example:
[ 164.964259] Out of memory: killed process 7400 (beam,smp) total-vm:3246464kB,anon-rss:1191984kB, file-rss:8kB, shmen-rss:0kB, UID:0 pgtables:2472kB oom_score_adj:200

but I think I haven't problem of memory, usually about 58% reaching 75% maximum, 2GB available

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-04-30 20:22:00 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TeslaMate is failed, restarting...
23-04-30 20:22:00 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_29b65938_teslamate application
23-04-30 20:22:02 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mattffffff/teslamate-aarch64 with version 0.18.1
23-04-30 20:22:17 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2579' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
23-04-30 20:23:08 ERROR (SyncWorker_2) [supervisor.docker.interface] Container addon_29b65938_teslamate is not running
23-04-30 20:23:14 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-04-30 20:23:14 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-04-30 20:23:14 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
23-04-30 20:23:14 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
23-04-30 20:23:30 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_29b65938_teslamate application
23-04-30 20:23:31 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on mattffffff/teslamate-aarch64 with version 0.18.1
23-04-30 20:23:47 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2947' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
23-04-30 20:38:14 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_29b65938_teslamate application
23-04-30 20:38:15 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on mattffffff/teslamate-aarch64 with version 0.18.1
23-04-30 20:38:31 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-5051' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
```

### Anything in the Host logs that might be useful for us?

```txt
Teslamate log:
[s6-init] making user provided files available at var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:56:34] INFO: Checking for Grafana folder: TeslaMate
[16:56:35] INFO: ... RESTORED timeline.json
[16:56:35] INFO: ... RESTORED statistics.json
[16:56:35] INFO: ... RESTORED projected-range.json
[16:56:36] INFO: ... RESTORED drives.json
[16:56:36] INFO: ... RESTORED charge-level.json
[16:56:36] INFO: ... RESTORED trip.json
[16:56:37] INFO: ... RESTORED updates.json
[16:56:37] INFO: ... RESTORED overview.json
[16:56:37] INFO: ... RESTORED charging-stats.json
[16:56:38] INFO: ... RESTORED vampire-drain.json
[16:56:38] INFO: ... RESTORED visited.json
[16:56:38] INFO: ... RESTORED mileage.json
[16:56:38] INFO: ... RESTORED drive-stats.json
[16:56:39] INFO: ... RESTORED efficiency.json
[16:56:39] INFO: ... RESTORED locations.json
[16:56:39] INFO: ... RESTORED states.json
[16:56:40] INFO: ... RESTORED charges.json
[16:56:40] INFO: ... RESTORED charge-details.json
[16:56:40] INFO: ... RESTORED drive-details.json
[16:56:40] INFO: Finished Importing Grafana Dashboards
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Killed
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
```

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1278
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 439.4 GB
disk_used | 29.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Home Assistant Google Drive Backup (0.110.4), Duck DNS (1.15.0), SQLite Web (3.7.1), SSH & Web Terminal (13.1.0), InfluxDB (4.6.0), Node-RED (14.1.5), Mosquitto broker (6.2.1), Grafana (8.2.2), PostgreSQL (1.0.0), ESPHome (2023.4.2), TeslaMate (0.18.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 de abril de 2023, 20:05
-- | --
current_recorder_run | 30 de abril de 2023, 20:17
estimated_db_size | 77.34 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
Unfortunately, this is a new behavior introduced with the latest Docker 23.0 release. It requires an add-on change, I've posted information to the relevant add-on issue: https://github.com/matt-FFFFFF/hassio-addon-teslamate/issues/92#issuecomment-1529644718. Please reopen in case this turns out to be something else, which needs addressing here.
