### ISSUE TITLE
Nabucasa in latest HA OS is not showing Alexa or Google

### ISSUE THREAD

**Issue by YardoDEVS** [home-assistant/operating-system#2534]
### Describe the issue you are experiencing

I recently updated to the latest version of HAOS in my raspberry, I updated all the integrations and addons to the latest too and now I can't see my devices from alexa side, then when I look at the Home Assistant Cloud (Nabucasa) I saw both Alexa and Google integrations are not there. What can be happening with this? Thanks in advance

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Open web interface of HAOS
2. Go to Nabucasa section
3. The only thing that appear to still working were the webhooks I created in the past. I can't see my Alexa and Google integrations
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I can't see nothing in logs related to the problem
```

### Anything in the Host logs that might be useful for us?

```txt
I can't see nothing in logs related to the problem
```

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @YardoDEVS!

If you updated to Home Assistant Core 2023.5.0: 
Alexa and Google moved to **Settings** > **Voice Assistant.** 
![image](https://user-images.githubusercontent.com/38767475/236203210-a4df96af-79be-4bcc-bb4e-12f57dd9708d.png)

Read all about the new Voice Assistant:
*  in this [blog post] (https://www.home-assistant.io/blog/2023/04/27/year-of-the-voice-chapter-2/) 
*  the (documentation on exposing devices)[https://www.home-assistant.io/docs/assist/voice_remote_expose_devices/], 
* setting up [an assistant](https://www.home-assistant.io/docs/assist/voice_remote_local_assistant/), 
* [building a voice remote](https://www.home-assistant.io/projects/thirteen-usd-voice-remote/)

Please check, if you find it at this location. If not, please open a new issue.
