### ISSUE TITLE
discovery works only on the main network interface

### ISSUE THREAD

**Issue by unclehack** [home-assistant/operating-system#2555]
### Describe the issue you are experiencing

I have HA OS installed on an x86_64 machine (actual hardware, not VM) with two network interfaces connected to two networks. Automatic discovery never worked for anything on the second network interface. It gave me the impression that discovery is completely broken. This turned out to not be the case when one day a device connected to the main network interface (default) was detected automatically. It was now obvious that discovery was broken only on the non-default network interfaces.

The issue seems to be related to mdns. I've tried to search to find a proper solution which can be implemented. Most threads and posts were recommending setting the default network interface.

I've noticed this issue with esphome based devices and a few other devices.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Set up HA OS on a system with two network interfaces & configure the two
2. Connect a device which is automatically discovered to the default network interface
3. The device is detected and shows up in HA
4. Connect the same device to the secondary network interface
5. The device isn't detected and doesn't show up in HA
...

### Anything in the Supervisor logs that might be useful for us?

```txt
not relevant
```

### Anything in the Host logs that might be useful for us?

```txt
not relevant
```

**Comment by agners** [comment]
This is a limitation of Home Assistant Core currently.
