### ISSUE TITLE
WIFI missing for Qualcomm Atheros QCA9377

### ISSUE THREAD

**Issue by siministry** [home-assistant/operating-system#2556]
### Describe the issue you are experiencing

WIFI firmware missing for Qualcomm Atheros QCA9377

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

On boot no WIFI device found

nmcli radio
WIFI-HW WIFI WWAN-HW WWAN
missing enabled missing enabled

### Anything in the Supervisor logs that might be useful for us?

```txt
.
```

### Anything in the Host logs that might be useful for us?

```txt
.
```

### System information

Debian 11

### Additional information
https://packages.debian.org/bullseye/all/firmware-atheros/download
.

**Comment by scottcopus** [comment]
I have this same hardware too that I would like to take advantage of... maybe for bluetooth too.
