### ISSUE TITLE
Intel WiFi card not supported on OVA

### ISSUE THREAD

**Issue by aapeliv** [home-assistant/operating-system#2558]
### Describe the issue you are experiencing

I'm running the generic-x86-64 image in KVM on a Ubuntu host. Whenever I shut down the computer I have to wait an extra 2 minutes for HA to be killed because it won't shut down by itself like my other VMs.

This seems related to #1896, but I'm not running the OVA image (I need the WiFi drivers so I can connect ESP32s).

How can I modify the systemd config or work around this?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Run in VM
2. Turn host off
3. Have to wait 2 minutes

### Anything in the Supervisor logs that might be useful for us?

```txt
nope
```

### Anything in the Host logs that might be useful for us?

```txt
nope
```

**Comment by agners** [comment]
Use the OVA image, it is meant to be used for virtualization and shuts down automatically on ACPI events.

**Comment by aapeliv** [comment]
So how does one get the intel wifi drivers on the OVA image?

**Comment by agners** [comment]
You are using WiFi from within your virtual machine? What is your use case?

**Comment by aapeliv** [comment]
Awesome, thank you!!
