### ISSUE TITLE
TrueNAS Core + NFS Network storage: "Protocol not supported"

### ISSUE THREAD

**Issue by transplier** [home-assistant/operating-system#2580]
### The problem

I went to add a backup network location in the UI and pointed it to my TrueNAS NFS mount. Unfortunately, after a couple seconds it fails and instructs me to check in the logs (aside, this message could be improved for clarity, see [1]). Checking the Host logs, I see:

```
Jun 08 04:17:24 homeassistant systemd[1]: Mounting Supervisor nfs mount: nas_backup...
Jun 08 04:17:24 homeassistant mount[495100]: mount.nfs: Protocol not supported
Jun 08 04:17:24 homeassistant systemd[1]: mnt-data-supervisor-mounts-nas_backup.mount: Mount process exited, code=exited, status=32/n/a
Jun 08 04:17:24 homeassistant systemd[1]: mnt-data-supervisor-mounts-nas_backup.mount: Failed with result 'exit-code'.
Jun 08 04:17:24 homeassistant systemd[1]: Failed to mount Supervisor nfs mount: nas_backup.
```

Maybe it's an NFS3 vs NFS4 issue? I was stymied in my efforts to set up NFS4 as I found it overcomplicated for what I needed.

A `mount` entry of the exact same share on my workstation is provided for reference:
```
192.168.1.15:/mnt/hdd-array/device-backups on /mnt/device-backups type nfs (rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.15,mountvers=3,mountport=956,mountproto=udp,local_lock=none,addr=192.168.1.15,_netdev)
```

[1] The message in the dialog was `Mounting nas_backup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-nas_backup.mount for details.`, which a user not familiar with the internals of linux, `systemd`, and how to get a shell in HA will not easily be able to figure out. Fortunately enough information is present in the `Host` logs in the UI, so maybe it would be a good idea to send the user there?

### What version of Home Assistant Core has the issue?

core-2023.6.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Jun 08 04:17:24 homeassistant systemd[1]: Mounting Supervisor nfs mount: nas_backup...
Jun 08 04:17:24 homeassistant mount[495100]: mount.nfs: Protocol not supported
Jun 08 04:17:24 homeassistant systemd[1]: mnt-data-supervisor-mounts-nas_backup.mount: Mount process exited, code=exited, status=32/n/a
Jun 08 04:17:24 homeassistant systemd[1]: mnt-data-supervisor-mounts-nas_backup.mount: Failed with result 'exit-code'.
Jun 08 04:17:24 homeassistant systemd[1]: Failed to mount Supervisor nfs mount: nas_backup.
```

**Comment by ludeeus** [comment]
v4 was added in OS 10.0 and v3 was added in OS 10.2, can you post your system health details?
<https://my.home-assistant.io/redirect/system_health/>
