### ISSUE TITLE
Dual Marvell 88e1512 ethernet not working

### ISSUE THREAD

**Issue by troky** [home-assistant/operating-system#2589]
### Describe the issue you are experiencing

I have fitlet3 SBC with dual Marvell 88e1512 ethernet that don't work on bare metal install.
Debian 12 works (Debian 11 doesn't work), latest Ubuntu works... Missing drivers or something?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.2, 11-dev

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Install HA OS on bare metal as per documentation.

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

### Additional information

[fitlet3 specification](http://fit-pc.com/wiki/index.php?title=Fitlet3_Specifications_and_block_diagram)

**Comment by agners** [comment]
> Missing drivers or something?

Probably. Can you share lspci or the host logs?

Or maybe `dmesg` and `lspci` from Debian, should help as well to identify the drivers loaded etc.

**Comment by troky** [comment]
lspci (HA OS):

00:17.0 Class 0106: 8086:4b63
00:1c.0 Class 0604: 8086:4b38
00:1b.6 Class 0c80: 8086:4bbf
00:08.0 Class 0880: 8086:4511
00:1f.0 Class 0601: 8086:4b00
00:1d.1 Class 0200: 8086:4ba1
00:13.0 Class 0c80: 8086:4b84
00:11.1 Class 0780: 8086:4b97
00:19.2 Class 0780: 8086:4b4d
00:16.0 Class 0780: 8086:4b70
01:00.0 Class 0108: 2646:500d
00:1b.0 Class 0c80: 8086:4bb9
00:1f.5 Class 0c80: 8086:4b24
00:19.0 Class 0c80: 8086:4b4b
00:1e.0 Class 0780: 8086:4b28
00:1f.3 Class 0401: 8086:4b58
00:00.0 Class 0600: 8086:4522
00:15.2 Class 0c80: 8086:4b7a
00:15.0 Class 0c80: 8086:4b78
00:1d.2 Class 0200: 8086:4bb1
00:1d.0 Class 0880: 8086:4bb3
00:1c.6 Class 0604: 8086:4b3e
00:1b.1 Class 0c80: 8086:4bba
00:14.2 Class 0500: 8086:4b7f
00:11.0 Class 0780: 8086:4b96
00:1c.4 Class 0604: 8086:4b3c
00:02.0 Class 0300: 8086:4555
00:1e.1 Class 0780: 8086:4b29
00:14.0 Class 0c03: 8086:4b7d
00:1f.4 Class 0c05: 8086:4b23
00:15.3 Class 0c80: 8086:4b7b

I don't know how to get logs from HA OS CLI.

I'll have dmesg/lspci from Debian 12 tomorrow...

**Comment by troky** [comment]
lspci (Debian 12 - working ethernet):

00:00.0 Host bridge: Intel Corporation Device 4522 (rev 01)
00:02.0 VGA compatible controller: Intel Corporation Elkhart Lake [UHD Graphics Gen11 16EU] (rev 01)
00:08.0 System peripheral: Intel Corporation Device 4511 (rev 01)
00:11.0 Communication controller: Intel Corporation Device 4b96 (rev 11)
00:11.1 Communication controller: Intel Corporation Device 4b97 (rev 11)
00:13.0 Serial bus controller: Intel Corporation Device 4b84 (rev 11)
00:14.0 USB controller: Intel Corporation Device 4b7d (rev 11)
00:14.2 RAM memory: Intel Corporation Device 4b7f (rev 11)
00:15.0 Serial bus controller: Intel Corporation Device 4b78 (rev 11)
00:15.2 Serial bus controller: Intel Corporation Device 4b7a (rev 11)
00:15.3 Serial bus controller: Intel Corporation Device 4b7b (rev 11)
00:16.0 Communication controller: Intel Corporation Device 4b70 (rev 11)
00:17.0 SATA controller: Intel Corporation Device 4b63 (rev 11)
00:19.0 Serial bus controller: Intel Corporation Device 4b4b (rev 11)
00:19.2 Communication controller: Intel Corporation Device 4b4d (rev 11)
00:1b.0 Serial bus controller: Intel Corporation Device 4bb9 (rev 11)
00:1b.1 Serial bus controller: Intel Corporation Device 4bba (rev 11)
00:1b.6 Serial bus controller: Intel Corporation Device 4bbf (rev 11)
00:1c.0 PCI bridge: Intel Corporation Device 4b38 (rev 11)
00:1c.4 PCI bridge: Intel Corporation Device 4b3c (rev 11)
00:1c.6 PCI bridge: Intel Corporation Device 4b3e (rev 11)
00:1d.0 System peripheral: Intel Corporation Device 4bb3 (rev 11)
00:1d.1 Ethernet controller: Intel Corporation Device 4ba1 (rev 11)
00:1d.2 Ethernet controller: Intel Corporation Device 4bb1 (rev 11)
00:1e.0 Communication controller: Intel Corporation Device 4b28 (rev 11)
00:1e.1 Communication controller: Intel Corporation Device 4b29 (rev 11)
00:1f.0 ISA bridge: Intel Corporation Device 4b00 (rev 11)
00:1f.3 Multimedia audio controller: Intel Corporation Device 4b58 (rev 11)
00:1f.4 SMBus: Intel Corporation Device 4b23 (rev 11)
00:1f.5 Serial bus controller: Intel Corporation Device 4b24 (rev 11)
01:00.0 Non-Volatile memory controller: Kingston Technology Company, Inc. OM3PDP3 NVMe SSD (rev 01)

---

00:1d.1 Ethernet controller: Intel Corporation Device 4ba1 (rev 11) (prog-if 18)
	DeviceName: Onboard - Ethernet
	Subsystem: Intel Corporation Device 7270
	Flags: bus master, fast devsel, latency 0, IRQ 133, IOMMU group 14
	Memory at 6001340000 (64-bit, non-prefetchable) [size=256K]
	Capabilities: [80] Power Management version 3
	Capabilities: [90] Vendor Specific Information: Len=14 <?>
	Capabilities: [d0] MSI: Enable+ Count=32/32 Maskable+ 64bit+
	Kernel driver in use: intel-eth-pci
	Kernel modules: dwmac_intel

00:1d.2 Ethernet controller: Intel Corporation Device 4bb1 (rev 11) (prog-if 19)
	DeviceName: Onboard - Ethernet
	Subsystem: Intel Corporation Device 7270
	Flags: bus master, fast devsel, latency 0, IRQ 165, IOMMU group 14
	Memory at 6001300000 (64-bit, non-prefetchable) [size=256K]
	Capabilities: [80] Power Management version 3
	Capabilities: [90] Vendor Specific Information: Len=14 <?>
	Capabilities: [d0] MSI: Enable+ Count=32/32 Maskable+ 64bit+
	Kernel driver in use: intel-eth-pci
	Kernel modules: dwmac_intel

ethernet adapters shown as Intel??

**Comment by troky** [comment]
Cool! Thanks.

**Comment by agners** [comment]
@troky can you give this image a try? https://os-builds.home-assistant.io/11.0.dev20230613/

**Comment by troky** [comment]
I've built image with your changes yesterday and I can confirm it works... Thanks again.
