### ISSUE TITLE
Broadcom Wifi card not detected

### ISSUE THREAD

**Issue by Daafip** [home-assistant/operating-system#2617]
### Describe the issue you are experiencing

My HP Thinclient T520 has a Broadcom BCM43228 802.11a/b/g/n.  [Should work in linux](https://linux-hardware.org/?id=pci:14e4-4359-14e4-05e2), however homeasstant OS doesn't recognise it. Same issue as mentioned by #1872 [(here)](https://github.com/home-assistant/operating-system/issues/1872), also documenten on the [community forum](https://community.home-assistant.io/t/internal-wi-fi-card-not-detected-no-wi-fi-driver/359844/30). I agree Ethernet is better, but continued support for wifi cards would be amazing!

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.1.34

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install broadcom BCM43228 802.11a/b/g/n chip.
2. Not recognized 

### Anything in the Supervisor logs that might be useful for us?

```txt
Nope
```

### Anything in the Host logs that might be useful for us?

```txt
Nope
```

### System information

# System information
Version	core-2023.6.3
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.11.4
Operating System Family	Linux
Operating System Version	6.1.34
CPU Architecture	x86_64
Timezone	Europe/Amsterdam
Configuration Directory	/config
Home Assistant Cloud
Logged In	true
Subscription Expiration	January 30, 2024 at 1:00 AM
Relayer Connected	true
Relayer Region	eu-central-1
Remote Enabled	true
Remote Connected	true
Alexa Enabled	false
Google Enabled	true
Remote Server	eu-central-1-3.ui.nabu.casa
Certificate Status	ready
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	ok
## Home Assistant Supervisor
Host Operating System	Home Assistant OS 10.3
Update Channel	stable
Supervisor Version	supervisor-2023.06.2
Agent Version	1.5.1
Docker Version	23.0.6
Disk Total	228.5 GB
Disk Used	12.4 GB
Healthy	true
Supported	true
Board	generic-x86-64
Supervisor API	ok

**Comment by atifhub** [comment]
@agners please reopen this issue 🙏
