### ISSUE TITLE
HA OS 10.3 file system errors on Pi 4

### ISSUE THREAD

**Issue by th3uiguy** [home-assistant/operating-system#2619]
### Describe the issue you are experiencing

ext4 filesystem read/write errors when using an SSD on Raspberry Pi 4

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Write HA OS 10.3 image to SSD though Raspberry Pi Imager
2. Start up the Raspberry Pi with SSD (USB) setup as the boot image location
3. Notice file system errors during initial setup

### Anything in the Supervisor logs that might be useful for us?

```txt
None
```

### Anything in the Host logs that might be useful for us?

```txt
None
```

### Additional information

Possibly due to kernel update?

**Comment by agners** [comment]
This sounds like a HW issue. Have you tried a different SD card and/or Raspberry Pi?

**Comment by Baxxy13** [comment]
For me it sounds like another problematic/incompatible USB->SATA Adapter because no SD-Card is involved.

There is already a Blacklist of Adapters which having problems with UAS-Mode. 
Maybe your Adapter should be blacklistet too.

Read here: #1743

**Comment by th3uiguy** [comment]
@agners It is a Kingston SSD (only a few months old). You think the drive when out? I do not see these errors on 10.2 so I don't know why it would be a hardware issue. They happened after updating to the 10.3 OS and then any time I try to reinstall using 10.3 is see them fill the screen, sorry I do not have screenshots.

**Comment by th3uiguy** [comment]
I am using the StarTech adapter: USB312SAT3CB

**Comment by th3uiguy** [comment]
I'll work on getting more details

**Comment by zillion42** [comment]
I think it's the same as this. I have not heard anyone booting from usb ssd on pi4 above HA OS 9.5 without errors:
https://github.com/home-assistant/operating-system/issues/2536

**Comment by markusmauch** [comment]
I have the same issue using the ORICO Extreme PRO Portable SSD External Hard Drive 128 GB USB 3.1 Gen-2 Type-C https://amzn.eu/d/e4Yx9yw

It worked perfectly prior to Home Assistant OS 10. Now I'm either stuck with 9.5 or have a system crash at least every second day.
