### ISSUE TITLE
HA operating system 10.3 ne se connecte pas à internet

### ISSUE THREAD

**Issue by domo-greg** [home-assistant/operating-system#2624]
### Describe the issue you are experiencing

Ha core 10.3 ne trouve pas la connexion internet sur mini pc nipogi 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Passer de la version 9.5 a la versio n 10.3

### Anything in the Supervisor logs that might be useful for us?

```txt
Je n'y ai plus accès
```

### Anything in the Host logs that might be useful for us?

```txt
Plus d'accès
```

**Comment by agners** [comment]
Please submit issues in English. Also provide the full system specifications.
