### ISSUE TITLE
system timezone can't modify

### ISSUE THREAD

**Issue by 931122** [home-assistant/operating-system#2647]
### Describe the issue you are experiencing

in x86 system, /etc/localtime/ and /etc/timezone can't modify.
if used incorrect zone, some docker can use this zone.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
The rootfs is a read-only system, so that is intended. We handle Timezone in the containers individually (e.g. in the Core container).

What is your use case/the problem you are seeing?
