### ISSUE TITLE
Update to HA OS 10.4 failing: '/dev/disk/by-partlabel/hassos-boot' not found / not existent

### ISSUE THREAD

**Issue by user45876** [home-assistant/operating-system#2670]
### Describe the issue you are experiencing

 When trying to 7pdate to HA OS 10.4, I am getting this:

`[supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Destination device '/dev/disk/by-partlabel/hassos-boot' not found`

Actually, there is no /dev/disk/by-partlabel/ on my installation:
```
ls -lah /dev/disk/
total 0
drwxr-xr-x    8 root     root         160 Aug  5 20:59 .
drwxr-xr-x   17 root     root        3.2K Aug  5 20:59 ..
drwxr-xr-x    2 root     root         220 Aug  5 21:04 by-diskseq
drwxr-xr-x    2 root     root         580 Aug  5 20:59 by-id
drwxr-xr-x    2 root     root         100 Aug  5 20:59 by-label
drwxr-xr-x    2 root     root         200 Aug  5 20:59 by-partuuid
drwxr-xr-x    2 root     root         220 Aug  5 20:59 by-path
drwxr-xr-x    2 root     root         100 Aug  5 20:59 by-uuid
```
The Hassos-Boot link can be found under 'by-label:

```
ls -lah /dev/disk/by-label/
total 0
drwxr-xr-x    2 root     root         100 Aug  5 20:59 .
drwxr-xr-x    8 root     root         160 Aug  5 20:59 ..
lrwxrwxrwx    1 root     root          15 Aug  5 20:59 hassos-boot -> ../../nvme0n1p1
lrwxrwxrwx    1 root     root          15 Aug  5 20:59 hassos-data -> ../../nvme0n1p8
lrwxrwxrwx    1 root     root          15 Aug  5 20:59 hassos-overlay -> ../../nvme0n1p7
```

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Have 10.3 running
2. Reboot (or don't)
3. Try upgrading to 10.4
4. Get logged errors

### Anything in the Supervisor logs that might be useful for us?

```txt
23-08-05 21:08:51 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/10.4/haos_generic-x86-64-10.4.raucb
23-08-05 21:08:57 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-10.4.raucb
23-08-05 21:08:58 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Destination device '/dev/disk/by-partlabel/hassos-boot' not found`
```

### Anything in the Host logs that might be useful for us?

```txt
See initial post.
```

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1331
Downloaded Repositories | 41
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 6. August 2023 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 457.7 GB
disk_used | 54.7 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (4.7.0), Grafana (9.0.3), Network UPS Tools (0.12.0), Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), Mosquitto broker (6.2.1), Z-Wave JS UI (1.15.3), Advanced SSH & Web Terminal (15.0.6), chrony (2.6.0), Log Viewer (0.15.1), AdGuard Home (4.8.13), TasmoBackup (1.05.00), Uptime Kuma (0.8.0), OneDrive Backup (2.1.2), ESPHome (2023.7.1), ioBroker (0.8.0), MariaDB (2.6.1), phpMyAdmin (0.8.7), Tailscale (0.11.1), TasmoAdmin (0.25.0), Studio Code Server (5.10.0), Whisper (1.0.0), Piper (1.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 26
views | 20
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6. Juli 2023 um 18:55
-- | --
current_recorder_run | 5. August 2023 um 20:13
estimated_db_size | 1463.03 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Additional information

**Comment by agners** [comment]
> Actually, there is no /dev/disk/by-partlabel/ on my installation:

Hm, there should be. From my generic-x86-64 installation:

```
# ls -la /dev/disk/by-partlabel
total 0
drwxr-xr-x    2 root     root           200 Jul 12 11:17 .
drwxr-xr-x    9 root     root           180 Jul 12 11:17 ..
lrwxrwxrwx    1 root     root            10 Jul 12 11:17 hassos-boot -> ../../sda1
...
```

What is `fdisk -l /dev/nvme0n1` saying?

If the GPT partition label is lost, maybe other things are corrupted too. Probably the best fix is to take a full backup and start with a new HAOS 10.4 installation.

**Comment by user45876** [comment]
Thanks, Stefan. This is the output:

```
fdisk -l /dev/nvme0n1
Disk /dev/nvme0n1: 465.76 GiB, 500107862016 bytes, 976773168 sectors
Disk model: CT500P3SSD8
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: DB832910-E6F3-94C2-C315-7931DD297683

Device           Start       End   Sectors   Size Type
/dev/nvme0n1p1    2048     67583     65536    32M EFI System
/dev/nvme0n1p2   69632    118783     49152    24M Linux filesystem
/dev/nvme0n1p3  120832    645119    524288   256M Linux filesystem
/dev/nvme0n1p4  647168    696319     49152    24M Linux filesystem
/dev/nvme0n1p5  698368   1222655    524288   256M Linux filesystem
/dev/nvme0n1p6 1224704   1241087     16384     8M Linux filesystem
/dev/nvme0n1p7 1243136   1439743    196608    96M Linux filesystem
/dev/nvme0n1p8 1441792 976773134 975331343 465.1G Linux filesystem
```
I am unable to grok it myself - is that good? I can not see any obvious signs of corruption.

Restore is an option, I would however try to avoid it, as it is not as hassle free, as it should be. The installation is not very old, I just put in the 'new' SSD several weeks ago.

**Comment by user45876** [comment]
I restored from backup and got it fixed that way.
