### ISSUE TITLE
Tronsmart Ara X5  WiFi not working

### ISSUE THREAD

**Issue by avi7630** [home-assistant/operating-system#2674]
### Describe the issue you are experiencing

the home assistant os wont recognize my wifi adapter even though when i had windows or ubuntu installed it worked just fine.
the system im usin is tronsmart ara x5 (not to confuse with the plus edition) based on instal atom x8300.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

just by clean install of hassio on my system

### Anything in the Supervisor logs that might be useful for us?

```txt
not really. it's probably a driver problem
```

### Anything in the Host logs that might be useful for us?

```txt
not really. it's probably a driver problem
```

**Comment by agners** [comment]
Do you have `dmesg` or other information about the exact WiFi chip on that platform?

From what I read it is a Broadcom BCM4330. It seems that the necessary driver `CONFIG_B43` is indeed not enabled on HAOS.
