### ISSUE TITLE
USB Serial Console support

### ISSUE THREAD

**Issue by rolf-tx** [home-assistant/operating-system#2683]
### Describe the issue you are experiencing

@agners 
I'm using homeassistant x86 OS.
I would like to use a USB serial cable and have console output to it.
I have "console=tty1  console=ttyUSB0,115200n8" to the cmdline.txt but get nothing on the serial.
```
[    0.000000] Command line: BOOT_IMAGE=(hd1,gpt2)/bzImage root=PARTUUID=8d3d53e
3-6d49-4c38-8349-aff6859e82fd rootwait zram.enabled=1 zram.num_devices=3 net.nam
ing-scheme=v250 systemd.machine_id=1233797a03a14c4e9ba0926b05bac010 fsck.repair=
yes console=tty1 console=ttyUSB0,115200 rauc.slot=A

[    7.253298] usbcore: registered new interface driver pl2303
[    7.253308] usbserial: USB Serial support registered for pl2303
[    7.253319] pl2303 1-6:1.0: pl2303 converter detected
[    7.253497] usb 1-6: pl2303 converter now attached to ttyUSB0
[    7.253775] usb 1-4: cp210x converter now attached to ttyUSB1
[    7.256462] usbcore: registered new interface driver btusb
[    7.266923] Bluetooth: hci0: Legacy ROM 2.x revision 5.0 build 25 week 20 2015
```

I'm seeing tty1 being setup as console, but not a similar line or ttyUSB0.
`  [    0.065342] printk: console [tty1] enabled`

Is the current version of homeassistant OS compiled with USB serial console enabled?
 CONFIG_USB_SERIAL_CONSOLE=y

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Add a USB serial cable to the system
2. Add console=ttyUSB0 to /mnt/boot/cmdline.txt 
3. Reboot and try to connect to USB serial port from other computer

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4844
Installed Version | 1.32.1
Stage | running
Available Repositories | 1269
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.0 GB
disk_used | 11.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (1.15.5), Let's Encrypt (4.12.9), Advanced SSH & Web Terminal (15.0.6), ESPHome (2023.7.1), Silicon Labs Flasher (0.2.0), Mosquitto broker (6.2.1), WeatherFlow to MQTT (3.1.6), File editor (5.6.0), Docker Wyze Bridge (2.3.14), Piper (1.2.0), Whisper (1.0.0), Silicon Labs Multiprotocol (2.3.1), Matter Server (4.9.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 2, 2023 at 19:50
-- | --
current_recorder_run | August 12, 2023 at 18:40
estimated_db_size | 554.40 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by agners** [comment]
> Is the current version of homeassistant OS compiled with USB serial console enabled?
> CONFIG_USB_SERIAL_CONSOLE=y

Currently it is not enabled.
