### ISSUE TITLE
Update HassOS from 10.3 to 10.4/10.5 won't work

### ISSUE THREAD

**Issue by CasaKatz** [home-assistant/operating-system#2700]
### Describe the issue you are experiencing

I was needed to extend my RASPI 4 memory by using an USB-stick for the system. It wasn't a problem at last OS-Updates, but since july I receive this on each try of update:

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. I start the update
2. 'm getting an unknown error message, should check the supervisor logs
3. and there I see: 
ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-08-23 16:52:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-08-23 16:52:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
23-08-23 16:52:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-08-23 16:53:00 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-08-23 16:53:02 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-08-23 16:53:02 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-08-23 16:53:02 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-08-23 16:53:05 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not WSMsgType.TEXT
23-08-23 16:53:05 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-08-23 16:53:08 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/10.5/haos_rpi4-64-10.5.raucb
23-08-23 16:53:23 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-10.5.raucb
23-08-23 16:53:25 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126
```

### Anything in the Host logs that might be useful for us?

```txt
last entries:

ug 23 15:18:37 RPI4 systemd-timesyncd[545]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).
Aug 23 15:18:46 RPI4 kernel: mmc0: Got data interrupt 0x00000002 even though no data operation was in progress.
Aug 23 15:18:46 RPI4 systemd-journal-gatewayd[205411]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Aug 23 15:19:20 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-c9600ced015552f1a8868a49585bd7c73376dec43f0e369f330445f8f152dc32-runc.vzb9kz.mount: Deactivated successfully.
Aug 23 15:19:28 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-781de6d73455f7705eb7e45c7fff457eb77735efeec50c38351fb47c05c6e48f-runc.Rjbj27.mount: Deactivated successfully.
Aug 23 15:20:21 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-c9600ced015552f1a8868a49585bd7c73376dec43f0e369f330445f8f152dc32-runc.3fA3AF.mount: Deactivated successfully.
Aug 23 15:21:45 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-75fc785a029fd8d836dfe6fc228208fad1e023d2a06530d1169ee08251327f7d-runc.0VWuzb.mount: Deactivated successfully.
Aug 23 15:22:22 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-c9600ced015552f1a8868a49585bd7c73376dec43f0e369f330445f8f152dc32-runc.hE1yXZ.mount: Deactivated successfully.
Aug 23 15:22:29 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-781de6d73455f7705eb7e45c7fff457eb77735efeec50c38351fb47c05c6e48f-runc.f2HdXA.mount: Deactivated successfully.
Aug 23 15:22:52 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-c9600ced015552f1a8868a49585bd7c73376dec43f0e369f330445f8f152dc32-runc.e7wLlX.mount: Deactivated successfully.
Aug 23 15:22:59 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-781de6d73455f7705eb7e45c7fff457eb77735efeec50c38351fb47c05c6e48f-runc.HLbn0s.mount: Deactivated successfully.
Aug 23 15:25:24 RPI4 systemd[1]: run-docker-runtime\x2drunc-moby-c9600ced015552f1a8868a49585bd7c73376dec43f0e369f330445f8f152dc32-runc.61cWmI.mount: Deactivated successfully.
```

## System Information

version | core-2023.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4960
Installed Version | 1.32.1
Stage | running
Available Repositories | 1331
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 18. September 2023 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 57.3 GB
disk_used | 13.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.87), Node-RED (14.4.5), Advanced SSH & Web Terminal (15.0.7), ESPHome (2023.8.2), Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), Studio Code Server (5.10.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 5
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20. August 2023 um 15:21
-- | --
current_recorder_run | 23. August 2023 um 16:52
estimated_db_size | 161.04 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

Home Assistant Core
2023-08-23 16:52:23.651 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-23 16:52:23.653 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-23 16:52:23.655 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-23 16:52:23.657 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-23 16:52:23.660 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-23 16:52:50.369 WARNING (MainThread) [alexapy.alexalogin] Domain amazon.com does not match reported account domain https://www.amazon.de; functionality is not likely to work, please fix
2023-08-23 16:53:25.528 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547715334592] Error updating Home Assistant Operating System: Unknown error, see supervisor

**Comment by lipcikm** [comment]
I'm suffering from the same problem 

### Invalid config
The following integrations and platforms could not be set up:

[watchman](https://github.com/dummylabs/thewatchman) ([Show logs](http://192.168.xxx.xxx:8123/config/logs?filter=watchman))
[waste_collection_schedule](https://github.com/mampfes/hacs_waste_collection_schedule#readme) ([Show logs](http://192.168.xxx.xxx:8123/config/logs?filter=waste_collection_schedule))
[frigate](https://github.com/blakeblackshear/frigate) ([Show logs](http://192.168.xxx.xxx:8123/config/logs?filter=frigate))
Please check your config and [logs](http://192.168.xxx.xxx:8123/config/logs).

**Comment by JonathanWilbur** [comment]
I get the same problem:

**Comment by pertakman** [comment]
Is there a workaround for this or should I just wait for the next update? I've tried a couple of times but fail.

Warmly, Per

**Comment by agners** [comment]
@pertakman do you also see the `Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126` error in the Supervisor logs?

**Comment by CasaKatz** [comment]
Hello Stefan,

 

please remember, my RPI4-8GB is extended with an USB-Stick for the memory used by HassIO.

I tried to update again right now. Here are my results:

 



Home Assistant Core


[547042714560] Error updating Home Assistant Operating System: Unknown error, see supervisor

13:33:06 – (FEHLER) Home Assistant WebSocket API

Update of update.home_assistant_operating_system_update is taking over 10 seconds

13:32:21 – (WARNUNG) helpers/entity.py

 


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data

aiohttp.http_exceptions.BadStatusLine: 400, message:

Bad status line "Invalid method encountered:\n\n b'\\x16\\x03'\n ^"

2023-09-26 13:32:21.396 WARNING (MainThread) [homeassistant.helpers.entity] Update of update.home_assistant_operating_system_update is taking over 10 seconds

2023-09-26 13:33:06.768 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547042714560] Error updating Home Assistant Operating System: Unknown error, see supervisor

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 212, in async_install

await async_update_os(self.hass, version)

File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper

raise HassioAPIError(data["message"])

homeassistant.components.hassio.handler.HassioAPIError: Unknown error, see supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service

await hass.services.async_call(

File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call

response_data = await coro

^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service

return await target(service_call)

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service

return await service.entity_service_call(

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call

response_data = await _handle_entity_call(

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call

result = await task

^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install

await entity.async_install_with_progress(version, backup)

File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 428, in async_install_with_progress

await self.async_install(version, backup)

File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 214, in async_install

raise HomeAssistantError(

homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: Unknown error, see supervisor

 



 






Supervisor





23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 11:27:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-09-26 11:33:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 11:33:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 11:57:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 12:10:13 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-09-26 12:10:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 12:27:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 12:57:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 13:18:48 INFO (MainThread) [supervisor.host.info] Updating local host information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.services] Updating service information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.network] Updating local network information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-09-26 13:21:52 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 13:27:05 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-26 13:32:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 13:32:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 13:32:25 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/10.5/haos_rpi4-64-10.5.raucb
23-09-26 13:32:40 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-10.5.raucb
23-09-26 13:33:06 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126








 
 

Gesendet: Dienstag, 26. September 2023 um 12:52 Uhr
Von: "Stefan Agner" ***@***.***>
An: "home-assistant/operating-system" ***@***.***>
Cc: "CasaKatz" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [home-assistant/operating-system] Update HassOS from 10.3 to 10.4/10.5 won't work (Issue #2700)


 

@pertakman do you also see the Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126 error in the Supervisor logs?

**Comment by CasaKatz** [comment]
Hello Stefan,

 

please remember, my RPI4-8GB is extended with an USB-Stick for the memory used by HassIO.

I tried to update again right now. Here are my results:

 



Home Assistant Core


[547042714560] Error updating Home Assistant Operating System: Unknown error, see supervisor

13:33:06 – (FEHLER) Home Assistant WebSocket API

Update of update.home_assistant_operating_system_update is taking over 10 seconds

13:32:21 – (WARNUNG) helpers/entity.py

 


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data

aiohttp.http_exceptions.BadStatusLine: 400, message:

Bad status line "Invalid method encountered:\n\n b'\\x16\\x03'\n ^"

2023-09-26 13:32:21.396 WARNING (MainThread) [homeassistant.helpers.entity] Update of update.home_assistant_operating_system_update is taking over 10 seconds

2023-09-26 13:33:06.768 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547042714560] Error updating Home Assistant Operating System: Unknown error, see supervisor

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 212, in async_install

await async_update_os(self.hass, version)

File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper

raise HassioAPIError(data["message"])

homeassistant.components.hassio.handler.HassioAPIError: Unknown error, see supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service

await hass.services.async_call(

File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call

response_data = await coro

^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service

return await target(service_call)

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service

return await service.entity_service_call(

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call

response_data = await _handle_entity_call(

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call

result = await task

^^^^^^^^^^

File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install

await entity.async_install_with_progress(version, backup)

File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 428, in async_install_with_progress

await self.async_install(version, backup)

File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 214, in async_install

raise HomeAssistantError(

homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: Unknown error, see supervisor

 



 






Supervisor

 



23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 11:23:12 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 11:27:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-09-26 11:33:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-09-26 11:33:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 11:33:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 11:57:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 12:10:13 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-09-26 12:10:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 12:23:12 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 12:23:13 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 12:27:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 12:57:04 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 13:18:48 INFO (MainThread) [supervisor.host.info] Updating local host information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.services] Updating service information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.network] Updating local network information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-09-26 13:18:49 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-09-26 13:21:52 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-09-26 13:23:13 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-26 13:27:05 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-09-26 13:32:11 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-26 13:32:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 13:32:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-09-26 13:32:25 INFO (MainThread) [supervisor.os.manager] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/10.5/haos_rpi4-64-10.5.raucb
23-09-26 13:32:40 INFO (MainThread) [supervisor.os.manager] Completed download of OTA update file /data/tmp/hassos-10.5.raucb
23-09-26 13:33:06 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126








 
 

Gesendet: Dienstag, 26. September 2023 um 12:52 Uhr
Von: "Stefan Agner" ***@***.***>
An: "home-assistant/operating-system" ***@***.***>
Cc: "CasaKatz" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [home-assistant/operating-system] Update HassOS from 10.3 to 10.4/10.5 won't work (Issue #2700)


 

@pertakman do you also see the Failed updating slot boot.0: failed to run slot hook: Child process exited with code 126 error in the Supervisor logs?
