### ISSUE TITLE
NTFS, exfat and xfs modules are not compiled in x86-64 arch

### ISSUE THREAD

**Issue by interkelstar** [home-assistant/operating-system#2723]
### Describe the issue you are experiencing

When launching a SambaNAS addon I can see in the logs 

```
modprobe: module ntfs3 not found in modules.dep
[12:33:37] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[12:33:37] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[12:33:37] WARNING: xfs module not available!
```

I am using Home Assistant OS in generic x86-64 device (smth like Intel NUC) and according to this comment from add-on repo
https://github.com/dianlight/hassio-addons/issues/160#issuecomment-1612717416
As well as some others https://github.com/dianlight/hassio-addons/issues/160#issuecomment-1612717416

The problem is that x86-64 version of Hassos doesn't have this modules compiled, but what surprises me that some other arch version has. So is there any particular reason for such a discrepancy? Will it be reasonable to compile these modules into the next release version of Hassos x86-64m even if it's not the main idea of the OS, but if aarch64 can have it, why not us?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 10.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install SambaNAS addon from https://github.com/dianlight/hassio-addons
2. Check the logs

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by agners** [comment]
> The problem is that x86-64 version of Hassos doesn't have this modules compiled, but what surprises me that some other arch version has. So is there any particular reason for such a discrepancy?

No particular reason. This is because we typically base board specific kernel default configurations of some existing configuration (e.g. from the Raspberry Pi team). 

I have on my todo to align the kernel configurations a bit more. Essentially move all "generic" kernel modules to the operating system kernel configuration.

> Will it be reasonable to compile these modules into the next release version of Hassos x86-64m even if it's not the main idea of the OS, but if aarch64 can have it, why not us?

I'll consider it. While I rather prefer to not support "wild" usage of HAOS, these modules are upstream and rather maintenance from HAOS point of view.

**Comment by codyrocco** [comment]
Personally i compile some of these modules - exfat, ntfs, ntfs3, even fuse - and load them manually, at homeassistant start. but this isn't always working with sambanas addon, depending by addons loading order.
having them compiled by default will bring the possibility to use the hardware in extended modes - actual minipcs could pack a lot of power, a lot more than HA requires

**Comment by tomw1964** [comment]
I was just about to move my XFS  4TB of storage from an old power hungry PC on to my shiny new HAOS box and have stumbled into this issue.  +1 vote for adding XFS into the kernel from me :-)

**Comment by adri535** [comment]
> requires

could you explain to me how to do that please?

**Comment by adri535** [comment]
> Personally i compile some of these modules - exfat, ntfs, ntfs3, even fuse - and load them manually, at homeassistant start. but this isn't always working with sambanas addon, depending by addons loading order. having them compiled by default will bring the possibility to use the hardware in extended modes - actual minipcs could pack a lot of power, a lot more than HA requires

could you explain a bit more on how to do that please?

**Comment by codyrocco** [comment]
first of all, reading this: https://developers.home-assistant.io/docs/operating-system/getting-started/

**Comment by lamauny** [comment]
@agners could you consider again adding support to these filesystems ? 
I'd really like using the SambaNAS addon with my NTFS disks too...

**Comment by lamauny** [comment]
added pull request #3516
