### ISSUE TITLE
Update open-vm-tools to latest version 12.3.0

### ISSUE THREAD

**Issue by Grandma-Betty** [home-assistant/operating-system#2733]
### Describe the issue you are experiencing

Not really an issue, but is it possible to update open-vm-tools to the latest version 12.3.0? There have many improvements and security fixes being made since the 11.3.5 version that HAOS has implemented. Should not be such a thing as it is part of the buildroot package and only the .ova image would be affected, right?
Thank you in advance and -as always- thank you for your great work!

EDIT: I just mentioned the version on the official buildroot package is also the outdated version 11.3.5. Is there any reason for that?

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

6.1.45

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

-

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by agners** [comment]
> Is there any reason for that?

The reason that open-vm-tools did not got updated in upstream buildroot? Lack of interest/contributors I guess.

The open-vm-tools is one of these packages which are just annoying to maintain: Quite some patches needed to make it work, and upstream has a rather annoying contributor license agreement process.

I'll give it a try, if upgrading is somewhat straight forward I can probably handle it.

**Comment by agners** [comment]
Yeah I've started an attempt, but the patches in buildroot are not cleanly apply to the current version. Also rebasing them is non-trivial, at least for some (specifically `0007-Use-configure-to-test-for-feature-instead-of-platfor.patch`).

Most of the patches are actually open PRs upstream (e.g. https://github.com/vmware/open-vm-tools/pull/383 or https://github.com/vmware/open-vm-tools/pull/631), but they seem not to make it through. So Buildroot and other (meta-)distributions have to keep maintain these patches :cry: 

I probably can the [latest patches from OpenEmbedded](http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-support/open-vm-tools/open-vm-tools), those have been rebased to 12.1.5 at least.

**Comment by agners** [comment]
Addressed with #2735.
