### ISSUE TITLE
Intalling addons "Installed version" still has the old version

### ISSUE THREAD

**Issue by dhewes** [home-assistant/operating-system#2848]
### Describe the issue you are experiencing

After the last update I tried to update WLED. Worked for all but one, so I thought it was that one device. Then it did the same on Node-RED, Plex Media Server Update,Studio Code Server Update,and UniFi Network Application Update.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

11

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.Just click on the Steetings. everything is stuck in the update list.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Not that I can find
```

### Anything in the Host logs that might be useful for us?

```txt
Not that I can find
```

## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1310
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 27, 2023 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 57.8 GB
disk_used | 17.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), File editor (5.6.0), Node-RED (14.6.1), Mosquitto broker (6.3.1), MariaDB (2.6.1), Studio Code Server (5.10.2), Google Assistant SDK (2.5.0), eWeLink Smart Home (1.4.3), Terminal & SSH (9.7.1), UniFi Network Application (2.7.0), Plex Media Server (3.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 10, 2023 at 12:28 PM
-- | --
current_recorder_run | October 17, 2023 at 8:33 AM
estimated_db_size | 477.91 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

A screen shot will show it all but I don't see where to upload it

**Comment by sairon** [comment]
If the Addons do not update, it's most likely a Supervisor (or network) issue. Don't forget to provide Supervisor logs, because they are needed to get understanding what's going on.
