### ISSUE TITLE
Cannot upgrade from OS 10.4 to 10.5

### ISSUE THREAD

**Issue by ThatBeardGuy** [home-assistant/operating-system#2898]
### Describe the issue you are experiencing

It has been a while since 10.5 came out, but I cannot update to it. I usually update straight away, but this issue prevented me from doing so. I thought it might be an issue in the update and it'll get fixed. Fastforward a few weeks, multiple other updates and reboots later, and I havent seen this issue posted for this version, and it didn't fix itself. 

How do I fix this or can this be fixed in the next version?

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.4

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Go to updates
2. Update Home Assistant Operating System
3. Get a notification to check supervisor

### Anything in the Supervisor logs that might be useful for us?

```txt
ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1
```

### Anything in the Host logs that might be useful for us?

```txt
Nov 02 01:23:27 homeassistant rauc[466]: input bundle: /mnt/data/supervisor/tmp/hassos-10.5.raucb
Nov 02 01:23:28 homeassistant kernel: loop4: detected capacity change from 0 to 250234
Nov 02 01:23:28 homeassistant kernel: loop4: detected capacity change from 250234 to 250232
Nov 02 01:23:28 homeassistant kernel: loop5: detected capacity change from 0 to 65536
Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
Nov 02 01:23:28 homeassistant rauc[29984]: rm: can't stat '/mnt/boot/overlays/*': Input/output error
Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/bcm2711-rpi-4-b.dtb': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/bcm2711-rpi-400.dtb': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/bcm2711-rpi-cm4.dtb': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/boot.scr': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/cmdline.txt': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/config.txt': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/fixup4.dat': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/fixup4cd.dat': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/fixup4x.dat': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't stat '/mnt/boot/overlays': Input/output error
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/start4.elf': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/start4cd.elf': File exists
Nov 02 01:23:29 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/start4x.elf': File exists
Nov 02 01:23:29 homeassistant rauc[29986]: cp: can't create '/mnt/boot/u-boot.bin': File exists
```

**Comment by agners** [comment]
```
Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
Nov 02 01:23:28 homeassistant rauc[29984]: rm: can't stat '/mnt/boot/overlays/*': Input/output error
Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
```

Uh, this seems like the boot partition corrupted.

I recommend taking a full backup and downloading it, then reinstall HAOS on a new SD card.

**Comment by ThatBeardGuy** [comment]
> ```
> Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
> Nov 02 01:23:28 homeassistant rauc[29984]: rm: can't stat '/mnt/boot/overlays/*': Input/output error
> Nov 02 01:23:28 homeassistant kernel: FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 0)
> ```
> 
> Uh, this seems like the boot partition corrupted.
> 
> I recommend taking a full backup and downloading it, then reinstall HAOS on a new SD card.

So... the SD card is just done for? I was planning on moving to an SSD in the future, seems like that future might be now.. Any idea if my devices from Zigbee2mqtt will move over from the backup to the new install?, because then it won't be much of an issue for me.

**Comment by N3rdix** [comment]
> So... the SD card is just done for? I was planning on moving to an SSD in the future, seems like that future might be now.. Any idea if my devices from Zigbee2mqtt will move over from the backup to the new install?, because then it won't be much of an issue for me.

Yes they will as long as you also backup Zigbee2MQTT. Your zigbee adapter doesn't change, so no need to pair again any device. I did a migration from SD to SSD a year back without any issue (besides the horribly long restore duration)
