### ISSUE TITLE
Can't update or install any add-ons (AddonManager.update blocked from execution)

### ISSUE THREAD

**Issue by aatifk** [home-assistant/operating-system#2915]
### Describe the issue you are experiencing

I'm unable to install or update any add-ons. For instance, I have a Node-RED update available and attempting to install it shows the message that AddonManager.update blocked from execution, was unable to update plugin(s) cli and all plugins must be up to date first. I'm running HA OS in a VirtualBox machine on a Debian 12 host (mini PC).

Here's what the error log details show:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:41:47 AM (1 occurrences)
Last logged: 11:41:47 AM

[140188699938880] Error updating Node-RED: 'AddonManager.update' blocked from execution, was unable to update plugin(s) cli and all plugins must be up to date first
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'AddonManager.update' blocked from execution, was unable to update plugin(s) cli and all plugins must be up to date first

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Node-RED: 'AddonManager.update' blocked from execution, was unable to update plugin(s) cli and all plugins must be up to date first

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

11.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

I guess update to HAOS 11.1?

### Anything in the Supervisor logs that might be useful for us?

```txt
Here's what the supervisor log shows: 

23-11-09 12:00:14 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/amd64-hassio-cli:2023.06.0 to ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0
23-11-09 12:00:14 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-cli with tag 2023.10.0.
23-11-09 12:00:18 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
23-11-09 12:00:18 ERROR (MainThread) [supervisor.plugins.cli] CLI update failed
23-11-09 12:00:18 WARNING (MainThread) [supervisor.jobs] 'AddonManager.update' blocked from execution, was unable to update plugin(s) cli and all plugins must be up to date first
```

### Anything in the Host logs that might be useful for us?

```txt
Not sure what counts as useful here, but this is what I see in the last few minutes:

Nov 09 16:59:15 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-7207f00dad91fe7e5c013a6d8b28fb53d509d26b2674b39801b2175c070922f2-runc.Zd6Bgb.mount: Deactivated successfully.
Nov 09 16:59:15 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9aff6cbeaa929439a14c4c35e5ad780422c8693e3668a01ecbb67c3813ce8d24-runc.ClkFh9.mount: Deactivated successfully.
Nov 09 16:59:45 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9aff6cbeaa929439a14c4c35e5ad780422c8693e3668a01ecbb67c3813ce8d24-runc.jOdsJU.mount: Deactivated successfully.
Nov 09 17:00:15 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-7207f00dad91fe7e5c013a6d8b28fb53d509d26b2674b39801b2175c070922f2-runc.rfkKPr.mount: Deactivated successfully.
Nov 09 17:00:18 homeassistant dockerd[415]: time="2023-11-09T17:00:18.671853257Z" level=error msg="Handler for GET /v1.43/images/ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0/json returned error: readlink /mnt/data/docker/overlay2: invalid argument"
Nov 09 17:01:15 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9aff6cbeaa929439a14c4c35e5ad780422c8693e3668a01ecbb67c3813ce8d24-runc.wnLx6f.mount: Deactivated successfully.
Nov 09 17:01:44 homeassistant kernel: audit: type=1334 audit(1699549304.498:273): prog-id=79 op=LOAD
Nov 09 17:01:44 homeassistant systemd-timesyncd[403]: Network configuration changed, trying to establish connection.
Nov 09 17:01:44 homeassistant systemd[1]: Started Journal Gateway Service.
Nov 09 17:01:44 homeassistant systemd-journal-gatewayd[5684]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Nov 09 17:01:45 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-7207f00dad91fe7e5c013a6d8b28fb53d509d26b2674b39801b2175c070922f2-runc.aXrlvY.mount: Deactivated successfully.
Nov 09 17:01:45 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9aff6cbeaa929439a14c4c35e5ad780422c8693e3668a01ecbb67c3813ce8d24-runc.uixPNo.mount: Deactivated successfully.
Nov 09 17:01:54 homeassistant systemd-timesyncd[403]: Timed out waiting for reply from 162.159.200.1:123 (time.cloudflare.com).
Nov 09 17:01:54 homeassistant systemd-timesyncd[403]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).
Nov 09 17:02:15 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9aff6cbeaa929439a14c4c35e5ad780422c8693e3668a01ecbb67c3813ce8d24-runc.QmgQ6w.mount: Deactivated successfully.
```

## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4768
Installed Version | 1.33.0
Stage | running
Available Repositories | 1397
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 22, 2023 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-3.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 30.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.1), Ring-MQTT with Video Streaming (5.6.3), Node-RED (15.0.0), Samba share (10.0.2), Home Assistant Google Drive Backup (0.111.1), ESPHome (2023.10.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 1, 2023 at 3:00 AM
-- | --
current_recorder_run | November 9, 2023 at 11:41 AM
estimated_db_size | 312.14 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by sairon** [comment]
In fact the problem comes from this line:
```
23-11-09 12:00:18 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/amd64-hassio-cli:2023.10.0/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
```
If you search around, there are many more people using Docker having this problem - the most probable cause is some file system corruption, in this case breaking the image for the CLI container. Since you're running a virtualized OS, you should be normally able to attach to the root console, enter `login` and remove and pull the corrupted image, but I'm not sure what happens when the CLI doesn't start, like in this case. If you get a standard shell console at least, it could be a way out, then do `docker rmi home-assistant/amd64-hassio-cli:2023.10.0 ; docker pull home-assistant/amd64-hassio-cli:2023.10.0`.

This is not an OS issue though - Supervisor should be probably able to cope with such a situation, so if you don't find a solution for your problem please file another issue there.
