### ISSUE TITLE
add on get's deactivated every 30 seconds

### ISSUE THREAD

**Issue by bkbartk** [home-assistant/operating-system#2927]
### Describe the issue you are experiencing

I have some performance gaps, and it feels like it has something to do with vscode addon being deactivated every 30 seconds.
I searched the forum and people have the same issue for different add-ns 

### What operating system image do you use?

yellow (Home Assistant Yellow)

### What version of Home Assistant Operating System is installed?

11.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

install this add-on
https://github.com/hassio-addons/addon-vscode

start it
 check the hosts log and see:
```
Nov 13 14:36:43 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.q7VxFu.mount: Deactivated successfully.
Nov 13 14:37:13 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.SPxQZS.mount: Deactivated successfully.
Nov 13 14:37:44 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.b9y157.mount: Deactivated successfully.
```

### Anything in the Supervisor logs that might be useful for us?

```txt
3-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-11-14 18:42:35 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete




23-11-14 19:00:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token



23-11-14 19:17:48 WARNING (MainThread) [supervisor.addons.validate] Add-on config using incompatible map options, 'addon_config' and 'homeassistant_config' are ignored if 'config' is included. Please report this to the maintainer of Studio Code Server
23-11-14 19:17:48 WARNING (MainThread) [supervisor.addons.validate] Add-on config using incompatible map options, 'addon_config' and 'homeassistant_config' are ignored if 'config' is included. Please report this to the maintainer of Terminal & SSH
23-11-14 19:17:48 WARNING (MainThread) [supervisor.addons.validate] Add-on config using incompatible map options, 'addon_config' and 'homeassistant_config' are ignored if 'config' is included. Please report this to the maintainer of Advanced SSH & Web Terminal
23-11-14 19:17:49 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/vscode/aarch64 with version 5.14.2
```

### Anything in the Host logs that might be useful for us?

```txt
Nov 13 14:36:43 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.q7VxFu.mount: Deactivated successfully.
Nov 13 14:37:13 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.SPxQZS.mount: Deactivated successfully.
Nov 13 14:37:44 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-e26355befd6fd5a0f339ce17c8210ceb5b4f338f6f88fe71d0b3869b8acfa757-runc.b9y157.mount: Deactivated successfully.
```

## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1341
Downloaded Repositories | 14
HACS Data | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 916.9 GB
disk_used | 100.0 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), ESPHome (2023.10.6), File editor (5.6.0), Home Assistant Google Drive Backup (0.111.1), Mosquitto broker (6.3.1), SQLite Web (3.10.0), Studio Code Server (5.14.2), Terminal & SSH (9.8.0), Vaultwarden (Bitwarden) (0.20.1), chrony (2.6.2), Advanced SSH & Web Terminal (16.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 5
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 5, 2023 at 09:44
-- | --
current_recorder_run | November 13, 2023 at 20:22
estimated_db_size | 1105.08 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

using the add-on you won't notice this issue, but sometimes the system "hangs" for a couple of seconds

**Comment by sairon** [comment]
This isn't about the add-on being deactivated, AFAIK these messages are caused by the Docker healthcheck and are harmless. We might consider silencing them because they just cause confusion but they're not the source of the issues you're seeing.
