### ISSUE TITLE
Network Manager fails to load

### ISSUE THREAD

**Issue by GitFixed** [home-assistant/operating-system#2938]
### Describe the issue you are experiencing

using standard HA OS install (ver 11.1), boot on RPi reports the Network Manager failing to load. It surfaces in the HA CLI rather than some version of the Pi OS (I have installed OS on multiple PIs w/o HA). Don’t see how to to push along the install. Google has examples of a related error, but most seem for VM/Docker installs and are beyond my experience level. How to get pass this? Flashed SD on my Mac with RPi Imager with no observable problems.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

11.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. flashed from HA OS as above with RPi Imager on Mac
2. booted on RPi 4B with wired internet connection
3. errors and boot resiulting in CLI as above
...

### Anything in the Supervisor logs that might be useful for us?

```txt
?
```

### Anything in the Host logs that might be useful for us?

```txt
?
```

**Comment by sairon** [comment]
Do you end up with a HA shell in the end? If so, could you please get the output of `systemctl status -n50 NetworkManager` (after entering `login` first)? If not, please share any sort of logs, at least taken with a camera.

**Comment by GitFixed** [comment]
I have an “HA >” prompt that doesn’t take a systemcli command

**Comment by sairon** [comment]
You must enter `login` first, it will take you to the OS shell, then `systemctl` should work.

**Comment by GitFixed** [comment]
the ‘login’ brought me to a ‘#’ prompt. The systemctl status -ns0 returned ‘Unit ns0 could not be found'

**Comment by sairon** [comment]
That's expected, because it's a wrong command :sweat_smile: Once again, the command should be:
```
systemctl status -n50 NetworkManager
```
It will produce quite a bit of text, so taking a photo of the output would be maybe the best option.

**Comment by GitFixed** [comment]
updated cmd results in:

Unit NetworkManager.service could not be found.

**Comment by GitFixed** [comment]
issue closed. Caused by a network connectivity problem.
