### ISSUE TITLE
After update to 11.2 KNXD Add On on /dev/ttyAMA0 stopped working

### ISSUE THREAD

**Issue by TravisWilder** [home-assistant/operating-system#2966]
### Describe the issue you are experiencing

Raspberry PI4
The KNX Serial Adapter is on GPIO and using /dev/ttyAMA0
After update to OS 11.2 KNXD add on fails to connect

### What operating system image do you use?

rpi-64

### What version of Home Assistant Operating System is installed?

11.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

upgrade to 11.2 & reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
did not found any usefull information
```

### Anything in the Host logs that might be useful for us?

```txt
Dec 05 13:01:39 homeassistant kernel: ttyAMA ttyAMA0: 1 input overrun(s)
Dec 05 13:01:46 homeassistant kernel: ttyAMA ttyAMA0: 1 input overrun(s)
Dec 05 13:02:21 homeassistant systemd[1]: serial-getty@ttyAMA0.service: Deactivated successfully.
Dec 05 13:02:22 homeassistant systemd[1]: serial-getty@ttyAMA0.service: Scheduled restart job, restart counter is at 77.
Dec 05 13:02:22 homeassistant systemd[1]: Stopped Serial Getty on ttyAMA0.
Dec 05 13:02:22 homeassistant systemd[1]: Started Serial Getty on ttyAMA0.
```

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4849
Installed Version | 1.33.0
Stage | running
Available Repositories | 1348
Downloaded Repositories | 22

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 24.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), InfluxDB (4.8.0), Node-RED (16.0.2), Terminal & SSH (9.8.1), Samba share (12.2.0), MariaDB (2.6.1), Let's Encrypt (5.0.3), KNXD daemon (0.4.7), Studio Code Server (5.14.2), Mosquitto broker (6.4.0), ESPHome (2023.11.6), phpMyAdmin (0.8.9), AdGuard Home (4.8.17)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 13
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. November 2023 um 08:20
-- | --
current_recorder_run | 5. Dezember 2023 um 13:31
estimated_db_size | 1622.16 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by agners** [comment]
> generic-x86-64 (Generic UEFI capable x86-64 systems)

That hardly seems correct.

What Raspberry Pi image are you using? 32-bit or 64-bit?

Did you adjust `config.txt` on your system?

**Comment by sairon** [comment]
Also please check the contents of `cmdline.txt`, as it was the culprit in #2941.

**Comment by adrianrdzv** [comment]
My Zigbee shield on /dev/ttyAMA0 also stopped working when I upgraded to 11.2
Downgrading to 11.1 fixed the issue. Will wait to see if there is anything discovered.

**Comment by sairon** [comment]
@adrianrdzv Can you please also share your `config.txt` and `cmdline.txt`?

**Comment by TravisWilder** [comment]
cmdline.txt: 
`dwc_otg.lpm_enable=0 `

config.txt
`# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# HAOS - don't change it!
disable_splash=1
kernel=u-boot.bin

# uncomment for aarch64 bit support
arm_64bit=1

# uncomment to enable primary UART console
#enable_uart=1

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

# Uncomment to disable continous SD-card poll (for USB SSD)
#dtparam=sd_poll_once=on

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Uncomment this to enable GPIO support for RPI-RF-MOD/HM-MOD-RPI-PCB
enable_uart=1
#dtparam=i2c_arm=on
dtoverlay=miniuart-bt
#dtoverlay=rpi-rf-mod

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[all]
#dtoverlay=vc4-fkms-v3d
#max_framebuffers=2
`

**Comment by TravisWilder** [comment]
> Also please check the contents of `cmdline.txt`, as it was the culprit in #2941.

adding console=tty1 fixed it now for me

**Comment by adrianrdzv** [comment]
In my case I didn't have the line, I added it but still no luck.
```
dwc_otg.lpm_enable=0
console=tty1
```
and
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# HassOS - don't change it!
disable_splash=1
kernel=u-boot.bin

# uncomment for aarch64 bit support
#arm_64bit=1

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[all]
#dtoverlay=vc4-fkms-v3d
#max_framebuffers=2

enable_uart=1
dtoverlay=pi3-miniuart-bt
```

**Comment by TravisWilder** [comment]
> In my case I didn't have the line, I added it but still no luck.
> 
> ```
> dwc_otg.lpm_enable=0
> console=tty1
> ```

afaik this needs to be on the same line so 
```
dwc_otg.lpm_enable=0 console=tty1
```

**Comment by adrianrdzv** [comment]
@TravisWilder You were right, after moving the line to the same line and upgrading HA OS everything works as usual.
Thanks a lot.

**Comment by KNXBroker** [comment]
Not sure but it seems my skyconnect stick stopped working as well after 11.2 upgrade.

**Comment by mnorrsken** [comment]
Same here on Odroid N2. My Conbee II stopped working, rolled back to 11.1. Will maybe test another port and 11.2 if its OTG issue. Odroid N2 dont have the same boot params afaik so cant use same fix.

**Comment by ScubaJonL** [comment]
> As far as I'm concerned, the removal of this option goes back to the installation of the POPP ZB-Shield. The installation instructions indicated a conflict with the Serial Console. https://popp.eu/wp-content/uploads/2021/05/EN_POPP_ZB-Shield_with_HA-1.pdf Adding the option solved the problem, thanks.

Same here - I installed Elelabs Zigbee Raspberry Pi Shield into OS 5.10 in July '21. My notes from the install say
"for EleLabs Zigbee Shield, remove "console=tty1" from CMDLINE.TXT on image SD"
but I can no longer find that in the current Elelabs documents online.

**Comment by Vegardbeider** [comment]
> Same here - I installed Elelabs Zigbee Raspberry Pi Shield into OS 5.10 in July '21. My notes from the install say "for EleLabs Zigbee Shield, remove "console=tty1" from CMDLINE.TXT on image SD" but I can no longer find that in the current Elelabs documents online.

Hi @ScubaJonL, did you resolve your issue? I also have the Elelabs Zigbee RPi Shield and I updated yesterday to the newest version and since not able to get the Elelabs Zigbee Shield to communicate with HA.

**Comment by Vegardbeider** [comment]
@adrianrdzv My bad. Miss read the comment, must have been reading too much the last day for the upcoming exams. However, I still can't get it to work. Should I add back the console=tty1? I recall removing it when I installed the shield. And I am on the Raspberry Pi 4, shouldn't it be able to have Bluetooth enabled? I don't need Bluetooth, so I can disable it if that will make it work. 

I am using Path: /dev/ttyS0 and Port Speed: 115200. What should data flow control be? I have tried both hardware, software and the blank option. 
I have tried disabling BT and add back console=tty1. 

Here are my files content. Have I overseen something?

cmdline.txt:
```
dwc_otg.lpm_enable=0 console=tty1 usb-storage.quirks=174c:55aa:u,2109:0715:u,152d:0578:u,152d:0579:u,152d:1561:u,174c:0829:u,14b0:0206:u,174c:225c:u
```

config.txt:
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# HAOS - don't change it!
disable_splash=1
kernel=u-boot.bin

# uncomment for aarch64 bit support
arm_64bit=1

# uncomment to enable primary UART console
#enable_uart=1

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

# Uncomment to disable continous SD-card poll (for USB SSD)
#dtparam=sd_poll_once=on

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Uncomment this to enable GPIO support for RPI-RF-MOD/HM-MOD-RPI-PCB
#enable_uart=1
#dtparam=i2c_arm=on
#dtoverlay=miniuart-bt
#dtoverlay=rpi-rf-mod

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
# Enable boost from 1.5Ghz to 1.8Ghz on compatible models
arm_boost=1

[all]
#dtoverlay=vc4-fkms-v3d
#max_framebuffers=2

enable_uart=1
#dtoverlay-pi3-miniuart-bt
dtoverlay=disable-bt
```

**Comment by Gustra** [comment]
I am running hassio on an RPi3 with 3 USB devices attached (Z-wave ZMEEUZB1, ConBee and Tellstick DUO), and can confirm that upgrading to 11.2 causes the ZMEEUAZB1 (as device /dev/ttyAMAC0) to no longer be available. Downgrading to 11.1 makes it available again.

**Comment by Vegardbeider** [comment]
Downgrading to 11.1 was the solution I went with as well.

**Comment by colas-sebastien** [comment]
I have a similar issue.
I am using ZHA with PiZiGate+ v2 connected on /dev/serial0
after the update ZHA refused to start:

>  Logger: homeassistant.config_entries
> Source: config_entries.py:402
> First occurred: 16:59:13 (1 occurrences)
> Last logged: 16:59:13
> Error setting up entry /dev/serial0 for zha

I tried to modify the cmdline.txt to add `console=tty1` without success.

Workaround: Downgrade to 11.1

**Comment by colas-sebastien** [comment]
The update to the release 11.3 HAOS does not solve the issue.
Workaround: Downgrade to 11.1

**Comment by colas-sebastien** [comment]
I compared my file 11.1 and 11.3 there are exactly the same:

my `/mnt/boot/cmdline.txt`

```
dwc_otg.lpm_enable=0 usb-storage.quirks=174c:55aa:u,2109:0715:u,152d:0578:u,152d:0579:u,152d:1561:u,174c:0829:u,14b0:0206:u,174c:225c:u
```
my `/mnt/boot/config.txt`

```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# HAOS - don't change it!
disable_splash=1
kernel=u-boot.bin

# uncomment for aarch64 bit support
arm_64bit=1

# uncomment to enable primary UART console
enable_uart=1

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

# Uncomment to disable continous SD-card poll (for USB SSD)
#dtparam=sd_poll_once=on

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Uncomment this to enable GPIO support for RPI-RF-MOD/HM-MOD-RPI-PCB
#enable_uart=1
#dtparam=i2c_arm=on
#dtoverlay=miniuart-bt
#dtoverlay=rpi-rf-mod

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
# Enable boost from 1.5Ghz to 1.8Ghz on compatible models
arm_boost=1

[all]
#dtoverlay=vc4-fkms-v3d
#max_framebuffers=2
```

**Comment by abmantis** [comment]
Can confirm the same problem with a Aeotec Zwave stick on OS 11.4. Downgrading to OS 11.1 fixes it.

**Comment by colas-sebastien** [comment]
I am able to make it work with the version Home Assistant OS 11.5 !!! 
I am using RPi4
Here is the procedure:

1. ssh you RPi
2. Access to the host file system:
`docker run --privileged --pid=host -it alpine:latest nsenter -t 1 -m -u -n -i sh`
3. Edit boot.cmd file
`vi /mnt/boot/cmdline.txt`
4. add the following parameter:
`console=tty1`
5. Reboot

**Comment by dzungpv** [comment]
> I am able to make it work with the version Home Assistant OS 11.5 !!! I am using RPi4 Here is the procedure:
> 
>     1. ssh you RPi
> 
>     2. Access to the host file system:
>        `docker run --privileged --pid=host -it alpine:latest nsenter -t 1 -m -u -n -i sh`
> 
>     3. Edit boot.cmd file
>        `vi /mnt/boot/cmdline.txt`
> 
>     4. add the following parameter:
>        `console=tty1`
> 
>     5. Reboot

I have them same problem with 13.2, your method does not work, anyone have any solution?  Seem that the tty not disable and send data to UART0

**Comment by dzungpv** [comment]
@TravisWilder Do you running 13.2 and it still working?
