### ISSUE TITLE
No wifi driver for RTL8852BE

### ISSUE THREAD

**Issue by parisisal** [home-assistant/operating-system#2974]
### Describe the issue you are experiencing

Home Assistant OS appears to be missing wifi support for on-board wireless card RTL8852BE.
I am using a miniPC (Telcast N20 Mini PC) and i installed the ISO following the guide :https://www.home-assistant.io/installation/generic-x86-64

No wifi card detected.
I think there is a driver missing for this chip. 
Could you include this driver in the next image?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.1.63-haos

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Just start the system

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

## System Information

version | core-2023.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4946
Installed Version | 1.33.0
Stage | running
Available Repositories | 1349
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 468.7 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Mosquitto broker (6.4.0), Samba share (12.2.0), Advanced SSH & Web Terminal (17.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 dicembre 2023 alle ore 12:58
-- | --
current_recorder_run | 9 dicembre 2023 alle ore 14:07
estimated_db_size | 0.26 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

LAN wireless Realtek RTL8852BE × 1
Support IEEE 802.11a/b/g/n/ac, 2,4 GHz+5 GHz
Bluetooth 5

**Comment by sairon** [comment]
After #3003 is merged, both driver and firmware should be available in HAOS.
