### ISSUE TITLE
Every boot has a 91 second "Wait until kernel time synchronized" timer

### ISSUE THREAD

**Issue by FusselTV** [home-assistant/operating-system#2976]
### Describe the issue you are experiencing

I am unsure if it is correct to post this issue here. My setup is the haos_ova-10.2.vmdk on Unraid, and every time I reboot, I get this for 91 seconds. There is an easy fix ([link](https://github.com/systemd/systemd/issues/15031)). Would it be possible to apply this?
![image](https://github.com/home-assistant/operating-system/assets/89834718/4c4cda84-9c78-4c99-82aa-720dc849cf1e)

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.1.63-haos

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

just reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
nope
```

### Anything in the Host logs that might be useful for us?

```txt
nope
```

**Comment by sairon** [comment]
Once the system boots, can you enter `login` to enter the OS console and check what `systemctl status systemd-timesyncd.service` reports? There is likely some issue with NTP sync in your environment, disabling the service mentioned in the ticket would not help, as it could lead to another problems in general.

**Comment by FusselTV** [comment]
This is my output 192.168.178.20 is the ip of my homeassistant any idea how to fix the problem?
![image](https://github.com/home-assistant/operating-system/assets/89834718/85fd84e7-c881-49ef-a355-1ece3f288af4)

**Comment by PieterHattinghZA** [comment]
I have the same issue

**Comment by Xornop** [comment]
I have the same issue, however my log does say "timed out waiting for reply from ..... (time.cloudflare.com)"

**Comment by fawzy46** [comment]
same issue here

**Comment by NoobOnTour024** [comment]
same

**Comment by kahoch** [comment]
same

**Comment by 0anton** [comment]
same

**Comment by bigruid** [comment]
Change the ntp server in this file
/etc/systemd/timesyncd.conf
