### ISSUE TITLE
Kernel configs for VM images are missing useful settings

### ISSUE THREAD

**Issue by Skirmisher** [home-assistant/operating-system#2987]
### Describe the issue you are experiencing

A follow-on to #2909 in a sense—here's a couple kernel switches I noticed were lacking when setting up HAOS in libvirt, which would make sense to turn on (as modules) for VM-enabled configurations.

- `CONFIG_VIRTIO_MEM` – [virtio-mem](https://virtio-mem.gitlab.io/) allows for growing and shrinking VM memory allocation at runtime, in cooperation with the guest. It could be seen as an advanced successor to virtio-balloon, with true memory hot(un)plug that's far more flexible. Seems useful for experimenting with addons (one of the main motivations to run HAOS in a VM, I think!).
- `CONFIG_DMI_SYSFS` (and/or `CONFIG_FW_CFG_SYSFS`) – Enables userspace access to SMBIOS tables (and, respectively, QEMU's `fw_cfg` user-defined values). Of interest is the SMBIOS Type 11 "OEM Strings" structure, which VMMs these days are using as a place for admins to provide arbitrary data to guests. systemd, as of v252, will read values for its [credentials](https://systemd.io/CREDENTIALS) from here to pass to services that request them; some [settings](https://www.freedesktop.org/software/systemd/man/latest/systemd.system-credentials.html) which HAOS admins might want to configure include `network.hosts` and `ssh.authorized_keys.root` (these are handled by `systemd-tmpfiles-setup.service`, which runs after `local-fs.target` is reached, so the `hassos-bind.target` mounts will already be set up at that point).
  - (systemd also reads credentials from `fw_cfg`, and has supported it for longer. However, it has several limitations and is QEMU-specific, so using it seems to be discouraged now, hence the "and/or". But on the other hand, throwing the module in only costs a couple dozen KiB uncompressed...)

### What operating system image do you use?

generic-aarch64 (Generic UEFI capable aarch64 systems)

### What version of Home Assistant Operating System is installed?

11.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. [Set up `virtio-mem` in libvirt](https://virtio-mem.gitlab.io/user-guide/user-guide-libvirt.html) for your HAOS VM
2. Realize you forgot to check if the guest kernel is even configured for it
3. Be sad when `zcat /proc/config.gz | grep CONFIG_VIRTIO_MEM` prints `# CONFIG_VIRTIO_MEM is not set`

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by agners** [comment]
> ssh.authorized_keys.root (these are handled by systemd-tmpfiles-setup.service

I wonder if this will be working out of-the-box with HAOS :thinking: If not, would be nice to get it to work.
