### ISSUE TITLE
Unable to assign a specific IP address to Home Assistant Yellow with Google Wifi (either through DHCP reservation or Static IP)

### ISSUE THREAD

**Issue by ZainAjam** [home-assistant/operating-system#3024]
### **STATIC IP address PROBLEM:**

I have been using a raspberry pi 4 for years now with Home Assistant OS running on it, and I have always had a problem when setting Home Assistant OS on the pi with a static IP address. The problem is that when I have a static IP address set in Home Assistant OS, then the device does not show up in my list of network devices in the Google Home app. Without seeing it on the list of network devices, I'm unable to select it for port forwarding, and I'm therefore not able to access the Home Assistant instance outside of my house. I should mention that I am able to access Home Assistant on the static IP address on my browser, but I just don't see it in the Google Home app for port forwarding purposes. This seems to only happen with Home Assistant devices. My other static IP address devices show up fine. So I've resorted to using DHCP reservation to get the assigned IP address. This is how I've been using home assistant on Pi4 for years now. The static IP address matter is still an issue, but I've lived with the workaround.

### **DHCP reservation PROBLEM:**

Now I've upgraded to Home Assistant Yellow, and it also has the static IP address problem but now it ALSO is not respecting the DHCP reservation I've set up for it in Google Home app. It just picks a random IP address instead of using the IP address I reserved for it.

### **COULD IT BE GOOGLE WIFI**

I considered that the problem may be with Google Wifi, however I factory reset Google Wifi while leaving Home Assistant as static ip address, and when Google Wifi was back up and running, I still could not see the Home Assistant instance for Yellow, and after changing to DHCP for Home Assistant Yellow, it still disrespected my DHCP reservation and just grabbed a random IP address. Not sure if it matters or not, but I'm using Google Wifi Gen 1

### **WHAT I HAD TO DO**

Due to both of the above problems, I've had to revert back to using RPI4 with Auto IP and using DHCP reservation on Google Wifi. It is the only combination that works for me.

### **SUMMARY** 

**Home Assistant OS on RPI4:** Auto IP with router DHCP Reservation works; Static IP works, but Yellow is not visible in Google Home app and can therefore not be port forwarded for external access

**Home Assistant OS on Home Assistant Yellow**: Auto IP with router DHCP Reservation does not work. Yellow grabs a random IP address instead of the IP address reserved for it; Static IP works, but Yellow is not visible in Google Home app and can therefore not be port forwarded for external access.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 11.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

See description of issue

### Anything in the Supervisor logs that might be useful for us?

```txt
Don't know if the logs will have anything specific to this issue. I will need guidance on where to look
```

### Anything in the Host logs that might be useful for us?

```txt
Don't know if the logs will have anything specific to this issue. I will need guidance on where to look
```

## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Africa/Johannesburg
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4744
Installed Version | 1.33.0
Stage | running
Available Repositories | 1370
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 27, 2024 at 02:00
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-8.ui.nabu.casa
certificate_status | ready
instance_id | 56cc0765d36842e3aa95fa9fe977cd83
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 16.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.105.2), AdGuard Home (5.0.1), MariaDB (2.6.1), NGINX Home Assistant SSL proxy (3.6.0), Terminal & SSH (9.8.1), Mosquitto broker (6.4.0), Nginx Proxy Manager (0.12.3), Matter Server (5.0.1), WireGuard (0.10.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 52
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 21, 2023 at 10:19
-- | --
current_recorder_run | December 29, 2023 at 13:56
estimated_db_size | 394.93 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 43 / 47
local_online | 38 / 38
debug | failed to load: 

</details>

**Comment by agners** [comment]
Home Assistant OS uses NetworkManager under the hood, which is a pretty standard network manager in Linux environments. Do you have other Linux based systems? Do they behave abnormally too?

Can you check the network manager logs using `ha host logs --identifier=NetworkManager`.

Do you use WiFi or Ethernet? We strongly recommend Ethernet, however, WiFi should work as well.
