### ISSUE TITLE
OS not booting on RasPi 4 after update

### ISSUE THREAD

**Issue by lennartschulte** [home-assistant/operating-system#3042]
### Describe the issue you are experiencing

I got more or less the same issue like in this Report: https://github.com/home-assistant/operating-system/issues/3025

Only difference for me is the Hardware. For me it is not booting anymore after the update. With SD card and monitor attached i just got a black screen. without it shows the RasPi bootloader screen.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

Cannot get the system to start and therefore it might be the current version or the version before

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Update to current OS on RasPi 4

### Anything in the Supervisor logs that might be useful for us?

```txt
no access due to not booting
```

### Anything in the Host logs that might be useful for us?

```txt
no access due to not booting
```

**Comment by cookie050** [comment]
Is this from 11.2 to 11.3?

**Comment by lesgrebe** [comment]
Hello,

+1. 

After Update to 11.3 my Raspi4 8GB didn't boot (I was waiting 30min). So I disconnected the power supply and I "killed" my Database but after that my Raspi4 did boot and Hass was alive. I restored from a Backup and never tried a reboot again. Strangley my System is up to date (see Screenshot) 🤷🏼‍♂️.

![image](https://github.com/home-assistant/operating-system/assets/37287548/d6b660d8-7759-4318-9c5c-3e2d7a4c2dae)

Regards
Michi

**Comment by lesgrebe** [comment]
Hello,

+1. 

After Update to 11.3 my Raspi4 8GB didn't boot (I was waiting 30min). So I disconnected the power supply and I "killed" my Database but after that my Raspi4 did boot and Hass was alive. I restored from a Backup and never tried a reboot again. Strangley my System is up to date (see Screenshot) 🤷🏼‍♂️.

![image](https://github.com/home-assistant/operating-system/assets/37287548/d6b660d8-7759-4318-9c5c-3e2d7a4c2dae)

Regards
Michi

**Comment by agners** [comment]
@lennartschulte do you use a USB SSD as well?

It sounds like a corrupted boot partition (first partition on the SD card). You can try to rescue it by coping the files of the first partition from a new installation (on a second SD card).

**Comment by cookie050** [comment]
I updated to 11.3 from 11.2, had no issues. 

First installed core update to 2024.1.2 and then maked a full backup (just in case). After this i updated and restart worked. 

HA os on a rpi4-64 9 on sd card (still need to upgrade to ssd, go it in house but still need to do it)

**Comment by cookie050** [comment]
I updated to 11.3 from 11.2, had no issues. 

First installed core update to 2024.1.2 and then maked a full backup (just in case). After this i updated and restart worked. 

HA os on a rpi4-64 9 on sd card (still need to upgrade to ssd, go it in house but still need to do it)
![Screenshot_2024-01-07-11-22-54-622_io homeassistant companion android-edit](https://github.com/home-assistant/operating-system/assets/17346927/c3fd5486-9148-4422-8f56-14e7f9c8274e)

**Comment by inverse** [comment]
Just to confirm I upgraded from 11.2 -> 11.3 without any issues.

My setup is USB SSD and had no issues on a Pi4 8gb

**Comment by GundosLV84** [comment]
Have same issue on Raspberry PI 5 8GB, had 11.3rc1, was working fine. After update to 11.3 partitions get corrupted if I run "reboot" command, tried with reinstalling on SD card and USB disk.

**Comment by nswint** [comment]
> Have same issue on Raspberry PI 5 8GB, had 11.3rc1, was working fine. After update to 11.3 partitions get corrupted if I run "reboot" command, tried with reinstalling on SD card and USB disk.

Same here with a Raspberry PI 5 8GB, 11.3rc1 worked fine.  I happened to check after like 2 hours and I heard the cpu far at full power, ethernet light went off went off on the switch, fans stopped for a few seconds and then started again.  I didn’t have a monitor connected but looks like it was in a boot loop.

**Comment by GundosLV84** [comment]
It might be related to update process, same happens when update 11.3rc1 to 11.4. Performed clean installation of 11.4 and then restored data from backup, looks to be working fine in that case.

**Comment by lennartschulte** [comment]
Sorry for not responding for such a long time. I was pretty ill the last days. I ended up making a complete new installation on another SD card (which I also wanted to do for some time) and restoring a backup. As my database is on an external server, I just lost the data for the time the system was not running. The last update on 11.4 worked fine for me without any issue. 

So for my end this topic/issue can be closed, but it seems that there are similar issues in this topic for others as well. Perhaps they can get their issues solved here.
