### ISSUE TITLE
Create Partial Backup service call not working properly with slug names that have hyphen

### ISSUE THREAD

**Issue by ovargasp** [home-assistant/operating-system#3055]
### Describe the issue you are experiencing

Create Partial Backup service fails with addons slug names that has a hyphen on it's name. You can call the service with most addons slug names and it works. I have the crowdsec-firewall-bouncer and the uptime-kuma addons slug names are: 424ccef4_crowdsec-firewall-bouncer and a0d7b954_uptime-kuma, and as soon as I try to use those slug names I get an error that says for example to change it to this “424ccef4_crowdsec_firewall_bouncer” and try again… If I do that, I don’t get the error but I also get an empty backup…

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

11.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. create new automation
2. go to section then do...
3. Add an action: call service "Home Assistant Supervisor: Create a partial backup."
4. add addons slug names to the list with hyphen in its name (crowdsec-firewall-bouncer and uptime-kuma are examples of it)
5. save and run the automation it will fail.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | America/Costa_Rica
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1372
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 10.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Terminal & SSH (9.8.1), chrony (3.0.1), WireGuard (0.10.2), Duck DNS (1.15.0), Log Viewer (0.17.0), Portainer (2.0.0), AdGuard Home (5.0.2), Advanced SSH & Web Terminal (17.0.2), DSS VoIP Notifier (4.0.0), Mosquitto broker (6.4.0), Crowdsec (1.5.4), Crowdsec Firewall Bouncer (v0.0.28), Grocy (0.21.0), Vaultwarden (Bitwarden) (0.21.0), Uptime Kuma (0.12.0), Frigate (0.12.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 14, 2023 at 1:51 AM
-- | --
current_recorder_run | January 6, 2024 at 8:27 AM
estimated_db_size | 709.23 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 23 / 27
local_online | 16 / 16
debug | failed to load: 

</details>

### Additional information

I opened a Topic in forums that explains what I did and it ended up in a recommendation to open an issue, here is the link to it [https://community.home-assistant.io/t/problems-with-proper-addon-names-while-using-the-create-partial-backup-service/668933](https://community.home-assistant.io/t/problems-with-proper-addon-names-while-using-the-create-partial-backup-service/668933) 
First I thought it was a wrong slug name issue, but it seems there is something else to the slug names that is not working, because I can use the same slug name that is failing in the Partial Backup to run a addon restart service call and it works.

I can create a partial backup from settings->system->backups, selecting the addons from the list including those two, but if I try to use the service call with the slug names it fails. there is nothing in the logs that can be used.

This is the service call code in YAML that works (removing the 2 addons with hyphen in names):

service: hassio.backup_partial
data:
  homeassistant_exclude_database: false
  compressed: true
  homeassistant: true
  location: HABackups
  folders:
    - homeassistant
    - share
    - ssl
  name: Partial HA-Main {year}-{month}-{day} {hr24}:{min}:{sec}
  addons:
    - core_samba
    - core_configurator
    - core_ssh
    - a0d7b954_chrony
    - a0d7b954_wireguard
    - core_duckdns
    - a0d7b954_logviewer
    - a0d7b954_portainer
    - a0d7b954_adguard
    - a0d7b954_ssh
    - 89275b70_dss_voip
    - core_mosquitto
    - 424ccef4_crowdsec
    - ccab4aaf_frigate

and this one fails

service: hassio.backup_partial
data:
  homeassistant_exclude_database: false
  compressed: true
  homeassistant: true
  location: HABackups
  folders:
    - homeassistant
    - share
    - ssl
  name: Partial HA-Main {year}-{month}-{day} {hr24}:{min}:{sec}
  addons:
    - core_samba
    - core_configurator
    - core_ssh
    - a0d7b954_chrony
    - a0d7b954_wireguard
    - core_duckdns
    - a0d7b954_logviewer
    - a0d7b954_portainer
    - a0d7b954_adguard
    - a0d7b954_ssh
    - 89275b70_dss_voip
    - core_mosquitto
    - 424ccef4_crowdsec
    - 424ccef4_crowdsec-firewall-bouncer
    - a0d7b954_uptime-kuma
    - ccab4aaf_frigate

**Comment by sairon** [comment]
The message is coming from validations in Core and is unrelated to HA Operating System, please file the issue there.
