### ISSUE TITLE
Unable to restore Raspberry Pi 5 from backup

### ISSUE THREAD

**Issue by acibo** [home-assistant/operating-system#3073]
### Describe the issue you are experiencing

After upgrading to 11.4 on 01/02/24 and rebooting I got stuck in the boot loop situation that has already been reported.  In past updates when this has occurred I reflashed the SD card with the latest Pi5 image and when presented with the option, used the "Restore" from the full backup I took before rebooting.  This has always worked, until now.  Now when I select Restore, provide the backup file name, and confirm I want a restore of the full backup, it spins as if restoring but nothing happens.  After 2 days I tried reflashing and doing again, same results.  I can connect to the Pi5 at its IP address, but it brings me to the "Welcome" page.  Any suggestions?

### What operating system image do you use?

rpi5-64  (Raspberry Pi 5 64-bit OS)

### What version of Home Assistant Operating System is installed?

11.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgraded to 11.4 from 11.3
2. Rebooted - stuck in reboot loop
3. Reflashed SD card w/ latest 11.4 from HAOS site
4. Booted RPi5
5. Set wifi network info
6. ha supervisor options --channel=beta  (as it was prior to rebooting)
7. ha supervisor reload
8. ha supervisor update
9. exit
10. Connected to IP of RPi5, which brought me to /onboarding.html page
11. Selected "Restore from Backup"
12. Selected "Upload Backup"
13. Selected backup .tar file from local PC and clicked "Open"
14. RPi5 goes to /onboarding.html?page=restore_backup
15. Pop-up presented with description of backup displayed, with "Full backup" radio button highlighte
16. Clicked "Restore"
17. Pop-up presented with warning that full system will be wiped and the backup restored - clicked "Restore"
18. "Restore in progress" presented in window, with spinning circle.  This goes on infinitely
19. If I close the browser and come from another browser, or a mobile device, they all come back to the /onboarding page.  It appears as if nothing on the SD card has been updated from the backup file.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Not available
```

### Anything in the Host logs that might be useful for us?

```txt
Not available
```

### System information

Not available

**Comment by Baxxy13** [comment]
You could read here... https://github.com/home-assistant/supervisor/issues/4806#issuecomment-1890910500

**Comment by user86000** [comment]
go to welcome screen and set username and password
if you now restore the backup error mesage supervisor older version appears..

set update to beta channel and update supervisor
restore backup successful

the only problem is the restore backup on first setup does not create an error message if supervisor is to old
