### ISSUE TITLE
rpi5: `overlay_prefix` required in `config.txt` for dtoverlay support

### ISSUE THREAD

**Issue by jens-maus** [home-assistant/operating-system#3079]
### Describe the issue you are experiencing

Due to the changed bootloading chain in the current RaspberryPi5 support it seems loading device tree overlays specified in the `/mnt/boot/config.txt` bootloader config file seems to be broken at the moment.

Even thought the documentation on the tryboot functionality in the RaspberryPi bootloader states that `os_prefix` is added to the existing `overlay_prefix` option (default: `overlays/`), this seems to be NOT the case at the moment (cf. https://www.raspberrypi.com/documentation/computers/config_txt.html#overlay_prefix)

This has become visible in the optional support for the `RPI-RF-MOD` Homematic RF module which requires to adapt the `/mnt/boot/config.txt` file, adding a `dtoverlay=rpi-rf-mod` statement to it. However, doing so in the current `config.txt` of the rpi5 version of HomeAssistantOS does not load the `rpi-rf-mod.dtbo` file. After looking at the output of the RaspberryPi bootloader one can see that the bootloader tries to load that dtoverlay, but fails:

<img width="433" alt="Bildschirmfoto 2024-01-16 um 10 11 56" src="https://github.com/home-assistant/operating-system/assets/5887769/35a7596f-37fa-4874-b43f-6d2b9f118290">

After adding the following additional (usually not required) `overlay_prefix` line to the `config.txt` file:

```
overlay_prefix=slot-A/overlays/
```

the bootloader can correctly load the `rpi-rf-mod.dtbo` (not the number of bytes mentioned in the rpi-rf-mod line):

<img width="426" alt="Bildschirmfoto 2024-01-16 um 10 13 46" src="https://github.com/home-assistant/operating-system/assets/5887769/21238f81-dd2a-44eb-a942-8089d85f6bbc">

Thus, it seems that with the tryboot functionality in place the stated `${os_prefix}${overlay_prefix}` prefixing (cf. https://www.raspberrypi.com/documentation/computers/config_txt.html#overlay_prefix) does not seem to be in place or work correctly in the context of HomeAssistantOS.

BTW: It can also be seen in the bootloader that it is also not able to load the `vc4-kms-v3d.dtbo` with the missing `overlay_prefix` line.

### What operating system image do you use?

RaspberryPi 5

### What version of Home Assistant Operating System is installed?

11.4

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. See that the bootloader is NOT loading the `vc4-kms-v3d.dtbo` dtoverlay
2. Add `overlay_prefix=slot-A/overlays/` to `config.txt`.
3. See that the bootloader is NOW able to load the `vc4-kms-v3d.dtbo` dtoverlay during bootup.

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### Anything in the Host logs that might be useful for us?

```txt
n/a
```

### System information

n/a

### Additional information

The issue has already been reported and investigated accordingly. See:

https://github.com/home-assistant/operating-system/discussions/3069
https://github.com/jens-maus/RaspberryMatic/discussions/2618

**Comment by agners** [comment]
> Even thought the documentation on the tryboot functionality in the RaspberryPi bootloader states that os_prefix is added to the existing overlay_prefix option (default: overlays/), this seems to be NOT the case at the moment (cf. https://www.raspberrypi.com/documentation/computers/config_txt.html#overlay_prefix)

So this is a bug in the Raspberry Pi firmware then right?

> The issue has already been reported and investigated accordingly. See:

Ah I see those are all our investigations.

Have you reported it upstream to the Raspberry Pi developers?

**Comment by sairon** [comment]
Not sure if we all missed it before or if it's been added recently, but the `overlay_prefix` now has a note in the docs:

> Unless `${os_prefix}${overlay_prefix}README` exists, overlays are shared with the main OS (i.e. `os_prefix` is ignored). 

I can confirm that adding an empty README file to the `overlays` directory does the trick, and overlays are then loaded fine. Kind of strange feature, but the fix is easy (and on the way).

**Comment by jens-maus** [comment]
> I can confirm that adding an empty README file to the `overlays` directory does the trick, and overlays are then loaded fine. Kind of strange feature, but the fix is easy (and on the way).

Really? This sounds indeed like a strange feature or side-effect. Can't be real that just adding an empty README fixes this issue. In fact, this might IMHO later end up in a potential regression in case someone else might think removing the README might be ok and then the issue appears again. Perhaps instead explicity adding `overlay_prefix=slot-A/overlays/` to the config.txt might be a better or more sustainable approach in the end?
