### ISSUE TITLE
Addon RuntimeError: This module can only be run on a Raspberry Pi!

### ISSUE THREAD

**Issue by gmoelter** [home-assistant/operating-system#3094]
### Describe the issue you are experiencing

The addon uses the RPi.GPIO module. RPi.GPIO checks the existence and contents of /proc/device-tree/system/linux,revision and /proc/cpuinfo. 
In HA OS 11.2, the /dev/cpuinfo file contains the necessary hardware and revision information. Since OS 11.3, however, information about hardware has been missing. That's why the hardware is not recognized as a Raspberry Pi.

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

11.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. docker exec -it myaddon-containerid sh
2. echo $(cat /proc/cpuinfo | grep "Hardware")
3. echo $(cat /proc/cpuinfo | grep "Revision")
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by sairon** [comment]
While the `Revision` is still present in `cpuinfo`, `Hardware` is not. This is the RPi's downstream Linux issue though, so it either needs to be fixed there, or the RPi.GPIO library needs to be update to be ready for that change. The string has been removed in [this commit](https://github.com/raspberrypi/linux/commit/e641fd7a50987ad6b7ce1ab36189bc8817295e42), so I guess the latter option is the correct one, as RPi developers think this record is misleading.
