### ISSUE TITLE
Can not boot HA in proxmox 8.1.4 after upgrade to 11.5.rc1

### ISSUE THREAD

**Issue by Rrapa** [home-assistant/operating-system#3112]
### Describe the issue you are experiencing

System stuck on boot with message Slot A (OK=1 TRY=1)
Restoring to previous version helps. 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

 11.5.rc1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade to new RC1 version

### Anything in the Supervisor logs that might be useful for us?

```txt
Not possible to access logs
```

### Anything in the Host logs that might be useful for us?

```txt
I'm on Proxmox 8.1.4

16 x Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz (1 Socket)
--
Kernel Version Linux 6.5.11-7-pve (2023-12-05T09:44Z)
Boot Mode EFI
Manager Version pve-manager/8.1.4
```

**Comment by AllardKatan** [comment]
I also experienced this error, but I am on Virtualbox instead of Proxmox.

**Comment by agners** [comment]
I was able to reproduce this, there seems to be a problem with the current OVA image.

You can either manually select the other boot slot, or reset the machine 4 times to let it fall back to the second boot slot. It then should boot again.

**Comment by agners** [comment]
Actually it seems the system boots it just doesn't display this on the console.

The release is currently no longer on the beta channel for the `ova` image.

**Comment by AllardKatan** [comment]
> I was able to reproduce this, there seems to be a problem with the current OVA image.
> 
> You can either manually select the other boot slot, or reset the machine 4 times to let it fall back to the second boot slot. It then should boot again.

Ah, thanks for that info. I had given up after three tries, plus a bunch of restart attempts from the snapshot taken after the first fail, and restored the backup of three days ago. Of course I should have made a snapshot before updating to a beta version but I was tired and not paying attention, I realized too late there is (of course) no automatic backup for OS updates like there is for regular updates.
I noticed that if you restart after manually selecting slot A, it will try slot A again, and fail. If I restart four times it will go to slot B, and restarting after that will automatically start from slot B.
If I can help to tackle this by supplying any log files let me know.

**Comment by Rrapa** [comment]
I have skipped that update but I may restor it in that case.. looks like was not patient enough but it was really confisuing.

**Comment by Igloczek** [comment]
Not sure if this is realted, but while upgrading to 11.5 my Proxmox VM went into some weird limbo state, reporintg "io-error" on HA VM, so I wasn't able to even kill it. 
After the whole Proxmox restart HA was alive, but still on 11.4 🤔
Tried two times, exact same results.

**Comment by Rrapa** [comment]
Works OK for me

**Comment by agners** [comment]
@Igloczek if that is reproducible for you, probably make sense to open a new issue.
