### ISSUE TITLE
Wifi drivers missing for RTL8273DU (Evolve III Maestro)

### ISSUE THREAD

**Issue by pierrehirschler** [home-assistant/operating-system#3131]
### Describe the issue you are experiencing

I've installed HAOS on an Evolve III Maestro. I tried both 11.4 and the dev build of 11.6 and the WiFi driver is not installed. From the information I can find online, the WiFi module is a RTL8723DU

The WiFi module does work with Ubuntu 23.

Please let me know if there's any other information I can provide that would be helpful!

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.6

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install HAOS from Ubuntu Live USB using Disks utility
3.nmcli radio shows WIFI-HW as missing
4.nmcli device wifi rescan shows "Error: No Wi-Fi device found."

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### System information

Can't access since I can't connect to home assistant, but the wifi module is the RTL8723DU

### Additional information

Apparently this is how you would install the drivers with a package manager based on this helpful [youtube video](https://www.youtube.com/watch?v=h8K2uDqU6po):

Commands to install new drivers (make sure secure boot is disabled):
sudo add-apt-repository ppa:kelebek333/kablosuz
sudo apt update
sudo apt install rtl8723du-dkms
(then restart)

**Comment by sairon** [comment]
There is no DKMS-like mechanism to install third-party drivers in HAOS, and we'd like to avoid using them in general, unless there is high demand for a particular driver. Thankfully, support for your card has been [added to upstream kernel in Linux v6.2](https://github.com/gregkh/linux/commit/87caeef032fc3921bc866ad7becb6ed51aa8b27b), so it should be available once we merge #3063 and enable newly added drivers.

**Comment by sairon** [comment]
@pierrehirschler Now that 12.0.rc1 is out, could you try it there, please? You don't need to switch to beta channel for that, you can only update OS from the CLI using `ha os update --version 12.0.rc1`.

**Comment by arripeo** [comment]
I know this type of bug, i got in the past the same problem than solved by an new OS release, so when I've seen that in 12.1 release they changed the driver of Wifi I've deiced to NOT UPDATE waiting for a new suitable release. So if you want, please vote my new feature request that cloud be, on my opinion, a strong solution for all these type of problem that are very common

https://community.home-assistant.io/t/interface-by-ui-or-cli-for-installing-wifi-propitary-driver-or-linux-compatible/716527
