### ISSUE TITLE
HAos forces gateway and dns setting on secondary nic

### ISSUE THREAD

**Issue by thplex48178** [home-assistant/operating-system#3135]
### Describe the issue you are experiencing

Haos with two nics forces me into a situation wher I have two default gateways resulting in asymmetric routing of traffic. 
The system is accessed by one ip and it tries to return on the other ip which causes the firewall to drop that traffic.

the only reason I have the scondary nic is because of mdns, media players. and some other plugins that just seem to run better this way.

This was no issue in my docker installation since I had control over the network, but it seems just harder and harder to stay up on a docker install vs HAos on a vm.

any way to not force the default gateway on every nic ?  thanks

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

6.1.71-haos

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1.
2.
3.
...
add second nic and try not to specify dns or default gw

### Anything in the Supervisor logs that might be useful for us?

```txt
na
```

### Anything in the Host logs that might be useful for us?

```txt
na
```

## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/Detroit
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1453
Downloaded Repositories | 22
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 10, 2025 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
instance_id | 42fad97479e6417794f77cf90df6c6fd
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 7.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Music Assistant BETA (2.0.0b90), Advanced SSH & Web Terminal (17.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 15
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 24, 2024 at 10:38 PM
-- | --
current_recorder_run | January 31, 2024 at 3:00 PM
estimated_db_size | 221.05 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by DocDrydenn** [comment]
+1
