### ISSUE TITLE
Intel NUC SD Card Reader doesn't work

### ISSUE THREAD

**Issue by YahyaAlfayad** [home-assistant/operating-system#3167]
### Describe the issue you are experiencing

I've updated to HA OS 11.3 which has [this fix](https://github.com/home-assistant/operating-system/issues/2688) but the issue still persist. I am using Intel NUC BOXNUC8i3BEK2.

The output of lspci command is:

<img width="1018" alt="lspci" src="https://github.com/home-assistant/operating-system/assets/5686018/ab74e310-be94-4dc3-aef7-ca00f54117da">

However, when I insert the SD card, nothing happens. No device added to `/dev` nor `/dev/disk/by-path` and nothing is logged in dmesg

According to [this](https://forums.gentoo.org/viewtopic-t-1093376-start-0.html), "MMC block device driver is also needed. Otherwise kernel recognizes the device but doesn't create a device to access it."

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

core-2024.2.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Run `ls /dev/disk/by-path`.
2. Insert SD card.
3. Run `ls /dev/disk/by-path` again.
4. SD Card is not recognised.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1388
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 234.0 GB
disk_used | 91.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | AirCast (4.2.0), Mosquitto broker (6.4.0), WireGuard Client (0.2.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.35.3-1), Filebrowser (2.23.0_12), ESPHome (2023.12.9), Whisper (1.0.2), openWakeWord (1.8.2), Music Assistant BETA (2.0.0b92), Advanced SSH & Web Terminal (17.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 1, 2024 at 11:16 AM
-- | --
current_recorder_run | February 9, 2024 at 10:20 PM
estimated_db_size | 668.06 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by sairon** [comment]
Thanks for reporting that, I've added the missing driver in the linked PR.
