### ISSUE TITLE
时区设置错误

### ISSUE THREAD

**Issue by XiaoXianNv-boot** [home-assistant/operating-system#3185]
### Describe the issue you are experiencing

在UI里面设置时区后,组件显示的时间存在问题
如:
将 时区 设置为 “(GMT+08:00) China Time - Beijing”
传感器日志显示，8 小时后
备份界面显示也是一样,图片中包括6小时后和7小时前

translation:
After setting the time zone in the UI, there is an issue with the time displayed by the component
example
Set the Time Zone to  “(GMT+08:00) China Time - Beijing”
Sensor log shows, after 8 hours
![捕获](https://github.com/home-assistant/operating-system/assets/76765956/4be67852-f73b-451d-9f66-dd865faf5685)
The backup screen shows the same, with pictures including 6 hours after and 7 hours ago

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 11.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.更改时区设置
2.重启主机
3.查看最新的传感器日志

translation:
1.Change the time zone setting
2.Restart the host
3.View the latest sensor logs

### Anything in the Supervisor logs that might be useful for us?

```txt
There is nothing needed
```

### Anything in the Host logs that might be useful for us?

```txt
There is nothing needed
```

## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 19.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.0), Assist Microphone (1.0.0), ESPHome (2023.11.6), Grafana (9.1.2), MariaDB (2.6.1), Mosquitto broker (6.4.0), Network UPS Tools (0.12.2), SQLite Web (4.1.2), Samba share (12.2.0), Studio Code Server (5.14.2), VLC (0.2.0), openWakeWord (1.8.2), jcm (1.0.6), phpMyAdmin (0.9.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2024年2月20日 00:14
-- | --
current_recorder_run | 2024年2月20日 10:02
estimated_db_size | 1.45 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Additional information

查看 “/etc/timezone”文件 发现 docker容器 “homeassistant” 时区已更改,但os 时区未更改

translation:
Looking at the "/etc/timezone" file, it was found that the docker container "homeassistant" time zone has changed, but the OS time zone has not

**Comment by jeffery-ljf** [comment]
请问最后是怎么解决的？
