### ISSUE TITLE
Stuck in kiosk mode

### ISSUE THREAD

**Issue by Manney74** [home-assistant/operating-system#3189]
### Describe the issue you are experiencing

Through testing and exploring I made the mistake of wrongfully setting the kiosk mode in the lovelace Yaml.
This results in being completely locked out of the UI of HA OS. I've looked trough the forum but none of the solutions work.
It can't be that something so simple can completely renders you HASS usesless right? I hope there is a solution to save the configurations and all and get back in control.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.6

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. set kiosk mode to "admin- setting" in stead of non-admin settings to hide header, menu and overflow
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Unable to reach this
```

### Anything in the Host logs that might be useful for us?

```txt
Unable to reach this
```

### System information

Unable to reach this

**Comment by sairon** [comment]
Sorry, this is not an OS issue. Please use community forums or Discord to seek for help.
