### ISSUE TITLE
CIFS mount issue: Cannot mount because it is not empty

### ISSUE THREAD

**Issue by Vaarlion** [home-assistant/operating-system#3192]
### Describe the issue you are experiencing

If for any reason a network mount point fail, Home assistant seam to don't know about it and keep backuping to the mount point folder.
This, later when the broken mount is raised, make it unsolvable with the following error:
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 21:12:20 (4 occurrences)
Last logged: 21:12:26

Failed to to call /mounts/Freenas_Backup - Cannot mount Freenas_Backup at /data/mounts/Freenas_Backup because it is not empty
```
Checking on the hassio_supervisor container in HA OS, i can confirm that some extra backup happened where the mount point is supposed to be.
``` bash
➜  ~ docker inspect -f '{{ .Mounts }}' hassio_supervisor 
[{bind  /run/docker.sock /run/docker.sock  rw true rprivate} {bind  /run/containerd/containerd.sock /run/containerd/containerd.sock  rw true rprivate} {bind  /run/systemd-journal-gatewayd.sock /run/systemd-journal-gatewayd.sock  rw true rprivate} {bind  /run/dbus /run/dbus  ro false rprivate} {bind  /run/supervisor /run/os  rw true rprivate} {bind  /run/udev /run/udev  ro false rprivate} {bind  /etc/machine-id /etc/machine-id  ro false rprivate} {bind  /mnt/data/supervisor /data  rw,slave true slave}]
➜  ~ docker exec -it hassio_supervisor bash
2059af9ec13d:/# cd /data/mounts/
2059af9ec13d:/data/mounts# ls -al
total 20
drwxr-xr-x    3 root     root          4096 Dec 19 22:20 .
drwxr-xr-x   16 root     root          4096 Feb 23 20:13 ..
d---------    2 root     root         12288 Feb 21 01:30 Freenas_Backup
2059af9ec13d:/data/mounts# ls -al Freenas_Backup/
total 217964
d---------    2 root     root         12288 Feb 21 01:30 .
drwxr-xr-x    3 root     root          4096 Dec 19 22:20 ..
-rw-r--r--    1 root     root      73656320 Feb 20 01:30 201353cf.tar
-rw-r--r--    1 root     root       2160640 Feb 19 20:47 471b19d7.tar
-rw-r--r--    1 root     root         61440 Feb  2 20:44 79495923.tar
-rw-r--r--    1 root     root      73625600 Feb 19 01:30 7a2eca56.tar
-rw-r--r--    1 root     root      73656320 Feb 21 01:30 a7030005.tar
2059af9ec13d:/data/mounts# 
```

As you can see, the folder permissions no-longer the default because in December i already encounter this, and try to solve it definitively by stopping write to mount the folder when unmounted. It didn't work because it look like the backup process run with root permission ?
Here is what i wrote in discord at the time.

> Home assistant keep writing to the local folder after the mount failed
> This mean you can't mount it back
> The /data/mount seams nowhere to be found
> 
> What you need:
>  
> Advanced SSH & Web Terminal with priviled
> 
> open the webui
> docker ps -a
> after inspecting all container i found that the mount we are searching for is on the hassio_supervisor container
> ➜  ~ docker inspect -f '{{ .Mounts }}' hassio_supervisor            
> [{bind  /run/systemd-journal-gatewayd.sock /run/systemd-journal-gatewayd.sock  rw true rprivate} {bind  /run/dbus /run/dbus  ro false rprivate} {bind  /run/supervisor /run/os  rw true rprivate} {bind  /run/udev /run/udev  ro false rprivate} {bind  /etc/machine-id /etc/machine-id  ro false rprivate} **{bind  /mnt/data/supervisor /data  rw,slave true slave}** {bind  /run/docker.sock /run/docker.sock  rw true rprivate} {bind  /run/containerd/containerd.sock /run/containerd/containerd.sock  rw true rprivate}]
> 
> Open a shell
> docker exec -it hassio_supervisor bash
> go to the path of the backup
> cd /data/mounts/
> ls -al backup_folder
> total 67331232
> drwxr-xr-x    2 root     root         12288 Dec 19 21:36 .
> drwxr-xr-x    4 root     root          4096 Dec 19 21:36 ..
> -rw-r--r--    1 root     root      55316480 Oct 11 00:30 005d4e1c.tar
> -rw-r--r--    1 root     root         20480 Sep  1 20:17 00d4ba8e.tar
> -rw-r--r--    1 root     root       2119680 Sep 14 15:48 027b4e75.tar
> -rw-r--r--    1 root     root      54763520 Sep 27 00:30 02f5e173.tar
> -rw-r--r--    1 root     root      54763520 Sep 26 00:30 041fbbb7.tar
> ...
> 
> 
> Your data are here, and the chmod don't stop ha from writing to it unmounted !
> Move the backup to a tmp folder
> mkdir tmp
> mv backup_folder/* tmp/
> 
> Lock the mount-point
> chmod 0000 backup_folder
> ls -al
> total 20
> drwxr-xr-x    4 root     root          4096 Dec 19 21:36 .
> drwxr-xr-x   16 root     root          4096 Dec 19 21:47 ..
> d---------    2 root     root         12288 Dec 19 21:08 backup_folder
> drwxr-xr-x    2 root     root         12288 Dec 19 21:36 tmp
> 
> And now, retry mounting it from the webui, it should work.
> ls -al
> total 20
> drwxr-xr-x    4 root     root          4096 Dec 19 21:36 .
> drwxr-xr-x   16 root     root          4096 Dec 19 21:47 ..
> drwxr-xr-x    2 root     root             0 Dec 19 21:08 backup_folder
> drwxr-xr-x    2 root     root         12288 Dec 19 21:36 tmp
> 
> You can the the permission are now OK and the size on disk is 0
> 
> Finally, move the backup back on the mount.
> This will take more time because it will actually upload them to your NAS
> mv tmp/* backup_folder/
>  
> Took me 45mn...

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

The reason the network device become unavailable is unknown
Maybe try to power down the SMB server and run a scheduled backup ?

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-23 21:12:26 INFO (MainThread) [supervisor.mounts.manager] Removing mount: Freenas_Backup
24-02-23 21:12:26 INFO (MainThread) [supervisor.mounts.mount] Mount Freenas_Backup is not mounted, skipping unmount
24-02-23 21:12:26 INFO (MainThread) [supervisor.mounts.manager] Creating or updating mount: Freenas_Backup
24-02-23 21:12:26 ERROR (MainThread) [supervisor.mounts.mount] Cannot mount Freenas_Backup at /data/mounts/Freenas_Backup because it is not empty
```

### Anything in the Host logs that might be useful for us?

```txt
No relevant log still available.
```

### Additional information

Requesting manual backup fail with the error 
```
24-02-23 21:11:31 ERROR (MainThread) [supervisor.backups.manager] Freenas_Backup is down, cannot back-up to it
```
 but can just after work while the mount error is still present in repair.
```
24-02-23 21:37:06 INFO (MainThread) [supervisor.backups.manager] Backup b5e1108e starting stage addon_repositories
24-02-23 21:37:06 INFO (MainThread) [supervisor.backups.manager] Backup b5e1108e starting stage docker_config
24-02-23 21:37:06 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug b5e1108e
24-02-23 21:37:06 INFO (MainThread) [supervisor.backups.manager] Backup b5e1108e starting stage addons
```

**Comment by JBakers** [comment]
Same issue as I experience 

https://github.com/home-assistant/supervisor/issues/4643

**Comment by Vaarlion** [comment]
i didn't search in the supervisor repo, i'm curious to know which repo is the right one for this

**Comment by sairon** [comment]
This is handled by the Supervisor, there's not much to do on the OS side IMHO. Let's keep the discussion in the issue referenced above.
