### ISSUE TITLE
Generic image cannot be flashed on usb stick more then 45%.

### ISSUE THREAD

**Issue by AditaNi** [home-assistant/operating-system#3213]
### Describe the issue you are experiencing

I cannot Flash an usb stick with Generic Image 12 more then 45% with balena etcher.

I tryed in linux and also in windows to flash the usb stick.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.0

### Did you upgrade the Operating System.

No...just flashing the usb stick.

### Steps to reproduce the issue

Hy Guys,

1. Download generic image x86-64 12.0
2. Download balena etcher
3. plug in the usb stick onto your laptop
4. start the flashing process.

Everything is working fine until 45%.

In windows 10 ...I receive a long error.
In linux is just hangs at 45 %

Regards
Adrian

### Anything in the Supervisor logs that might be useful for us?

```txt
nope...because nothing is installed.
```

### Anything in the Host logs that might be useful for us?

```txt
also not
```

### System information

Thinkpad edge E145 laptop

**Comment by sairon** [comment]
Sorry for the trouble, however it's almost surely not an issue of the OS image itself - in the end it's just a bunch of binary data that needs to be written on the disk. I suggest filing an issue in the Balena Etcher support channels, or trying a different tool for the job.

**Comment by AditaNi** [comment]
Hi,

have you retested and you cannot confirm it?

Regards
Adrian

**Comment by sairon** [comment]
Yeah, here's a screenshot of the verification step just a second before it finishes. I tried a random USB drive I had around and latest x86 image (compressed, to leave unpacking on the Etcher):

![image](https://github.com/home-assistant/operating-system/assets/211416/5fd51ddd-c235-4637-8596-5853b04444f8)

Not sure if you tried, but maybe check it with a different drive first. If it doesn't help, refer to Balena Echer support: https://github.com/balena-io/etcher/blob/master/docs/SUPPORT.md

**Comment by AditaNi** [comment]
i have tried with 5 different usb sticks and two different pc's....but same windows 10 version.
Maybe i have bad luck...who knows.
