### ISSUE TITLE
USB SSD Enclosure fails with SQUASHFS errors

### ISSUE THREAD

**Issue by bigwave** [home-assistant/operating-system#3217]
### Describe the issue you are experiencing

Booting from an SSD in a "Tccmebius 2.5'' External Hard Drive Enclosure, USB 3.0 to SATA HDD Case (TCC-S9-UK)"fails. Console displays:

SQUASHFS error: read_indexec: reading block....
SQUASHFS error: Unable to read metadata cache entry....

Adding `152d:0562:u` to `usb-storage.quirks` in the cmdline file on the boot partition fixes this.

![61g8xcu5ogL _AC_SX679_](https://github.com/home-assistant/operating-system/assets/693474/2b412b1b-3157-4ec8-a9f4-c3b12fcbbc10)

Bought from Amazon (https://www.amazon.co.uk/Tccmebius-Enclosure-Tool-Free-Automatic-TCC-S9-UK-Black/dp/B07KPVG67C)

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.0

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Flash SSD with Raspberry PI imager.
2. Boot Raspberry Pi
3. HDMI console displays multiple errors

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### System information

N/A

### Additional information

N/A

**Comment by sairon** [comment]
It seems it's quite a common issue for this driver. Adding the record to `usb-storage.quirks` is the correct workaround for this problem, I've created a PR to make it default for all new installs. Thanks!
