### ISSUE TITLE
repository function missing

### ISSUE THREAD

**Issue by andreacinci** [home-assistant/operating-system#3233]
### Describe the issue you are experiencing

Good morning, I would like help... why don't I have the "repository" entry in the three dots at the top right? I installed the haos_rpi4-64-12.0.img version and of course I enabled advanced mode. Thank you
![Screenshot](https://github.com/home-assistant/operating-system/assets/162689691/6fe819ca-23b8-4cb3-af44-53370d221922)

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

don't I have the "repository" entry in the three dots at the top right

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by agners** [comment]
This is an issue tracker, not a help forum. Please use Discord or the Community forums for such questions.

That said, in my english installation repositories is the 2nd entry there. Maybe a bad translation?
