### ISSUE TITLE
Virus detected in HAOS OVA 12.1 File

### ISSUE THREAD

**Issue by Kevin1904** [home-assistant/operating-system#3249]
### Describe the issue you are experiencing

Download fails with Chrome or Edge and Windows Defender

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Download from Github

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by agners** [comment]
Hm, yeah this looks a false positive as this seems to be a Win32 virus. I don't think we can do anything from our side here.

I'd suggest to report the file to Microsoft/Windows Defender, this seems to be possible at: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide.
