### ISSUE TITLE
PCIE reset - kernel issue - cannot change kernel setting

### ISSUE THREAD

**Issue by bjorrod** [home-assistant/operating-system#3265]
### Describe the issue you are experiencing

PCIE controller resets due to faulty kernel setting. Running Hass Os on pi 5. Cannot change the kernel setting. Reacurs every 3-5 min sort of. HA hangs slightly during reset.

### What operating system image do you use?

rpi5-64  (Raspberry Pi 5 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. reacurring with approximately 3-5  min intervalls
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No warnings in supervisor log
```

### Anything in the Host logs that might be useful for us?

```txt
Mar 22 09:13:57 homeassistant kernel: nvme nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0x10
Mar 22 09:13:57 homeassistant kernel: nvme nvme0: Does your device have a faulty power saving mode enabled?
Mar 22 09:13:57 homeassistant kernel: nvme nvme0: Try "nvme_core.default_ps_max_latency_us=0 pcie_aspm=off" and report a bug
Mar 22 09:13:57 homeassistant kernel: nvme 0000:01:00.0: enabling device (0000 -> 0002)
Mar 22 09:13:57 homeassistant kernel: nvme nvme0: 4/0/0 default/read/poll queues
Mar 22 09:13:57 homeassistant kernel: nvme nvme0: Ignoring bogus Namespace Identifiers
```

**Comment by sairon** [comment]
What NVMe adapter are you using for the drive? If you have an M.2 drive enclosure, you can try taking the drive out and editing the `cmdline.txt` in the boot partiton on a PC (it is a FAT filesystem, so it should be possible to mount it easily even on Windows) and adding those parameters. But most likely this is issue with the adapter or RPi kernel, so if the issue persists, a test with official RPi OS is desirable.
