### ISSUE TITLE
Using timers on automation bug

### ISSUE THREAD

**Issue by kevvar** [home-assistant/operating-system#3300]
### Describe the issue you are experiencing

Hi everyone,

I'm encountering some issues with the timers in my automations. For example, when the motion sensor is triggered, it cancels the timer; otherwise, it starts the timer when no motion is detected. Additionally, when the timer finishes, it turns off a light.

However, since the last Home Assistant update (I think), every time the automation cancels the timer due to motion detection, the light turns off. This seems incorrect because the timer was canceled and did not complete its countdown. Is this behavior a bug?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

2024.4

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

N/A

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by sairon** [comment]
This is the wrong place to ask. This repository serves for tracking the operating system issues. For general support use the [community forums](https://community.home-assistant.io/), and if you think you've found a bug, file it in the proper repository (in this case [Home Assistant Core](https://github.com/home-assistant/core)). In your case, more details, like automation traces, would be needed to figure out what's going wrong, so I suggest starting a topic on community first, you'll find many wise people eager to help there :blush:
