### ISSUE TITLE
(OVA) HA OS unable to be updated from 12.1 to 12.2

### ISSUE THREAD

**Issue by Onepamopa** [home-assistant/operating-system#3309]
### Describe the issue you are experiencing

The update from 12.1 to 12.2 "succeeds", but:
When the VM reboots after the update - it pre-selects "Slot B" which has "unknown filesystem".
I can manually select "Slot A" to boot - it boots 12.1 w/o an update to 12.2.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Update from 12.1 to 12.2
2. Wait for it to reboot
3. Open VNC/KVM/etc and observe.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing in any of the HAOS logs indicates an issue.
```

### Anything in the Host logs that might be useful for us?

```txt
Nothing in any of the Host logs indicates an issue.
```

### System information

Proxmox 6.x (Yes, I know it's EOL), LVM storage only (no lvm-thin or disk storage).
I had to convert the qcow2 image into a "raw" LVM disk (which I also resized from 32G to 60G).

qm importdisk VMID THE_DOWNLOADED_DISK.qcow2 Target_LVM_Storage --format raw
qm resize VMID virtio1 +28G (where virtio1 is the imported disk)

After this - the VM booted, HA utilized the whole storage:
df -h |less
![image](https://github.com/home-assistant/operating-system/assets/3053279/7894a551-243b-4e69-86c3-2dcfeffdcaa0)
![image](https://github.com/home-assistant/operating-system/assets/3053279/72418a30-c2c6-467d-8ed0-6762536cafbd)
![image](https://github.com/home-assistant/operating-system/assets/3053279/6f13f879-88e1-408a-bd04-cedf4b878a55)

And
mount |less
![image](https://github.com/home-assistant/operating-system/assets/3053279/1e69c875-97f6-4846-b233-23dcc37bf577)
![image](https://github.com/home-assistant/operating-system/assets/3053279/c553a17e-8fb8-45b3-85d6-1d2b006dec62)
![image](https://github.com/home-assistant/operating-system/assets/3053279/ae3cd8dc-1a1a-4d56-b6de-50fb8e458303)
![image](https://github.com/home-assistant/operating-system/assets/3053279/08756a2f-6b1b-4825-b39e-b1025eeaebb9)
![image](https://github.com/home-assistant/operating-system/assets/3053279/6421d3f2-ce52-4ff2-851c-516dbf87d310)
![image](https://github.com/home-assistant/operating-system/assets/3053279/2c859ad0-c9da-4432-b337-64b4f57e8d00)
![image](https://github.com/home-assistant/operating-system/assets/3053279/70d7df1e-54ac-4ca5-a792-c8c95ec3908d)
![image](https://github.com/home-assistant/operating-system/assets/3053279/199b1749-f037-462c-a928-e619abaac9e8)
![image](https://github.com/home-assistant/operating-system/assets/3053279/4894707d-3b99-437a-b0db-35ff21c31b2d)
![image](https://github.com/home-assistant/operating-system/assets/3053279/b539cd23-6798-448f-81b4-2f41bf4879de)
![image](https://github.com/home-assistant/operating-system/assets/3053279/49abe96e-605a-4da7-8015-3ac908ccfbbf)

Restored my backup, all good. All updates work fine, apart from the OS 12.2 one...

Here's the VM config:
```
agent: 1,type=virtio
balloon: 0
bios: ovmf
boot: order=ide2;virtio1;net0
cores: 4
cpu: host,flags=+aes
cpuunits: 150000
efidisk0: NVME_SMS:vm-106-disk-1,size=4M
ide2: none,media=cdrom
machine: q35
memory: 4096
name: HAOS
net0: virtio=16:42:50:80:BF:E5,bridge=vmbr0,firewall=1
numa: 0
onboot: 1
ostype: l26
scsihw: virtio-scsi-single
smbios1: uuid=cf66a7bc-1960-4d89-b3c9-b08c01a9ddf4
sockets: 1
startup: order=0,up=30
usb0: host=3-1,usb3=1
virtio1: NVME_SMS:vm-106-disk-2,iothread=1,size=60G
vmgenid: 4cb1066f-7cdd-4604-8c63-f57c4042eb20
```

**Comment by agners** [comment]
From the screenshot it looks like you have two disks attached now (vda and sda). If both are disks with a full HAOS installation, this is very problematic: We use partition and file system labels to identify the right partitions. Now these labels are in the system twice, which means the system might pick one of the partition at random.

Make sure you have only one disk with HAOS installed on attached to your VM.

It seems the main data disk is used from `/dev/vda8`, so I'd try to detach whatever `/dev/sda` is (I guess the SCSI disk).

**Comment by agners** [comment]
Also, can you run `blkid` to see all partitions and disks in your system?

**Comment by Onepamopa** [comment]
@agners You're spot on!
I completely forgot to detach the old disk, just changed the boot order to boot from the new one.
Its entry is at the very bottom of the VM config and didn't get selected/copied.

Now.. detached the old disk, updated to 12.2 - all good.
