### ISSUE TITLE
Entity ID Already in use regardless of if I've used it before

### ISSUE THREAD

**Issue by Krispkiwi** [home-assistant/operating-system#3314]
### Describe the issue you are experiencing

Any time I'm renaming an entity, I get the already in use error message even if I rename it to absolute gibberish. This was on a fresh installation, It's also occurring on a brand new docker dev installation I spun up 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Rename an entity
2. Check logs

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing in supervisor
```

### Anything in the Host logs that might be useful for us?

```txt
NOthing in host
```

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 17, 2024 at 12:25 AM
-- | --
current_recorder_run | April 17, 2024 at 12:25 PM
estimated_db_size | 0.20 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by tomlut** [comment]
Confirmed:

Before:
![38a22bd354f7b19e4dbf1dc3f5ccf04a930dd9f6_2_343x500](https://github.com/home-assistant/operating-system/assets/10679300/c85f9e3c-a2b4-44ec-86de-12efe68f81c4)

After (there was no sensor that ended in "foobar"):
![86efcabc09ceb4a390f96093c42242aecb56aeb8_2_343x500](https://github.com/home-assistant/operating-system/assets/10679300/240bd6be-fa86-40dd-874f-50fb0d3a1af5)


Result:
```
Logger: homeassistant.components.recorder.entity_registry
Source: components/recorder/entity_registry.py:72
integration: Recorder (documentation, issues)
First occurred: 13:44:44 (2 occurrences)
Last logged: 13:46:47

Cannot migrate history for entity_id `sensor.cinema_window_voltage` to `sensor.cinema_window_voltage_foobar` because the new entity_id is already in use
```
