### ISSUE TITLE
Downloading whl in v2.13-fix

### ISSUE THREAD

**Issue by Portagoras** [home-assistant/operating-system#3340]
### Describe the issue you are experiencing

Links are still going to the v.2.13 release versions, which you have deleted. So you can't really setup the addon atm.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Not relevant

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install the HACS Addon (fresh install)
2. Try to set it up
3. See the Error 404 with it trying to aquite the following file 'https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl'

### Anything in the Supervisor logs that might be useful for us?

```txt
Not really
```

### Anything in the Host logs that might be useful for us?

```txt
Following Entries in order
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 12:50:02 AM (5 occurrences)
Last logged: 12:55:27 AM
Unable to install package https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl: ERROR: HTTP error 404 while getting https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl ERROR: Could not install requirement llama-cpp-python==0.2.64 from https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl for URL https://github.com/acon96/home-llm/releases/download/v0.2.13/llama_cpp_python-0.2.64-cp312-cp312-musllinux_1_2_x86_64.whl

Logger: custom_components.llama_conversation.utils
Source: custom_components/llama_conversation/utils.py:118
integration: LLaMA Conversation (documentation)
First occurred: 12:50:02 AM (5 occurrences)
Last logged: 12:55:27 AM
Error installing llama-cpp-python. Could not install the binary wheels from GitHub for platform: x86_64, python version: 3.12. Please manually build or download the wheels and place them in the `/config/custom_components/llama_conversation` directory.Make sure that you download the correct .whl file for your platform and python version from the GitHub releases page.

Logger: custom_components.llama_conversation.config_flow
Source: custom_components/llama_conversation/config_flow.py:364
integration: LLaMA Conversation (documentation)
First occurred: 12:50:02 AM (5 occurrences)
Last logged: 12:55:27 AM
Failed to install wheel: False
```

### System information

Not relevant

### Additional information

Not really, should be clear.

**Comment by agners** [comment]
> Links are still going to the v.2.13 release versions, which you have deleted.

https://github.com/acon96/home-llm/ is a 3rd party repository which we have no control of. Please report the deletion in that repository.

> 1. Install the HACS Addon

This is about operation system issues themselfs. Report the wrong path to the repository of the HACS add-on.
