### ISSUE TITLE
500 MB of more RAM usage since version 12.3

### ISSUE THREAD

**Issue by iz8mbw** [home-assistant/operating-system#3346]
### Describe the issue you are experiencing

Just upgraded HA Operating System from 12.2 to 12.3 and the RAM usage is incresed of 500 MB.

This is the Memory usage:
![image](https://github.com/home-assistant/operating-system/assets/3474082/d0f7be00-dcd8-4fec-92ec-40abe4126db8)

as you can see, after the upgrade from 12.2 to 12.3, the RAM usage is increased from 1.03 GB to 1.52 GB.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgarde from 12.2 to 12,3

### Anything in the Supervisor logs that might be useful for us?

```txt
.
```

### Anything in the Host logs that might be useful for us?

```txt
.
```

**Comment by iz8mbw** [comment]
After a reboot, it seems OK:

![image](https://github.com/home-assistant/operating-system/assets/3474082/c459eb77-cbd5-4ac7-9032-8dc5eab08ed4)


going to close for now.

**Comment by Impact123** [comment]
Proxmox VE also displays cache and buffers there so this is not a reliable way to check "used" memory.
Check directly in the VM via `free -h`, the system monitor or <https://my.home-assistant.io/redirect/hardware/>.
