### ISSUE TITLE
upgrade to 12.3 prevents full boot with zooz 800 long range usb dongle plugged in

### ISSUE THREAD

**Issue by mfarich** [home-assistant/operating-system#3350]
### Describe the issue you are experiencing

After installing the upgrade to os 12.3 my rpi was unable to fully boot.  Plugging in a monitor to it showed hardware interrupt errors.  Upon rebooting the cli is initially responsive for a few seconds and the home assistant ip responds to pings, but shortly after the interrupt errors start appearing and the cli is no longer responsive and the network can no longer see the rpi.  

After a while I realized if I remove the zooz long range zwave hub from the usb port it will boot normally.  The nortek combo zigbee/zwave hub being plugged in still didn't affect it.  I had to roll back to os version 12.2 and everything works normally again.

![PXL_20240508_172753345](https://github.com/home-assistant/operating-system/assets/5767455/cf6dfc64-7d0f-48b4-a23a-57a3fe55dcc5)

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. have working zooz 800 long range zwave dongle configured with zwavejs on home assistant os 12.2
2. upgrade to 12.3
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
was unable to fully boot 12.3 to get logs
```

### Anything in the Host logs that might be useful for us?

```txt
was unable to fully boot 12.3 to get logs
```

## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1394
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.8 GB
disk_used | 6.0 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.13.0), Duck DNS (1.17.0), Let's Encrypt (5.0.18), Z-Wave JS UI (3.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 29, 2024 at 8:09 PM
-- | --
current_recorder_run | May 8, 2024 at 1:57 PM
estimated_db_size | 128.02 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

![PXL_20240508_172753345](https://github.com/home-assistant/operating-system/assets/5767455/46ddefe0-14fd-41c6-8e1c-3e2e2d246ddb)

**Comment by sairon** [comment]
Seems to be identical with #3362 which I'd like to use for tracking this bug as well. Please see [this message](https://github.com/home-assistant/operating-system/issues/3362#issuecomment-2107327277) and report details about your setup there.
