### ISSUE TITLE
CLI full of Bluetooth hci0 messages

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/operating-system#3359]
### Describe the issue you are experiencing

Since some versions, my CLI is always reporting that it is unable to disable Scanning and that stoping background scan failed:

![grafik](https://github.com/home-assistant/operating-system/assets/26391061/e502b84f-5c43-4d8d-a059-8377dd34a884)

```
2024-05-10 08:25:57.521 homeassistant kernel: Bluetooth: hci0: Opcode 0x2042 failed: -112
2024-05-10 08:25:57.521 homeassistant kernel: Bluetooth: hci0: Unable to disable scanning: -112
2024-05-10 08:25:57.521 homeassistant kernel: Bluetooth: hci0: stop background scanning failed: -112
2024-05-10 08:29:57.531 homeassistant kernel: Bluetooth: hci0: Opcode 0x2042 failed: -112
2024-05-10 08:29:57.531 homeassistant kernel: Bluetooth: hci0: Unable to disable scanning: -112
2024-05-10 08:29:57.531 homeassistant kernel: Bluetooth: hci0: stop background scanning failed: -112
```

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

6.6.29

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

unknown

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
nothing visible
```

## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1408
Downloaded Repositories | 61
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 16. Dezember 2024 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-8.ui.nabu.casa
certificate_status | ready
instance_id | 95cf7be52e4b4745a2b3ff26026a6a0d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | beta
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 35.7 GB
disk_used | 27.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), ESPHome (2024.4.2), Matter Server (5.6.0), Samba share (12.3.1), Advanced SSH & Web Terminal (17.2.0), openWakeWord (1.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 31
views | 55
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. April 2024 um 12:57
-- | --
current_recorder_run | 9. Mai 2024 um 09:10
estimated_db_size | 2269.44 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by cospeedster** [comment]
Same here with HA OS VM on pve. Did you found any solution?
