### ISSUE TITLE
Recent VMware Tools downgrade from 12.X to 11.X, why?

### ISSUE THREAD

**Issue by infocfc** [home-assistant/operating-system#3366]
### Describe the issue you are experiencing

Hi. I just realized in my VMWare ESX based installation, that the Open-VM Tools have been recently downgraded in the last two OS Version from 12.XX to 11.XX Versions. (But have been upgraded from HASSOS 12.2 from 11364 to 11365). Ist there any reason fror that rather masive downgrade ofthe open-vm tools, or is that a bug?

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

12.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install an old Version (pre 12.2) of OS on VMware, and  in VMware, check out the vmware tools version. It is from the current 12XXX branch (the most recent one I've seen being 12384).
2. Upgrade to OS 12.2, and subsequently 12.3, and check the tools versions. They will be downgraded to 11364 (12.2) or 11365 (12.3)

### Anything in the Supervisor logs that might be useful for us?

```txt
No.
```

### Anything in the Host logs that might be useful for us?

```txt
No.
```

**Comment by sairon** [comment]
That was indeed not intentional, thanks for pointing that out. A commit that bumps `openvmtools` was not pushed upstream and for some reason I missed it when cherry-picking downstream-only changes. Sorry for that, I'll pick it again.
