### ISSUE TITLE
HAOS 12.3 does not boot on Fujitsu Esprimo Q920

### ISSUE THREAD

**Issue by knipknap** [home-assistant/operating-system#3385]
### Describe the issue you are experiencing

After upgrading from 12.2 to 12.3, HAOS no longer works on the Fujitsu Esprimo Q920. It gets stuck showing the Grub boot menu. I am only able to continue in recovery mode.

I then tried reinstalling 12.3 from scratch, leading to the same result.

Then I reinstalled again from 12.2, which works again.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install the Generic image on a Fujitsu Esprimo Q920.
2. Boot.
3. Note that the boot procedure shows the Grub menu, but does not continue.
4. Try to manually select HAOS option from the menu, the first two do not start.
5. Try instead to select a recovery option, and it boots.

### Anything in the Supervisor logs that might be useful for us?

```txt
UI does not start. HA CLI does not start.
```

### Anything in the Host logs that might be useful for us?

```txt
UI does not start. HA CLI does not start.
```

### System information

UI does not start. HA CLI does not start.

**Comment by sairon** [comment]
Already being investigated: #3348
