### ISSUE TITLE
Home Assistant OS 12.3 issue with conbee II

### ISSUE THREAD

**Issue by lordcharro** [home-assistant/operating-system#3391]
### Describe the issue you are experiencing

After updating from Home Assistant OS 12.2 to 12.3 whenever the conbee II USB stick is connected the system tries to start it but without success, having the following:  
```
raspberrrypi-clk soc:firmware:clocks: Failed to change fw-clk-arm frequency: -110
mmc0: timeout waiting for hardware interrupt.
```

and the entries rcu from the picture.
![PXL_20240523_112613478](https://github.com/home-assistant/operating-system/assets/16090828/0d650d68-9cf1-4e62-adeb-6f9378cbe3a0)

It will print those outputs for a minute and then it restarts, doing all over again. 

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade from 12.2 to 12.3
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No.
```

### Anything in the Host logs that might be useful for us?

```txt
Picture from above.
```

### Additional information

As a workaround I choose the previous boot-slot that had Home Assistant OS 12.2 and it works fine.

**Comment by sairon** [comment]
It's a known issue with the `dwc_otg` driver. Adding `dtoverlay=dwc2` to `config.txt` seems to be a working solution/workaround, but we still don't know what exactly is going on. For more details please refer to https://github.com/home-assistant/operating-system/issues/3362, closing this issue as a duplicate.
