### ISSUE TITLE
[WARN] Home Assistant CLI is not running! Jump into emergency console

### ISSUE THREAD

**Issue by Mrsash2020** [home-assistant/operating-system#3434]
### Describe the issue you are experiencing

After update I get this message in the console. I am on VirtualBox 7 latest on Win 11 x86 Machine.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 12.4

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

I am on VirtualBox 7 latest on Win 11 x86 Machine
Intel 13600K
Asrock Z790 Steel Legend WiFi
DDR5 32GB
SLZB-06 POE for Z2MQTT

### Steps to reproduce the issue

1.Launch VirtualBox > HASS 
2.[WARN] Home Assistant CLI is not running! Jump into emergency console
3.Link to get to home assistant still works

## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1463
Downloaded Repositories | 36
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 24.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Studio Code Server (5.15.0), Mosquitto broker (6.4.1), Duck DNS (1.17.0), NGINX Home Assistant SSL proxy (3.9.0), File editor (5.8.0), Samba Backup (5.2.0), Samba share (12.3.1), ESPHome (2024.6.0), go2rtc (1.9.4), Zigbee2MQTT (1.38.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 34
views | 39
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 19, 2024 at 11:49 PM
-- | --
current_recorder_run | June 20, 2024 at 9:57 AM
estimated_db_size | 5.45 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

I started having this issue after I updated yesterday. I have tried typing login and other suggestions including going to a previous backup being restored but this message on the console stays put. thanks

**Comment by Mrsash2020** [comment]
Todays update fixed the issue

**Comment by puffo1969** [comment]
I have the same issue with raspberry pi 

I used 
![image](https://github.com/user-attachments/assets/e6e33014-0744-49d9-b8fb-4472498955ed)

Thank you in advance
