### ISSUE TITLE
No ethernet connection on fresh Raspberry Pi 5 installation

### ISSUE THREAD

**Issue by OnSive** [home-assistant/operating-system#3447]
### Describe the issue you are experiencing

I tried the raspberry installer and flashing it on my own (12.4/haos_rpi5-64-12.4.img.xz) but either way the ethernet jack does not work on my raspberry pi 5.

I tried raspberry os and the jack worked fine. Don't even know how I could access my raspberry in this state to debug further.

### What operating system image do you use?

rpi5-64  (Raspberry Pi 5 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.4

### Hardware details

Raspberry Pi 5 (with and without POE header)

### Steps to reproduce the issue

1. Get a Raspberry Pi 5
2. Install the latest Raspberry Home Assistant OS

**Comment by OnSive** [comment]
Just flashed version 12.3 and Ethernet is working (with POE header)

**Comment by sairon** [comment]
If you used Windows for flashing the image, then it's almost surely the pinned issue (#3437).

**Comment by OnSive** [comment]
@sairon Thanks, then it's probably this issue, thought that mine may be unrelated 👍
