### ISSUE TITLE
unable to upgrade HA OS 12.3 to 12.4

### ISSUE THREAD

**Issue by SL552114** [home-assistant/operating-system#3452]
### Describe the issue you are experiencing

when attempting the upgrade of HA OS 12.3 to 12.4 the system throws an error and asks me to check the supervisor logs.

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.3

### Did the problem occur after upgrading the Operating System?

No

## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 457.7 GB
disk_used | 16.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.17.0), File editor (5.8.0), Samba share (12.3.1), Studio Code Server (5.15.0), Terminal & SSH (9.14.0), Node-RED (18.0.1), AdGuard Home (5.1.1), OneDrive Backup (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 16
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 21, 2024 at 6:29 PM
-- | --
current_recorder_run | June 30, 2024 at 4:13 PM
estimated_db_size | 1470.65 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Steps to reproduce the issue

1 navigate to upgdates: will show HA OS 12.4
2. click on update
3. wait for error message

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-06-30 21:07:14.393 ERROR (MainThread) [supervisor.os.manager] Home Assistant Operating System update failed with: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1
```

### Anything in the Host logs that might be useful for us?

```txt
nothing in host, but in Core:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:19:24 PM (2 occurrences)
Last logged: 9:07:14 PM

[546728974016] Unexpected exception
[546728979056] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 213, in async_install
    await async_update_os(self.hass, version)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 57, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 224, in async_update_os
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 599, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Unknown error, see supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 215, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: Unknown error, see supervisor
```

## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 457.7 GB
disk_used | 16.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.17.0), File editor (5.8.0), Samba share (12.3.1), Studio Code Server (5.15.0), Terminal & SSH (9.14.0), Node-RED (18.0.1), AdGuard Home (5.1.1), OneDrive Backup (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 16
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 21, 2024 at 6:29 PM
-- | --
current_recorder_run | June 30, 2024 at 4:13 PM
estimated_db_size | 1471.60 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

I have restarted everything multiple times and other updates, of Surpervisor or of add-ins/ integrations as well as HACS are running smoothly.

**Comment by sairon** [comment]
Can you access the device directly (i.e. with a keyboard and display)? It would be interesting to see what `journalctl -u rauc.service` shows.

Anyway, since #3432 shows exactly the same symptoms, I'm closing this as a duplicate. Please use the other issue for tracking the issue.
