### ISSUE TITLE
Official fan is not working on Khadas Vim3

### ISSUE THREAD

**Issue by Nicooow** [home-assistant/operating-system#3455]
### Describe the issue you are experiencing

The official fan does not work on Khadas VIM3. It never turns on, and no commands seem to activate it. It seems that a driver is missing in the OS.

I have tried everything I could find, but my Linux skills are too limited to make any progress.
If needed, I have two VIM3 devices available with Home Assistant for testing.

Here is the doc : https://docs.khadas.com/products/sbc/vim3/configurations/cooling-fan 

![image](https://github.com/home-assistant/operating-system/assets/46629108/d63bdbc2-df1c-4371-be70-e8e17fd2f3f8)
![image](https://github.com/home-assistant/operating-system/assets/46629108/249b2d3d-d09b-4f63-8939-f685c0adb9fc)

### What operating system image do you use?

khadas-vim3 (Khadas VIM3)

### What version of Home Assistant Operating System is installed?

12.4

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

Khadas vim3 with 3705 Cooling Fan (https://www.khadas.com/product-page/3705-cooling-fan)

### Steps to reproduce the issue

Plug the fan

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by LaZyCraZy71** [comment]
hi there,

any update from your issue ?

**Comment by LaZyCraZy71** [comment]
nice! thanks for your great work !! 👍
