### ISSUE TITLE
unable to add and save a static route "nmcli (1.46.0) and NetworkManager (1.44.2) versions don't match".

### ISSUE THREAD

**Issue by gb-0001** [home-assistant/operating-system#3461]
### Describe the issue you are experiencing

Hello,

unable to add and save a static route it indicates different versions "nmcli (1.46.0) and NetworkManager (1.44.2) versions don't match" and won't save it:
nmcli> save persistent
Error: Failed to save 'Supervisor enu1u1' (6c74c7ef-634c-39a4-8f51-fc138b6dc41f) connection: connection.autoconnect-ports: unknown property

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

Home Assistant 12.4

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

RPI3B+

### Steps to reproduce the issue

---------------
➜  ~ nmcli con edit "Supervisor enu1u1" 
**Warning: nmcli (1.46.0) and NetworkManager (1.44.2) versions don't match. Restarting NetworkManager is advise**d.

===| nmcli interactive connection editor |===

Editing existing '802-3-ethernet' connection: 'Supervisor enu1u1'

Type 'help' or '?' for available commands.
Type 'print' to show all the connection properties.
Type 'describe [<setting>.<prop>]' for detailed property description.

You may edit the following settings: connection, 802-3-ethernet (ethernet), 802-1x, dcb, sriov, ethtool, match, ipv4, ipv6, hostname, link, tc, proxy
nmcli> set ipv4.routes 10.8.0.0/24 192.168.0.30
nmcli> print ipv4
['ipv4' setting values]
ipv4.method:                            manual
ipv4.dns:                               192.168.0.1
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.addresses:                         192.168.0.12/24
ipv4.gateway:                           192.168.0.1
ipv4.routes:                            { ip = 10.8.0.0/24, nh = 192.168.0.30 }
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.routing-rules:                     --
ipv4.replace-local-rule:                -1 (default)
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-iaid:                         --
ipv4.dhcp-dscp:                         --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.dhcp-hostname-flags:               0x0 (none)
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.required-timeout:                  -1 (default)
ipv4.dad-timeout:                       -1 (default)
ipv4.dhcp-vendor-class-identifier:      --
ipv4.link-local:                        0 (default)
ipv4.dhcp-reject-servers:               --
ipv4.auto-route-ext-gw:                 -1 (default)
nmcli> **save persistent**
**Error: Failed to save 'Supervisor enu1u1' (6c74c7ef-634c-39a4-8f51-fc138b6dc41f) connection: connection.autoconnect-ports: unknown property**
nmcli> quit
➜  ~ nmcli -v                          
nmcli tool, version 1.46.0
➜  ~ NetworkManager --version              
1.46.0

### Anything in the Supervisor logs that might be useful for us?

```txt
nc
```

### Anything in the Host logs that might be useful for us?

```txt
nc
```

### System information

Home Assistant

Core
2024.7.1
Supervisor
2024.06.2
Operating System
12.4
Interface utilisateur
20240705.0

**Comment by sairon** [comment]
Please see [this answer](https://github.com/home-assistant/operating-system/issues/3396#issuecomment-2163186589), the same goes for this issue.
