### ISSUE TITLE
Ethernet driver missing for Ugreen DXP480T

### ISSUE THREAD

**Issue by YugiFanGX** [home-assistant/operating-system#3478]
### Describe the issue you are experiencing

aquantia multigigabit nic driver missing for Ugreen DXP480T. 

I am unable to boot, due to Kernel time synchronization.
Did use a external ethernet adapter, which is the only workaround.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

12.7

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

 AQC113 (?) Marvell driver. Not sure, just saw this in a subreddit.

### Steps to reproduce the issue

1. Install HAOS
2. connect ethernet cable
3. no connection
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by sairon** [comment]
The driver should be available since beta release 13.0.rc1, please report back if it still doesn't work.
