### ISSUE TITLE
High CPU usage `kworker/0:0+kacpid`

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/operating-system#3514]
### Describe the issue you are experiencing

I noticed an increase of the CPU usage of my machine several months ago. Where it was usually at 60% it now is at 99%.

I like to keep my updates in day, so I apply them as early as possible.

I'm sure this issue was non-existing in the past, but then it started happenning.

![image](https://github.com/user-attachments/assets/50b71223-0df8-4a5b-b8a4-f751477f3cd3)

Searching on the internet, everything points to some issue with the operating system/kernel, therefore I'm reporting this bug here.

Then I followed this guide and found out that I can "fix" the issue with:

```
echo "disable" > /sys/firmware/acpi/interrupts/gpe03
```

https://gist.github.com/liejuntao001/ea69affcc497ee0cc580018001e931f2

To make it persistent on reboots, I added this command to my Terminal add-on startup commands:

```
docker run --rm --pid=host --privileged ubuntu nsenter --target 1 sh -c 'grep disabled /sys/firmware/acpi/interrupts/gpe03 || echo disable >
/ sys/firmware/acpi/interrupts/gpe03'
```

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.6.33-haos

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Blitzwolf BW-MPC1 https://device.report/manual/1226135

Intel J4125 - 8GB RAM

![image](https://github.com/user-attachments/assets/10f1cf72-d9bd-4db2-bd37-e13b514fce1e)

No USB devices plugged
No Wi-Fi or Bluetooth PCIe
No Zigbee
Coral PCI-E M.2 board
SATA 256GB M.2 SSD
SATA 1TB HDD

### Steps to reproduce the issue

Unfortunately, I don't think the issue is portable. But I can very easily reproduce the issue with:

```
echo "enable" > /sys/firmware/acpi/interrupts/gpe03
```

(Provided I had previously "disable"d it to resolve it).

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't see anything useful there.
```

### Anything in the Host logs that might be useful for us?

```txt
[logs.txt](https://github.com/user-attachments/files/16551723/logs.txt)
```

## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4959
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 13
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.0 GB
disk_used | 128.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Advanced SSH & Web Terminal (18.0.0), Mosquitto broker (6.4.1), Cloudflared (5.1.17), Asterisk (4.4.0), RPC Shutdown (2.5), ESPHome (2024.7.3), AdGuard Home (5.1.1), OneDrive Backup (2.3.1), MariaDB (2.7.1), Nginx Proxy Manager (1.0.1), Traccar (0.25.0), Frigate (0.14.0), WireGuard (0.10.2), Glances (0.21.1), Netdata (1.46.3), Increase Swap (1.1.3), Uptime Kuma (0.12.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 4
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 1, 2024 at 4:43 PM
-- | --
current_recorder_run | August 8, 2024 at 2:34 PM
estimated_db_size | 610.03 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 2 / 2
local_online | 2 / 2

</details>

**Comment by sairon** [comment]
The high ACPI interrupt usage points to misbehaving hardware or its driver/firmware. It's hard to tell what uses that particular ACPI interrupt but if you want to go down the rabbit hole, you can find quite detailed instructions in [this post](https://www.reddit.com/r/linuxdev/comments/11uwxu8/understanding_the_acpi_interrupts_and_gpes/jd0951d/). Alternatively you can try disconnecting all on-board peripherals like WiFi card (if it's possible) and the Coral TPU, ultimately booting a fresh HAOS install from a single drive and see if it changes anything.

And eventually, a better permanent solution would be to mask the interrupt by adding `acpi_mask_gpe=0x03` to the `cmdline.txt` in your boot partition.

**Comment by felipecrs** [comment]
> Ultimately booting a fresh HAOS install from a single drive and see if it changes anything.

Right. I will try to test it. Thank you.

> And eventually, a better permanent solution would be to mask the interrupt by adding `acpi_mask_gpe=0x03` to the `cmdline.txt` in your boot partition.

Interesting. However, my `/boot` seems to be a read-only partition. Even if I can manager to hack and write to it, I wonder if it would survive OS upgrades.

Do you have any reference for changing `/boot/cmdline.txt` on HA OS?

**Comment by felipecrs** [comment]
Turns out it's my Coral TPU. After unplugging it, problem is gone. Regardless of there's an application using it or not.

This is the one I have: https://coral.ai/products/m2-accelerator-dual-edgetpu

It's hard to believe it became defective though. Also, disabling `gpe03` doesn't seem to affect any functionality of it.

I will try booting some different OSes to check how they work.

**Comment by felipecrs** [comment]
I can reproduce the issue with Ubuntu 24.04, 20.04 and 18.04. Meaning this is indeed a hardware defect then.

@sairon, thank you very much for the help. Would you just mind clarifying the above? (`/boot/cmdline.txt`).

**Comment by sairon** [comment]
@felipecrs 

> Would you just mind clarifying the above? (`/boot/cmdline.txt`).

Sure! First of all, you need to access the host OS directly. Either by using the [host SSH access](https://developers.home-assistant.io/docs/operating-system/debugging#enabling-ssh-access-to-the-host) or by connecting to the host directly (which means attaching a display and keyboard and typing `login` in the CLI). But it seems you're beyond that, so then the only catch is that the boot partition is mounted in `/mnt/boot` :innocent:

**Comment by felipecrs** [comment]
Perfect, thanks a lot. It worked.

This is how it ended up like, given I already had `console==tty1` on it for some reason.

```console
# cat /mnt/boot/cmdline.txt
console=tty1 acpi_mask_gpe=0x03
```

**Comment by felipecrs** [comment]
I hope this issue is useful for people with similar issues in the future, I will close it now.

**Comment by sairon** [comment]
> This is how it ended up like, given I already had `console==tty1` on it for some reason.

FTR, that is correct - it's there to ensure you have Systemd boot log on your HDMI display. We later changed it to `tty0` for consistency (and this change is one of those that are not applied to existing `cmdline.txt` on upgrade) but in this case it makes no difference.
