### ISSUE TITLE
No Such image ("raspberrypi3-64-homeassistant:2024.8.1")

### ISSUE THREAD

**Issue by djfanatix** [home-assistant/operating-system#3521]
### Describe the issue you are experiencing

I am trying to install a fresh HA install on a rpi3b

I tried Raspberry pi imager and balana etcher, but I always get the error

"[supervisor.docker.interface] Can't install ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1/json: Not Found ("No such image: ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1")
"

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

none

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

Rpi 3b

### Steps to reproduce the issue

Fresh install

### Anything in the Supervisor logs that might be useful for us?

```txt
[supervisor.docker.interface] Can't install ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1/json: Not Found ("No such image: ghcr.io/home-assistant/raspberrypi3-64-homeassistant:2024.8.1")
```

### Anything in the Host logs that might be useful for us?

```txt
none
```

**Comment by sairon** [comment]
This is most likely (or almost surely) a network error. Make sure that the device is connected to network with access to the internet and working DNS. It must be able to resolve `ghcr.io` (you can check by connecting a keyboard and an HDMI display to the RPi, typing `login` and running `ping ghcr.io`).
