### ISSUE TITLE
Pi5 bootloop after Update

### ISSUE THREAD

**Issue by Space-Banane** [home-assistant/operating-system#3590]
### Describe the issue you are experiencing

The whole pi wont start and read the FS
![image](https://github.com/user-attachments/assets/643d4d53-aab5-40ed-95a0-388a8a5984b0)
![image](https://github.com/user-attachments/assets/af6d8a36-46cb-40de-ba18-38c107819d1a)

### What operating system image do you use?

rpi5-64  (Raspberry Pi 5 64-bit OS)

### What version of Home Assistant Operating System is installed?

I Dont remember

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Just a PI5

### Steps to reproduce the issue

1. Update

### Anything in the Supervisor logs that might be useful for us?

```txt
I cant access my system
```

### Anything in the Host logs that might be useful for us?

```txt
See the picture above
```

**Comment by sairon** [comment]
This seems like a problem with the SD card, I'm afraid there's little we can do about it. What brand and model is that, and is it coming from a reputable source? You can try using an SD card reader in another PC and recovering the data from it. But in any case, I'd not put much trust into it even if you managed to reinstall the OS on the same card.
