### ISSUE TITLE
zsh went nuts, I do not know why

### ISSUE THREAD

**Issue by avlemos** [home-assistant/operating-system#3601]
### Describe the issue you are experiencing

I cannot pinpoint when this started to happen, but my shell now shows:

\[\e]0;\u@\h:\w\a\]\W $

and the first time I realised something was wrong, was when I noticed that files I had on a /media folder, now were under root ownership, and ~/ no longer has the files, so I am guessing this went nuts when this change happened?

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

13.1

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

This is a Dell Wyse 5070 with an external hard drive (just for media storage) and an Arduino for RF control.

Bus 002 Device 002: ID 0bda:0411
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 004: ID 0a12:0001
Bus 002 Device 004: ID 0bda:0415
Bus 001 Device 002: ID 0bda:5411
Bus 002 Device 003: ID 059f:10be
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 005: ID 0bda:5415
Bus 001 Device 003: ID 2341:0042

### Steps to reproduce the issue

1. Login via SSH (using key)
2. what the hell happened with zsh?
3.
4. profit

### Anything in the Supervisor logs that might be useful for us?

```txt
afaik, nothing weird
```

### Anything in the Host logs that might be useful for us?

```txt
just some audits and stuff
```

## System Information

version | core-2024.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1489
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 58.0 GB
disk_used | 12.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), AdGuard Home (5.1.2), Plex Media Server (3.6.0), Advanced SSH & Web Terminal (19.0.0), Glances (0.21.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 13
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 25, 2024 at 12:56
-- | --
current_recorder_run | September 28, 2024 at 14:20
estimated_db_size | 452.34 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by sairon** [comment]
The OS doesn't have ZSH installed and there is only access to the developer SSH port on 22222 (if enabled). You should head over here:
- https://github.com/hassio-addons/addon-ssh/issues/788
