### ISSUE TITLE
After upgrading to OS 13.1, Home Assistant crashes during startup when a Z-Stick Gen5 is plugged in

### ISSUE THREAD

**Issue by aygee** [home-assistant/operating-system#3612]
### Describe the issue you are experiencing

After updating to Home Assistant OS 13.1, the system won't start if my Z-Stick Gen5 is plugged in. 

It throws the following errors and the reboots:

```
hwmon hwmon1: Failed to get throttled (-110)
INFO: rcu_preempt detected stalls on CPUs/tasks
mmc0: timeout waiting for hardware interrupt
```

If I unplug the Z-Stick, the system boots fine. I can then plug in the Z-Stick after startup, and my Z-Wave devices would work fine.

Before updating the OS to 13.1, I updated the Core to 2024.10.1 and I did not experience the issue after rebooting.

Prior to the update, I was on Core version 2023.5.3. I don't remember exactly the OS version, but it was probably 10.2.

I attempted a fresh install of OS 13.1 on a new SD card. However, when restoring from a backup, similar errors occur, followed by a reboot. After rebooting, the system reports that the setup did not complete. 

I attempted another fresh install, this time I unplugged the Z-Stick before restoring and it completed successfully.

I tested with OS 12.4 with the same result.

Finally, I was able to successfully install and restore from backup while keeping the Z-Stick plugged in throughout the process when using OS 11.5.

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

13.1

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Raspberry Pi 3 64bit
Memory: 1GB
Z-Stick Gen5

### Steps to reproduce the issue

1. Fresh Install
2. Restore from backup
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
None because it wouldn't start the system when it happens.
```

### Anything in the Host logs that might be useful for us?

```txt
None because it wouldn't start the system when it happens.
```

## System Information

version | core-2024.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 229.2 GB
disk_used | 6.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (3.13.2), Advanced SSH & Web Terminal (19.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 24, 2024 at 10:49 PM
-- | --
current_recorder_run | October 7, 2024 at 11:28 PM
estimated_db_size | 2315.00 MiB
database_engine | mysql
database_version | 10.11.3

</details>

### Additional information

![20241007_234038](https://github.com/user-attachments/assets/08c24230-72ad-4d74-918d-b88a5bf71db7)

**Comment by N3rdix** [comment]
have you tried a different SD card? Sounds like your card could be corrupted

**Comment by aygee** [comment]
When I tried to install different OS version, I was using a different SD card. The issue exists in 13.1 and 12.4, but not 11.5

**Comment by sairon** [comment]
AFAIK Aeotec Gen 5 is the same hardware as the problematic Z-Wave.me stick. Using the `dwc2` driver should help there, see https://github.com/home-assistant/operating-system/issues/3362 for details. Closing this as a duplicate.

**Comment by aygee** [comment]
Thanks for the help. The `dwc2` driver fixed it for me!
