### ISSUE TITLE
Onboarding Stuck creating user no error

### ISSUE THREAD

**Issue by pyrosrock** [home-assistant/operating-system#3651]
### Describe the issue you are experiencing

it seems that when setting up a new instance and at the new user creation page of the on-boarding it will stick with no error message if change the username to have a capital letter.

### What operating system image do you use?

generic-aarch64 (Generic UEFI capable aarch64 systems)

### What version of Home Assistant Operating System is installed?

6.6.51

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

tested running in docker through portainer on a Raspberry Pi 4

### Steps to reproduce the issue

1. Start with a fresh install
2.Click create my smart home
3.type the name
4.Change the username first letter to a capital
5.Click create account
6.No error but sits there stuck looking like its just taking a long time
...

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by sairon** [comment]
There's already a frontend issue for this, I just reopened it and will ping someone from the frontend team to take another look at it: https://github.com/home-assistant/frontend/issues/21333
