### ISSUE TITLE
HAOS 14.0 wiped out network

### ISSUE THREAD

**Issue by jonlove234** [home-assistant/operating-system#3717]
### Describe the issue you are experiencing

Via the GUI, updated to HAOS 14

Rebooted and no connectivity. Same when reverting back to 13.X

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

14.0

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

HAOS x86 running in Unraid VM

### Steps to reproduce the issue

1. Update to HAOS 14.0
2. Reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
Attached network related screenshots
```

### Anything in the Host logs that might be useful for us?

```txt
Can't access CLI
```

### Additional information

![image](https://github.com/user-attachments/assets/c4fdcc10-c2db-4bcd-8abb-0bbca0bfa0df)
![image](https://github.com/user-attachments/assets/7d5dbccd-f499-4d6b-a8b7-95d4e9bce4fb)
![image](https://github.com/user-attachments/assets/5c2d3278-351b-496d-8cdd-f61927c0f7f8)
![image](https://github.com/user-attachments/assets/a9248399-aa64-4daf-9ace-13b97284b392)

**Comment by jonlove234** [comment]
Restored a VM backup and worked, so going to close this and assume it was something unrelated to HAOS

**Comment by jonlove234** [comment]
Can't repo

**Comment by matvit92** [comment]
I have the same issue, any other way to repair without restoring VM backup?
