### ISSUE TITLE
Missing NETFILTER_XT_TARGET_TCPMSS kernel module on ODROID-N2

### ISSUE THREAD

**Issue by KOPRajs** [home-assistant/operating-system#3730]
### Describe the issue you are experiencing

After installing a 3rd party WireGuard Client addon, I'm getting the following error:
```
[#] iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
Warning: Extension TCPMSS revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain FORWARD
```

The addon can be found here: https://github.com/bigmoby/hassio-repository-addon

Please consider adding the _NETFILTER_XT_TARGET_TCPMSS_ kernel module, so we can use WireGuard VPN directly on HAOS. It should be less than 20 kB.

Thank you.

### What operating system image do you use?

odroid-n2 (Hardkernel ODROID-N2/N2+)

### What version of Home Assistant Operating System is installed?

12.4

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

ODROID-N2/N2+

### Steps to reproduce the issue

1. iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

### Anything in the Supervisor logs that might be useful for us?

```txt
[#] iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
Warning: Extension TCPMSS revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain FORWARD
```

### Anything in the Host logs that might be useful for us?

```txt
[#] iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
Warning: Extension TCPMSS revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain FORWARD
```

**Comment by sairon** [comment]
Seems the modules is usually present in base kernel configs for other targets but not for N2. Shouldn't be a problem to add it there too.
