### ISSUE TITLE
I’m using anel_pwrctrl and it works so far.

### ISSUE THREAD

**Issue by WolleSoso** [home-assistant/operating-system#3764]
I’m using anel_pwrctrl and it works so far.
The 8 channels are found and can be switched. There is also an extension for the Net-Hub, NET-PwrCtrl HUT EX, for an additional 8 channels. see here [ANEL-Elektronik AG 1](https://shop.anel.eu/main_bigware_29.php?cName=netpwrctrl-hut-extender). However, these are not displayed in HA. How do I get the 8 additional channels? Thank you for your help.

_Originally posted by @WolleSoso in https://github.com/home-assistant/core/issues/88931#issuecomment-1550301437_

**Comment by agners** [comment]
This is not a Home Assistant Operating System issue.
