### ISSUE TITLE
Intel NUC won't boot off NVME M.2 drive

### ISSUE THREAD

**Issue by bruhautomation** [home-assistant/operating-system#422]
Hello! Thanks for the awesome work on HassOS. 

I'm trying to run HassOS off of a NUC. Everything works great when I use a standard SSD. I burned the image directly to the drive using balenaEtcher via a USB-to-SATA adapter. Pop the drive into the NUC and it's rolling. 

However, when I repeat this exact process with a NVME M.2 drive, HassOS refuses to boot. I've tried copying the partitions from the working drive to the NVME drive, but that didn't resolve the issue. 

I have the secure boot settings turned off in the BIOS and confirmed the NUC can see the NVME M.2 drive. I've scrubed the drive and confirmed that all the partions are being written identically to the working standard SSD. 

No matter what I try, HassOS on the NVME M.2 drive tries to boot, but ultimately leaves me stuck at HassOS boot menu. 

Do you have a guess why the switch the NVME M.2 drive prevents HassOS from booting/running? 

I'm wondering if the partition labels are affecting something. 

The working SSD uses /dev/sda1 /dev/sda2, etc. The not-working NVME drive uses /dev/nvme0n1p1 /dev/nvmeon1p2 etc. 

Is HassOS looking for the standard partition labels on boot? 

Thanks much!

**Comment by botne** [comment]
Hi!

I have the same issue.
Did you find a workaround for this?

Br,
Frank

**Comment by botne** [comment]
ok, @bruhautomation. Will change the m.2 nvme for a m.2 sas instead. I guess that will fly :)

**Comment by pvizeli** [comment]
I think it's a barebox issue. I hope uboot come also soon with an working UEFI support

**Comment by rovrell** [comment]
Ahh, that's the problem :/ tried for 2 days now.

**Comment by xbmcnut** [comment]
Hey Ben. Happening for me too. Sorry, I duplicated the issue here https://github.com/home-assistant/hassio/issues/1365

**Comment by SBerg1980** [comment]
I have the same problem, i want to switch from my pi to my NUC with a nvme disk but when i run de gunzip and then boot the NUC its stuck on boot.

**Comment by air720boarder** [comment]
This is currently a blocker for me as well

**Comment by Mathijs0** [comment]
This is why I now use Debian with hass.io and not hassos

**Comment by air720boarder** [comment]
Any fixes in the pipeline for this?

**Comment by Mathijs0** [comment]
Ore a warning on the install page?

**Comment by niXta1** [comment]
Also got stuck here...

**Comment by AdamNaj** [comment]
Same problem for me... Was so excited when the NUC arrived, didn't last long...

**Comment by niXta1** [comment]
> Same problem for me... Was so excited when the NUC arrived, didn't last long...

Install a sata ssd or go with another OS... Only options for now...

**Comment by manavees** [comment]
Any news about how to run hass in nvme ssd on a NUC? I am thinking of getting a NUC for my home assistant and would like to go with nvme

**Comment by xbmcnut** [comment]
You'll have to run something like Promox as I ended up doing. Check out Drzzs videos in that process.

**Comment by manavees** [comment]
> You'll have to run something like Promox as I ended up doing. Check out Drzzs videos in that process.

What about using a 2,5'' SSD? Will it work without any issues?

**Comment by xbmcnut** [comment]
Should do no issue although some reported that 3.8 was causing issues on my YouTube channel. Maybe 3.9 resolved this?

**Comment by manavees** [comment]
So basically also a simple m.2 sata could work. Like the Samsung (https://s3.ap-northeast-2.amazonaws.com/global.semi.static/Samsung_SSD_860_EVO_M2_Data_Sheet_Rev1.pdf)

**Comment by niXta1** [comment]
> So basically also a simple m.2 sata could work. Like the Samsung (https://s3.ap-northeast-2.amazonaws.com/global.semi.static/Samsung_SSD_860_EVO_M2_Data_Sheet_Rev1.pdf)
No, that has a m2 interface, it needs to have a SATA connector (2.5").

**Comment by Mathijs0** [comment]
Is there any progress in this issue?

**Comment by Blankf** [comment]
Same question here, is there any progress on this issue? Or is someone looking at it?

**Comment by tradiuz** [comment]
When you burn the NVMe with etcher, what do you see under `/dev` in the HassOS boot menu.  I was able to get my AtomicPi to boot manually by mounting `/dev/usbdisk1.hassos-kernel0` to `/mnt/system` because the system0 script assumes the drive is named `disk*.hassos-kernel0`  I suspect the NVMe drives show up similarly different from a "disk".

A stupid fix might just be changing the `disk*` to just `*` or some regex of all possible drive types (mmcblk, nvmeon, disk, usbdisk, etc).

**Comment by Blankf** [comment]
How were you able to mount it from the shell?

i see a bunch of 
disks0/1/2/3/4/5/6/7 and
disk1/2/3/4/5/6/7
disk0.hassos-boot
disk0.hassos-bootstate
disk0.hassos-data
disk0.hassos-kernel0
disk0.hassos-kernel1
disk0.hassos-overlay
disk0.hassos-system0 en 1

not seeing anything that looks like nvme.

**Comment by Mathijs0** [comment]
Nice and thank you! I am gone try it out soon.

**Comment by Mathijs0** [comment]
O this issue is closed but not jet released, when wil this fix be implemented? Now that I formatted my drive :-(

**Comment by frenck** [comment]
Yes, issues close when development is finished and does not tell anything about availability.

We don't have a schedule for this. Things are ready when they are ready.

**Comment by Mathijs0** [comment]
okey thanks for your work!!

**Comment by Joc007** [comment]
Success, it works now.
If you need details, see this: https://community.home-assistant.io/t/my-steps-to-success-for-hass-io-on-intel-nuc/43915/323

**Comment by Infraviored** [comment]
I have the same issue. Still, i do not understand how to apply this community post 'guide' - it lack so much information.
Instead of using etcher, use the restore disk feature built into ubuntu?
