### ISSUE TITLE
Impossible install of hassos on 32gb on raspberry 3b+

### ISSUE THREAD

**Issue by Nemesis24** [home-assistant/operating-system#490]
Ok i will try to explain... i've got using hassos 3.5 on a sdcard 32gb on a raspberry 3b+ and after a reboot, my install was broken.

For the first time, i think that my sdcard was broken...corrupt
So i decided to make a new install of hass.io on my sdcard 32gb, but the install don't boot.
So i decided to have a new sdcard 32 gb to be sure, but the install don't boot.
Finally i try with an old sdcard in 16gb and the install boot

Thanks

**Comment by ciotlosm** [comment]
@Nemesis24 try connecting the rpi 3b+ to a monitor and look at output to understand where it failed to boot.

**Comment by Nemesis24** [comment]
I have connected my rpi3b+ on a monitor, but i couldn't see anything because, there was only 20 lines who go very very fast and reboot all the time , on my 32 gb card i can install a rasbian lite without any problems.
For now i use hassio on my 16gb card.

**Comment by ciotlosm** [comment]
Which version of hassos did you try? The 32bit or 64bit?

**Comment by Nemesis24** [comment]
The 32 bit because recomanded.

**Comment by cogneato** [comment]
You can hook up a keyboard and hit enter to interrupt the running log. But it's possible that what you are seeing is the normal log which doesn't really end.

Logging in as root, no password, will get you to the Hassio CLI.

**Comment by Nemesis24** [comment]
i've got the keyboard but hit enter do nothing in this case, and it doesn't explain the difference beetween 32 and 16 gb of comportement.

**Comment by ciotlosm** [comment]
I tried a 32GB card and it booted for me. Can you try the 2.x version?

**Comment by Nemesis24** [comment]
Thanks, but i try again, with 3.5 and 2.12, that was the same thing. I've got only the red led on pi now with 32gb and 16gb perhaps it's related to a bad alimentation, i will try another alimentation... i've got a raspbee, i try without it was the same thing.

**Comment by ciotlosm** [comment]
What specs is your current power supply?

**Comment by Nemesis24** [comment]
This is a 5v , 2.4A.

**Comment by caesar1987sk** [comment]
i have same problem with my 32GB card. infinite loops. But i dont have smaller one :(
Raspbian is running on another 32GB card without problems.

**Comment by caesar1987sk** [comment]
its look like hassos_rpi3-1.13.img.gz is working without any problem.

**Comment by caesar1987sk** [comment]
after update to latest version (from hassio ui) is again not possible to start it.

**Comment by MuadDev** [comment]
I see observe the same behaviour as @caesar1987sk and @Nemesis24 do. I also use a 32GB SD card and a Pi3+.

**Comment by JokerQyou** [comment]
Same behavior here, except that I don't see anything on the HDMI monitor, no boot log, nothing. Pi 3 B+ with a 128GB SD card, flashed `hassos_rpi3-2.12.img.gz` with balenaEtcher `1.5.64`.

**Comment by Matthijsy** [comment]
I also have the same behaviour on a Raspberry Pi3B. I managed to capture the error, it is complaining about the MBR header. 

Here is the error log (not that clear since it goes very fast)
![WhatsApp Image 2019-12-10 at 13 24 42](https://user-images.githubusercontent.com/5302372/70529323-8d4a1e80-1b50-11ea-99d5-02ba0a88b260.jpeg)

**Comment by Matthijsy** [comment]
I am not sure this problem is solved already. Could someone give an update?
