### ISSUE TITLE
"disabled due to remaining attempts" on Hyper-V VM

### ISSUE THREAD

**Issue by onlize** [home-assistant/operating-system#507]
Hello,

My Hyper-V VM worked for a few months without any issues. Now, for some reason, I cannot boot it. It goes to the menu:
![image](https://user-images.githubusercontent.com/28982031/70664823-d376af00-1c30-11ea-84f3-3de260a20160.png)

When I select Shell and type boot, I see the following:
![image](https://user-images.githubusercontent.com/28982031/70664885-f43f0480-1c30-11ea-9e59-22c7f580610c.png)

it loads correctly if I type 
```
boot system0
```

My question is why is it doing this and how can I make it work aromatically as it worked before. I do not want to go shell and type that command.

Is the problem because I see
```
disabled due to remaining attempts = 0
```
How to fix it?

Thank you.

**Comment by pvizeli** [comment]
After boot, there should be a job they mark it system as correct. Try `rauc status mark-good`. What is the output of `rauc info`?

**Comment by onlize** [comment]
What do you mean after the boot. When I go to number four (shell)? When I try commands, I see this:
![image](https://user-images.githubusercontent.com/28982031/70757037-cecefb00-1d03-11ea-90bf-37ebc7266ee0.png)

**Comment by pvizeli** [comment]
yes, after boot into host system, not on bootloader
