### ISSUE TITLE
Pi 4 Incorrectly Tracking via Bluetooth

### ISSUE THREAD

**Issue by ghost** [home-assistant/operating-system#522]
Hass.io Supervisor : 193
System: HassOS 3.7
Raspberry Pi 4

Updated to the latest versions after a few Bluetooth tracking issues and it seems they are still occurring. Our iPhones worked flawlessly but now it changes between 'Home' and 'Away' every few minutes.

**Comment by talondnb** [comment]
Possibly the same issue as this?

https://github.com/home-assistant/home-assistant/issues/30147#issuecomment-569816486
