### ISSUE TITLE
Allow storage=volatile for journald

### ISSUE THREAD

**Issue by jdeluyck** [home-assistant/operating-system#543]
**HassOS release with the issue:**
3.8

**Supervisor logs:**
N/A

**Journal logs:**
N/A

**Kernel logs:**
N/A

**Description of problem:**
Currently HassOS is configuring journald persistent storage (storage=auto and /var/log/journal exists). This causes additional wear & tear on the SD card, and it would be great if people that know what they're doing could easily disable this (changing storage to volatile for only in-memory storage)

**Comment by pvizeli** [comment]
If you want do this:
- Look if you can change the config with dbus
- Add support for this dbus on supervisor
- Make it configurable on supervisor

**Comment by jdeluyck** [comment]
> If you want do this:
> 
> * Look if you can change the config with dbus
> * Add support for this dbus on supervisor
> * Make it configurable on supervisor

Might have a look at what's possible.

**Comment by pvizeli** [comment]
I'm also fine to move that to data partition...

**Comment by pvizeli** [comment]
Fix with 4.6
