### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Magnatolia** [home-assistant/operating-system#547]
Hi,

I tried installing this, and it keeps looping with an IPV6 error, "link is not ready". 

I didn't understand the WiFi config section. I created a folder structure CONFIG/network, and created a file called my-network (no extension). I copied the default details on the how to page the first time, then tried removing the IPV6 section. I also added the section for WLAN.

Is that the right thing to do? Can someone please explain what I'm doing wrong?

Thanks!

**Comment by roybosch** [comment]
When I started with hassio I had the same problem. The IPv6 error "link is not ready" you mention, is in fact no (related) error. It's showing all the time, even if your config file doesn't contain mistakes.

I advice you to first start hassio with a wire and preferably keep it that way as it's way more stable than a wireless connection.
