### ISSUE TITLE
Intel AC-7265 wireless/bluetooth problem

### ISSUE THREAD

**Issue by alesoft73** [home-assistant/operating-system#548]
I have Installing Hass.io with intel-nuc image 3.8
The intel AC-7265 wireless/bluetooth work a few minuts. After don't work. (bluetooth).
If a restart, continue to work a few minuts...
Is possible to update the driver ?
Many thanks!

**Comment by pvizeli** [comment]
This it work better with 4.0? `hassio os update --version 4.0`

**Comment by alesoft73** [comment]
> 
> 
> This it work better with 4.0? `hassio os update --version 4.0`

I test, many thanks!

**Comment by alesoft73** [comment]
Work a few minuts... After down
shiw image
![Screenshot_2020-01-23-21-15-22-486_com android chrome](https://user-images.githubusercontent.com/46445679/73020474-fbf3ea80-3e25-11ea-8142-fcefffa804f1.jpg)

**Comment by alesoft73** [comment]
![Screenshot_2020-01-23-23-03-07-431_com android chrome](https://user-images.githubusercontent.com/46445679/73027912-ad018180-3e34-11ea-83e5-8144222ecd1e.jpg)

**Comment by alesoft73** [comment]
Many thanks, in version 3.10 bluetooth work perfect.
I love you :-)

**Comment by alesoft73** [comment]
> 
> 
> This it work better with 4.0? `hassio os update --version 4.0`

Many thanks, in version 3.10 bluetooth work perfect.
And  have test with bluetootrh dongle with broadcom! perfect too!
I love you :-)
