### ISSUE TITLE
HassOS 3.10 does not ship  Kernel 4.19.102 as mentioned.

### ISSUE THREAD

**Issue by vandalon** [home-assistant/operating-system#580]
➜  ~ hassio hassos info      
board: rpi4
boot: B
version: "3.10"
version_cli: "16"
version_cli_latest: "16"
version_latest: "3.10"
➜  ~ uname -a
Linux a0d7b954-ssh 4.19.93-v7l #1 SMP Mon Feb 10 06:47:22 UTC 2020 armv7l Linux
➜  ~ uptime  
 14:26:53 up 8 min,  load average: 1.08, 1.10, 0.73

**Comment by pvizeli** [comment]
Yeah, RPi have his own downstream kernel. I fix the changelog

**Comment by vandalon** [comment]
Ok, but when I check the rpi kernel on github they are also at .102. What upstream are you using? (just out of curiosity, there are some fixes in .102 in regards to overclocking.).
