### ISSUE TITLE
bootchooser not working (USB boot on NUC)

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/operating-system#583]
**HassOS release with the issue:**
3.10 stable

using Intel dn2820fykh NUC:

when booting from usb (wrote the Etcher image); the Hassos boot menu is shown. However, booting is not working..
Am i doing something wrong?  I've updated bios, formatted the SSD to NTFS.

![image](https://user-images.githubusercontent.com/3382443/74414581-fa747b80-4e41-11ea-80c4-888dea20294c.png)

**Comment by marine1988** [comment]
same problem here!

**Comment by SamJongenelen** [comment]
FIY: I ended up with Ubuntu with Docker

**Comment by pvizeli** [comment]
It just works over a native UEFI block storage protocol.

**Comment by ericlamotte** [comment]
This is happening to me on my NUC7i3BNH (updated BIOS) with HassOS 3.13. Sometimes I can get it to work for a few boots before it stops booting. Can you explain more, pvizeli?

**Comment by BigDoom** [comment]
Had the exact same issue; this post helped me: https://community.home-assistant.io/t/my-steps-to-success-for-hass-io-on-intel-nuc/43915/356

What I ended up doing was to take out the SSD from my NUC, connect it to my laptop, directly load the HassOS image for NUC onto the SSD, but it back into my NUC, booted and everything started like it should. 

Perhaps it works for you as well.
