### ISSUE TITLE
FTP Add-on pulling incorrect time information for file modification info

### ISSUE THREAD

**Issue by JimmyJones79** [home-assistant/operating-system#595]
I already posted this on the FTP add-on Git and was directed here from the creator since his add-on gets it's time info from Hass.

I am on the East coast of the US in the Easter Time Zone, my Raspberry Pi 3b+ is running the latest updated version of Hass.io (Home Assistant).

For some reason the FTP Add-on is showing file creation times as if it was Hawaiian time instead of East Coast time. This is weird because Hassio and the Raspberry OS are showing the correct time.

**Expected behavior**
Show the file creation time as Eastern Time

**Actual behavior**
file creation time is the Hawaiian time zone

See the screen shot attached.  On the left you will see Hass's time at 15:01 (3:01pm) on the right you will see the last directory was created at 10:00am, However this just happened at 3pm.  For some reason the FTP server is using Hawaiian time.

![Timezone](https://user-images.githubusercontent.com/43500955/74976020-fde5a500-53f5-11ea-95a0-0bdc4663e0f6.JPG)

**Comment by pvizeli** [comment]
This is for Home Assistant OS and not Raspberry OS. Please open a issue on Raspberry Pi

**Comment by JimmyJones79** [comment]
It is Home Assistant OS running on a Raspberry Pi 3b+
