### ISSUE TITLE
Unable to install with latest raspberry images

### ISSUE THREAD

**Issue by martinscholz83** [home-assistant/operating-system#599]
**HassOS release with the issue:**
3.11

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**
I'm trying to flash sd card with the latest raspberry images. When i insert the card into the raspberry nothing happens. When looking on the sd card it looks like this
<img width="721" alt="Bildschirmfoto 2020-02-17 um 12 58 36" src="https://user-images.githubusercontent.com/19551763/75575111-cb742180-5a5f-11ea-9704-767846a57d26.png">
This also happened with 3.10 release.

**Comment by ptoulouse** [comment]
Same issue here. Flashed a 64GB  SD with 3.11.  The Pi does not start. No output on HDMI. The Pi is wired to ethernet and does not get an IP from the router. Tested the SD card by flashing Raspbian-lite on it and it boots fine, so not an SD card issue.

**Comment by ptoulouse** [comment]
Tried again with 3.12 and I have the same issue.
