### ISSUE TITLE
how to login to shell on host system

### ISSUE THREAD

**Issue by byte4geek** [home-assistant/operating-system#602]
when i type "login" to access to the shell on host system i have an automatic logout.
i'm using hassos 3.11

sh: /usr/bin/xauth: not found
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
 _    _                                         _     _              _
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ ` _ \ / _ \   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|

Welcome on Home Assistant command line.

For more details use 'help' and 'exit' to close.
If you need access to host system use 'login'.

ha > login
[cmd] /bin/cli.sh exited 10
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by KingJ** [comment]
This has been fixed in version 21 of the HassOS CLI, see https://github.com/home-assistant/hassos-cli/pull/10 .

If you run `os update-cli` and then reconnect once completed, you should now be able to use the `login` command.
