### ISSUE TITLE
OrangePi Prime support dropped

### ISSUE THREAD

**Issue by deece** [home-assistant/operating-system#608]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

It looks like OrangePi Prime support was dropped in commit dc4ee618097ddec7a081217a3162fbe43f17b3ab

This has the side-effect of breaking HassOS/HassIO upgrades for these machines (I have a few instances running across different properties).

Could we add them back please? If not, can you please advise how to switch HassIO over from using image=homeassistant/orangepi-prime-homeassistant to image=homeassistant/qemuarm-64-homeassistant?

**Comment by pvizeli** [comment]
There was no maintainer for it, and the hardware was dropped by manufacture. We now have a new policy: no orange pi hardware / too many defects, and the support by the manufacture is just horrible.
