### ISSUE TITLE
intel NUC i219-v NIC support?

### ISSUE THREAD

**Issue by dick902** [home-assistant/operating-system#618]
**HassOS release with the issue:**
0.107.7

**Operating environment (HassOS/Generic):**
HassOS, Intel NUC10FNH with 250GB SSD 32G RAM

**Supervisor logs:**
N/A

**Journal logs:**
N/A

**Kernel logs:**
N/A

**Description of problem:**
The onboard intel i219-V NIC was not detected on boot up, the installation hang and cannot continuous.
Can this be fix?

**Comment by dlo747** [comment]
same issue. i219-v NIC. NUC Hassio image 4.8 on NVME not recognizing network
