### ISSUE TITLE
HassOS /addons directory is empty even after some HassIO addons are installed

### ISSUE THREAD

**Issue by PieBru** [home-assistant/operating-system#634]
**HassOS release with the issue:**

HassOS = 3.13
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7l
python_version | 3.7.7
timezone | Europe/Rome
version | 0.108.8
virtualenv | false

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

[44592.523772] sd 0:0:0:0: [sda] 243728384 512-byte logical blocks: (125 GB/116 GiB)
[44592.526316] sd 0:0:0:0: [sda] Write Protect is off
[44592.529151] sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
[44592.529410] sd 0:0:0:0: [sda] No Caching mode page found
[44592.532306] sd 0:0:0:0: [sda] Assuming drive cache: write through
[44592.540617]  sda: sda1

**Description of problem:**
Willing to access `/dev/sda` for offline backup purposes (`rpi-clone`), as described by `NotoriousBDG` [here](https://community.home-assistant.io/t/how-to-mount-a-usb-thumb-drive-external-storage-in-hassio-and-add-ons/44090/5) I looked for `config.json` of the SSH addon, but the directory `/addon` is empty, while `/backup`, `/config`, ..., are populated with the corresponding content.

`/addon` is mounted by HassOS as:
```
/dev/mmcblk0p8 on /addons type ext4 (rw,relatime)
```
Also, I coudn't `find` the above `config.json` in the filesystem visible as SSH root.

So:
1. How can I access the HassOS after-installation addons configs?
2. There is another way yo map RasPI HassOS USB devices so they are visible to the SSH addon apps?

NOTE: I experienced this problem on HassOS with all the addons I use to access the host file-system, such as ssh, ftp, samba, so I open the issue here instead of in the ssh addon repo.

Thank you all for the great HASS ecosystem,
Piero

**Comment by frenck** [comment]
The add-ons folder is for accessing/creating custom / your own add-ons, and if you don't have any of those, it is supposed to be empty.

Add-ons from the store are shipped as pre-build Docker containers.
