### ISSUE TITLE
Boot from USB on Odroid N2

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/operating-system#654]
Hi. Is any plans when will be implement to operating system for Odroid N2 option to boot from USB ? Now we can use SDCard and eMMc. Good option will be also USB to use USB SSD disk which is sometime faster than eMMC.

**Comment by pvizeli** [comment]
Read https://github.com/home-assistant/operating-system/blob/dev/Documentation/partition.md

it will not more support as that

**Comment by pepeEL** [comment]
I read but dont understand... I am not an exprert.
Summary
It is no possible to implement boot from usb on this Odroid N2?
It is probably the Best hasrdwear for Home Assistant. But we must use eMMC or MicroSD. But SSD is better and faster... 
Also boot is not possible by Petiboot on Odroid N2?

**Comment by pepeEL** [comment]
please explaine me ....

**Comment by bramkragten** [comment]
You can move your data partition to an external USB hard drive with `datactl move /dev/xxx`

**Comment by pepeEL** [comment]
Better will be implement option to install on USB as example for RPI and boot from USB

**Comment by bramkragten** [comment]
No

**Comment by pepeEL** [comment]
But it is technical not possible ?

**Comment by frenck** [comment]
Your question was answered now, multiple times. Locking this issue.
