### ISSUE TITLE
Offering downgrade (to 3.13) as an upgrade (from 4.6)

### ISSUE THREAD

**Issue by maretodoric** [home-assistant/operating-system#674]
HassOS release with the issue: 4.6
**Supervisor logs:

> ~ $ ha su logs
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
>     resp = await task
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/security.py", line 157, in token_validation
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/utils.py", line 61, in wrap_api
>     answer = await method(api, *args, **kwargs)
>   File "/usr/src/supervisor/supervisor/api/addons.py", line 293, in options
>     body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
>   File "/usr/src/supervisor/supervisor/api/utils.py", line 121, in api_validate
>     data_validated = schema(data)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
>     return base_validate(path, iteritems(data), out)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
>     cval = cvalue(key_path, value)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
>     return self._exec(self._compiled, value, path)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
>     return func(path, v)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
>     return schema(data)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
>     return self._exec(self._compiled, value, path)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
>     v = func(path, v)
>   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
>     return schema(data)
>   File "/usr/src/supervisor/supervisor/addons/validate.py", line 354, in validate
>     options[key] = _nested_validate_list(coresys, typ[0], value, key)
>   File "/usr/src/supervisor/supervisor/addons/validate.py", line 421, in _nested_validate_list
>     for element in data_list:
> TypeError: 'NoneType' object is not iterable
> 20-05-15 09:48:28 INFO (SyncWorker_8) [supervisor.docker.interface] Clean addon_local_openvpn-client application
> 20-05-15 09:48:28 INFO (SyncWorker_8) [supervisor.docker.addon] Start Docker add-on local/amd64-addon-openvpn-client with version 0.2.9
> 20-05-15 09:48:46 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_local_openvpn-client application
> 20-05-15 09:48:47 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on local/amd64-addon-openvpn-client with version 0.2.9
> 20-05-15 09:49:37 INFO (SyncWorker_9) [supervisor.docker.interface] Clean addon_local_openvpn-client application
> 20-05-15 09:49:38 INFO (SyncWorker_9) [supervisor.docker.addon] Start Docker add-on local/amd64-addon-openvpn-client with version 0.2.9
> 20-05-15 09:54:19 INFO (SyncWorker_5) [supervisor.docker.interface] Clean addon_local_openvpn-client application
> 20-05-15 09:54:19 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on local/amd64-addon-openvpn-client with version 0.2.9
> 20-05-15 09:56:12 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/core_configurator
> 20-05-15 09:56:12 INFO (SyncWorker_8) [supervisor.docker.interface] Pull image homeassistant/amd64-addon-configurator tag 5.0.0.
> 20-05-15 09:56:19 INFO (MainThread) [supervisor.addons] Add-on 'core_configurator' successfully installed
> 20-05-15 09:56:36 INFO (SyncWorker_3) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-configurator with version 5.0.0
> 20-05-15 09:58:36 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-05-15 10:02:32 INFO (SyncWorker_4) [supervisor.docker.interface] Restart homeassistant/qemux86-64-homeassistant
> 20-05-15 10:02:47 INFO (MainThread) [supervisor.homeassistant] Home Assistant pip installation in progress
> 20-05-15 10:03:07 INFO (MainThread) [supervisor.homeassistant] Home Assistant pip installation done
> 20-05-15 10:03:12 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
> 20-05-15 10:05:13 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_configurator
> 20-05-15 10:07:23 INFO (SyncWorker_13) [supervisor.docker.interface] Restart homeassistant/qemux86-64-homeassistant
> 20-05-15 10:07:43 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
> 20-05-15 10:13:22 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_ssh
> 20-05-15 10:13:36 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_ssh
> 20-05-15 10:28:56 INFO (SyncWorker_5) [supervisor.docker.interface] Restart homeassistant/qemux86-64-homeassistant
> 20-05-15 10:29:17 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
> 20-05-15 11:09:14 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.host.info] Update local host information
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.host.services] Update service information
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.host.network] Update local network DNS information
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
> 20-05-15 11:15:54 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
> 20-05-15 11:34:54 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-05-15 12:09:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
> 20-05-15 12:09:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
> 20-05-15 12:09:16 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
> 20-05-15 13:09:14 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.host.info] Update local host information
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.host.services] Update service information
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.host.network] Update local network DNS information
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
> 20-05-15 13:22:34 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
> 20-05-15 15:09:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
> 20-05-15 15:09:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
> 20-05-15 15:09:14 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
> 20-05-15 15:09:16 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.host.info] Update local host information
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.host.services] Update service information
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.host.network] Update local network DNS information
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
> 20-05-15 15:29:14 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
> 20-05-15 16:19:55 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-05-15 17:06:16 INFO (SyncWorker_13) [supervisor.docker.interface] Restart homeassistant/qemux86-64-homeassistant
> 20-05-15 17:06:37 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
> 20-05-15 17:09:14 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
> 20-05-15 17:13:11 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from core_ssh
> ~ $

Journal logs: This command is not available in HassOS SSH
Kernel logs: It's large but i don't believe it's necessary here due to the nature of the bug.
Description of problem:
I'm using qcow image of HassOS and inside Supervisor panel (Dashboard tab) it's offering me to "upgrade" to 3.13" and it's clearly saying right underneath " You are currently running version 4.6 "
I don't know why is it reading 3.13 as an upgrade, or there is another versioning system implemented here?

**Comment by frenck** [comment]
It works based on a stability channel.
The current latest stable is 3.13, so you are on the stable channel right now, while running a beta release. It will offer an "upgrade" to stable.

If you want to follow beta, switch to the beta channel. You can enable it by going to the Supervisor panel -> System -> Join beta.
