### ISSUE TITLE
Enable 9p VIRTIO kernel module

### ISSUE THREAD

**Issue by JumpMaster** [home-assistant/operating-system#676]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**
As part of a migration from a Supervised Linux install to HASSOS on KVM I am missing the ability to share a directory with the host os.  This is possible within KVM but the OS is missing the required 9p kernel module.  This leads to the following error when trying to mount:

mount -t 9p -o trans=virtio,version=9p2000.L hostshare /tmp/host_files
mount: unknown filesystem type '9p'

I believe the two required module are 9pnet and 9pnet_virtio

**Comment by JumpMaster** [comment]
I've been thinking more about this and it's probably a lot more work then I originally anticipated to have this fully supported.  ie. Been able to mount directories from within the supervisor ui.

**Comment by xiki808** [comment]
I would love to see this. I am currently trying to setup HAOS in an LXD VM and it works, but I cannot run any commands inside the VM from my bash script running at the host, since the agent is missing in the OS
