### ISSUE TITLE
OVA - running 4.7 but version_latest shows 3.13

### ISSUE THREAD

**Issue by SimplyRun** [home-assistant/operating-system#686]
**HassOS release with the issue: 4.7

```
arch: amd64
channel: stable
docker: 19.03.8
hassos: "4.7"
homeassistant: 0.110.2
hostname: hassio
logging: info
machine: qemux86-64
supervisor: "224"
supported_arch:
- amd64
- i386
```

**Supervisor logs:**

no errors, so not needed?

**Journal logs:**

no errors, so not needed?

**Kernel logs:**

no errors, so not needed?

**Description of problem:**
In Supervisor the latest OS Version is displayed as: 
Operating System 3.13
You are currently running version 4.7

command:
`➜  ~ ha os info`
board: ova
boot: A
version: "4.7"
version_latest: "3.13"

Did I miss something or is this an issue?

**Comment by Marlor** [comment]
4.7 is marked as stable but not released, just wait.
https://version.home-assistant.io/stable.json
