### ISSUE TITLE
Not bootable odroid N2 after upgrade from 4.6 to 4.7

### ISSUE THREAD

**Issue by liudger** [home-assistant/operating-system#692]
**HassOS release with the issue:**
 v 4.7

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

After updating using the supervisor the system is not booting at all. So no logs.

**Comment by pvizeli** [comment]
fix on 4.8

**Comment by pvizeli** [comment]
You can replace this file on the boot partition to make it working: https://drive.google.com/open?id=13uMbfZeM_TTQdEmiWUFinW-fFDwiSBXf

**Comment by liudger** [comment]
The link is protected?  Need verification. I already flashed the firmware on the eMMC. So I’ll wait for the compile of 4.8

**Comment by liudger** [comment]
Thanks the new firmware works!
