### ISSUE TITLE
Update to 0.110.3 - HACS Error

### ISSUE THREAD

**Issue by brianrozs5br** [home-assistant/operating-system#700]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**
[[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
12:39:24 PM – custom_components/hacs/hacsbase/data.py (CRITICAL)
JSON file reading failed: /config/.storage/hacs/120370503.hacs
12:39:24 PM – util/json.py (ERROR)

**Comment by frenck** [comment]
Hi there @brianrozs5br, thanks for opening up an issue.

Unfortunately, HACS is not supported by Home Assistant.

Please file your issue with the HACS issue tracker. Thanks! 👍
