### ISSUE TITLE
update to 4.8 failed

### ISSUE THREAD

**Issue by ohadlevy** [home-assistant/operating-system#710]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Hi,

I've just upgrade to 4.8 and my RPI stopped working, it seems none of the containers were able to start.

I had ssh debugging (not the ssh addon) enabled, and when trying to ssh i get
```
ssh root@haas -p 22222 
sh: /usr/bin/xauth: not found
Error: No such container: hassio_cli
Shared connection to haas closed.
```

any guidance on how to move forward, or must i revert to a snapshot?

**Comment by alexisml** [comment]
+1 my raspy won't boot after the update

**Comment by balloob** [comment]
We've released 4.9 with fixes. Give it a try: https://github.com/home-assistant/operating-system/releases/tag/4.9

**Comment by ohadlevy** [comment]
@balloob  thanks, can you suggest the procedure to upgrade from this stage? is there a way to put the new image on the sd card via a linux machine?

**Comment by ghitchen** [comment]
> @balloob thanks, can you suggest the procedure to upgrade from this stage? is there a way to put the new image on the sd card via a linux machine?

https://www.raspberrypi.org/documentation/installation/installing-images/linux.md

**Comment by ohadlevy** [comment]
thanks, but thats not what I had in mind... resolved anyway..
