### ISSUE TITLE
Disk usage increases very rapidly after latest updates

### ISSUE THREAD

**Issue by tosion** [home-assistant/operating-system#711]
I have realized in my systems running Homeassistant in NUC (NUC image) that disk usage increases very rapidly. I think this happened within few days ago after updates with supervisor 226/HassOS 4.8/Grafana/Influx to latest versions.

For a long time my system monitor showed around 4 GiB used and 99 Gib free. Now it shows 7 GiB used and 96GiB free?

Below the status of my two NUCs with Disk Use in 7 days and one more chart below for 90 days

![image](https://user-images.githubusercontent.com/48414735/83681429-123b5f80-a5eb-11ea-8ce0-0a1db83d2323.png)

![image](https://user-images.githubusercontent.com/48414735/83681381-fe8ff900-a5ea-11ea-8e65-a495b9cb0107.png)

![image](https://user-images.githubusercontent.com/48414735/83684394-9ee81c80-a5ef-11ea-8831-449329b9d626.png)

**Comment by brinzlee** [comment]
There is a memory leak somewhere....I'm noticing the same issue this was HassOS 4.8

**Comment by tomlut** [comment]
Yeah I've noticed an increase of ~5GB disk use per day since updating. My disk use was essentially flat for months before the update to 4.8. 
Using HassOS NUC image.

**Comment by frenck** [comment]
Any indication on where the disk space grows? As in, a specific folder?

**Comment by tomlut** [comment]
No not yet. It does not appear to be in /config. Or swapfile.

Apologies but I overstated my issue.

I thought I had a 500G SSD but it's only 125G. So the 1% increase today was only 1GB not 5GB. And it seems to have stopped increasing.

**Comment by tosion** [comment]
I would like to help but I am not sure what to look for. Wit Win10/Samba I do not see too much. When connected thru RPI3B+/Rasbian (maybe first time in my life - I see this - But what to look, that's a question) 

![image](https://user-images.githubusercontent.com/48414735/83687447-71ea3880-a5f4-11ea-8d82-86dd27765700.png)

**Comment by mbo18** [comment]
I have the same issue, NUC, HA OS 4.8, HA 110.4. Growing by 220Mb per day (including 30Mb per day for my DB)
I did not find what's taking so much space. It does not seems to be an add-on as I have removed them all (except deconz) and re-installed them later

**Comment by tomlut** [comment]
At the CLI try:
```
du -sh /*
```
To get a list of directory sizes.

**Comment by tosion** [comment]
This?

![image](https://user-images.githubusercontent.com/48414735/83688661-6c8ded80-a5f6-11ea-8f7f-7af7c20830cf.png)

**Comment by mbo18** [comment]
Did it also in / using SSH Add-on from Franck. Made a diff a day later and only changed I saw is the size of the config folder due to my DB growing

**Comment by boekhorstr** [comment]
I have noticed the same issue since the upgrade to HassOS 4.8. A little investigation led me to the systemd journals in /mnt/data/logs. In a few days time it grew to 4GB. 

![image](https://user-images.githubusercontent.com/52204703/83691258-2d5d9d80-a5f2-11ea-8445-cc55d55d147e.png)

So I wondered if this is normal/desired behaviour. But it seems that size limitations on the systemd journal config (/etc/systemd/journald.conf) have been removed in #649

**Comment by balloob** [comment]
We made this change to align how other operating systems like Raspbian and Debian configure systemd. By limiting things we lose important logs that help with debugging.

Limiting used size would not help in reducing disk writes, as the `MaxUse` settings would remove old logs, while new logs are still written to disk.

For the default settings that apply now, see https://www.freedesktop.org/software/systemd/man/journald.conf.html#SystemMaxUse=

**Comment by tosion** [comment]
Thanks for this valuable piece of info!
 
If anyone knows is this disk use just going increase or stop somehow, I would appreciate that info also.

**Comment by balloob** [comment]
It's in the docs I linked :)

**Comment by tosion** [comment]
I tried my best to read it but with my background (you would be surprised how far I have gone with this HA as a passenger with no idea how to drive - many thanks for you guys!) understanding part was a bit difficult ;-)

**Comment by mbo18** [comment]
If I understand correctly, 10 and 15% of the file system size with a maximum of 4Gb

`The first pair defaults to 10% and the second to 15% of the size of the respective file system, but each value is capped to 4G `

**Comment by balloob** [comment]
This part is also important: "something else causes the file system to fill up, journald will stop using more space"

**Comment by tosion** [comment]
Excellent - so I have plenty of room with my 120 G SSD ... and nothing to worry about

**Comment by aechelon** [comment]
Is there an easy way to restore the original MaxUse settings for journald.conf?
Looks like the file system is mounted read-only.

**Comment by aechelon** [comment]
This change is rather annoying for those of us who run HASSOS inside a VM and keep that image lean to accelerate snapshots.

Would it be possible to get an option to configure the MaxUse variables (or Storage=volatile) through the supervisor or even through ssh?

For those who are interested in a temporary solution, once you have ssh access to the host (see [here](https://developers.home-assistant.io/docs/operating-system/debugging/)) you can recreate the original journald.conf on a writable portion of the file system (e.g. under /root/), and then replace the default journald.conf with the modified version using mount -o bind.  Once that's done just reload journald:

```
mount -o bind /root/journald.conf /etc/systemd/journald.conf
systemctl force-reload systemd-journald
```

I've tried to get this running at boot through udev rules (see [here](https://community.home-assistant.io/t/solved-how-to-include-a-script-to-initialize-usb-device-on-hass-io-hassos-startup/93987)) but systemd-udev won't persist the mount outside the udev rule without mountflags=shared, so for now I'm stuck running the script manually after reboots (which luckily are infrequent).

**Comment by CarlosGS** [comment]
@aechelon I'm stuck here as well, did you find a long term solution?

The journald.conf default parameters are incorrect.

**Comment by aechelon** [comment]
Not yet.  Currently I have to remember to run a script that does the _mount -o bind_ on the host whenever I reboot the VM.  Luckily recently I haven't had to reboot very often.
I took the time to shrink the VM as much as possible and I keep an eye on the size of the backups I perform before any major upgrade.

**Comment by hosoludi** [comment]
Same Problem here

**Comment by soundslikeluke** [comment]
I am running on a Nuc On a VM and my storage has gone up to 300GB and I really dont know what is using it. The Home-assistant_v2.db is 29gb but that doesnt explain the 300GB disk ussage.

**Comment by RobertusIT** [comment]
> I am running on a Nuc On a VM and my storage has gone up to 300GB and I really dont know what is using it. The Home-assistant_v2.db is 29gb but that doesnt explain the 300GB disk ussage.

same here and no one, know how to fix it. is very annoing

**Comment by agners** [comment]
As state above, the journal grows to a 4GB max.

@RobertusIT  if your system fills up 300GB, there must be another reason and it probably warrants a separate issue/investigation. What add-ons are you using?

As for option to set size for the journal: TBH, what is 4GB these days? I think its well worth the debugging capabilities it brings.

**Comment by RobertusIT** [comment]
> As state above, the journal grows to a 4GB max.
> 
> @RobertusIT if your system fills up 300GB, there must be another reason and it probably warrants a separate issue/investigation. What add-ons are you using?
> 
> As for option to set size for the journal: TBH, what is 4GB these days? I think its well worth the debugging capabilities it brings.

![image](https://user-images.githubusercontent.com/11599774/129876345-94ef36bb-33f2-4523-8764-7908d917d076.png)

As you can see, i have only some plugin actived.

Frigate get audio and video, but system, grow up since without frigate, so isn't frigate the problem.
As you can see, frigate, get only 3GB for now
![image](https://user-images.githubusercontent.com/11599774/129876721-47bf8982-bac9-4488-807e-f6d5971aa4d8.png)

My HA proxmox
![image](https://user-images.githubusercontent.com/11599774/129876844-cc0bc882-2557-4eb6-a7db-3cdcc9891916.png)

And my local-lvm, as you can see, very annoing that grow up a lot
![image](https://user-images.githubusercontent.com/11599774/129876978-107eb543-9be5-47cf-954e-28516985a58c.png)

33.44GB of what ? :(

Every monday, you can see a decrease of space used, because i create a service with fstrim -a:
```
# systemctl 
fstrim.timer                                                                                           loaded active waiting   Discard unused blocks once a week 
```
I have also, for now, recorder in **configuration.yaml**:
`  purge_keep_days: 1`

How can i figure out ?

Thanks to reply

**Comment by it4rz4n** [comment]
Did you ever figure this out? I have the exact same issue.

**Comment by mofonics** [comment]
Did this get solved? I have the same problem

**Comment by LookInIs** [comment]
Did this get solved? I have the same problem

**Comment by jgoakley** [comment]
Still having this problem as well.

Running a bare-metal x86-64 install with a 128GB SSD and /mnt/data/logs grew to 53.4 GB leaving less than 5% of the disk available. Currently on HAOS 14.1.

Only just realized it when one of my backups failed due to lack of storage space.

![Image](https://github.com/user-attachments/assets/f777ac0e-3c93-4085-8cbd-bcf2d7d298d7)

![Image](https://github.com/user-attachments/assets/4bcecfc5-978a-4230-9614-f7965a6c3e30)
