### ISSUE TITLE
HassOS 4.9 won't install on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by chriselera** [home-assistant/operating-system#714]
**HassOS release with the issue:**
4.9

**Supervisor logs:**
N/A

**Journal logs:**
N/A

**Kernel logs:**
N/A

**Description of problem:**
HassOS 4.9 won't install on Raspberry Pi 3b+.  Downloaded 4.9 image, flashed to SD card using Balena Etcher, plugged in to Pi3.  Installation process does notstart and http://<Pi's Ip address>:8123 is unreachable even after 10 minutes.  Checked on router and Pi 3 is not online.  Note: this is the same issue with 4.7 and 4.8.

Flashed 3.13 to the same SD card and HassOS installs fine on the same Pi 3.

**Comment by Visje31** [comment]
I'm having the same issue.
Update of HassOS doesn't work. Not from the interface nor from the shell.
There is enough disk space, only way back is to cut the power, disconnect the pi and remove the SD-card. After that when trying to reboot the OS will revert to version 3.13.
(I know, sounds silly, but only that way I get the OS to revert without flashing the card again.)

**Comment by Br4v3St4rr** [comment]
Also having the same issue.  Attempt to log into CLI reports

`Error: No such container: hassio_cli`

Same fix as @Visje31, not sure about removing the SD Card but a couple of powercycles reverted it.

**Comment by brusarp** [comment]
@Visje31 and @Br4v3St4rr are you talking about upgrading to 4.** 8 ** or 4.** 9 ** version?

**Comment by pverberckmoes** [comment]
I've got the same.
Manual update won't work because the 4.9 version is not visible.
(
![HassOS](https://user-images.githubusercontent.com/45134041/83729199-9cb1ac80-a647-11ea-83fe-bf06a20e0d3f.png)

)

**Comment by Visje31** [comment]
I was upgrtading from 3.13 to the latest 4.9 version

**Comment by Tom-ahawk** [comment]
I have tried 4 times now,  upgrading from 3.13 to the latest 4.8 version. Every time I have to restart 3 times to go back  to 3.13.

**Comment by brusarp** [comment]
This issue was opened for 4.**9**
Don't go OT...

**Comment by Sagitr** [comment]
After upgrade to 4.8 RPI4 and 4.9 the system will no longer boot. Not visible on the network. Just the end. Many users have this problem. reinstallation from an older backup will help. :(

**Comment by 0plus6** [comment]
> 
> 
> I have tried 4 times now, upgrading from 3.13 to the latest 4.8 version. Every time I have to restart 3 times to go back to 3.13.

Same. 4.8 or 4.9, doesn't matter. Claims installed, reboots and still 3.13.

**Comment by schusz** [comment]
Powercycling 5 times worked for me to revert HassOS v3.13.

**Comment by phcella** [comment]
I'm on 4.8 and now it's saying to "upgrate" to 3.13.  Is it right?

**Comment by pverberckmoes** [comment]
> I'm on 4.8 and now it's saying to "upgrate" to 3.13. Is it right?
I've got the same. Expected to see 4.9 but did the downgrade. System is stable now and I'm waiting for 3.9 and some positive reviews before upgrading.

**Comment by TopoDiFogna** [comment]
> I'm on 4.8 and now it's saying to "upgrate" to 3.13. Is it right?

Same here, there's the 4.9 for rpi3 but the system doesn't detect it and instead suggests 3.13.

**Comment by Adorem** [comment]
IDK why but yes for now for rpi2 and rpi3 the version is now back to "3.13".
https://version.home-assistant.io/beta.json

**Comment by TopoDiFogna** [comment]
Also for stable version, noticed that rpi3 64bit is 4.9

https://version.home-assistant.io/stable.json

**Comment by balloob** [comment]
We've set it back to 3.13 while we address some of the issues that have come up.

**Comment by pvizeli** [comment]
Fix with 4.10

**Comment by Adorem** [comment]
Tested just now 4.10 on my rpi and it's working fine this time. Thanks :+1:

**Comment by phcella** [comment]
Working like a charm for me too. Thanks

**Comment by Visje31** [comment]
Works great! thanks!
