### ISSUE TITLE
No Raspberry Pi 2 upgrade to 4.9?

### ISSUE THREAD

**Issue by slim0287** [home-assistant/operating-system#715]
There doesn't appear to be a Pi2 version available for HassOS 4.9 despite one of the "Changed" items being "Fix issue with RPi2 armhf / armv7."  I see _rpi, _rpi0, _rpi3, _rpi4 however _rpi2 is missing.

**Comment by martymarty004** [comment]
I have the same question

**Comment by martymarty004** [comment]
@slim0287  It's out now, probably they had to finish compiling it

**Comment by balloob** [comment]
Each board needs to be build separately, it takes time. You can follow releases here https://dev.azure.com/home-assistant/Operating-System/_build?definitionId=58

**Comment by bcmitri** [comment]
> Each board needs to be build separately, it takes time. You can follow releases here https://dev.azure.com/home-assistant/Operating-System/_build?definitionId=58

Not to be impatient, but how long does this normally take?  I'm still only seeing 3.13 for the rpi 2 and rpi 3.
