### ISSUE TITLE
A request to upgrade 4.9  with v. 4.8? 

### ISSUE THREAD

**Issue by jrhodk** [home-assistant/operating-system#717]
![48_49](https://user-images.githubusercontent.com/541646/83773551-f1274d00-a684-11ea-8c56-14bad74c289e.png)

**HassOS release 4.9 with the issue:** 

- to "upgrade" to version 4.8?

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

**Comment by allanpersson** [comment]
It's because it's not released yet, except in dev 🙏

**Comment by allanpersson** [comment]
See:
https://version.home-assistant.io/stable.json
https://version.home-assistant.io/beta.json
https://version.home-assistant.io/dev.json

And actually it's not even in dev yet 🙏

**Comment by jrhodk** [comment]
Thanks but in the stable json it says: 
odroid-n2 | "4.9"

**Comment by allanpersson** [comment]
It the moment of my reply it didn't 🙏
