### ISSUE TITLE
HaasOS 4.9->4.10 upgrade via Supervisor - Suspected Memory Leak

### ISSUE THREAD

**Issue by Warlord1390** [home-assistant/operating-system#730]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

Home assistant inside of ESXi host memory usage jumped from 2GB to maxing out the instance to 4GB, after restarting the VM the memory usage dropped down to 1.5GB Suspect a memory leak in the supervisor method of upgrading.

I noticed impact while trying to connect through the iOS client on my phone directly to the server (self hosted domain).

**Comment by pvizeli** [comment]
No changes for OVA between 4.9 - 4.10
