### ISSUE TITLE
RPI4 boot USB

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/operating-system#743]
Hi
Is any chance to when we have beta Firmware with boot option USB on  RPI4 to write image on SSD and then connect it to USB and boot from USB ? Similary as on RPI3....

**Comment by VR29** [comment]
According to [https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/release-notes.md](url) it is on stable now.

**Comment by pepeEL** [comment]
correct link

**Comment by VR29** [comment]
Corrected

**Comment by pepeEL** [comment]
But when it share stable it was also correct image to option only burn on ssd and connect to USB and it willl be working ?

**Comment by pvizeli** [comment]
Duplicate of #164
