### ISSUE TITLE
GuruMeditation Hard Crash on Update - VINF_EM_TRIPLE_FAULT

### ISSUE THREAD

**Issue by jhuang0** [home-assistant/operating-system#748]
**HassOS release with the issue:**
4.10

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

https://pastebin.com/FzRXCUVi
Error occurs on line 1504

**Description of problem:**
I'm running HassOS in a Windows 10 Virtual Machine hosted in Oracle VirtualBox. I've attempted to user the Supervisor to update my HassOS from 3.13 to 4.10 twice and have crashed out twice with GuruMeditation faults. 

VM Spec: 2560 MB RAM (32 GB system), 4 CPU cores (AMD 2700x), 32 GB storage allocated.

**Comment by balloob** [comment]
This is an issue with your VirtualBox installation.
