### ISSUE TITLE
intel_nuc image doesn't boot when flashed on the emmc of the odroid H2+

### ISSUE THREAD

**Issue by tidalf** [home-assistant/operating-system#763]
Hello, 

I've tried to flash the intel nuc hass.img on the emmc of an odroid h2+, it doesn't work (stop waiting for root device because of the lack of mmc support).

Also the intel_nuc image doesn't provide the rtl8125 ethernet driver for the ports available in the device.

**Comment by balloob** [comment]
ODroid H2 is not currently supported.

**Comment by tidalf** [comment]
Hey Balloob,

it seems it's basically a cheap nuc, it works well with the above patch.

**Comment by balloob** [comment]
Correct, but we're not currently planning on extending our support for different boards. Each board that we officially adopt will need to be tested on every release that we do, and we lack the resources for that currently. We're hiring (#751) so this might change in the future.

**Comment by tidalf** [comment]
Oki !
