### ISSUE TITLE
No sound card detected under vmware

### ISSUE THREAD

**Issue by SilverWx** [home-assistant/operating-system#798]
I'm using vhdx image under VmWare Workstation, I've tested to connect virtual sound card but Hassos doesnnot recognize it :

**HassOS release with the issue:**
4.11 

**Supervisor logs:**

**Journal logs:**

**Description of problem:**
![image](https://user-images.githubusercontent.com/16896194/89123368-18f13080-d4cf-11ea-9871-0b131c3648f6.png)

Hardware description -> No sound card

serial:
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2118359-if00
/dev/ttyACM0
/dev/ttyS2
/dev/ttyS3
/dev/ttyS1
/dev/ttyS0
input:
AT Translated Set 2 keyboard
VMware VMware Virtual USB Mouse
ImPS/2 Generic Wheel Mouse
Power Button
disk:
gpio:
audio:

**Comment by SilverWx** [comment]
Commit  #770  seems to resolve it, wait for hassos update

**Comment by pvizeli** [comment]
Fix with 5.1
