### ISSUE TITLE
Bluetooth Drivers Realtek rtl 8761a missing 

### ISSUE THREAD

**Issue by SilverWx** [home-assistant/operating-system#821]
HassOS 4.12

**Description of problem:**
Drivers for bluetooth 5 adapter based on Realtek rtl 8761a is missing while is currently supported by linux 

![image](https://user-images.githubusercontent.com/16896194/90075589-1330f180-dcfe-11ea-8731-254508bc8e57.png)

Drivers can be downloaded here : https://mpow.s3-us-west-1.amazonaws.com/mpow_MPBH456AB_driver+for+Linux.tgz

**Comment by pvizeli** [comment]
- This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

**Comment by SilverWx** [comment]
It's not really a feature since bluetooth dongle are supported, the problem is all  bluetooth 5 dongle are not supported because of drivers missing
