### ISSUE TITLE
Add xen guest tools package to OS

### ISSUE THREAD

**Issue by rb2k** [home-assistant/operating-system#822]
We already seem to ship VMWare's open-vm-tools and the qemu agent with the operating system, it would be great if we could also add xen guest utilities. This would allow for a clean shutdown and better metrics.

The discussion came up here already:
https://github.com/home-assistant/operating-system/pull/265#issuecomment-671254522

The XCP-NG project's wiki on the topic:
https://xcp-ng.org/docs/guests.html#linux

The official repo is:
https://github.com/xenserver/xe-guest-utilities

I guess a fix would look similar to https://github.com/home-assistant/operating-system/pull/505/files

**Comment by resistr** [comment]
Not adding large value to this thread; but echoing the need for this. Thanks!

**Comment by pvizeli** [comment]
- This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

**Comment by rb2k** [comment]
Moved it to https://community.home-assistant.io/t/add-xen-guest-tools-package-to-hass-os/219573
