### ISSUE TITLE
Rock64 support

### ISSUE THREAD

**Issue by chrisrock1984** [home-assistant/operating-system#865]
Hello,

As I am running Hassio for 3 years on my Rock64 board I fear that the support of the docker version will end some day, as the warning in the System settings indicates.
Thats why I would like to ask if there are any plans to port Hassos to the Rock64?

Thanks!!

**Comment by balloob** [comment]
There are currently no plans. Feature requests should go to the [forums](https://community.home-assistant.io/c/feature-requests/13)

**Comment by chrisrock1984** [comment]
Thx for the info!
