### ISSUE TITLE
Worse performance than in docker

### ISSUE THREAD

**Issue by adrianmihalko** [home-assistant/operating-system#879]
**HassOS release with the issue:**

Frontend version: 20200918.2 - latest

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

https://pastebin.com/raw/d9N6ijrk

**Description of problem:**

In the last days I decided to switch from my good old, but now unsupported HA installation (with Frenck's script) to new in a standalone virtual machine. Here come the problem. For some reason with my ESXI the Hass.io official .vmdk is much slower than my old Ubuntu&HA installation in Docker. Bot has 4GB of memory, 2 CPU. 

Comparison:

https://www.youtube.com/watch?v=wSKjI_wDQgY

First tab: Ubuntu&HA
Second tab: Hass.io .vmdk

top is showing 0% cpu use and there is a lot of free memory:

<img width="920" alt="Screenshot 2020-09-26 at 14 35 40" src="https://user-images.githubusercontent.com/733361/94349346-dcabfd80-0043-11eb-8f08-e0ae143f87ee.png">

Theoretically it should be faster, because it has slimmer host OS, but in practice it is much slower and I simply don’t understand why.

**Comment by balloob** [comment]
Was your ubuntu installation also inside a VM?

**Comment by balloob** [comment]
Your video shows UI which has nothing to do with the backend. That's all rendered in the frontend.

**Comment by adrianmihalko** [comment]
Hi Paul,

Yes, the other installation was running on the same ESXI inside a VM:

![Screenshot_2020-09-26_at_22_40_41](https://user-images.githubusercontent.com/733361/94349956-db7dcf00-0049-11eb-942c-4e7b372e8bed.jpg)

The Ubuntu VM furthermore runs bunch of other software as well.

Hass.io VM is using minimal CPU & load is also low:

<img width="1023" alt="Screenshot 2020-09-26 at 22 46 46" src="https://user-images.githubusercontent.com/733361/94349995-3a434880-004a-11eb-8751-3906d7133f10.png">

<img width="972" alt="Screenshot 2020-09-26 at 22 48 15" src="https://user-images.githubusercontent.com/733361/94350014-64950600-004a-11eb-9e84-19bd76237399.png">

I literally have no idea what's casuing the slowness on the new VM. One more example: when I open up Unused entities, on the Ubuntu installation is fast and takes about 70%CPU (Developer tools - Timelines), but on new Hassi.io VM it takes 110% often page become blank and I get the usual This page is using significant memory. Closing it may improve...

Do you think that this is a front-end problem or a problem with my VM installation?

**Comment by balloob** [comment]
Unused entities does not query the backend. It's pure frontend.

**Comment by adrianmihalko** [comment]
Thanks, for now I am switching back to supervisored Ubuntu installation. If someone had any idea, please leave here a comment in the future.
