### ISSUE TITLE
HassOS on Proxmox - Issue with USB UPS Eaton

### ISSUE THREAD

**Issue by woody4165** [home-assistant/operating-system#880]
Home Assistant release with the issue:

Home Assistant 0.115.3
Operating environment (HassOS/Generic):

System HassOS 4.13
Supervisor logs:

Description of problem:

I used to have Hassio on Ubuntu on a Proxmox VM and I have an Eaton UPS connected via USB to an Intel NUC i3.
In this configuration all was working.

Then I decided to move (around version 0.113.x) to a VM with HassOS and since then I'm having issue with the NUT addon to connect to the UPS.

Device connected to USB port, but not seen in HassOS.
I've tried in a new RPi3 installation and all is working.

On Proxmox the device is enabled and seen:

![Schermata 2020-09-27 alle 16 48 33](https://user-images.githubusercontent.com/6501444/94367844-59d98000-00e1-11eb-86c1-7151a0d0e715.png)

I have also a Conbee stick that is correctly seen by Proxmox and by HassOS.

This is what I see in the Hardware section in HassOS

![Schermata 2020-09-27 alle 16 50 06](https://user-images.githubusercontent.com/6501444/94367894-973e0d80-00e1-11eb-8be5-40f5b780c2af.png)

And this is the error I get in the Host Log in the System page

```
[  377.272291] usb 2-2: new low-speed USB device number 3 using xhci_hcd
[  379.835404] usb 2-2: New USB device found, idVendor=0463, idProduct=ffff, bcdDevice= 1.00
[  379.836703] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=4
[  379.837923] usb 2-2: Product: Protection Station
[  379.838854] usb 2-2: Manufacturer: EATON
[  379.839756] usb 2-2: SerialNumber: XXXXXXXXX
[  379.843842] usb 2-2: can't set config #1, error -32
```

What can I check?

Thanks

**Comment by agners** [comment]
Hm, not sure this is HAOS related. I found this thread in Proxmox:
https://forum.proxmox.com/threads/usb-passthru-to-windows-2016.35056/

It is Windows related, but he was able to reproduce it on Linux with the same error message you have. And there is a solution, maybe this helps in your case?
