### ISSUE TITLE
I see RP3 as homeassistant in a network app unable to visit in browser

### ISSUE THREAD

**Issue by TheRephaim** [home-assistant/operating-system#881]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

I followed the steps for installing 

but I'm not able to visit home assistant in browser or connect with iOS app
I tried 2 different MacBooks an iMac and the iOS app 

with the iOS app I let the app search and tried manually 

and for all the devices I tried the .local option and the option to use the IP adres

I got a Network analyzing app on my iPhone and it says that home assistant is online

Can somebody help me out ?
it's the first time I post a "cry for help"
normally I could find solutions for issue's myself 

if additional info is required I will provide

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer and the help you are looking for in those places.

Thanks! 👍
