### ISSUE TITLE
Hassos doesn't boot after update hassos 5.3

### ISSUE THREAD

**Issue by hdjweb** [home-assistant/operating-system#900]
**HassOS release with the issue:**

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

**Comment by hdjweb** [comment]
Hassos doesn't start after update with terminal to hassos 5.3 i give the command with terminal " ha os update --version 5.3"

**Comment by SilverWx** [comment]
Hi,

I never updated hassos through CLI but I think the right command is
`ha os update --version=5.3`
but I don't know if this can work since 5.3 is not on the main branch.
Also, you have to provide more details if you want some help I think.

**Comment by pvizeli** [comment]
Please fill out the template, otherwise, I close the issue

**Comment by SilverWx** [comment]
Update done on vmware installation flawlessly ;)

**Comment by agners** [comment]
Closing due to incomplete information.
