### ISSUE TITLE
HassOS updated to 4.14 want to update to 4.13

### ISSUE THREAD

**Issue by Aldoszx** [home-assistant/operating-system#904]
**HassOS release with the issue:** 4.14

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:** HassOS manually updated to 4.14 offers the update to 4.13

**Comment by mohannadalsharief** [comment]
Any update on how to downgrade

**Comment by Aldoszx** [comment]
Thank you !
