### ISSUE TITLE
Firmware for Realtek Bluetooth 5.0 dongle not available

### ISSUE THREAD

**Issue by embcla** [home-assistant/operating-system#908]
**HassOS release with the issue:**

4.13

**Supervisor logs:**

none applicable

**Journal logs:**

**Kernel logs:**

![realtek driver fails](https://user-images.githubusercontent.com/54371771/96338027-a46c6d80-108b-11eb-8c01-e5a37218cca5.png)

**Description of problem:**
Drivers for the stick are not available, the entire folder /lib/firmware/rtl_bt is missing (check here for the relative debian package https://reposcope.com/package/firmware-realtek )

**Comment by pvizeli** [comment]
This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

**Comment by vBrolin** [comment]
This is not a feature request, these devices were working before 4.13, then it broke, not sure why the folder is missing but it was probably there before since it was working just fine before that upgrade.
