### ISSUE TITLE
Add hassos beta version to beta.json 

### ISSUE THREAD

**Issue by xchwarze** [home-assistant/operating-system#927]
Hi! 
I'm running Development 5 build 3 and I wanted to keep updating with beta versions but I don't see any way to do it other than reinstall everything.
Please add beta releases to https://version.home-assistant.io/beta.json

**Comment by tech-freak** [comment]
`ha os update --version 5.4`

run this command via **SSH & Web Terminal** add-on to update 5.4 without re-install

**Comment by xchwarze** [comment]
thanks tech-freak!
