### ISSUE TITLE
With HassOS 5.4 Raspberry 3 does not boot anymore

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/operating-system#928]
**HassOS release with the issue:** 5.4

**Supervisor logs:** None

**Journal logs:** None

**Kernel logs:** None

**Description of problem:**
When I upgraded from HassOS 5.3 to 5.4 today, my Pi 3B+ does not boot anymore. When I connect a HDMI cable, the only output I get is the colored image. I reflashed the SD card with 5.4 again to see if it was a upgrade error, but still same issue. I then flashed version 5.3 and the Pi booted normal again. Unfortunately I can't attach any logs, since there where just no logs anywhere. So I assume that something in 5.4 broke something for the Pi3 (maybe other Pi versions, but I only have version 3 to test here)

For reference, this is what I mean with a "colored image":
![image](https://user-images.githubusercontent.com/1368405/97114405-9accb080-16f0-11eb-962c-43a0a94a82e5.png)

**Comment by archerne** [comment]
Same issue with the 64bit Rasp Pi 4 8GB

**Comment by archerne** [comment]
I did a fresh install of 5.4 and it started (still testing to make sure everything works) but looks like the upgrade from 5.3 to 5.4 breaks something

**Comment by SmarterHomeLife** [comment]
Seems to break something with the SD card, I upgraded my system that runs on an SSD with no issues but upgrading or a fresh install on an SD card fails to boot for me.

**Comment by SeanPM5** [comment]
Can confirm, my secondary instance on an RPi4 (64bit / 4GB) was bricked after updating from 5.3 to 5.4.  It can no longer boot off the SD card.

**Comment by fabiocastagnino** [comment]
Same issue with the 64bit Rasp Pi 4 8GB, upgrading from 5.2 to 5.4 or clean install. It can no longer boot off the SD card.

**Comment by Gadgit83** [comment]
Same for me - RPI 4 8GB. 64bit image. Rolled back to 4.15 and worked fine. 5.3 appears to be booting OK.

Thought it was me - first time I'm trying the Pi with HA. Tried everything, different USB cables, different power supply, reflashed card, used balenEtcher and the Pi Imager, no luck. Should have known better than to rely on a dev version :).

**Comment by cogneato** [comment]
I wasn't sure what "colored image" was referring to, but now I see.

**Comment by TheZoker** [comment]
Thanks @cogneato for the hint, I placed an example image in the issue description 🙂

**Comment by selmaohneh** [comment]
Same here. But my screen is not colored, it just stays black. 🙄

**Comment by cogneato** [comment]
@TheZoker That was more me confirming what you were describing. I have a picture I was going to upload too but yours is straighter than mine. :+1: 

I've since booted a fresh install of HA OS 5.3 64 bit without issues on this pi4 4GB. We probably won't hear back from anyone about 5.4 for another 12 hours at least.

**Comment by agners** [comment]
Hm, it seems that the firmware bump in #899 is responsible for this. Using `start4.elf` and `fixup4.dat` from the firmware we used before (https://github.com/raspberrypi/firmware/commit/7caead9416f64b2d33361c703fb243b8e157eba4) makes it work for me.

I guess we have to revert the firmware until we bump to Linux 5.4.

**Comment by Jpsy** [comment]
Can confirm that update from 5.3 to 5.4 works flawlessly on an SSD based system without SD card.

**Comment by Beduir** [comment]
I have successfully upgraded from 5.3 to 5.4 (SSD without SD card). But the Razberry board stopped working. I went back to 5.3 and everything works again.

**Comment by Jpsy** [comment]
@Beduir:  Did your system stall immediately after upgrade or did it work for some time before it stopped?
I am on 5.4 for about 20 hours now without any problems.

**Comment by fabiocastagnino** [comment]
in my case the system die immediately after upgrade (RPi4 8gb)

**Comment by Beduir** [comment]
@Jpsy 
Everything worked well except Razberry (Z-wave).

**Comment by Jpsy** [comment]
@Beduir: Aaaah, I got you wrong. Did not check that Razberry is a Z-wave Pi hat!

**Comment by archerne** [comment]
@Beduir I had an issue with my Raspbee 2 hat as well, the serial changed from /dev/ttyAMA0 to /dev/ttyS0, once I made that change the hat worked again

**Comment by Beduir** [comment]
@archerne 
It does not help.

Yeelight lamps also stop working. The reason is not yet clear.

**Comment by agners** [comment]
Reverted to the firmware used in 5.3, should be working again with the next release.

**Comment by tmm1** [comment]
Sorry for all the trouble here. I'm not quite sure what happened, and why only some RPI are affected. I will try to investigate more.

**Comment by tmm1** [comment]
I think this issue is related to https://github.com/raspberrypi/firmware/issues/1457

The Sep 2020 stable release does not support booting from hybrid GPT from SD card. This was fixed in subsequent beta firmware released after the Sep 2020 stable build. The last known working firmware for hybrid GPT before Sep 2020 is Jun 2020 (1.20200601), which is what was being used before.

**Comment by deftdawg** [comment]
Booting 5.4 from didn't work for me either on Pi4 4GB.   @agners unless the devs actually did something that fixes the issue, the issue should be reopened; otherwise a lot of users gonna suffer when it goes GA.
