### ISSUE TITLE
HA OS 5.x reports only updates for 4.x releases

### ISSUE THREAD

**Issue by Jpsy** [home-assistant/operating-system#931]
**HassOS release with the issue:**

5.2, 5.3, 5.4

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**
_Frontend -> Supervisor_ on an OS 5.x based system reports the available updates for the 4.x release series, but not the updates for the 5.x series.
The following screenshot was taken more than 3 days after OS 5.4 was released. So this is not a timing problem but a real HA problem. 

![image](https://user-images.githubusercontent.com/1806058/97104274-d6488a00-16b2-11eb-9c62-75a76e46ca9e.png)

After manual update to 5.4 the 4.x update message still persists. (HA CLI: `ha os update --version 5.4`)

![image](https://user-images.githubusercontent.com/1806058/97104481-823ea500-16b4-11eb-9eb4-e8374d9b72ce.png)

Expected behavior is that HA should report the available 5.4 update and should not report the 4.x series. Actually my system breaks if I click the 4.x update button!

I am not sure though, whether _HA OS -> issues_ is the right place to report this issue as it could be a mere frontend problem.

**Comment by ludeeus** [comment]
This happens because 5.x is on the dev channel only, and you are on the beta channel.
<https://version.home-assistant.io/stable.json>
<https://version.home-assistant.io/beta.json>
<https://version.home-assistant.io/dev.json>

4.15 is the latest version of the beta channel.

However, this is "fixed" in the supervisor by hiding those "updates" and will be a part of the next supervisor release.

**Comment by Jpsy** [comment]
Thanks for the details @ludeeus. Is there a way in Home Assistant (Hass.io install) to switch to dev channel?

**Comment by ludeeus** [comment]
You can use the CLI `ha su options --help`, but only do that if it's a secondary unit.

**Comment by Jpsy** [comment]
With 5.x I am on a dev OS anyway. So is there any additional risk to set the Supervisor to dev channel?
Would this change more than just the releases that are displayed? Wouldn't I still have to manually trigger the update to a new dev release?
