### ISSUE TITLE
SSD only booting via USB 2.0. USB 3.0 Fails.

### ISSUE THREAD

**Issue by Teleportist** [home-assistant/operating-system#945]
HassOS 5.3
Home Assistant 0.116.4

RPi 4B 4GB Rev 1.2 (Firmware upgrade/latest bootloader - September 03/09/2020)

Eluteng USB to SSD Adapter
https://amzn.to/3mFA6jT

Kingston A400 120GB SSD
https://amzn.to/3kMf0Qb

Both adapter and drive are well tested and verified to boot on the RPi 4 according to this compatibility list.
https://storage.jamesachambers.com/popular/

HassOS will only boot when the SSD drive is connected to either a USB 2.0 port, or when connected to a USB 3.0 port via a USB 2.0 extension cable. This is the case regardless of connecting the RPi via ethernet or wreless.

**Comment by agners** [comment]
What do you mean exactly by "via a USB extension cable"? It sound the other cable is bad then?

**Comment by Teleportist** [comment]
> What do you mean exactly by "via a USB extension cable"? It sound the other cable is bad then?

Placing a USB (2.0) extension cable of 0.5m between the RPi and the SSD adapter lead+SSD. The idea was to eliminate any interference caused by close proximity, as the SSD adapter lead is only ~120mm long.

**Comment by agners** [comment]
OK I see now, a USB 2.0 extension cable of course makes it act as a USB 2.0 device.

We do use U-Boot whereas RPi OS does not, so it could be that U-Boot has troubles enumerating this device.

So in the USB 3.0 case, is anything showing on the HDMI display? Do you have access to a USB to UART TTL adapter to access the serial console (https://github.com/home-assistant/operating-system/tree/dev/Documentation/boards/raspberrypi#serial-console)?

**Comment by Teleportist** [comment]
I've now obtained a mini HDMI adapter, so can provide more info in the form of photos taken during start up.
I tried to cover the key messages below, but have also uploaded a complete video of the boot (6:40 until a login prompt appears!) just in case I've missed anything.

[https://youtu.be/Sm5rpPWXFfA](url)

Although I do eventually get to a login prompt, I'm never able to gain access via webpage or app. At this time the access light on my USB to SATA adapter goes solid and remains so.

Sorry, I don't have an adapter or the knowledge to access the serial console.

I hope someone can make sense of this. Thanks

![image](https://user-images.githubusercontent.com/61894621/98421132-9608e480-2080-11eb-9f51-f8778024720f.png)

![image](https://user-images.githubusercontent.com/61894621/98421305-eed87d00-2080-11eb-8d9a-180bbd9dabcc.png)

![image](https://user-images.githubusercontent.com/61894621/98421329-031c7a00-2081-11eb-8b9c-fb12b8bcd890.png)

![image](https://user-images.githubusercontent.com/61894621/98421904-58a55680-2082-11eb-8174-299f52ff225e.png)

![image](https://user-images.githubusercontent.com/61894621/98422000-90ac9980-2082-11eb-8a3a-ab081a65039c.png)

![image](https://user-images.githubusercontent.com/61894621/98422143-d8332580-2082-11eb-8575-444779e9b076.png)

![image](https://user-images.githubusercontent.com/61894621/98422197-f436c700-2082-11eb-9e49-6fd2b526dc8e.png)

![image](https://user-images.githubusercontent.com/61894621/98422284-2ba57380-2083-11eb-97a1-acc9e0adb0fd.png)

![image](https://user-images.githubusercontent.com/61894621/98422564-e766a300-2083-11eb-9e84-93627279b8e7.png)

**Comment by Teleportist** [comment]
OK, It seems I had a 'dodgy' Eluteng adapter.

According to Andrew G's post here, the incompatible ones can be identified by the Eluteng logo being on a sticker on the underside.
[https://jamesachambers.com/raspberry-pi-4-usb-boot-config-guide-for-ssd-flash-drives/comment-page-18/#comment-7379](url)

My Kingspec SSD arrived today, which works perfectly from SSD.

Again thanks for all responses to my original post.
Closing.

**Comment by Jpsy** [comment]
> According to Andrew G's post here, the incompatible ones can be identified by the Eluteng logo being on a sticker on the underside.
> [https://jamesachambers.com/raspberry-pi-4-usb-boot-config-guide-for-ssd-flash-drives/comment-page-18/#comment-7379](url).

@Teleportist please check your link. It is broken (although the link text is correct).

**Comment by bcutter** [comment]
Yeah and where is that information on the sticker thing? Can't find the name you mentioned.

**Comment by Teleportist** [comment]
Thanks jpsy - have fixed the link in my original post, but your quote still replicates the original broken one.

@bcutter - you'll need to scroll trough the comments, as that site has no direct way to link to individual posts. Good luck.

**Comment by bcutter** [comment]
Well so that´s the comment (currently on page 17):

> I bought 4 Eluteng USB SATA adaptors from Amazon and they all worked perfectly. However I recently purchased one more of the same Eluteng adaptors from Amazon and this one didn’t work. It should have been exactly the same item, but closer inspection shows the USB A connector is moulded differently from the pictures of the Eluteng adaptor, and on the rear of the SATA connector the Eluteng label is applied with a sticker.

The proper ones that work report from `lsusb` that they use the ASMedia/ASM chipset, the so-called Eluteng adaptor that doesn’t work shows it’s got a JMicron chipset. It’s worth double-checking what you receive, either Eluteng have gone cheap(?) with their adaptors or there are cheap knock-offs being sold as Eluteng adaptors.

I checked mine and it reports as JMicron (JMS567) and it has the sticker. I can´t check if works but as the comment states it´s very likely it won´t. **What would you recommend - send it back immediately?**
