### ISSUE TITLE
Local Time not being returned in query in SQLite Web addon

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/operating-system#955]
## The problem

Query not returning the local datetime in SQLite Web addon even after using the datetime modifier "localtime". 

```
SELECT datetime('now','localtime') time
union all
SELECT datetime('now')
```
The first row in the query should return time in local time zone and not UTC. The query returns both rows in UTC and not local time.

## Environment

- Home Assistant Core release with the issue:  0.117
- Last working Home Assistant Core release (if known): 0.116.4
- Operating environment (OS/Container/Supervised/Core): HassOS 4.15
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
I created an [issue ](https://github.com/hassio-addons/addon-sqlite-web/issues/96) against the addon. The issue was closed stating the issue is with the OS.

**Comment by agners** [comment]
Timezone is handled on application level, so in Home Assistant Core. SQLite seems to rely on system timezone, which is set to UTC always...

This would need a non-trivial change on OS level (and likely also in Supervisor etc to make it configurable from the frontend).
