### ISSUE TITLE
Additional drives can't be mounted, e.g. in media

### ISSUE THREAD

**Issue by mplogas** [home-assistant/operating-system#959]
**HassOS release with the issue:**
4.15

**Description of problem:**
Home Assistant is offering a media player option which can be used with local storage. In order to utilize the feature I would like to attach a 2nd SSD to my NUC-based HassOS/Hass.io instance. I have enabled the debug SSH and was able to eventually mount my /dev/sda1 to media folder inside my supervisor/media folder. This is not a persistent solution, obviously. I tried mounting through systemd, but ofc the this part is +ro. 
Would you please consider offering an option to (automatically) mount new internal drives (and USB drives, too) in media?

Please let me know if you need any further details or logs.

**Comment by frenck** [comment]
Even if this was possible, it would not work as expected (due to docker limitations).

IMHO, this is a feature requests that belong in our forums, not our issue tracker, as it is not an issue.
