### ISSUE TITLE
Can't upgrade HassOS 4.15 to 4.16

### ISSUE THREAD

**Issue by Loents** [home-assistant/operating-system#975]
Can't upgrade HassOS 4.15 to 4.16, this is what is written in the terminal:

![Без имени](https://user-images.githubusercontent.com/9423312/98588977-3c4d2800-22d5-11eb-9adf-5a1af16d0fa4.jpg)

Please tell me what to do

**Comment by fabaff** [comment]
At first glance: Same issue as #944.
