### ISSUE TITLE
HassOS 4.16: Nuki and xiaomi vaccum not anymore available

### ISSUE THREAD

**Issue by xabaras75** [home-assistant/operating-system#990]
**HassOS release with the issue:**
<4.16

Home Assistant 0.117.5 and Home Assistant 0.117.6 (both versions)

**Description of problem:**
Nuki lock and Xiaomi vaccun cleaner not available anymore  (State:  "unavailable")
--

**Comment by agners** [comment]
Did those break with a OS update or with a Core update?

**Comment by xabaras75** [comment]
I guess with core. Anyhow, in the meanwhile I have solved for both of them making again the WiFi onboarding so I get a new token. In this way I was able to get again the 2 devices connected on Hassio.
